// ##################
// authored (generated by gemini, Jun 03 2026 18:20 WITA)
// ##################

import React, { useState, useEffect, useRef } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { trpc } from "@/utils/trpc";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import {
  Clock,
  AlertTriangle,
  ChevronLeft,
  ChevronRight,
  Send,
  Loader2,
  ListOrdered,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface QuizModalProps {
  assessmentId: string;
  enrollmentId: string;
  isOpen: boolean;
  onClose: () => void;
  onComplete: (score: number) => void;
}

/**
 * QuizModal Component
 * Renders the assessment interface in a dialog modal, including:
 * - Two-panel layout (Left panel for question grid & timer, Right panel for questions & options)
 * - Countdown timer synced with attempt start time (auto-submits when time expires)
 * - Navigation grid with question status (answered/active/unanswered)
 * - Progress bar that turns green at 100%
 * - Safe locks (prevent closing by clicking outside/pressing escape)
 *
 * @param props QuizModalProps
 */
export function QuizModal({
  assessmentId,
  enrollmentId,
  isOpen,
  onClose,
  onComplete,
}: QuizModalProps) {
  // 1. Fetch full assessment (questions & options)
  const { data: assessment, isLoading: isLoadingAssessment } = useQuery({
    ...trpc.pelatihan.assessment.getAssessmentById.queryOptions({
      id: assessmentId,
    }),
    enabled: isOpen && !!assessmentId,
  });

  // States
  const [attemptId, setAttemptId] = useState<string | null>(null);
  const [startedAt, setStartedAt] = useState<string | null>(null);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [remainingSeconds, setRemainingSeconds] = useState<number | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showMobileNav, setShowMobileNav] = useState(false);

  // Timer Ref
  const timerIntervalRef = useRef<NodeJS.Timeout | null>(null);

  // 2. Start attempt mutation (triggered on mount / open)
  const startAttemptMutation = useMutation(
    trpc.pelatihan.assessment.startAttempt.mutationOptions({
      onSuccess: (data) => {
        if (data.success) {
          setAttemptId(data.attemptId);
          if (data.startedAt) {
            setStartedAt(data.startedAt);
          } else {
            setStartedAt(new Date().toISOString());
          }
        }
      },
      onError: (err) => {
        toast.error(err.message || "Gagal memulai ujian");
        onClose();
      },
    }),
  );

  // 3. Submit attempt mutation
  const submitAttemptMutation = useMutation(
    trpc.pelatihan.assessment.submitAttempt.mutationOptions({
      onSuccess: (data) => {
        setIsSubmitting(false);
        if (data.success) {
          onComplete(data.score);
        }
      },
      onError: (err) => {
        setIsSubmitting(false);
        toast.error(err.message || "Gagal mengirim jawaban");
      },
    }),
  );

  // Trigger startAttempt on open
  useEffect(() => {
    if (isOpen && assessmentId && enrollmentId) {
      startAttemptMutation.mutate({ enrollmentId, assessmentId });
      setCurrentQuestionIndex(0);
      setAnswers({});
      setAttemptId(null);
      setStartedAt(null);
      setRemainingSeconds(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, assessmentId, enrollmentId]);

  // Handle timer countdown
  useEffect(() => {
    if (
      !startedAt ||
      !assessment ||
      assessment.timeLimit === null ||
      assessment.timeLimit === undefined
    ) {
      return;
    }

    const totalSeconds = assessment.timeLimit * 60;
    const calculateRemaining = () => {
      const startTime = new Date(startedAt).getTime();
      const elapsed = Math.floor((Date.now() - startTime) / 1000);
      return Math.max(0, totalSeconds - elapsed);
    };

    // Set initial remaining time
    const initialRemaining = calculateRemaining();
    setRemainingSeconds(initialRemaining);

    if (initialRemaining <= 0) {
      // Already expired on load, auto-submit immediately
      handleAutoSubmit();
      return;
    }

    // Start interval
    timerIntervalRef.current = setInterval(() => {
      const remaining = calculateRemaining();
      setRemainingSeconds(remaining);

      if (remaining <= 0) {
        if (timerIntervalRef.current) clearInterval(timerIntervalRef.current);
        handleAutoSubmit();
      }
    }, 1000);

    return () => {
      if (timerIntervalRef.current) clearInterval(timerIntervalRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [startedAt, assessment]);

  const handleAutoSubmit = () => {
    if (isSubmitting || !attemptId) return;
    setIsSubmitting(true);
    toast.warning("Waktu pengerjaan habis! Menyerahkan jawaban Anda...");

    // Submit answers immediately
    submitAttemptMutation.mutate({
      attemptId,
      answers,
    });
  };

  const handleOptionSelect = (questionId: string, optionId: string) => {
    setAnswers((prev) => ({
      ...prev,
      [questionId]: optionId,
    }));
  };

  const handleNext = () => {
    if (!assessment) return;
    if (currentQuestionIndex < assessment.questions.length - 1) {
      setCurrentQuestionIndex((prev) => prev + 1);
    }
  };

  const handlePrev = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex((prev) => prev - 1);
    }
  };

  const handleSubmit = () => {
    if (!attemptId || isSubmitting) return;

    setIsSubmitting(true);
    submitAttemptMutation.mutate({
      attemptId,
      answers,
    });
  };

  const isLoading = isLoadingAssessment || startAttemptMutation.isPending;

  // Format timer
  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  const isTimeUrgent = remainingSeconds !== null && remainingSeconds < 300; // less than 5 minutes

  // Calculate progress
  const totalQuestions = assessment?.questions.length || 0;
  const answeredCount = Object.keys(answers).length;
  const progressPercent = totalQuestions
    ? Math.round((answeredCount / totalQuestions) * 100)
    : 0;
  const isProgressComplete = progressPercent === 100;

  return (
    <Dialog
      open={isOpen}
      onOpenChange={(open) => {
        // Prevent closing when clicking outside or pressing escape
        if (!open && !isSubmitting) {
          // Only allow close if not in-progress or explicitly cancelled
        }
      }}
    >
      <DialogContent
        className="flex h-[90vh] w-[95vw] max-w-6xl flex-col gap-0 overflow-hidden rounded-xl border bg-background p-0 shadow-2xl md:h-[80vh] md:w-[90vw] md:flex-row"
        onPointerDownOutside={(e) => e.preventDefault()}
        onEscapeKeyDown={(e) => e.preventDefault()}
        showCloseButton={false}
      >
        <DialogTitle className="sr-only">
          {assessment?.title || "Mengerjakan Ujian"}
        </DialogTitle>

        {isLoading ? (
          <div className="flex flex-1 flex-col items-center justify-center space-y-4 bg-background">
            <Loader2 className="h-10 w-10 animate-spin text-primary" />
            <p className="animate-pulse text-muted-foreground">
              Menyiapkan lembar soal ujian...
            </p>
          </div>
        ) : !assessment || !attemptId ? (
          <div className="flex flex-1 flex-col items-center justify-center space-y-4 bg-background p-6">
            <AlertTriangle className="h-12 w-12 text-destructive" />
            <p className="text-lg font-semibold">Gagal memulai ujian</p>
            <p className="max-w-sm text-center text-muted-foreground">
              Terjadi kesalahan saat memuat soal ujian. Silakan coba kembali
              atau hubungi administrator.
            </p>
            <Button onClick={onClose}>Tutup</Button>
          </div>
        ) : (
          <>
            {/* LEFT PANEL: Grid Question Numbers & Timer (Desktop only) */}
            <div className="hidden w-80 shrink-0 flex-col justify-between border-r border-slate-900 bg-slate-950 p-6 text-slate-100 md:flex">
              <div>
                <div className="mb-6">
                  <p className="text-xs font-semibold tracking-wider text-slate-500 uppercase">
                    Status Anda
                  </p>
                  <h3 className="mt-1 text-lg font-bold text-slate-200 capitalize">
                    {assessment.type.replace("_", " ")}
                  </h3>
                </div>

                <p className="mb-3 text-xs font-semibold tracking-wider text-slate-500 uppercase">
                  Navigasi Soal
                </p>
                <div className="grid max-h-[40vh] grid-cols-5 gap-2 overflow-y-auto pr-1">
                  {assessment.questions.map((q, idx) => {
                    const isActive = idx === currentQuestionIndex;
                    const isAnswered = !!answers[q.id];

                    return (
                      <button
                        key={q.id}
                        onClick={() => {
                          setCurrentQuestionIndex(idx);
                          setShowMobileNav(false);
                        }}
                        className={cn(
                          "flex h-10 w-10 cursor-pointer items-center justify-center rounded-lg text-sm font-semibold transition-all",
                          isActive
                            ? "scale-105 bg-blue-600 font-bold text-white ring-2 ring-blue-400 ring-offset-2 ring-offset-slate-950"
                            : isAnswered
                              ? "border border-blue-700/60 bg-blue-950/80 text-blue-200 hover:bg-blue-900"
                              : "hover:bg-slate-850 border border-slate-800 bg-slate-900/80 text-slate-400 hover:text-slate-200",
                        )}
                      >
                        {idx + 1}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Countdown Timer */}
              {remainingSeconds !== null && (
                <div
                  className={cn(
                    "mt-6 flex flex-col items-center justify-center gap-1 rounded-xl border p-4 transition-all",
                    isTimeUrgent
                      ? "animate-pulse border-red-800/60 bg-red-950/40 text-red-400"
                      : "border-slate-850 bg-slate-900/60 text-blue-400",
                  )}
                >
                  <div className="flex items-center gap-2 text-xs font-semibold tracking-wider text-slate-500 uppercase">
                    <Clock
                      className={cn(
                        "h-4 w-4",
                        isTimeUrgent ? "text-red-400" : "text-slate-500",
                      )}
                    />
                    Waktu Tersisa
                  </div>
                  <div
                    className={cn(
                      "font-mono text-3xl font-bold tracking-wider",
                      isTimeUrgent ? "text-red-500" : "text-slate-200",
                    )}
                  >
                    {formatTime(remainingSeconds)}
                  </div>
                </div>
              )}
            </div>

            {/* MOBILE TOP BAR */}
            <div className="flex shrink-0 items-center justify-between border-b bg-slate-950 p-4 text-slate-200 md:hidden">
              <div className="flex flex-col">
                <span className="text-xs tracking-wider text-slate-500 uppercase">
                  {assessment.type.replace("_", " ")}
                </span>
                <span className="text-sm font-bold">
                  Soal {currentQuestionIndex + 1} / {totalQuestions}
                </span>
              </div>
              <div className="flex items-center gap-3">
                {remainingSeconds !== null && (
                  <div
                    className={cn(
                      "flex items-center gap-1 rounded-lg border px-3 py-1.5 font-mono text-sm font-bold",
                      isTimeUrgent
                        ? "border-red-800 bg-red-950/60 text-red-500"
                        : "border-slate-800 bg-slate-900 text-blue-400",
                    )}
                  >
                    <Clock className="h-3.5 w-3.5" />
                    {formatTime(remainingSeconds)}
                  </div>
                )}
                <Button
                  size="sm"
                  variant="outline"
                  className="hover:bg-slate-850 border-slate-800 bg-slate-900 text-slate-300"
                  onClick={() => setShowMobileNav(!showMobileNav)}
                >
                  <ListOrdered className="mr-1 h-4 w-4" /> Soal
                </Button>
              </div>
            </div>

            {/* MOBILE COLLAPSIBLE QUESTION GRID */}
            {showMobileNav && (
              <div className="shrink-0 border-b border-slate-900 bg-slate-950 p-4 md:hidden">
                <p className="mb-2 text-xs font-semibold tracking-wider text-slate-500 uppercase">
                  Pilih Nomor Soal:
                </p>
                <div className="grid max-h-[30vh] grid-cols-6 gap-2 overflow-y-auto">
                  {assessment.questions.map((q, idx) => {
                    const isActive = idx === currentQuestionIndex;
                    const isAnswered = !!answers[q.id];
                    return (
                      <button
                        key={q.id}
                        onClick={() => {
                          setCurrentQuestionIndex(idx);
                          setShowMobileNav(false);
                        }}
                        className={cn(
                          "flex h-9 w-9 items-center justify-center rounded-lg text-xs font-semibold transition-all",
                          isActive
                            ? "bg-blue-600 text-white ring-2 ring-blue-400"
                            : isAnswered
                              ? "border border-blue-800 bg-blue-950 text-blue-300"
                              : "border border-slate-800 bg-slate-900 text-slate-400",
                        )}
                      >
                        {idx + 1}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* RIGHT PANEL: Question content & answers */}
            <div className="flex h-full flex-1 flex-col justify-between overflow-hidden bg-background">
              {/* Progress Header */}
              <div className="shrink-0 border-b bg-background p-4 md:p-6">
                <div className="mb-2 flex items-center justify-between">
                  <span className="text-sm font-semibold text-muted-foreground">
                    Pertanyaan {currentQuestionIndex + 1} dari {totalQuestions}
                  </span>
                  <span
                    className={cn(
                      "text-sm font-bold",
                      isProgressComplete ? "text-green-600" : "text-blue-600",
                    )}
                  >
                    {progressPercent}% Terjawab
                  </span>
                </div>
                <Progress
                  value={progressPercent}
                  className={cn(
                    "h-2 transition-all",
                    isProgressComplete
                      ? "bg-green-100 [&>div]:bg-green-500"
                      : "bg-blue-100 [&>div]:bg-blue-600",
                  )}
                />
              </div>

              {/* Question & Option Body */}
              <div className="flex-1 space-y-6 overflow-y-auto bg-background/50 p-6 md:p-8">
                <div className="text-lg leading-relaxed font-bold text-foreground md:text-xl">
                  {assessment.questions[currentQuestionIndex]?.questionText}
                </div>

                <div className="space-y-3">
                  {assessment.questions[currentQuestionIndex]?.options.map(
                    (option, optIdx) => {
                      const questionId =
                        assessment.questions[currentQuestionIndex]!.id;
                      const isSelected = answers[questionId] === option.id;
                      const letter = String.fromCharCode(65 + optIdx); // A, B, C, D...

                      return (
                        <button
                          key={option.id}
                          onClick={() =>
                            handleOptionSelect(questionId, option.id)
                          }
                          disabled={isSubmitting}
                          className={cn(
                            "flex w-full cursor-pointer items-center gap-4 rounded-xl border-2 p-4 text-left transition-all duration-200 disabled:pointer-events-none",
                            isSelected
                              ? "border-blue-600 bg-blue-50/40 font-medium text-blue-700 dark:bg-blue-950/20 dark:text-blue-400"
                              : "border-muted text-foreground hover:border-slate-400 hover:bg-muted/30",
                          )}
                        >
                          <div
                            className={cn(
                              "flex h-8 w-8 shrink-0 items-center justify-center rounded-full border-2 text-sm font-bold transition-all duration-200",
                              isSelected
                                ? "border-blue-600 bg-blue-600 text-white"
                                : "border-muted bg-background text-muted-foreground",
                            )}
                          >
                            {letter}
                          </div>
                          <span className="text-sm leading-relaxed md:text-base">
                            {option.optionText}
                          </span>
                        </button>
                      );
                    },
                  )}
                </div>
              </div>

              {/* Navigation Footer */}
              <div className="flex shrink-0 items-center justify-between border-t bg-background p-4 md:p-6">
                <Button
                  variant="outline"
                  onClick={handlePrev}
                  disabled={currentQuestionIndex === 0 || isSubmitting}
                  className="px-4 py-2"
                >
                  <ChevronLeft className="mr-1.5 h-4 w-4" /> Kembali
                </Button>

                {currentQuestionIndex < totalQuestions - 1 ? (
                  <Button
                    onClick={handleNext}
                    disabled={isSubmitting}
                    className="bg-blue-600 px-5 py-2 text-white hover:bg-blue-700"
                  >
                    Selanjutnya <ChevronRight className="ml-1.5 h-4 w-4" />
                  </Button>
                ) : (
                  <Button
                    onClick={handleSubmit}
                    disabled={isSubmitting}
                    className={cn(
                      "flex items-center gap-2 px-6 py-2 font-bold text-white shadow-md transition-all",
                      isProgressComplete
                        ? "bg-green-600 hover:bg-green-700"
                        : "bg-blue-600 hover:bg-blue-700",
                    )}
                  >
                    {isSubmitting ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" /> Mengirim...
                      </>
                    ) : (
                      <>
                        Kirim Jawaban <Send className="h-4 w-4" />
                      </>
                    )}
                  </Button>
                )}
              </div>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
