// ##################
// authored (generated by gemini, Jun 14 2026 09:25 WITA)
// ##################

import LandingNavbar from "@/components/navbar";
import Footer from "@/components/footer";
import ImageWithFallback from "@/components/image-with-fallback";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { pageHead } from "@/utils/page-head";
import { useState } from "react";
import { trpc } from "@/utils/trpc";
import { useQuery } from "@tanstack/react-query";
import {
  ArrowLeft,
  Download,
  ExternalLink,
  Info,
  Search,
  Loader2,
  FileText,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { getPublicUrl } from "@/utils/url";

export const Route = createFileRoute("/ppid/berkala")({
  component: PPIDBerkalaListPage,
  head: () => pageHead("Informasi Berkala - PPID Balai K3 Samarinda"),
});

/**
 * PPIDBerkalaListPage component displaying the list of periodic public documents
 * organized in premium accordion cards.
 * @returns {JSX.Element} React Component
 */
function PPIDBerkalaListPage() {
  const navigate = useNavigate();
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  // Jadwal Pelatihan active tab state
  const [activeJadwalTab, setActiveJadwalTab] = useState<number>(0);
  const jadwalImages = [
    { src: "/assets/jadwal_pelatihan_1.webp", name: "Jadwal Bagian 1" },
    { src: "/assets/jadwal_pelatihan_2.webp", name: "Jadwal Bagian 2" },
    { src: "/assets/jadwal_pelatihan_3.webp", name: "Jadwal Bagian 3" },
  ];

  // Laporan Pelayanan PPID state & queries
  const [reportSearchQuery, setReportSearchQuery] = useState("");
  const [reportPage, setReportPage] = useState(1);
  const reportPerPage = 5;

  const { data: reportData, isLoading: isReportLoading } = useQuery(
    trpc.platform.ppid.getPublicDocuments.queryOptions(
      {
        category: "berkala",
        title: reportSearchQuery,
        page: reportPage,
        perPage: reportPerPage,
      },
      {
        placeholderData: (prev: any) => prev,
      },
    ),
  );

  const reports = reportData?.data || [];
  const totalReportPages = reportData?.pageCount || 1;

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setReportSearchQuery(e.target.value);
    setReportPage(1);
  };

  const toggleAccordion = (index: number) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  const categories = [
    {
      title: "Profil, Tugas dan Fungsi Balai K3 Samarinda",
    },
    {
      title: "Struktur organisasi Balai K3 Samarinda",
    },
    {
      title: "Maklumat Pelayanan",
    },
    {
      title: "Jadwal Pelatihan K3",
    },
    {
      title: "Laporan Pelayanan Informasi Publik",
    },
  ];

  return (
    <div className="flex min-h-screen w-full flex-col overflow-x-hidden overflow-y-auto bg-white dark:bg-neutral-950">
      <LandingNavbar />

      {/* Back Button */}
      <div className="container mx-auto max-w-[1232px] px-4 pt-8">
        <Button
          variant="ghost"
          className="gap-2 text-muted-foreground hover:text-foreground"
          onClick={() => navigate({ to: "/ppid" })}
        >
          <ArrowLeft className="size-4" />
          Kembali ke Portal PPID
        </Button>
      </div>

      {/* Title Section (Figma Node: 1986:22428) */}
      <section className="container mx-auto flex max-w-[1000px] flex-col items-center justify-center px-4 pt-12 pb-12 text-center">
        {/* Figma Badge: Frame 31 */}
        <div className="inline-flex items-center justify-start gap-2.5">
          <div data-svg-wrapper>
            <svg
              width="14"
              height="14"
              viewBox="0 0 14 14"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect
                width="14"
                height="14"
                fill="url(#paint0_linear_1986_17673)"
              />
              <defs>
                <linearGradient
                  id="paint0_linear_1986_17673"
                  x1="0"
                  y1="7"
                  x2="14"
                  y2="7"
                  gradientUnits="userSpaceOnUse"
                >
                  <stop stop-color="#1061D6" />
                  <stop offset="1" stop-color="#78E275" />
                </linearGradient>
              </defs>
            </svg>
          </div>
          <div className="font-poppins justify-start text-xl leading-6 font-semibold text-[#1061D6] dark:text-blue-400">
            Informasi Publik
          </div>
        </div>

        {/* Figma Group 3 (Title + Underline) */}
        <div className="relative mt-5 inline-block w-full max-w-[822px] text-center">
          <h1 className="font-poppins text-[36px] leading-[118%] font-semibold text-[#1061D6] md:text-[60px] dark:text-blue-400">
            Informasi Berkala
          </h1>
          {/* Underline Decoration - Figma: Frame 32 */}
          <div className="mx-auto mt-4 h-[12px] w-full max-w-[617px] rounded-full bg-[linear-gradient(90deg,#1061D6_34%,#78E275_58%,transparent_98%)]" />
        </div>

        {/* Figma Description */}
        <p className="font-poppins mt-6 max-w-[1000px] text-lg leading-[150%] font-medium text-neutral-600 sm:text-xl md:text-[24px] dark:text-neutral-300">
          Informasi yang wajib diumumkan secara rutin dan berkala oleh Balai K3
          Samarinda sebagai bentuk transparansi kinerja dan kegiatan kepada
          masyarakat.
        </p>
      </section>

      {/* Accordion Cards Section (Figma Node: 1986:22436) */}
      <main className="container mx-auto max-w-[1232px] px-4 pb-24">
        <div className="space-y-4">
          {categories.map((cat, idx) => {
            const isExpanded = expandedIndex === idx;

            return (
              <div
                key={idx}
                className="overflow-hidden rounded-[30px] border border-slate-100 bg-white shadow-sm transition-all duration-300 hover:shadow-md dark:border-neutral-800 dark:bg-neutral-900"
              >
                {/* Header Row */}
                <button
                  onClick={() => toggleAccordion(idx)}
                  className="flex h-32 w-full flex-col items-start justify-center gap-2.5 rounded-[30px] bg-white px-8 py-8 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-[#1061D6] md:px-16 dark:bg-neutral-900"
                >
                  <div className="inline-flex w-full max-w-[1104px] items-center justify-between gap-4">
                    <div className="font-poppins justify-start text-xl leading-8 font-semibold tracking-tight text-[#1061D6] md:text-2xl dark:text-blue-400">
                      {cat.title}
                    </div>
                    <div className="relative h-[60px] w-[60px] shrink-0">
                      <svg
                        width="60"
                        height="60"
                        viewBox="0 0 60 60"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                        className="absolute inset-0"
                      >
                        <rect width="60" height="60" rx="30" fill="#1061D6" />
                      </svg>
                      <svg
                        width="35"
                        height="35"
                        viewBox="0 0 35 35"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                        className={`absolute top-[12.5px] left-[12.5px] transition-transform duration-300 ${isExpanded ? "rotate-45" : ""}`}
                      >
                        <path
                          d="M10.208 24.7891L24.7913 10.2057M24.7913 24.7891L24.7913 10.2057L10.208 10.2057"
                          stroke="white"
                          strokeWidth="2.91667"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </svg>
                    </div>
                  </div>
                </button>

                {/* Expanded Panel Content */}
                {isExpanded && (
                  <div className="animate-in border-t border-slate-100 bg-slate-50/30 px-8 py-10 duration-300 fade-in slide-in-from-top-2 md:px-16 md:py-12 dark:border-neutral-800 dark:bg-neutral-900/10">
                    {/* Content Accordion 1: Profil, Tugas & Fungsi */}
                    {idx === 0 && (
                      <div className="grid grid-cols-1 gap-12 lg:grid-cols-12 lg:items-start lg:gap-16">
                        {/* Left Column: Image */}
                        <div className="flex justify-center lg:col-span-5">
                          <ImageWithFallback
                            src="/assets/profile_balai_k3-330b7b.webp"
                            alt="Profil Balai K3"
                            className="h-[600px] w-full max-w-[480px] rounded-[18px] shadow-sm"
                            imgClassName="object-cover"
                          />
                        </div>

                        {/* Right Column: Title & Text */}
                        <div className="flex flex-col gap-6 lg:col-span-7">
                          <h3 className="font-poppins text-3xl leading-[110%] font-semibold text-neutral-700 md:text-[50px] dark:text-neutral-200">
                            Balai Keselamatan dan Kesehatan Kerja Samarinda
                          </h3>
                          <p className="font-poppins text-lg leading-[36px] font-medium text-neutral-600 dark:text-neutral-300">
                            Balai Keselamatan dan Kesehatan Kerja (K3) Samarinda
                            merupakan lembaga resmi yang berperan dalam
                            mendukung penerapan keselamatan dan kesehatan kerja
                            melalui kegiatan pembinaan, pengujian, dan
                            pelatihan.
                          </p>
                          <p className="font-poppins text-lg leading-[36px] font-medium text-neutral-600 dark:text-neutral-300">
                            Balai K3 Samarinda bertujuan mewujudkan lingkungan
                            kerja yang aman, sehat, dan produktif guna
                            meningkatkan kesejahteraan tenaga kerja serta
                            mendukung keberlangsungan industri sesuai dengan
                            ketentuan yang berlaku.
                          </p>
                        </div>

                        {/* Full Width Bottom Content */}
                        <div className="mt-4 space-y-6 lg:col-span-12">
                          <p className="font-poppins text-lg leading-[36px] font-medium text-neutral-600 dark:text-neutral-300">
                            Dalam pelaksanaannya, Balai K3 Samarinda bertugas
                            melaksanakan pengujian, peningkatan kapasitas dan
                            uji kompetensi personil, pemeriksaan kesehatan
                            kerja, konsultansi, serta pengembangan jejaring di
                            bidang keselamatan dan kesehatan kerja.
                          </p>
                          <p className="font-poppins text-lg leading-[36px] font-medium text-neutral-600 dark:text-neutral-300">
                            Untuk mendukung tugas tersebut, Balai K3
                            menyelenggarakan fungsi penyusunan program dan
                            anggaran, pelaksanaan pengujian dan analisis K3,
                            peningkatan kapasitas dan uji kompetensi,
                            pemeriksaan kesehatan kerja, pelayanan konsultasi,
                            serta pengelolaan administrasi dan pelaporan.
                          </p>

                          <div className="flex flex-col items-center justify-between gap-6 pt-6 sm:flex-row">
                            {/* Experience Badge */}
                            <div className="flex h-[99px] w-[227px] shrink-0 flex-col items-start justify-center rounded-[20px] bg-[#1061D6] py-2 pl-6">
                              <span className="font-poppins text-4xl leading-[130%] font-semibold text-white">
                                30+
                              </span>
                              <span className="font-poppins text-lg leading-[150%] font-semibold text-white">
                                Tahun Pengalaman
                              </span>
                            </div>

                            {/* Download PDF Button */}
                            <a
                              href="/assets/profile_balai_k3.pdf"
                              download="Profil_Balai_K3_Samarinda.pdf"
                              target="_blank"
                              rel="noopener noreferrer"
                              className="font-poppins flex h-[56px] w-full items-center justify-center gap-3 rounded-[12px] bg-[#1061D6] text-lg font-semibold text-white shadow-[0px_0px_100px_-2px_rgba(16,97,214,0.14)] transition-colors duration-200 hover:bg-blue-700 sm:w-[588px]"
                            >
                              <Download className="size-6 shrink-0" />
                              <span>Unduh Profil Balai (PDF)</span>
                            </a>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* Content Accordion 2: Struktur Organisasi */}
                    {idx === 1 && (
                      <div className="w-full space-y-8">
                        {/* Catatan Dasar Hukum */}
                        <div className="flex items-center gap-4 rounded-[20px] border border-slate-200/60 bg-slate-50 p-5 dark:border-neutral-800 dark:bg-neutral-900">
                          <Info className="size-6 shrink-0 text-[#1061D6]" />
                          <p className="font-poppins text-sm leading-[140%] text-neutral-600 dark:text-neutral-400">
                            Struktur organisasi ini berdasarkan PERMENAKER RI
                            Nomor 1 Tahun 2022 Tentang Organisasi dan Tata Kerja
                            Unit Pelaksana Teknis di Kementerian Ketenagakerjaan
                          </p>
                        </div>

                        {/* Schematic Layout (Desktop & Scrollable Mobile) */}
                        <div className="w-full overflow-x-auto py-6">
                          <div className="relative mx-auto h-[640px] w-[920px] rounded-[30px] border border-slate-100 bg-slate-50/50 p-8 dark:border-neutral-800/50 dark:bg-neutral-900/10">
                            {/* Box 1 (BALAI K3) */}
                            <div className="absolute top-8 left-1/2 h-[130px] w-[840px] -translate-x-1/2 rounded-[20px] bg-gradient-to-r from-[#169AF9] to-[#0C74EA] p-[5px] shadow-xs">
                              <div className="flex h-full w-full items-center justify-center rounded-[15px] bg-white px-6 dark:bg-neutral-950">
                                <span className="text-center font-roboto text-xl leading-[140%] font-bold tracking-wide text-black lg:text-[26px] dark:text-white">
                                  BALAI KESELAMATAN DAN KESEHATAN KERJA (K3)
                                  SAMARINDA
                                </span>
                              </div>
                            </div>

                            {/* Vertical Line Connector */}
                            <div className="absolute top-[163px] left-1/2 h-[290px] w-2 -translate-x-1/2 bg-[#1061D6]" />

                            {/* Horizontal Line Connector */}
                            <div className="absolute top-[308px] left-1/2 h-2 w-[115px] bg-[#1061D6]" />

                            {/* Box 2 (SUBBAGIAN UMUM) */}
                            <div className="absolute top-[243px] left-[calc(50%+115px)] h-[130px] w-[280px] rounded-[20px] bg-gradient-to-r from-[#169AF9] to-[#0C74EA] p-[5px] shadow-xs">
                              <div className="flex h-full w-full items-center justify-center rounded-[15px] bg-white px-4 dark:bg-neutral-950">
                                <span className="font-poppins text-center text-xl leading-[140%] font-semibold text-black lg:text-[24px] dark:text-white">
                                  SUBBAGIAN
                                  <br />
                                  UMUM
                                </span>
                              </div>
                            </div>

                            {/* Box 3 (KELOMPOK JABATAN FUNGSIONAL) */}
                            <div className="absolute top-[453px] left-1/2 h-[150px] w-[280px] -translate-x-1/2 rounded-[20px] bg-gradient-to-r from-[#169AF9] to-[#0C74EA] p-[5px] shadow-xs">
                              <div className="flex h-full w-full items-center justify-center rounded-[15px] bg-white px-4 dark:bg-neutral-950">
                                <span className="font-poppins text-center text-xl leading-[130%] font-bold text-black lg:text-[24px] dark:text-white">
                                  KELOMPOK
                                  <br />
                                  JABATAN
                                  <br />
                                  FUNGSIONAL
                                </span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* Content Accordion 3: Maklumat Pelayanan */}
                    {idx === 2 && (
                      <div className="flex flex-col items-center gap-8">
                        <div className="relative w-full max-w-[1060px] overflow-hidden rounded-[20px] border border-slate-100 bg-white p-2 shadow-[0px_0px_100px_-2px_rgba(16,97,214,0.14)] dark:border-neutral-900 dark:bg-neutral-950">
                          <ImageWithFallback
                            src="/assets/maklumat_pelayanan.png"
                            alt="Maklumat Pelayanan Balai K3 Samarinda"
                            className="h-auto w-full rounded-[15px]"
                            imgClassName="object-contain"
                          />
                        </div>
                        <div className="flex items-center gap-3">
                          <a
                            href="/assets/maklumat_pelayanan.png"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-5 py-2.5 text-sm font-semibold text-neutral-700 shadow-sm transition-colors hover:bg-slate-50 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-200 dark:hover:bg-neutral-700/80"
                          >
                            <ExternalLink className="size-4" />
                            Buka Ukuran Penuh
                          </a>
                          <a
                            href="/assets/maklumat_pelayanan.png"
                            download="Maklumat_Pelayanan_Balai_K3_Samarinda.png"
                            className="inline-flex items-center gap-2 rounded-full bg-[#1061D6] px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-blue-700"
                          >
                            <Download className="size-4" />
                            Unduh Gambar
                          </a>
                        </div>
                      </div>
                    )}

                    {/* Content Accordion 4: Jadwal Pelatihan K3 */}
                    {idx === 3 && (
                      <div className="flex flex-col items-center gap-8">
                        {/* Tab Switcher Pills */}
                        <div className="flex flex-wrap items-center justify-center gap-2.5 rounded-full bg-slate-100 p-1.5 dark:bg-neutral-900">
                          {jadwalImages.map((tab, tIdx) => (
                            <button
                              key={tIdx}
                              onClick={() => setActiveJadwalTab(tIdx)}
                              className={`rounded-full px-5 py-2 text-sm font-semibold transition-all ${
                                activeJadwalTab === tIdx
                                  ? "bg-[#1061D6] text-white shadow-xs"
                                  : "text-neutral-600 hover:text-neutral-800 dark:text-neutral-400 dark:hover:text-neutral-200"
                              }`}
                            >
                              {tab.name}
                            </button>
                          ))}
                        </div>

                        {/* Image Viewer */}
                        {(() => {
                          const activeJadwal = jadwalImages[
                            activeJadwalTab
                          ] || { src: "", name: "" };
                          return (
                            <>
                              <div className="relative w-full max-w-[1000px] overflow-hidden rounded-[20px] border border-slate-100 bg-white p-2 shadow-[0px_0px_100px_-2px_rgba(16,97,214,0.14)] transition-all duration-300 dark:border-neutral-900 dark:bg-neutral-950">
                                <ImageWithFallback
                                  src={activeJadwal.src}
                                  alt={activeJadwal.name}
                                  className="h-auto max-h-[850px] w-full rounded-[15px]"
                                  imgClassName="object-contain"
                                />
                              </div>

                              {/* Downloads */}
                              <div className="flex items-center gap-3">
                                <a
                                  href={activeJadwal.src}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-5 py-2.5 text-sm font-semibold text-neutral-700 shadow-sm transition-colors hover:bg-slate-50 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-200 dark:hover:bg-neutral-700/80"
                                >
                                  <ExternalLink className="size-4" />
                                  Buka Ukuran Penuh
                                </a>
                                <a
                                  href={activeJadwal.src}
                                  download={`${activeJadwal.name.replace(/\s+/g, "_")}.png`}
                                  className="inline-flex items-center gap-2 rounded-full bg-[#1061D6] px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-blue-700"
                                >
                                  <Download className="size-4" />
                                  Unduh Gambar
                                </a>
                              </div>
                            </>
                          );
                        })()}
                      </div>
                    )}

                    {/* Content Accordion 5: Laporan Pelayanan Informasi Publik */}
                    {idx === 4 && (
                      <div className="mx-auto w-full max-w-5xl space-y-6">
                        {/* Search bar inside panel */}
                        <div className="flex justify-end">
                          <div className="relative w-full sm:max-w-xs">
                            <Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-slate-400" />
                            <Input
                              type="text"
                              placeholder="Cari laporan..."
                              value={reportSearchQuery}
                              onChange={handleSearchChange}
                              className="rounded-xl pl-9"
                            />
                          </div>
                        </div>

                        {/* Dynamic Table */}
                        <div className="overflow-hidden rounded-[20px] border border-slate-100 bg-white shadow-sm dark:border-neutral-800 dark:bg-neutral-950">
                          {isReportLoading ? (
                            <div className="flex h-64 items-center justify-center text-muted-foreground">
                              <Loader2 className="mr-2 size-8 animate-spin text-primary" />
                              <span>Memuat daftar laporan...</span>
                            </div>
                          ) : reports.length === 0 ? (
                            <div className="flex h-64 flex-col items-center justify-center text-muted-foreground">
                              <FileText className="mb-3 size-12 text-slate-300" />
                              <p className="text-lg">
                                Laporan pelayanan PPID tidak ditemukan
                              </p>
                            </div>
                          ) : (
                            <table className="w-full border-collapse text-left">
                              <thead>
                                <tr className="font-poppins bg-[#1061D6] text-sm font-semibold tracking-wider text-white uppercase">
                                  <th className="w-16 px-6 py-5 text-center">
                                    NO
                                  </th>
                                  <th className="px-6 py-5">
                                    Judul Dokumen Laporan
                                  </th>
                                  <th className="w-32 px-6 py-5 text-center">
                                    Tampilkan
                                  </th>
                                </tr>
                              </thead>
                              <tbody>
                                {reports.map((doc: any, rIndex: number) => (
                                  <tr
                                    key={doc.id}
                                    className="border-b border-[#1b6bdd]/20 text-sm text-slate-800 transition-colors hover:bg-slate-50/50 dark:text-neutral-200 dark:hover:bg-neutral-900/30"
                                  >
                                    <td className="px-6 py-4 text-center font-semibold text-neutral-400 dark:text-neutral-500">
                                      {(reportPage - 1) * reportPerPage +
                                        rIndex +
                                        1}
                                      .
                                    </td>
                                    <td className="font-poppins px-6 py-4 font-medium text-neutral-700 dark:text-neutral-300">
                                      {doc.title}
                                    </td>
                                    <td className="px-6 py-4 text-center">
                                      {doc.fileUrl && (
                                        <Button
                                          variant="outline"
                                          size="sm"
                                          asChild
                                          className="rounded-full border-[#1061D6] font-bold text-[#1061D6] hover:bg-[#1061D6]/5 dark:border-blue-500 dark:text-blue-400 dark:hover:bg-blue-950/20"
                                        >
                                          <a
                                            href={getPublicUrl(doc.fileUrl)}
                                            target="_blank"
                                            rel="noreferrer"
                                          >
                                            Lihat
                                          </a>
                                        </Button>
                                      )}
                                    </td>
                                  </tr>
                                ))}
                              </tbody>
                            </table>
                          )}
                        </div>

                        {/* Pagination inside Accordion */}
                        {!isReportLoading && totalReportPages > 1 && (
                          <div className="flex items-center justify-between pt-2">
                            <span className="text-xs text-muted-foreground">
                              Halaman {reportPage} dari {totalReportPages}
                            </span>
                            <div className="flex items-center gap-2">
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() =>
                                  setReportPage((prev) => Math.max(1, prev - 1))
                                }
                                disabled={reportPage === 1}
                                className="h-9 gap-1 rounded-lg"
                              >
                                <ChevronLeft className="size-4" />
                                Sebelumnya
                              </Button>
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() =>
                                  setReportPage((prev) =>
                                    Math.min(totalReportPages, prev + 1),
                                  )
                                }
                                disabled={reportPage === totalReportPages}
                                className="h-9 gap-1 rounded-lg"
                              >
                                Selanjutnya
                                <ChevronRight className="size-4" />
                              </Button>
                            </div>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </main>

      <Footer />
    </div>
  );
}
