// ##################
// authored (generated by gemini, Jun 04 2026 00:55 WITA)
// ##################

import { pageHead } from "@/utils/page-head";
import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";

// Sub-components
import { ProfilTab } from "./_components/profil-tab";
import { ElearningTab } from "./_components/elearning-tab";
import { BimtekTab } from "./_components/bimtek-tab";
import { WebinarTab } from "./_components/webinar-tab";
import { SertifikatTab } from "./_components/sertifikat-tab";
import { TransaksiTab } from "./_components/transaksi-tab";

const dashboardSearchSchema = z.object({
  tab: z
    .enum([
      "profil",
      "e-learning",
      "bimtek",
      "webinar",
      "sertifikat",
      "riwayat-transaksi",
    ])
    .default("profil")
    .catch("profil"),
  page: z.number().int().positive().default(1).catch(1),
  limit: z.number().int().positive().default(10).catch(10),
});

export const Route = createFileRoute("/(core)/dashboard/pelatihan/")({
  validateSearch: dashboardSearchSchema,
  head: () => pageHead("Dashboard Pelatihan K3"),
  component: RouteComponent,
});

function RouteComponent() {
  const { tab, page, limit } = Route.useSearch();
  const navigate = Route.useNavigate();

  const handlePageChange = (newPage: number) => {
    navigate({
      search: (prev) => ({ ...prev, page: newPage }),
    });
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="mb-8 space-y-2">
        <h1 className="font-['Plus_Jakarta_Sans'] text-3xl font-extrabold tracking-tight text-slate-800">
          Dashboard Pelatihan
        </h1>
        <p className="font-['Poppins'] text-sm text-slate-500">
          Kelola profil, pantau progres belajar, akses sertifikat, dan kelola
          riwayat transaksi Anda.
        </p>
      </div>

      {/* Main Content Area (Full Width) */}
      <main className="w-full">
        <div className="rounded-2xl bg-slate-50/50 p-1">
          {tab === "profil" && <ProfilTab />}
          {tab === "e-learning" && (
            <ElearningTab
              page={page}
              limit={limit}
              onPageChange={handlePageChange}
            />
          )}
          {tab === "bimtek" && (
            <BimtekTab
              page={page}
              limit={limit}
              onPageChange={handlePageChange}
            />
          )}
          {tab === "webinar" && (
            <WebinarTab
              page={page}
              limit={limit}
              onPageChange={handlePageChange}
            />
          )}
          {tab === "sertifikat" && (
            <SertifikatTab
              page={page}
              limit={limit}
              onPageChange={handlePageChange}
            />
          )}
          {tab === "riwayat-transaksi" && (
            <TransaksiTab
              page={page}
              limit={limit}
              onPageChange={handlePageChange}
            />
          )}
        </div>
      </main>
    </div>
  );
}

// ##################
// end authored
// ##################
