import { createFileRoute, Outlet, redirect } from "@tanstack/react-router";
import { trpc } from "@/utils/trpc";
import { MaterialSidebar } from "../-components/material-sidebar";
import { useQuery } from "@tanstack/react-query";
import { z } from "zod";
import { pageHead } from "@/utils/page-head";

// ##################
// authored (generated by antigravity, Jun 24 2026 21:18 WITA)
// ##################

export const Route = createFileRoute("/(core)/pelatihan/belajar/$enrollmentId")(
  {
    params: z.object({ enrollmentId: z.string().uuid() }),
    loader: async ({ context, params }) => {
      try {
        return await context.queryClient.ensureQueryData(
          context.trpc.pelatihan.enrollment.getUserEnrollmentById.queryOptions({
            id: params.enrollmentId,
          }),
        );
      } catch (error) {
        throw redirect({ to: "/pelatihan/transaksi" });
      }
    },
    head: () => pageHead("Pelatihan - Belajar"),
    component: BelajarLayout,
  },
);

function BelajarLayout() {
  const { enrollmentId } = Route.useParams();

  const { data: enrollment, isLoading } = useQuery(
    trpc.pelatihan.enrollment.getUserEnrollmentById.queryOptions({
      id: enrollmentId,
    }),
  );

  if (isLoading || !enrollment) {
    return (
      <div className="flex h-[calc(100vh-64px)] items-center justify-center">
        <div className="flex animate-pulse flex-col items-center gap-4">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
          <p className="text-muted-foreground">Memuat data pelatihan...</p>
        </div>
      </div>
    );
  }

  // Handle if not enrolled/in progress
  if (
    enrollment.status !== "enrolled" &&
    enrollment.status !== "in_progress" &&
    enrollment.status !== "completed"
  ) {
    return (
      <div className="flex h-[calc(100vh-64px)] items-center justify-center">
        <div className="space-y-2 text-center">
          <h2 className="text-2xl font-bold tracking-tight">
            Belum Memiliki Akses
          </h2>
          <p className="text-muted-foreground">
            Status pendaftaran Anda saat ini adalah {enrollment.status}.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-[calc(100vh-64px)] w-full overflow-hidden bg-background">
      <MaterialSidebar
        materials={enrollment.pelatihan?.materials ?? []}
        assessments={enrollment.pelatihan?.assessments ?? []}
        progresses={enrollment.progresses ?? []}
        enrollmentId={enrollmentId}
        progressPercentage={enrollment.progressPercentage ?? 0}
      />
      <div className="flex-1 overflow-y-auto">
        <Outlet />
      </div>
    </div>
  );
}
