import {
  createTRPCRouter,
  formDataProcedure,
  formDataInput,
  withPermission,
  withProtectedRateLimit,
} from "../../index";
import { runEffect } from "../../utils/run-effect";
import { Effect } from "effect";
import { kepegawaianExcelQueries } from "@tepian-k3/queries/platform/kepegawaian-excel.queries";
import { importKepegawaianExcelFormSchema } from "@tepian-k3/schema/platform/kepegawaian-excel.schema";
import {
  parseKepegawaianExcelBuffer,
  buildKepegawaianExportWorkbook,
  buildKepegawaianErrorReport,
  buildKepegawaianTemplateWorkbook,
} from "@tepian-k3/services/excel";
import { TRPCError } from "@trpc/server";
import { rateLimiters } from "@tepian-k3/services/rate-limiter";

// ##################
// authored (generated by claude, Jul 12 2026)
// ##################

export const kepegawaianExcelRouter = createTRPCRouter({
  downloadTemplate: withPermission("kepegawaian-import-export.read").query(
    async () =>
      await runEffect(
        Effect.gen(function* () {
          const buffer = yield* Effect.tryPromise({
            try: () => buildKepegawaianTemplateWorkbook(),
            catch: (e) =>
              new TRPCError({
                code: "INTERNAL_SERVER_ERROR",
                message: "Failed to build template",
                cause: e,
              }),
          });
          return {
            base64: buffer.toString("base64"),
          };
        }),
      ),
  ),

  importData: withProtectedRateLimit(rateLimiters.moderate())
    .use(
      withPermission("kepegawaian-import-export.create")._def.middlewares[0] ||
        (async ({ ctx, next }) => next({ ctx })),
    )
    .input(formDataInput)
    .use(formDataProcedure(importKepegawaianExcelFormSchema))
    .mutation(
      async ({ ctx }) =>
        await runEffect(
          Effect.gen(function* () {
            const arrayBuffer = yield* Effect.tryPromise<
              ArrayBuffer,
              TRPCError
            >({
              try: () => ctx.input.data.file.arrayBuffer(),
              catch: (e) =>
                new TRPCError({
                  code: "BAD_REQUEST",
                  message: "Failed to read file",
                  cause: e,
                }),
            });
            const buffer = Buffer.from(arrayBuffer);

            const parsedData = yield* Effect.tryPromise({
              try: () => parseKepegawaianExcelBuffer(buffer),
              catch: (e) =>
                new TRPCError({
                  code: "INTERNAL_SERVER_ERROR",
                  message: "Failed to parse excel",
                  cause: e,
                }),
            });

            if (parsedData.parseErrors.length > 0) {
              const errorBuffer = yield* Effect.tryPromise({
                try: () => {
                  const summary: Record<
                    string,
                    { processed: number; success: number; failed: number }
                  > = {
                    jabatan: {
                      processed: parsedData.jabatan.length,
                      success: parsedData.jabatan.length,
                      failed: 0,
                    },
                    pegawai: {
                      processed: parsedData.pegawai.length,
                      success: parsedData.pegawai.length,
                      failed: 0,
                    },
                    sertifikasiPegawai: {
                      processed: parsedData.sertifikasi.length,
                      success: parsedData.sertifikasi.length,
                      failed: 0,
                    },
                  };

                  for (const err of parsedData.parseErrors) {
                    const sheetKey =
                      Object.keys(summary).find((k) =>
                        k
                          .toLowerCase()
                          .includes(
                            (
                              err.sheet.split(" ")[0] || err.sheet
                            ).toLowerCase(),
                          ),
                      ) || err.sheet;
                    if (!summary[sheetKey]) {
                      summary[sheetKey] = {
                        processed: 0,
                        success: 0,
                        failed: 0,
                      };
                    }
                    summary[sheetKey].failed += 1;
                    summary[sheetKey].processed += 1;
                  }

                  return buildKepegawaianErrorReport({
                    summary,
                    errors: parsedData.parseErrors,
                  });
                },
                catch: (e) =>
                  new TRPCError({
                    code: "INTERNAL_SERVER_ERROR",
                    message: "Failed to build error report",
                    cause: e,
                  }),
              });

              return {
                success: false,
                hasErrors: true,
                errorCount: parsedData.parseErrors.length,
                errorReportBase64: errorBuffer.toString("base64"),
                summary: null,
              };
            }

            const importResult = yield* kepegawaianExcelQueries.importFromParsedData(
              parsedData,
              ctx.user.id,
              ctx.user.email,
            );

            // Jika ada error pada proses upsert di database yang kita masukkan ke importResult.errors
            if (importResult.errors.length > 0) {
               const errorBuffer = yield* Effect.tryPromise({
                 try: () => buildKepegawaianErrorReport({
                    summary: importResult.summary,
                    errors: importResult.errors,
                  }),
                  catch: (e) => new TRPCError({
                    code: "INTERNAL_SERVER_ERROR",
                    message: "Failed to build error report for db errors",
                    cause: e,
                  }),
               });

               return {
                  success: false, // true partially actually, but we want UI to show report
                  hasErrors: true,
                  errorCount: importResult.errors.length,
                  errorReportBase64: errorBuffer.toString("base64"),
                  summary: importResult.summary,
               };
            }

            return {
              success: true,
              hasErrors: false,
              errorCount: 0,
              summary: importResult.summary,
            };
          }),
        ),
    ),

  exportData: withPermission("kepegawaian-import-export.read").query(
    async () =>
      await runEffect(
        Effect.gen(function* () {
          const data = yield* kepegawaianExcelQueries.exportAllData();

          const exportData = {
            jabatan: data.jabatan,
            pegawai: data.pegawai,
            sertifikasi: data.sertifikasi,
          };

          const buffer = yield* Effect.tryPromise<Buffer, TRPCError>({
            try: () => buildKepegawaianExportWorkbook(exportData),
            catch: (e) =>
              new TRPCError({
                code: "INTERNAL_SERVER_ERROR",
                message: "Failed to build excel",
                cause: e,
              }),
          });

          return {
            buffer: buffer.toString("base64"),
            filename: `Export_Master_Kepegawaian_${new Date().toISOString().split("T")[0]}.xlsx`,
          };
        }),
      ),
  ),
});

// ##################
// end authored
// ##################
