// ##################
// authored (generated by claude, Jun 14 2026 20:30 WITA)
// ##################

import mediaPublicationsSchema from "@tepian-k3/schema/platform/media-publications.schema";
import {
  createTRPCRouter,
  formDataInput,
  formDataProcedure,
  withPermission,
  withRateLimit,
} from "../..";
import mediaPublicationsQueries from "@tepian-k3/queries/platform/media-publications.queries";
import z from "zod";
import { TRPCError } from "@trpc/server";
import { runEffect } from "../../utils/run-effect";
import { rateLimiters } from "@tepian-k3/services/rate-limiter";
import { CACHE_KEYS, CACHE_TTL } from "@tepian-k3/constants";
import { withCache, withCacheInvalidation } from "../../utils/cache-helper";
import { Effect } from "effect";
import {
  processAndUploadImage,
  processAndUploadImageIfPresent,
} from "../../utils/image-upload";

export const mediaPublicationsRouter = createTRPCRouter({
  getPublicOffsetPaginatedMedia: withRateLimit(rateLimiters.moderate())
    .input(mediaPublicationsSchema.getAllMediaSchema)
    .query(async ({ input }) => {
      // Force public filter constraints
      const publicInput = {
        ...input,
        isPublished: true,
        showDeleted: false,
      };

      const { data, pageCount } = await runEffect(
        mediaPublicationsQueries.getOffsetPaginatedMedia(publicInput),
      );

      return { data, pageCount };
    }),

  getPublicMediaById: withRateLimit(rateLimiters.moderate())
    .input(
      z.object({
        id: z.uuidv7(),
      }),
    )
    .query(
      async ({ ctx, input }) =>
        await withCache(
          `${CACHE_KEYS.MEDIA_PREFIX}${input.id}`,
          CACHE_TTL.MEDIUM,
          async () => {
            const mediaItem = await runEffect(
              mediaPublicationsQueries.getPublishedMediaById(input.id),
            );

            if (!mediaItem) {
              throw new TRPCError({
                code: "NOT_FOUND",
                message: "Media dan publikasi tidak ditemukan",
              });
            }

            return mediaItem;
          },
          () => ctx.c.header("X-Data-Source", "cache"),
        ),
    ),

  getPaginatedMedia: withPermission("media-publications.view")
    .input(mediaPublicationsSchema.getAllMediaSchema)
    .query(async ({ input }) => {
      const { data, pageCount } = await runEffect(
        mediaPublicationsQueries.getOffsetPaginatedMedia(input),
      );

      return { data, pageCount };
    }),

  getMediaById: withPermission("media-publications.read")
    .input(
      z.object({
        id: z.uuidv7(),
      }),
    )
    .query(async ({ input }) => {
      const mediaItem = await runEffect(
        mediaPublicationsQueries.getMediaById(input.id),
      );

      if (!mediaItem) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Media dan publikasi tidak ditemukan",
        });
      }

      return mediaItem;
    }),

  createMedia: withPermission("media-publications.create")
    .input(formDataInput)
    .use(formDataProcedure(mediaPublicationsSchema.createMediaSchema))
    .mutation(
      async ({ ctx }) =>
        await withCacheInvalidation([CACHE_KEYS.MEDIA_ALL], () =>
          runEffect(
            Effect.gen(function* () {
              const uploadedFile = yield* processAndUploadImage(
                ctx.input.data.image,
                {
                  folder: "media",
                },
              );

              const { image, ...dataWithoutImage } = ctx.input.data;

              const result = yield* mediaPublicationsQueries.createMedia(
                dataWithoutImage,
                uploadedFile.key,
              );

              return result;
            }),
          ),
        ),
    ),

  updateMedia: withPermission("media-publications.update")
    .input(formDataInput)
    .use(formDataProcedure(mediaPublicationsSchema.updateMediaSchema))
    .mutation(
      async ({ ctx }) =>
        await withCacheInvalidation(
          [
            CACHE_KEYS.MEDIA_ALL,
            `${CACHE_KEYS.MEDIA_PREFIX}${ctx.input.data.id}`,
          ],
          () =>
            runEffect(
              Effect.gen(function* () {
                const imageUrl = yield* processAndUploadImageIfPresent(
                  ctx.input.data.image,
                  { folder: "media" },
                );

                const { image, ...dataWithoutImage } = ctx.input.data;

                const result = yield* mediaPublicationsQueries.updateMedia(
                  dataWithoutImage,
                  imageUrl,
                );

                return result;
              }),
            ),
        ),
    ),

  deleteMedia: withPermission("media-publications.delete")
    .input(
      z.object({
        id: z.uuidv7(),
      }),
    )
    .mutation(
      async ({ input }) =>
        await withCacheInvalidation(
          [CACHE_KEYS.MEDIA_ALL, `${CACHE_KEYS.MEDIA_PREFIX}${input.id}`],
          () => runEffect(mediaPublicationsQueries.deleteMedia(input.id)),
        ),
    ),

  restoreMedia: withPermission("media-publications.delete")
    .input(
      z.object({
        id: z.uuidv7(),
      }),
    )
    .mutation(
      async ({ input }) =>
        await withCacheInvalidation(
          [CACHE_KEYS.MEDIA_ALL, `${CACHE_KEYS.MEDIA_PREFIX}${input.id}`],
          () =>
            runEffect(mediaPublicationsQueries.restoreDeletedMedia(input.id)),
        ),
    ),

  hardDeleteMedia: withPermission("media-publications.delete")
    .input(
      z.object({
        id: z.uuidv7(),
      }),
    )
    .mutation(
      async ({ input }) =>
        await withCacheInvalidation(
          [CACHE_KEYS.MEDIA_ALL, `${CACHE_KEYS.MEDIA_PREFIX}${input.id}`],
          () => runEffect(mediaPublicationsQueries.hardDeleteMedia(input.id)),
        ),
    ),
});

// ##################
// end authored
// ##################
