import { createFileRoute } from "@tanstack/react-router";
import { requirePermission } from "@/utils/require-permission";
import { z } from "zod";
import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { trpc } from "@/utils/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import {
  IconUsers,
  IconLoader2,
  IconCircleCheck,
  IconCircleX,
  IconSearch,
  IconDownload,
  IconChevronLeft,
  IconChevronRight,
  IconEye,
} from "@tabler/icons-react";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import ImageWithFallback from "@/components/image-with-fallback";

export const Route = createFileRoute(
  "/(core)/back-office/pelatihan/$pelatihanId/peserta",
)({
  params: z.object({
    pelatihanId: z.string(),
  }),
  beforeLoad: async ({ context }) =>
    await requirePermission(context, { permission: "pelatihan.view" }),
  component: PesertaTab,
});

const statusConfig: Record<
  string,
  { label: string; cls: string; Icon: typeof IconUsers }
> = {
  enrolled: {
    label: "Terdaftar",
    cls: "bg-slate-100 text-slate-600",
    Icon: IconUsers,
  },
  in_progress: {
    label: "Berjalan",
    cls: "bg-blue-100 text-blue-700",
    Icon: IconLoader2,
  },
  completed: {
    label: "Selesai",
    cls: "bg-emerald-100 text-emerald-700",
    Icon: IconCircleCheck,
  },
  failed: {
    label: "Tidak Lulus",
    cls: "bg-red-100 text-red-700",
    Icon: IconCircleX,
  },
  expired: {
    label: "Kedaluwarsa",
    cls: "bg-amber-100 text-amber-700",
    Icon: IconCircleX,
  },
};

function ProgressBar({ value }: { value: number }) {
  return (
    <div className="flex min-w-[90px] items-center gap-2">
      <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-100">
        <div
          className={`h-full rounded-full transition-all ${
            value === 100 ? "bg-emerald-500" : "bg-blue-500"
          }`}
          style={{ width: `${value}%` }}
        />
      </div>
      <span className="w-7 shrink-0 text-right text-[10px] font-semibold text-slate-500">
        {value}%
      </span>
    </div>
  );
}

function ScoreCell({ score }: { score: number | null }) {
  if (score === null || score === undefined)
    return <span className="text-xs font-medium text-slate-300">—</span>;
  return (
    <span
      className={`text-xs font-bold ${
        score >= 70 ? "text-emerald-600" : "text-red-500"
      }`}
    >
      {score}
    </span>
  );
}

function PesertaTab() {
  const { pelatihanId } = Route.useParams();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [page, setPage] = useState(1);
  const perPage = 10;

  const [rejectingEnrollmentId, setRejectingEnrollmentId] = useState<
    string | null
  >(null);
  const [rejectionReason, setRejectionReason] = useState("");
  // ##################
  // authored (generated by claude, Jun 10 2026 05:25 WITA)
  // ##################
  const [reviewingEnrollment, setReviewingEnrollment] = useState<any | null>(
    null,
  );
  // ##################
  // end authored
  // ##################

  // Fetch real enrollments
  const { data, isLoading, error, refetch } = useQuery(
    trpc.pelatihan.enrollment.getAllEnrollments.queryOptions({
      pelatihanId,
      page,
      perPage,
      search,
      status: statusFilter === "all" ? undefined : (statusFilter as any),
    }),
  );

  const verifyMutation = useMutation(
    trpc.pelatihan.enrollment.verifyEnrollment.mutationOptions({
      onSuccess: () => {
        toast.success("Status verifikasi berhasil diperbarui");
        setRejectingEnrollmentId(null);
        setRejectionReason("");
        refetch();
      },
      onError: (err) => {
        toast.error(`Gagal melakukan verifikasi: ${err.message}`);
      },
    }),
  );

  const handleReject = () => {
    if (!rejectingEnrollmentId) return;
    if (!rejectionReason.trim()) {
      toast.error("Alasan penolakan wajib diisi");
      return;
    }
    verifyMutation.mutate({
      enrollmentId: rejectingEnrollmentId,
      status: "rejected",
      rejectionReason: rejectionReason.trim(),
    });
  };

  const enrollments = data?.data ?? [];
  const pagination = data?.pagination ?? {
    page: 1,
    perPage: 10,
    totalPages: 1,
    totalItems: 0,
  };

  // We can count stats dynamically based on the current search scope or default
  // To keep it clean, let's derive stats from returned items or simple count aggregates
  const totalItems = pagination.totalItems;
  const inProgressCount = enrollments.filter(
    (e) => e.status === "in_progress",
  ).length;
  const completedCount = enrollments.filter(
    (e) => e.status === "completed",
  ).length;
  const failedCount = enrollments.filter((e) => e.status === "failed").length;

  const statCards = [
    {
      key: "total",
      label: "Total Peserta",
      value: totalItems,
      Icon: IconUsers,
      color: "text-blue-600",
      bg: "bg-blue-50",
    },
    {
      key: "progress",
      label: "Sedang Berjalan",
      value: inProgressCount,
      Icon: IconLoader2,
      color: "text-violet-600",
      bg: "bg-violet-50",
    },
    {
      key: "done",
      label: "Selesai",
      value: completedCount,
      Icon: IconCircleCheck,
      color: "text-emerald-600",
      bg: "bg-emerald-50",
    },
    {
      key: "fail",
      label: "Tidak Lulus",
      value: failedCount,
      Icon: IconCircleX,
      color: "text-red-500",
      bg: "bg-red-50",
    },
  ];

  const formatDate = (dateStr: string) => {
    try {
      const date = new Date(dateStr);
      return date.toLocaleDateString("id-ID", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      });
    } catch {
      return dateStr;
    }
  };

  return (
    <div className="space-y-4">
      {/* Stat Cards */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {statCards.map((stat) => (
          <div
            key={stat.key}
            className="flex items-center gap-3 rounded-xl border border-[#E2E8F0] bg-white p-4 shadow-sm"
          >
            <div className={`rounded-xl p-2.5 ${stat.bg} shrink-0`}>
              <stat.Icon className={`size-5 ${stat.color}`} />
            </div>
            <div>
              <p className="text-xs font-medium text-[#768094]">{stat.label}</p>
              <p className="text-xl font-bold text-[#334155]">
                {isLoading ? (
                  <Skeleton className="mt-0.5 h-6 w-10" />
                ) : (
                  stat.value
                )}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Search + Filter + Export */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="relative max-w-sm flex-1">
          <IconSearch className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setPage(1); // Reset page to 1
            }}
            placeholder="Cari nama atau email..."
            className="h-9 w-full rounded-lg border border-[#E2E8F0] bg-white pr-4 pl-9 text-sm text-[#475569] transition-colors placeholder:text-slate-400 focus:border-[#1061D6] focus:outline-none"
          />
        </div>
        <div className="flex items-center gap-2">
          {/* Status Filter */}
          <div className="w-40">
            <Select
              value={statusFilter}
              onValueChange={(val) => {
                setStatusFilter(val);
                setPage(1);
              }}
            >
              <SelectTrigger className="h-9 rounded-lg border-[#E2E8F0] text-xs">
                <SelectValue placeholder="Semua Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Semua Status</SelectItem>
                <SelectItem value="enrolled">Terdaftar</SelectItem>
                <SelectItem value="in_progress">Berjalan</SelectItem>
                <SelectItem value="completed">Selesai</SelectItem>
                <SelectItem value="failed">Tidak Lulus</SelectItem>
                <SelectItem value="expired">Kedaluwarsa</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Button
            variant="outline"
            size="sm"
            className="h-9 gap-1.5 border-[#E2E8F0] px-3 text-xs text-[#768094] hover:text-[#475569]"
          >
            <IconDownload className="size-3.5" />
            Export
          </Button>
        </div>
      </div>

      {/* Data Table */}
      <div className="overflow-hidden rounded-xl border border-[#E2E8F0] bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[850px] text-left">
            <thead>
              <tr className="border-b border-slate-100 bg-slate-50/50">
                <th className="w-10 px-5 py-4 text-xs font-semibold text-[#768094]">
                  No
                </th>
                <th className="px-5 py-4 text-xs font-semibold text-[#768094]">
                  Nama Peserta
                </th>
                <th className="px-5 py-4 text-xs font-semibold text-[#768094]">
                  Status
                </th>
                <th className="px-5 py-4 text-xs font-semibold text-[#768094]">
                  Progress
                </th>
                <th className="w-24 px-5 py-4 text-center text-xs font-semibold text-[#768094]">
                  Pre-Test
                </th>
                <th className="w-24 px-5 py-4 text-center text-xs font-semibold text-[#768094]">
                  Post-Test
                </th>
                <th className="px-5 py-4 text-xs font-semibold text-[#768094]">
                  Terdaftar
                </th>
                <th className="px-5 py-4 text-xs font-semibold text-[#768094]">
                  Verifikasi & Berkas
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {isLoading ? (
                Array.from({ length: 5 }).map((_, idx) => (
                  <tr key={idx}>
                    <td colSpan={8} className="px-5 py-4">
                      <Skeleton className="h-6 w-full" />
                    </td>
                  </tr>
                ))
              ) : enrollments.length === 0 ? (
                <tr>
                  <td
                    colSpan={8}
                    className="px-5 py-12 text-center text-xs font-medium text-[#768094]"
                  >
                    Tidak ada peserta terdaftar untuk course ini.
                  </td>
                </tr>
              ) : (
                enrollments.map((row: any, i: number) => {
                  const badge =
                    statusConfig[row.status] ?? statusConfig.enrolled!;
                  const userObj = row.user ?? {
                    name: "Pengguna Tepian",
                    email: "-",
                  };

                  return (
                    <tr
                      key={row.id}
                      className="transition-colors hover:bg-slate-50/50"
                    >
                      <td className="px-5 py-4 text-xs font-semibold text-[#768094]">
                        {(page - 1) * perPage + i + 1}
                      </td>
                      <td className="px-5 py-4">
                        <p className="text-xs font-semibold text-[#334155]">
                          {row.participantName || userObj.name}
                        </p>
                        <p className="mt-0.5 text-[10px] text-[#768094]">
                          {row.participantEmail || userObj.email}
                        </p>
                        {/* Documents Links */}
                        {(row.employmentLetterUrl ||
                          row.consentLetterUrl ||
                          row.diplomaUrl) && (
                          <div className="mt-1 flex flex-wrap items-center gap-2">
                            {row.employmentLetterUrl && (
                              <a
                                href={row.employmentLetterUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="animate-fade-in inline-flex items-center gap-0.5 text-[10px] text-blue-600 hover:underline"
                              >
                                <IconDownload className="size-2.5" /> SK Kerja
                              </a>
                            )}
                            {row.consentLetterUrl && (
                              <a
                                href={row.consentLetterUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="animate-fade-in inline-flex items-center gap-0.5 text-[10px] text-blue-600 hover:underline"
                              >
                                <IconDownload className="size-2.5" /> Kesediaan
                              </a>
                            )}
                            {row.diplomaUrl && (
                              <a
                                href={row.diplomaUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="animate-fade-in inline-flex items-center gap-0.5 text-[10px] text-blue-600 hover:underline"
                              >
                                <IconDownload className="size-2.5" /> Ijazah
                              </a>
                            )}
                          </div>
                        )}
                      </td>
                      <td className="px-5 py-4">
                        <span
                          className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${badge.cls}`}
                        >
                          {badge.label}
                        </span>
                      </td>
                      <td className="px-5 py-4">
                        <ProgressBar value={row.progressPercentage ?? 0} />
                      </td>
                      <td className="px-5 py-4 text-center">
                        <ScoreCell score={row.preTestScore} />
                      </td>
                      <td className="px-5 py-4 text-center">
                        <ScoreCell score={row.postTestScore} />
                      </td>
                      <td className="px-5 py-4 text-xs font-medium whitespace-nowrap text-[#768094]">
                        {formatDate(row.enrolledAt)}
                      </td>
                      <td className="px-5 py-4">
                        <div className="flex items-center gap-2">
                          {row.verificationStatus === "verified" ? (
                            <div className="flex items-center gap-1.5">
                              <Badge className="bg-emerald-100 font-semibold text-emerald-800 hover:bg-emerald-100">
                                Disetujui
                              </Badge>
                              {/* ##################
                                  authored (generated by claude, Jun 10 2026 05:25 WITA)
                              ################## */}
                              <Button
                                size="sm"
                                variant="ghost"
                                className="h-7 w-7 rounded-lg p-0 text-slate-400 hover:bg-slate-100 hover:text-slate-700"
                                onClick={() => setReviewingEnrollment(row)}
                                title="Lihat Detail Berkas"
                              >
                                <IconEye className="size-3.5" />
                              </Button>
                              {/* ##################
                                  end authored
                              ################## */}
                            </div>
                          ) : row.verificationStatus?.startsWith("rejected") ? (
                            <div className="flex items-center gap-1.5">
                              <div className="animate-fade-in flex flex-col gap-0.5">
                                <Badge className="bg-rose-100 font-semibold text-rose-800 hover:bg-rose-100">
                                  Ditolak
                                </Badge>
                                {row.rejectionReason && (
                                  <span
                                    className="max-w-[150px] truncate text-[9px] text-[#768094]"
                                    title={row.rejectionReason}
                                  >
                                    Alasan: {row.rejectionReason}
                                  </span>
                                )}
                              </div>
                              {/* ##################
                                  authored (generated by claude, Jun 10 2026 05:25 WITA)
                              ################## */}
                              <Button
                                size="sm"
                                variant="ghost"
                                className="h-7 w-7 rounded-lg p-0 text-slate-400 hover:bg-slate-100 hover:text-slate-700"
                                onClick={() => setReviewingEnrollment(row)}
                                title="Lihat Detail Berkas"
                              >
                                <IconEye className="size-3.5" />
                              </Button>
                              {/* ##################
                                  end authored
                              ################## */}
                            </div>
                          ) : (
                            <div className="animate-fade-in flex items-center gap-1.5">
                              {/* ##################
                                  authored (generated by claude, Jun 10 2026 05:25 WITA)
                              ################## */}
                              <Button
                                size="sm"
                                variant="outline"
                                className="h-7 rounded-lg border-blue-200 bg-blue-50/50 px-2 text-[10px] font-bold text-blue-700 hover:bg-blue-100"
                                onClick={() => setReviewingEnrollment(row)}
                              >
                                <IconEye className="mr-1 size-3.5" />
                                Review
                              </Button>
                              {/* ##################
                                  end authored
                              ################## */}
                              <Button
                                size="sm"
                                variant="outline"
                                className="h-7 rounded-lg border-emerald-200 bg-emerald-50/50 px-2.5 text-[10px] font-bold text-emerald-700 hover:bg-emerald-100"
                                onClick={() => {
                                  if (
                                    confirm(
                                      `Apakah Anda yakin ingin menyetujui pendaftaran ${row.participantName || userObj.name}?`,
                                    )
                                  ) {
                                    verifyMutation.mutate({
                                      enrollmentId: row.id,
                                      status: "verified",
                                    });
                                  }
                                }}
                                disabled={verifyMutation.isPending}
                              >
                                Setujui
                              </Button>
                              <Button
                                size="sm"
                                variant="outline"
                                className="h-7 rounded-lg border-rose-200 bg-rose-50/50 px-2.5 text-[10px] font-bold text-rose-700 hover:bg-rose-100"
                                onClick={() => setRejectingEnrollmentId(row.id)}
                                disabled={verifyMutation.isPending}
                              >
                                Tolak
                              </Button>
                            </div>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination Footer */}
        {!isLoading && enrollments.length > 0 && (
          <div className="flex items-center justify-between border-t border-slate-100 bg-white px-5 py-3">
            <span className="text-xs font-medium text-[#768094]">
              Menampilkan {(page - 1) * perPage + 1} -{" "}
              {Math.min(page * perPage, pagination.totalItems)} dari{" "}
              {pagination.totalItems} peserta
            </span>
            <div className="flex items-center gap-1">
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8 border-[#E2E8F0] text-[#768094] hover:text-[#334155]"
                disabled={page === 1}
                onClick={() => setPage((p) => Math.max(1, p - 1))}
              >
                <IconChevronLeft className="size-4" />
              </Button>
              <span className="px-3 text-xs font-semibold text-[#334155]">
                {page} / {pagination.totalPages}
              </span>
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8 border-[#E2E8F0] text-[#768094] hover:text-[#334155]"
                disabled={page === pagination.totalPages}
                onClick={() =>
                  setPage((p) => Math.min(pagination.totalPages, p + 1))
                }
              >
                <IconChevronRight className="size-4" />
              </Button>
            </div>
          </div>
        )}
      </div>

      {/* Dialog Penolakan Pendaftaran */}
      <Dialog
        open={!!rejectingEnrollmentId}
        onOpenChange={(open) => {
          if (!open) {
            setRejectingEnrollmentId(null);
            setRejectionReason("");
          }
        }}
      >
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Tolak Pendaftaran Peserta</DialogTitle>
            <DialogDescription>
              Berikan alasan mengapa pendaftaran ini ditolak. Alasan ini akan
              ditampilkan kepada peserta di dashboard mereka.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <Textarea
              value={rejectionReason}
              onChange={(e) => setRejectionReason(e.target.value)}
              placeholder="Contoh: Berkas SK Kerja tidak terbaca atau tidak valid. Silakan unggah ulang."
              rows={4}
              className="w-full rounded-lg"
            />
          </div>
          <DialogFooter className="flex gap-2 sm:justify-end">
            <Button
              variant="outline"
              onClick={() => {
                setRejectingEnrollmentId(null);
                setRejectionReason("");
              }}
              disabled={verifyMutation.isPending}
            >
              Batal
            </Button>
            <Button
              className="bg-rose-600 text-white hover:bg-rose-700"
              onClick={handleReject}
              disabled={verifyMutation.isPending || !rejectionReason.trim()}
            >
              {verifyMutation.isPending ? "Memproses..." : "Kirim & Tolak"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Dialog Detail Review Berkas Pendaftaran */}
      {/* ##################
          authored (generated by claude, Jun 10 2026 05:25 WITA)
      ################## */}
      <Dialog
        open={!!reviewingEnrollment}
        onOpenChange={(open) => !open && setReviewingEnrollment(null)}
      >
        <DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto font-['Poppins']">
          <DialogHeader>
            <DialogTitle className="text-lg font-bold text-slate-800">
              Review Berkas Pendaftaran
            </DialogTitle>
            <DialogDescription className="text-xs text-slate-500">
              Tinjau berkas persyaratan dan data profil peserta sebelum
              memberikan keputusan persetujuan.
            </DialogDescription>
          </DialogHeader>

          <div className="grid grid-cols-1 gap-6 py-4 md:grid-cols-2">
            {/* Kolom Kiri: Data Teks */}
            <div className="space-y-6">
              {/* Data Diri */}
              <div className="space-y-3 rounded-xl border border-slate-100 bg-slate-50/50 p-4">
                <div className="flex items-center gap-2 border-b border-slate-200/60 pb-2">
                  <span className="text-[#1061D6]">👤</span>
                  <h4 className="font-['Poppins'] text-xs font-bold tracking-wide text-slate-800 uppercase">
                    Data Diri Peserta
                  </h4>
                </div>
                <div className="grid grid-cols-2 gap-x-4 gap-y-2.5 text-xs text-slate-600">
                  <div className="col-span-2">
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Nama Lengkap
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.participantName ||
                        reviewingEnrollment?.user?.name ||
                        "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      NIK
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.participantNik || "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Golongan Darah
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.participantBloodType || "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Tempat Lahir
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.participantBirthPlace || "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Tanggal Lahir
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.participantBirthDate
                        ? new Date(
                            reviewingEnrollment.participantBirthDate,
                          ).toLocaleDateString("id-ID", {
                            day: "numeric",
                            month: "long",
                            year: "numeric",
                          })
                        : "—"}
                    </span>
                  </div>
                  <div className="col-span-2">
                    <span className="block text-[10px] font-semibold text-slate-400">
                      No. WhatsApp / HP
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.participantPhone || "—"}
                    </span>
                  </div>
                  <div className="col-span-2">
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Alamat Lengkap
                    </span>
                    <span className="block font-medium whitespace-pre-wrap text-slate-800">
                      {reviewingEnrollment?.participantAddress || "—"}
                    </span>
                  </div>
                </div>
              </div>

              {/* Data Perusahaan */}
              <div className="space-y-3 rounded-xl border border-slate-100 bg-slate-50/50 p-4">
                <div className="flex items-center gap-2 border-b border-slate-200/60 pb-2">
                  <span className="text-[#1061D6]">🏢</span>
                  <h4 className="font-['Poppins'] text-xs font-bold tracking-wide text-slate-800 uppercase">
                    Data Perusahaan Sponsor
                  </h4>
                </div>
                <div className="grid grid-cols-2 gap-x-4 gap-y-2.5 text-xs text-slate-600">
                  <div className="col-span-2">
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Nama Perusahaan
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.companyName || "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      KBLI Usaha
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.companyKbli || "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Kecamatan
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.companyDistrict?.name || "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Kota/Kabupaten
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.companyRegency?.name || "—"}
                    </span>
                  </div>
                  <div>
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Provinsi
                    </span>
                    <span className="font-bold text-slate-800">
                      {reviewingEnrollment?.companyProvince?.name || "—"}
                    </span>
                  </div>
                  <div className="col-span-2">
                    <span className="block text-[10px] font-semibold text-slate-400">
                      Alamat Perusahaan
                    </span>
                    <span className="block font-medium whitespace-pre-wrap text-slate-800">
                      {reviewingEnrollment?.companyAddress || "—"}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Kolom Kanan: Pratinjau Berkas */}
            <div className="space-y-4">
              <div className="h-full space-y-3 rounded-xl border border-slate-100 bg-slate-50/50 p-4">
                <div className="flex items-center gap-2 border-b border-slate-200/60 pb-2">
                  <span className="text-[#1061D6]">📄</span>
                  <h4 className="font-['Poppins'] text-xs font-bold tracking-wide text-slate-800 uppercase">
                    Berkas Persyaratan
                  </h4>
                </div>

                <div className="space-y-3">
                  {/* Pass Foto Latar Merah */}
                  {reviewingEnrollment?.passPhotoUrl ? (
                    <div className="space-y-3 rounded-xl border border-slate-200 bg-white p-3.5 shadow-sm">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-bold text-slate-700">
                          🔴 Pass Foto Latar Merah
                        </span>
                        <a
                          href={reviewingEnrollment.passPhotoUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center gap-1 text-[10px] font-bold text-blue-600 hover:underline"
                        >
                          Buka Tab Baru ↗
                        </a>
                      </div>
                      <div className="flex justify-center">
                        <div className="relative h-40 w-32 overflow-hidden rounded-lg border border-slate-200 bg-slate-50 shadow-inner">
                          <ImageWithFallback
                            src={reviewingEnrollment.passPhotoUrl}
                            alt="Pass Foto Latar Merah"
                            className="h-full w-full object-cover"
                          />
                          <div className="pointer-events-none absolute inset-0 bg-red-600/10 mix-blend-multiply" />
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="rounded-xl border border-dashed border-slate-200 bg-white p-3 text-center text-xs text-slate-400">
                      Pass Foto Latar Merah tidak diunggah / tidak diperlukan
                    </div>
                  )}

                  {/* Dokumen Lainnya */}
                  {[
                    {
                      label: "KTP (Kartu Identitas)",
                      url: reviewingEnrollment?.ktpDocUrl,
                      name: reviewingEnrollment?.ktpDocName,
                    },
                    {
                      label: "Surat Keterangan Kerja",
                      url: reviewingEnrollment?.employmentLetterUrl,
                      name: reviewingEnrollment?.employmentLetterName,
                    },
                    {
                      label: "Surat Pernyataan Kesediaan",
                      url: reviewingEnrollment?.consentLetterUrl,
                      name: reviewingEnrollment?.consentLetterName,
                    },
                    {
                      label: "Ijazah Terakhir",
                      url: reviewingEnrollment?.diplomaUrl,
                      name: reviewingEnrollment?.diplomaName,
                    },
                  ].map((doc, index) => (
                    <div key={index}>
                      {doc.url ? (
                        <div className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-white p-3 shadow-sm transition-colors hover:border-[#1061D6]/20">
                          <div className="min-w-0 flex-1">
                            <span className="block text-[10px] font-semibold text-slate-400">
                              {doc.label}
                            </span>
                            <span className="block truncate text-xs font-bold text-slate-700">
                              {doc.name || "File Terlampir"}
                            </span>
                          </div>
                          <a
                            href={doc.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-600 transition-colors hover:bg-blue-100"
                            title="Buka Berkas"
                          >
                            <IconDownload className="size-4" />
                          </a>
                        </div>
                      ) : (
                        <div className="rounded-xl border border-dashed border-slate-200 bg-white p-3 text-center text-xs text-slate-400">
                          {doc.label} tidak diunggah / tidak diperlukan
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <DialogFooter className="gap-3 border-t border-slate-100 pt-5 sm:gap-0">
            <Button
              type="button"
              variant="outline"
              onClick={() => setReviewingEnrollment(null)}
              className="h-10 rounded-xl"
            >
              Tutup
            </Button>

            {reviewingEnrollment?.verificationStatus === "pending" && (
              <div className="flex gap-2">
                <Button
                  type="button"
                  onClick={() => {
                    setRejectingEnrollmentId(reviewingEnrollment.id);
                    setReviewingEnrollment(null);
                  }}
                  className="h-10 rounded-xl border border-rose-200 bg-rose-50 px-4 font-semibold text-rose-700 hover:bg-rose-100"
                >
                  Tolak Berkas
                </Button>
                <Button
                  type="button"
                  onClick={() => {
                    if (
                      confirm(
                        `Apakah Anda yakin ingin menyetujui pendaftaran ${reviewingEnrollment.participantName || reviewingEnrollment.user?.name || "peserta"}?`,
                      )
                    ) {
                      verifyMutation.mutate({
                        enrollmentId: reviewingEnrollment.id,
                        status: "verified",
                      });
                      setReviewingEnrollment(null);
                    }
                  }}
                  disabled={verifyMutation.isPending}
                  className="h-10 rounded-xl bg-emerald-600 px-4 font-semibold text-white hover:bg-emerald-700"
                >
                  Setujui Berkas
                </Button>
              </div>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>
      {/* ##################
          end authored
      ################## */}
    </div>
  );
}

// ##################
// end authored
// ##################
