// ##################
// authored (generated by gemini, Jun 03 2026 22:55 WITA)
// ##################

import { createFileRoute } from "@tanstack/react-router";
import { requirePermission } from "@/utils/require-permission";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, trpc } from "@/utils/trpc";
import { cn } from "@/lib/utils";
import {
  Plus,
  Pencil,
  Trash2,
  HelpCircle,
  Clock,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import { globalErrorToast, globalSuccessToast } from "@/lib/toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type AssessmentQuestionOption = {
  id: string;
  optionText: string;
  isCorrect: boolean;
};

type AssessmentQuestion = {
  id: string;
  questionText: string;
  type: "multiple_choice" | "true_false" | "essay";
  points: number | null;
  options: AssessmentQuestionOption[];
  orderIndex: number | null;
};

type Assessment = {
  id: string;
  pelatihanId: string;
  type: "pre_test" | "post_test";
  title: string;
  description: string | null;
  passingScore: number | null;
  timeLimit: number | null;
  maxAttempts: number | null;
  randomizeQuestions: boolean | null;
  questions: AssessmentQuestion[];
};

type AssessmentWithType = Assessment & { type: "pre_test" | "post_test" };

export const Route = createFileRoute(
  "/(core)/back-office/pelatihan/$pelatihanId/quiz",
)({
  params: z.object({
    pelatihanId: z.string(),
  }),
  beforeLoad: async ({ context }) =>
    await requirePermission(context, { permission: "pelatihan.view" }),
  component: QuizTab,
});

const typeLabel: Record<string, { label: string; cls: string }> = {
  pre_test: {
    label: "Pre-Test",
    cls: "bg-amber-50 text-amber-700 border-amber-200",
  },
  post_test: {
    label: "Post-Test",
    cls: "bg-violet-50 text-violet-700 border-violet-200",
  },
};

const qTypeLabel: Record<string, string> = {
  multiple_choice: "Pilihan Ganda",
  true_false: "Benar/Salah",
  essay: "Esai",
};

/**
 * Komponen utama tab Quiz dan Evaluasi pada halaman detail pelatihan back-office.
 *
 * @returns React element
 */
function QuizTab() {
  const { pelatihanId } = Route.useParams();
  const [expandedId, setExpandedId] = useState<string | null>(null);

  // Dialog open states
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isEditOpen, setIsEditOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [isAddQuestionOpen, setIsAddQuestionOpen] = useState(false);
  const [isDeleteQuestionOpen, setIsDeleteQuestionOpen] = useState(false);

  // Selected item states
  const [selectedAssessment, setSelectedAssessment] =
    useState<Assessment | null>(null);
  const [selectedQuestion, setSelectedQuestion] =
    useState<AssessmentQuestion | null>(null);

  // Form states
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [passingScore, setPassingScore] = useState(70);
  const [timeLimit, setTimeLimit] = useState("");
  const [maxAttempts, setMaxAttempts] = useState("");
  const [randomizeQuestions, setRandomizeQuestions] = useState(false);
  const [assessmentType, setAssessmentType] = useState<
    "pre_test" | "post_test"
  >("pre_test");

  // Question form states
  const [questionText, setQuestionText] = useState("");
  const [questionType, setQuestionType] = useState<
    "multiple_choice" | "true_false" | "essay"
  >("multiple_choice");
  const [points, setPoints] = useState(10);
  const [options, setOptions] = useState<
    Array<{ optionText: string; isCorrect: boolean }>
  >([
    { optionText: "", isCorrect: false },
    { optionText: "", isCorrect: false },
    { optionText: "", isCorrect: false },
    { optionText: "", isCorrect: false },
  ]);

  // Query Pre-Test
  const {
    data: preTest,
    isLoading: isPreLoading,
    refetch: refetchPre,
  } = useQuery({
    ...trpc.pelatihan.assessment.getAssessmentByPelatihan.queryOptions({
      pelatihanId,
      type: "pre_test",
    }),
    retry: false,
  });

  // Query Post-Test
  const {
    data: postTest,
    isLoading: isPostLoading,
    refetch: refetchPost,
  } = useQuery({
    ...trpc.pelatihan.assessment.getAssessmentByPelatihan.queryOptions({
      pelatihanId,
      type: "post_test",
    }),
    retry: false,
  });

  const isLoading = isPreLoading || isPostLoading;

  // Invalidate handler
  const invalidateQueries = async () => {
    await queryClient.invalidateQueries(
      trpc.pelatihan.assessment.getAssessmentByPelatihan.queryOptions({
        pelatihanId,
        type: "pre_test",
      }),
    );
    await queryClient.invalidateQueries(
      trpc.pelatihan.assessment.getAssessmentByPelatihan.queryOptions({
        pelatihanId,
        type: "post_test",
      }),
    );
  };

  // Mutations
  const createMutation = useMutation(
    trpc.pelatihan.assessment.createAssessment.mutationOptions({
      onSuccess: async () => {
        globalSuccessToast("Ujian berhasil dibuat");
        await invalidateQueries();
        setIsCreateOpen(false);
      },
      onError: (err) => {
        globalErrorToast(err.message, "Gagal membuat ujian");
      },
    }),
  );

  const updateMutation = useMutation(
    trpc.pelatihan.assessment.updateAssessment.mutationOptions({
      onSuccess: async () => {
        globalSuccessToast("Ujian berhasil diperbarui");
        await invalidateQueries();
        setIsEditOpen(false);
      },
      onError: (err) => {
        globalErrorToast(err.message, "Gagal memperbarui ujian");
      },
    }),
  );

  const deleteMutation = useMutation(
    trpc.pelatihan.assessment.deleteAssessment.mutationOptions({
      onSuccess: async () => {
        globalSuccessToast("Ujian berhasil dihapus");
        await invalidateQueries();
        setIsDeleteOpen(false);
      },
      onError: (err) => {
        globalErrorToast(err.message, "Gagal menghapus ujian");
      },
    }),
  );

  const addQuestionMutation = useMutation(
    trpc.pelatihan.assessment.addQuestion.mutationOptions({
      onSuccess: async () => {
        globalSuccessToast("Soal berhasil ditambahkan");
        await invalidateQueries();
        setIsAddQuestionOpen(false);
      },
      onError: (err) => {
        globalErrorToast(err.message, "Gagal menambahkan soal");
      },
    }),
  );

  const deleteQuestionMutation = useMutation(
    trpc.pelatihan.assessment.deleteQuestion.mutationOptions({
      onSuccess: async () => {
        globalSuccessToast("Soal berhasil dihapus");
        await invalidateQueries();
        setIsDeleteQuestionOpen(false);
      },
      onError: (err) => {
        globalErrorToast(err.message, "Gagal menghapus soal");
      },
    }),
  );

  const toggleExpand = (id: string) =>
    setExpandedId((prev) => (prev === id ? null : id));

  // Dialog helpers
  const openCreateDialog = (type: "pre_test" | "post_test") => {
    setAssessmentType(type);
    setTitle(type === "pre_test" ? "Pre-Test" : "Post-Test");
    setDescription("");
    setPassingScore(70);
    setTimeLimit("60");
    setMaxAttempts("3");
    setRandomizeQuestions(false);
    setIsCreateOpen(true);
  };

  const openEditDialog = (assessment: Assessment) => {
    setSelectedAssessment(assessment);
    setTitle(assessment.title);
    setDescription(assessment.description ?? "");
    setPassingScore(assessment.passingScore ?? 70);
    setTimeLimit(assessment.timeLimit ? String(assessment.timeLimit) : "");
    setMaxAttempts(
      assessment.maxAttempts ? String(assessment.maxAttempts) : "",
    );
    setRandomizeQuestions(assessment.randomizeQuestions ?? false);
    setIsEditOpen(true);
  };

  const openDeleteDialog = (assessment: Assessment) => {
    setSelectedAssessment(assessment);
    setIsDeleteOpen(true);
  };

  const openAddQuestionDialog = (assessment: Assessment) => {
    setSelectedAssessment(assessment);
    setQuestionText("");
    setQuestionType("multiple_choice");
    setPoints(10);
    setOptions([
      { optionText: "", isCorrect: false },
      { optionText: "", isCorrect: false },
      { optionText: "", isCorrect: false },
      { optionText: "", isCorrect: false },
    ]);
    setIsAddQuestionOpen(true);
  };

  const openDeleteQuestionDialog = (question: AssessmentQuestion) => {
    setSelectedQuestion(question);
    setIsDeleteQuestionOpen(true);
  };

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    createMutation.mutate({
      pelatihanId,
      type: assessmentType,
      title,
      description: description || null,
      passingScore,
      timeLimit: timeLimit ? Number(timeLimit) : null,
      maxAttempts: maxAttempts ? Number(maxAttempts) : null,
      randomizeQuestions,
      randomizeOptions: false,
    });
  };

  const handleEditSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedAssessment) return;
    updateMutation.mutate({
      id: selectedAssessment.id,
      title,
      description: description || null,
      passingScore,
      timeLimit: timeLimit ? Number(timeLimit) : null,
      maxAttempts: maxAttempts ? Number(maxAttempts) : null,
      randomizeQuestions,
    });
  };

  const handleDeleteSubmit = () => {
    if (!selectedAssessment) return;
    deleteMutation.mutate({ id: selectedAssessment.id });
  };

  const handleQuestionTypeChange = (
    val: "multiple_choice" | "true_false" | "essay",
  ) => {
    setQuestionType(val);
    if (val === "true_false") {
      setOptions([
        { optionText: "Benar", isCorrect: true },
        { optionText: "Salah", isCorrect: false },
      ]);
    } else if (val === "essay") {
      setOptions([]);
    } else {
      setOptions([
        { optionText: "", isCorrect: false },
        { optionText: "", isCorrect: false },
        { optionText: "", isCorrect: false },
        { optionText: "", isCorrect: false },
      ]);
    }
  };

  const handleAddQuestionSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedAssessment) return;

    // Validate multiple choice has at least one correct option
    if (questionType === "multiple_choice") {
      const hasCorrect = options.some((o) => o.isCorrect);
      if (!hasCorrect) {
        globalErrorToast(
          "Pilih minimal satu jawaban benar untuk pilihan ganda",
        );
        return;
      }
    }

    addQuestionMutation.mutate({
      assessmentId: selectedAssessment.id,
      questionText,
      type: questionType,
      points,
      options: options.filter((o) => o.optionText.trim() !== ""),
    });
  };

  const handleDeleteQuestionSubmit = () => {
    if (!selectedQuestion) return;
    deleteQuestionMutation.mutate({ id: selectedQuestion.id });
  };

  if (isLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-6 w-32" />
        <Skeleton className="h-32 w-full rounded-xl" />
        <Skeleton className="h-32 w-full rounded-xl" />
      </div>
    );
  }

  // Compile active assessments
  const assessments: AssessmentWithType[] = [];
  if (preTest) assessments.push({ ...(preTest as any), type: "pre_test" });
  if (postTest) assessments.push({ ...(postTest as any), type: "post_test" });

  const hasAssessments = assessments.length > 0;

  return (
    <div className="space-y-6">
      {/* Header Info */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-base font-bold text-[#1E293B]">
            Evaluasi & Quiz
          </h2>
          <p className="text-xs text-[#768094]">
            Kelola lembar ujian Pre-Test dan Post-Test untuk mengukur kompetensi
            peserta
          </p>
        </div>
        <Button
          onClick={() => openCreateDialog("pre_test")}
          className="h-10 gap-2 rounded-lg bg-[#1061D6] px-4 text-sm font-semibold text-white hover:bg-blue-700"
        >
          <Plus className="size-4" />
          Tambah Quiz
        </Button>
      </div>

      {/* Render Real Assessments */}
      {hasAssessments ? (
        <div className="space-y-4">
          {assessments.map((assessment) => {
            const typeCfg = typeLabel[assessment.type] ?? typeLabel.pre_test!;
            const isExpanded = expandedId === assessment.id;
            const questions = assessment.questions ?? [];

            return (
              <div
                key={assessment.id}
                className="overflow-hidden rounded-xl border border-[#E2E8F0] bg-white shadow-sm"
              >
                {/* Header Card */}
                <div className="flex items-center justify-between gap-4 p-5 transition-colors hover:bg-slate-50/50">
                  <div className="flex min-w-0 flex-1 items-center gap-4">
                    {/* Badge */}
                    <span
                      className={cn(
                        "shrink-0 rounded-full border px-3 py-1 text-xs font-semibold",
                        typeCfg.cls,
                      )}
                    >
                      {typeCfg.label}
                    </span>

                    {/* Title & Info */}
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm font-semibold text-[#334155]">
                        {assessment.title}
                      </p>
                      <div className="mt-1.5 flex flex-wrap items-center gap-4">
                        <div className="flex items-center gap-1 text-[10px] font-medium text-[#768094]">
                          <HelpCircle className="size-3.5" />
                          <span>{questions.length} soal</span>
                        </div>
                        {assessment.timeLimit && (
                          <div className="flex items-center gap-1 text-[10px] font-medium text-[#768094]">
                            <Clock className="size-3.5" />
                            <span>{assessment.timeLimit} menit</span>
                          </div>
                        )}
                        <span className="text-[10px] font-medium text-[#768094]">
                          Nilai Lulus: {assessment.passingScore}%
                        </span>
                        {assessment.randomizeQuestions && (
                          <span className="rounded-full border border-blue-100 bg-blue-50 px-2 py-0.5 text-[10px] font-semibold text-blue-600">
                            Acak Soal
                          </span>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex shrink-0 items-center gap-1">
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 text-[#768094] hover:bg-slate-100 hover:text-[#1061D6]"
                      title="Edit Quiz"
                      onClick={() => openEditDialog(assessment)}
                    >
                      <Pencil className="size-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 text-[#768094] hover:bg-red-50 hover:text-red-500"
                      title="Hapus Quiz"
                      onClick={() => openDeleteDialog(assessment)}
                    >
                      <Trash2 className="size-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 text-[#768094] hover:bg-slate-100"
                      onClick={() => toggleExpand(assessment.id)}
                      title={isExpanded ? "Tutup" : "Lihat Soal"}
                    >
                      {isExpanded ? (
                        <ChevronUp className="size-4" />
                      ) : (
                        <ChevronDown className="size-4" />
                      )}
                    </Button>
                  </div>
                </div>

                {/* Expandable Questions Table */}
                {isExpanded && (
                  <div className="border-t border-slate-100">
                    <div className="flex items-center justify-between bg-slate-50/50 px-5 py-3">
                      <p className="text-xs font-bold text-[#475569]">
                        Daftar Soal Ujian
                      </p>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => openAddQuestionDialog(assessment)}
                        className="h-7 gap-1 border-[#E2E8F0] text-xs text-[#1061D6] hover:bg-blue-50"
                      >
                        <Plus className="size-3" />
                        Tambah Soal
                      </Button>
                    </div>

                    {questions.length > 0 ? (
                      <table className="w-full min-w-[500px] text-left">
                        <thead>
                          <tr className="border-b border-slate-100 bg-slate-50/20">
                            <th className="w-8 px-5 py-2.5 text-[10px] font-semibold text-[#768094]">
                              No
                            </th>
                            <th className="px-5 py-2.5 text-[10px] font-semibold text-[#768094]">
                              Pertanyaan Soal
                            </th>
                            <th className="w-28 px-5 py-2.5 text-[10px] font-semibold text-[#768094]">
                              Tipe
                            </th>
                            <th className="w-20 px-5 py-2.5 text-[10px] font-semibold text-[#768094]">
                              Opsi
                            </th>
                            <th className="w-16 px-5 py-2.5 text-[10px] font-semibold text-[#768094]">
                              Poin
                            </th>
                            <th className="w-20 px-5 py-2.5 text-[10px] font-semibold text-[#768094]">
                              Aksi
                            </th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-50 bg-white">
                          {questions.map((q, i) => (
                            <tr
                              key={q.id}
                              className="transition-colors hover:bg-slate-50/50"
                            >
                              <td className="px-5 py-3 text-xs font-semibold text-[#768094]">
                                {i + 1}
                              </td>
                              <td className="max-w-[300px] px-5 py-3 text-xs font-medium text-[#334155]">
                                <p className="truncate">{q.questionText}</p>
                              </td>
                              <td className="px-5 py-3 text-xs text-[#64748B]">
                                {qTypeLabel[q.type] ?? q.type}
                              </td>
                              <td className="px-5 py-3 text-xs text-[#64748B]">
                                {q.options?.length ?? 0} opsi
                              </td>
                              <td className="px-5 py-3 text-xs font-semibold text-[#334155]">
                                {q.points}
                              </td>
                              <td className="px-5 py-3">
                                <div className="flex items-center gap-1">
                                  <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => openDeleteQuestionDialog(q)}
                                    className="h-6 w-6 text-[#768094] hover:text-red-500"
                                  >
                                    <Trash2 className="size-3.5" />
                                  </Button>
                                </div>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    ) : (
                      <div className="bg-white px-5 py-8 text-center text-xs font-medium text-[#768094]">
                        Belum ada pertanyaan soal dalam quiz ini. Klik "Tambah
                        Soal" untuk mulai menyusun.
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      ) : null}

      {/* Elegant state if either or both are missing */}
      {(!preTest || !postTest) && (
        <div className="space-y-4 rounded-xl border border-dashed border-[#E2E8F0] bg-slate-50 p-6">
          <div className="flex items-center gap-2">
            <HelpCircle className="size-5 text-[#1061D6]" />
            <h4 className="text-xs font-bold text-[#1E293B]">
              Konfigurasi Evaluasi Pembelajaran
            </h4>
          </div>
          <p className="max-w-lg text-xs text-[#64748B]">
            Untuk mengukur pemahaman peserta, Anda dapat menambahkan lembar
            evaluasi berupa ujian awal (Pre-Test) sebelum mengakses materi, dan
            ujian kompetensi akhir (Post-Test) sebagai prasyarat sertifikasi
            kelulusan.
          </p>
          <div className="flex items-center gap-2">
            {!preTest && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => openCreateDialog("pre_test")}
                className="h-8 rounded-lg border-[#E2E8F0] bg-white text-xs font-bold text-[#1061D6] hover:bg-blue-50"
              >
                Buat Pre-Test
              </Button>
            )}
            {!postTest && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => openCreateDialog("post_test")}
                className="h-8 rounded-lg border-[#E2E8F0] bg-white text-xs font-bold text-[#1061D6] hover:bg-blue-50"
              >
                Buat Post-Test
              </Button>
            )}
          </div>
        </div>
      )}

      {/* Complete empty state */}
      {!hasAssessments && (
        <div className="flex flex-col items-center gap-3 rounded-xl border border-[#E2E8F0] bg-white p-16 text-center shadow-sm">
          <div className="flex h-16 w-16 items-center justify-center rounded-full bg-slate-100">
            <HelpCircle className="size-8 text-slate-400" />
          </div>
          <p className="text-sm font-bold text-[#334155]">
            Ujian & Quiz Belum Dibuat
          </p>
          <p className="max-w-sm text-xs text-[#64748B]">
            Course ini belum memiliki quiz evaluasi (Pre-Test atau Post-Test)
            untuk peserta.
          </p>
          <Button
            onClick={() => openCreateDialog("pre_test")}
            className="mt-2 h-10 gap-2 rounded-lg bg-[#1061D6] px-5 font-semibold text-white hover:bg-blue-700"
          >
            <Plus className="size-4" />
            Buat Quiz Evaluasi
          </Button>
        </div>
      )}

      {/* Dialog: Create Assessment */}
      <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <form onSubmit={handleCreateSubmit}>
            <DialogHeader>
              <DialogTitle className="text-[#1E293B]">
                Buat Ujian Baru
              </DialogTitle>
              <DialogDescription className="text-[#64748B]">
                Lengkapi pengaturan untuk lembar evaluasi pelatihan.
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="grid gap-1">
                <Label className="text-xs font-bold text-[#475569]">
                  Tipe Ujian
                </Label>
                <Select
                  value={assessmentType}
                  onValueChange={(val: "pre_test" | "post_test") => {
                    setAssessmentType(val);
                    setTitle(val === "pre_test" ? "Pre-Test" : "Post-Test");
                  }}
                >
                  <SelectTrigger className="rounded-lg border-[#E2E8F0]">
                    <SelectValue placeholder="Pilih Tipe" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="pre_test">Pre-Test</SelectItem>
                    <SelectItem value="post_test">Post-Test</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="grid gap-1">
                <Label className="text-xs font-bold text-[#475569]">
                  Judul Ujian
                </Label>
                <Input
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="rounded-lg border-[#E2E8F0]"
                  required
                />
              </div>

              <div className="grid gap-1">
                <Label className="text-xs font-bold text-[#475569]">
                  Deskripsi
                </Label>
                <Textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="min-h-[80px] rounded-lg border-[#E2E8F0]"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Batas Waktu (Menit)
                  </Label>
                  <Input
                    type="number"
                    value={timeLimit}
                    onChange={(e) => setTimeLimit(e.target.value)}
                    className="rounded-lg border-[#E2E8F0]"
                  />
                </div>
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Nilai Kelulusan (%)
                  </Label>
                  <Input
                    type="number"
                    value={passingScore}
                    onChange={(e) => setPassingScore(Number(e.target.value))}
                    className="rounded-lg border-[#E2E8F0]"
                    required
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Maksimal Percobaan
                  </Label>
                  <Input
                    type="number"
                    value={maxAttempts}
                    onChange={(e) => setMaxAttempts(e.target.value)}
                    className="rounded-lg border-[#E2E8F0]"
                  />
                </div>
                <div className="flex items-center gap-2 pt-6">
                  <input
                    type="checkbox"
                    id="randomize"
                    checked={randomizeQuestions}
                    onChange={(e) => setRandomizeQuestions(e.target.checked)}
                    className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
                  />
                  <Label
                    htmlFor="randomize"
                    className="cursor-pointer text-xs font-bold text-[#475569]"
                  >
                    Acak Soal
                  </Label>
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button
                type="button"
                variant="ghost"
                onClick={() => setIsCreateOpen(false)}
              >
                Batal
              </Button>
              <Button
                type="submit"
                className="bg-[#1061D6] text-white hover:bg-blue-700"
                disabled={createMutation.isPending}
              >
                Buat Ujian
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Dialog: Edit Assessment */}
      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <form onSubmit={handleEditSubmit}>
            <DialogHeader>
              <DialogTitle className="text-[#1E293B]">Edit Ujian</DialogTitle>
              <DialogDescription className="text-[#64748B]">
                Ubah konfigurasi evaluasi di bawah.
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="grid gap-1">
                <Label className="text-xs font-bold text-[#475569]">
                  Judul Ujian
                </Label>
                <Input
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="rounded-lg border-[#E2E8F0]"
                  required
                />
              </div>

              <div className="grid gap-1">
                <Label className="text-xs font-bold text-[#475569]">
                  Deskripsi
                </Label>
                <Textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="min-h-[80px] rounded-lg border-[#E2E8F0]"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Batas Waktu (Menit)
                  </Label>
                  <Input
                    type="number"
                    value={timeLimit}
                    onChange={(e) => setTimeLimit(e.target.value)}
                    className="rounded-lg border-[#E2E8F0]"
                  />
                </div>
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Nilai Kelulusan (%)
                  </Label>
                  <Input
                    type="number"
                    value={passingScore}
                    onChange={(e) => setPassingScore(Number(e.target.value))}
                    className="rounded-lg border-[#E2E8F0]"
                    required
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Maksimal Percobaan
                  </Label>
                  <Input
                    type="number"
                    value={maxAttempts}
                    onChange={(e) => setMaxAttempts(e.target.value)}
                    className="rounded-lg border-[#E2E8F0]"
                  />
                </div>
                <div className="flex items-center gap-2 pt-6">
                  <input
                    type="checkbox"
                    id="randomize-edit"
                    checked={randomizeQuestions}
                    onChange={(e) => setRandomizeQuestions(e.target.checked)}
                    className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
                  />
                  <Label
                    htmlFor="randomize-edit"
                    className="cursor-pointer text-xs font-bold text-[#475569]"
                  >
                    Acak Soal
                  </Label>
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button
                type="button"
                variant="ghost"
                onClick={() => setIsEditOpen(false)}
              >
                Batal
              </Button>
              <Button
                type="submit"
                className="bg-[#1061D6] text-white hover:bg-blue-700"
                disabled={updateMutation.isPending}
              >
                Simpan Perubahan
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Dialog: Delete Assessment Confirmation */}
      <Dialog open={isDeleteOpen} onOpenChange={setIsDeleteOpen}>
        <DialogContent className="sm:max-w-[400px]">
          <DialogHeader>
            <DialogTitle className="text-[#1E293B]">Hapus Ujian</DialogTitle>
            <DialogDescription className="text-[#64748B]">
              Apakah Anda yakin ingin menghapus ujian{" "}
              <strong>{selectedAssessment?.title}</strong>? Aksi ini tidak dapat
              dibatalkan.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="mt-4 gap-2 sm:gap-0">
            <Button variant="ghost" onClick={() => setIsDeleteOpen(false)}>
              Batal
            </Button>
            <Button
              onClick={handleDeleteSubmit}
              className="bg-red-600 text-white hover:bg-red-700"
              disabled={deleteMutation.isPending}
            >
              Ya, Hapus
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Dialog: Add Question */}
      <Dialog open={isAddQuestionOpen} onOpenChange={setIsAddQuestionOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <form onSubmit={handleAddQuestionSubmit}>
            <DialogHeader>
              <DialogTitle className="text-[#1E293B]">
                Tambah Soal Ujian
              </DialogTitle>
              <DialogDescription className="text-[#64748B]">
                Masukkan pertanyaan, pilih tipe soal, dan tambahkan pilihan
                jawaban.
              </DialogDescription>
            </DialogHeader>
            <div className="grid max-h-[60vh] gap-4 overflow-y-auto px-1 py-4">
              <div className="grid gap-1">
                <Label className="text-xs font-bold text-[#475569]">
                  Pertanyaan Soal
                </Label>
                <Textarea
                  value={questionText}
                  onChange={(e) => setQuestionText(e.target.value)}
                  placeholder="Ketik pertanyaan di sini..."
                  className="min-h-[80px] rounded-lg border-[#E2E8F0]"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Tipe Soal
                  </Label>
                  <Select
                    value={questionType}
                    onValueChange={handleQuestionTypeChange}
                  >
                    <SelectTrigger className="rounded-lg border-[#E2E8F0]">
                      <SelectValue placeholder="Pilih Tipe" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="multiple_choice">
                        Pilihan Ganda
                      </SelectItem>
                      <SelectItem value="true_false">Benar / Salah</SelectItem>
                      <SelectItem value="essay">Esai</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid gap-1">
                  <Label className="text-xs font-bold text-[#475569]">
                    Poin Soal
                  </Label>
                  <Input
                    type="number"
                    value={points}
                    onChange={(e) => setPoints(Number(e.target.value))}
                    className="rounded-lg border-[#E2E8F0]"
                    required
                  />
                </div>
              </div>

              {/* Options fields based on type */}
              {questionType === "multiple_choice" && (
                <div className="space-y-3">
                  <Label className="text-xs font-bold text-[#475569]">
                    Pilihan Jawaban
                  </Label>
                  {options.map((opt, idx) => (
                    <div key={idx} className="flex items-center gap-3">
                      <input
                        type="radio"
                        name="correct-option"
                        checked={opt.isCorrect}
                        onChange={() => {
                          setOptions((prev) =>
                            prev.map((o, i) => ({
                              ...o,
                              isCorrect: i === idx,
                            })),
                          );
                        }}
                        className="h-4 w-4 text-[#1061D6] focus:ring-[#1061D6]"
                      />
                      <Input
                        placeholder={`Pilihan ${idx + 1}`}
                        value={opt.optionText}
                        onChange={(e) => {
                          const val = e.target.value;
                          setOptions((prev) =>
                            prev.map((o, i) =>
                              i === idx ? { ...o, optionText: val } : o,
                            ),
                          );
                        }}
                        className="flex-1 rounded-lg border-[#E2E8F0]"
                        required
                      />
                    </div>
                  ))}
                </div>
              )}

              {questionType === "true_false" && (
                <div className="space-y-3">
                  <Label className="text-xs font-bold text-[#475569]">
                    Jawaban Benar
                  </Label>
                  <div className="flex gap-4">
                    <label className="flex cursor-pointer items-center gap-2 text-xs font-semibold text-[#475569]">
                      <input
                        type="radio"
                        name="tf-answer"
                        checked={options[0]?.isCorrect}
                        onChange={() => {
                          setOptions([
                            { optionText: "Benar", isCorrect: true },
                            { optionText: "Salah", isCorrect: false },
                          ]);
                        }}
                        className="h-4 w-4 text-[#1061D6]"
                      />
                      Benar
                    </label>
                    <label className="flex cursor-pointer items-center gap-2 text-xs font-semibold text-[#475569]">
                      <input
                        type="radio"
                        name="tf-answer"
                        checked={options[1]?.isCorrect}
                        onChange={() => {
                          setOptions([
                            { optionText: "Benar", isCorrect: false },
                            { optionText: "Salah", isCorrect: true },
                          ]);
                        }}
                        className="h-4 w-4 text-[#1061D6]"
                      />
                      Salah
                    </label>
                  </div>
                </div>
              )}
            </div>
            <DialogFooter>
              <Button
                type="button"
                variant="ghost"
                onClick={() => setIsAddQuestionOpen(false)}
              >
                Batal
              </Button>
              <Button
                type="submit"
                className="bg-[#1061D6] text-white hover:bg-blue-700"
                disabled={addQuestionMutation.isPending}
              >
                Simpan Soal
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Dialog: Delete Question Confirmation */}
      <Dialog
        open={isDeleteQuestionOpen}
        onOpenChange={setIsDeleteQuestionOpen}
      >
        <DialogContent className="sm:max-w-[400px]">
          <DialogHeader>
            <DialogTitle className="text-[#1E293B]">
              Hapus Soal Ujian
            </DialogTitle>
            <DialogDescription className="text-[#64748B]">
              Apakah Anda yakin ingin menghapus soal ini dari lembar ujian?
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="mt-4 gap-2 sm:gap-0">
            <Button
              variant="ghost"
              onClick={() => setIsDeleteQuestionOpen(false)}
            >
              Batal
            </Button>
            <Button
              onClick={handleDeleteQuestionSubmit}
              className="bg-red-600 text-white hover:bg-red-700"
              disabled={deleteQuestionMutation.isPending}
            >
              Ya, Hapus Soal
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
