// ##################
// authored (generated by gemini, Jun 05 2026 18:00 WITA)
// ##################

import { useState, useRef, useEffect } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { trpc } from "@/utils/trpc";
import { requirePermission } from "@/utils/require-permission";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import {
  Settings,
  Trash2,
  Move,
  Eye,
  Download,
  Plus,
  RefreshCw,
  Search,
  ChevronLeft,
  ChevronRight,
  Sliders,
  Type,
} from "lucide-react";
import { z } from "zod";
import ImageWithFallback from "@/components/image-with-fallback";

export const Route = createFileRoute(
  "/(core)/back-office/pelatihan/$pelatihanId/sertifikat",
)({
  params: z.object({
    pelatihanId: z.string(),
  }),
  beforeLoad: async ({ context }) => {
    await requirePermission(context, {
      permission: "pelatihan-certificates.read",
    });
  },
  component: CertificateConfigComponent,
});

interface FieldConfig {
  x: number;
  y: number;
  fontSize: number;
  color: string;
  align: "left" | "center" | "right";
  enabled: boolean;
}

interface QRCodeConfig {
  x: number;
  y: number;
  width: number;
  height: number;
  enabled: boolean;
}

interface FieldMappings {
  participantName: FieldConfig;
  certificateNumber: FieldConfig;
  pelatihanTitle: FieldConfig;
  completionDate: FieldConfig;
  issuedAt: FieldConfig;
  finalScore: FieldConfig;
  instructorName: FieldConfig;
  companyName: FieldConfig;
  qrCode: QRCodeConfig;
}

const DEFAULT_MAPPINGS: FieldMappings = {
  participantName: {
    x: 50,
    y: 45,
    fontSize: 32,
    color: "#1E293B",
    align: "center",
    enabled: true,
  },
  certificateNumber: {
    x: 50,
    y: 15,
    fontSize: 14,
    color: "#64748B",
    align: "center",
    enabled: true,
  },
  pelatihanTitle: {
    x: 50,
    y: 55,
    fontSize: 24,
    color: "#0F172A",
    align: "center",
    enabled: true,
  },
  completionDate: {
    x: 50,
    y: 65,
    fontSize: 14,
    color: "#475569",
    align: "center",
    enabled: true,
  },
  issuedAt: {
    x: 75,
    y: 80,
    fontSize: 12,
    color: "#475569",
    align: "center",
    enabled: true,
  },
  finalScore: {
    x: 50,
    y: 72,
    fontSize: 12,
    color: "#475569",
    align: "center",
    enabled: false,
  },
  instructorName: {
    x: 25,
    y: 80,
    fontSize: 14,
    color: "#1E293B",
    align: "center",
    enabled: true,
  },
  companyName: {
    x: 50,
    y: 35,
    fontSize: 14,
    color: "#475569",
    align: "center",
    enabled: false,
  },
  qrCode: { x: 85, y: 15, width: 70, height: 70, enabled: true },
};

function CertificateConfigComponent() {
  const { pelatihanId } = Route.useParams();
  const queryClient = useQueryClient();
  const [activeTab, setActiveTab] = useState<"templates" | "issued">(
    "templates",
  );

  // Queries
  const { data: pelatihan, refetch: refetchPelatihan } = useQuery(
    trpc.pelatihan.base.getPelatihanById.queryOptions({ id: pelatihanId }),
  );

  const { data: templates = [], isLoading: isLoadingTemplates } = useQuery(
    trpc.pelatihan.certificate.getTemplates.queryOptions({ pelatihanId }),
  );

  // Pagination for Issued Certificates
  const [issuedPage, setIssuedPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");

  useEffect(() => {
    const timer = setTimeout(() => setDebouncedSearch(searchQuery), 500);
    return () => clearTimeout(timer);
  }, [searchQuery]);

  const { data: issuedData, isLoading: isLoadingIssued } = useQuery(
    trpc.pelatihan.certificate.getCertificatesByPelatihan.queryOptions({
      pelatihanId,
      page: issuedPage,
      limit: 10,
      search: debouncedSearch || undefined,
    }),
  );

  // Mutations
  const uploadFileMutation = useMutation(
    trpc.pelatihan.certificate.uploadTemplateFile.mutationOptions(),
  );

  const createTemplateMutation = useMutation(
    trpc.pelatihan.certificate.createTemplate.mutationOptions({
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: [["pelatihan", "certificate"]],
        });
        toast.success("Template sertifikat berhasil dibuat.");
        setIsCreating(false);
        setUploadResult(null);
      },
      onError: (err) => {
        toast.error(`Gagal membuat template: ${err.message}`);
      },
    }),
  );

  const updateTemplateMutation = useMutation(
    trpc.pelatihan.certificate.updateTemplate.mutationOptions({
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: [["pelatihan", "certificate"]],
        });
        toast.success("Konfigurasi template berhasil disimpan.");
        setSelectedTemplate(null);
      },
      onError: (err) => {
        toast.error(`Gagal menyimpan konfigurasi: ${err.message}`);
      },
    }),
  );

  const setActiveTemplateMutation = useMutation(
    trpc.pelatihan.certificate.setActiveTemplate.mutationOptions({
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: [["pelatihan", "certificate"]],
        });
        toast.success("Template aktif berhasil diubah.");
      },
      onError: (err) => {
        toast.error(`Gagal mengubah template aktif: ${err.message}`);
      },
    }),
  );

  const deleteTemplateMutation = useMutation(
    trpc.pelatihan.certificate.deleteTemplate.mutationOptions({
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: [["pelatihan", "certificate"]],
        });
        toast.success("Template berhasil dihapus.");
      },
      onError: (err) => {
        toast.error(`Gagal menghapus template: ${err.message}`);
      },
    }),
  );

  const updateNumberFormatMutation = useMutation(
    trpc.pelatihan.base.updatePelatihan.mutationOptions({
      onSuccess: () => {
        refetchPelatihan();
        toast.success("Format nomor sertifikat diperbarui.");
      },
      onError: (err) => {
        toast.error(`Gagal memperbarui nomor: ${err.message}`);
      },
    }),
  );

  const revokeCertMutation = useMutation(
    trpc.pelatihan.certificate.revokeCertificate.mutationOptions({
      onSuccess: () => {
        queryClient.invalidateQueries({
          queryKey: [["pelatihan", "certificate"]],
        });
        toast.success("Sertifikat berhasil dicabut.");
      },
      onError: (err) => {
        toast.error(`Gagal mencabut sertifikat: ${err.message}`);
      },
    }),
  );

  // UI States
  const [isCreating, setIsCreating] = useState(false);
  const [newTemplateName, setNewTemplateName] = useState("");
  const [newTemplateDesc, setNewTemplateDesc] = useState("");
  const [uploadResult, setUploadResult] = useState<{
    url: string;
    name: string;
  } | null>(null);
  const [selectedTemplate, setSelectedTemplate] = useState<any | null>(null);

  // Custom Drag & Drop Canvas State
  const canvasRef = useRef<HTMLDivElement>(null);
  const [activeDragField, setActiveDragField] = useState<string | null>(null);
  const [editorMappings, setEditorMappings] =
    useState<FieldMappings>(DEFAULT_MAPPINGS);
  const [selectedField, setSelectedField] =
    useState<keyof FieldMappings>("participantName");

  const [numberFormatInput, setNumberFormatInput] = useState(
    pelatihan?.certificateNumberFormat || "",
  );

  useEffect(() => {
    if (pelatihan) {
      setNumberFormatInput(pelatihan.certificateNumberFormat || "");
    }
  }, [pelatihan]);

  useEffect(() => {
    if (selectedTemplate) {
      setEditorMappings({
        ...DEFAULT_MAPPINGS,
        ...(selectedTemplate.fieldMappings as any),
      });
    }
  }, [selectedTemplate]);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const allowedTypes = ["application/pdf", "image/png", "image/jpeg"];
    if (!allowedTypes.includes(file.type)) {
      toast.error("Format file harus berupa PDF, PNG, atau JPEG.");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);

    const promise = uploadFileMutation.mutateAsync(formData);
    toast.promise(promise, {
      loading: "Mengunggah berkas template...",
      success: (data) => {
        setUploadResult({ url: data.url, name: data.name });
        return "Berkas berhasil diunggah.";
      },
      error: "Gagal mengunggah berkas.",
    });
  };

  const handleCreateTemplate = () => {
    if (!newTemplateName.trim()) {
      toast.error("Nama template wajib diisi.");
      return;
    }
    if (!uploadResult) {
      toast.error("Silakan unggah berkas template.");
      return;
    }

    const ext = uploadResult.name.split(".").pop()?.toLowerCase() || "pdf";
    const templateFileType =
      ext === "pdf" ? "pdf" : ext === "png" ? "png" : "jpeg";

    createTemplateMutation.mutate({
      pelatihanId,
      name: newTemplateName,
      description: newTemplateDesc,
      templateFileUrl: uploadResult.url,
      templateFileName: uploadResult.name,
      templateFileType,
      fieldMappings: DEFAULT_MAPPINGS,
    });
  };

  const handleSaveEditor = () => {
    if (!selectedTemplate) return;

    updateTemplateMutation.mutate({
      id: selectedTemplate.id,
      fieldMappings: editorMappings,
    });
  };

  // Drag logic
  const handlePointerDown = (e: React.PointerEvent, field: string) => {
    e.preventDefault();
    setActiveDragField(field);
    setSelectedField(field as any);
  };

  const handlePointerMove = (e: React.PointerEvent) => {
    if (!activeDragField || !canvasRef.current) return;

    const rect = canvasRef.current.getBoundingClientRect();

    // Compute percentage coordinates relative to the preview container
    let x = ((e.clientX - rect.left) / rect.width) * 100;
    let y = ((e.clientY - rect.top) / rect.height) * 100;

    // Constrain percentages
    x = Math.max(0, Math.min(100, x));
    y = Math.max(0, Math.min(100, y));

    setEditorMappings((prev: any) => ({
      ...prev,
      [activeDragField]: {
        ...prev[activeDragField],
        x: Math.round(x),
        y: Math.round(y),
      },
    }));
  };

  const handlePointerUp = () => {
    setActiveDragField(null);
  };

  const handleFieldChange = (
    field: keyof FieldMappings,
    key: string,
    value: any,
  ) => {
    setEditorMappings((prev: any) => ({
      ...prev,
      [field]: {
        ...prev[field],
        [key]: value,
      },
    }));
  };

  return (
    <div className="space-y-6 font-['Poppins']">
      {/* Expiry / Number Format Global Config */}
      <div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm md:flex-row md:items-center md:justify-between">
        <div className="space-y-1">
          <h2 className="flex items-center gap-2 text-base font-bold text-slate-800">
            <Settings className="h-5 w-5 text-blue-600" />
            Pengaturan Penomoran & Masa Berlaku
          </h2>
          <p className="text-xs text-slate-500">
            Atur format nomor sertifikat dan masa kadaluarsa (sertifikat
            otomatis berlaku 2 tahun sejak kelulusan).
          </p>
        </div>
        <div className="flex w-full max-w-md items-center gap-2">
          <div className="grid w-full items-center gap-1.5">
            <Label
              htmlFor="number-format"
              className="text-xs font-semibold text-slate-600"
            >
              Format Penomoran
            </Label>
            <div className="flex gap-2">
              <Input
                id="number-format"
                placeholder="Contoh: K3-BIMTEK/{{YEAR}}/{{SEQ}}"
                value={numberFormatInput}
                onChange={(e) => setNumberFormatInput(e.target.value)}
                className="h-9 text-xs"
              />
              <Button
                size="sm"
                onClick={() =>
                  updateNumberFormatMutation.mutate({
                    id: pelatihanId,
                    certificateNumberFormat: numberFormatInput,
                  })
                }
                disabled={updateNumberFormatMutation.isPending}
                className="h-9 bg-blue-600 text-xs text-white hover:bg-blue-700"
              >
                {updateNumberFormatMutation.isPending ? (
                  <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  "Simpan"
                )}
              </Button>
            </div>
            <p className="text-[10px] text-slate-400">
              Gunakan placeholder:{" "}
              <code className="rounded bg-slate-100 px-1">{"{{SEQ}}"}</code>{" "}
              (urutan),{" "}
              <code className="rounded bg-slate-100 px-1">{"{{YEAR}}"}</code>{" "}
              (tahun),{" "}
              <code className="rounded bg-slate-100 px-1">{"{{MONTH}}"}</code>{" "}
              (bulan)
            </p>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-slate-200">
        <nav className="flex gap-6">
          <button
            onClick={() => setActiveTab("templates")}
            className={`border-b-2 pb-3 text-sm font-bold transition-all ${
              activeTab === "templates"
                ? "border-blue-600 text-blue-600"
                : "border-transparent text-slate-500 hover:text-slate-700"
            }`}
          >
            Template Sertifikat
          </button>
          <button
            onClick={() => setActiveTab("issued")}
            className={`border-b-2 pb-3 text-sm font-bold transition-all ${
              activeTab === "issued"
                ? "border-blue-600 text-blue-600"
                : "border-transparent text-slate-500 hover:text-slate-700"
            }`}
          >
            Sertifikat Diterbitkan
          </button>
        </nav>
      </div>

      {activeTab === "templates" && (
        <div className="space-y-6">
          {selectedTemplate ? (
            /* Visual Configurator (Opsi A) */
            <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
              {/* Canvas Preview Column */}
              <div className="space-y-4 lg:col-span-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setSelectedTemplate(null)}
                      className="h-8 text-xs"
                    >
                      <ChevronLeft className="mr-1 h-4 w-4" /> Kembali
                    </Button>
                    <span className="text-sm font-bold text-slate-700">
                      Visual Editor: {selectedTemplate.name}
                    </span>
                  </div>
                  <Button
                    size="sm"
                    onClick={handleSaveEditor}
                    disabled={updateTemplateMutation.isPending}
                    className="h-8 bg-emerald-600 text-xs text-white hover:bg-emerald-700"
                  >
                    {updateTemplateMutation.isPending
                      ? "Menyimpan..."
                      : "Simpan Tata Letak"}
                  </Button>
                </div>

                {/* PDF/Canvas workspace wrapper */}
                <div className="relative flex items-center justify-center overflow-hidden rounded-xl border border-slate-300 bg-slate-100 p-4 shadow-md">
                  <div
                    ref={canvasRef}
                    onPointerMove={handlePointerMove}
                    onPointerUp={handlePointerUp}
                    onPointerLeave={handlePointerUp}
                    className="relative aspect-[297/210] w-full overflow-hidden rounded border border-slate-200 bg-white shadow select-none"
                  >
                    {/* Background Template rendered based on file type */}
                    {selectedTemplate.templateFileType === "pdf" ? (
                      <iframe
                        src={`${selectedTemplate.templateFileUrl}#toolbar=0&navpanes=0&scrollbar=0`}
                        className="pointer-events-none absolute inset-0 h-full w-full border-none select-none"
                      />
                    ) : (
                      <ImageWithFallback
                        src={selectedTemplate.templateFileUrl}
                        alt="Template Background"
                        className="pointer-events-none absolute inset-0 h-full w-full object-fill select-none"
                      />
                    )}

                    {/* Drag overlays */}
                    <div className="pointer-events-auto absolute inset-0 h-full w-full">
                      {Object.entries(editorMappings).map(
                        ([fieldName, config]) => {
                          if (!config.enabled) return null;

                          const isQr = fieldName === "qrCode";

                          return (
                            <div
                              key={fieldName}
                              onPointerDown={(e) =>
                                handlePointerDown(e, fieldName)
                              }
                              style={{
                                left: `${config.x}%`,
                                top: `${config.y}%`,
                                transform: isQr
                                  ? "translate(-50%, -50%)"
                                  : "translate(-50%, -50%)",
                              }}
                              className={`group absolute z-10 cursor-move rounded border border-dashed p-2 transition-colors select-none ${
                                selectedField === fieldName
                                  ? "border-blue-600 bg-blue-50/70"
                                  : "border-slate-400 bg-slate-100/50 hover:border-slate-600 hover:bg-slate-50"
                              }`}
                            >
                              {isQr ? (
                                <div
                                  style={{
                                    width: `${(config as QRCodeConfig).width}px`,
                                    height: `${(config as QRCodeConfig).height}px`,
                                  }}
                                  className="flex items-center justify-center border border-slate-400 bg-slate-200 text-center font-mono text-[10px] leading-tight text-slate-500"
                                >
                                  QR CODE
                                  <br />
                                  VERIFIKASI
                                </div>
                              ) : (
                                <span
                                  style={{
                                    fontSize: `${(config as FieldConfig).fontSize / 1.5}px`, // Scaled for preview display
                                    color: (config as FieldConfig).color,
                                    textAlign: (config as FieldConfig).align,
                                  }}
                                  className="block font-bold whitespace-nowrap"
                                >
                                  {fieldName === "participantName" &&
                                    "Nama Peserta"}
                                  {fieldName === "certificateNumber" &&
                                    "No: CERT/2026/0001"}
                                  {fieldName === "pelatihanTitle" &&
                                    pelatihan?.title}
                                  {fieldName === "completionDate" &&
                                    "25 Juni 2026"}
                                  {fieldName === "issuedAt" &&
                                    "Jakarta, 26 Juni 2026"}
                                  {fieldName === "finalScore" &&
                                    "Nilai Akhir: 95"}
                                  {(fieldName === "instructorName" &&
                                    pelatihan?.instructorName) ||
                                    "Nama Instruktur"}
                                  {fieldName === "companyName" &&
                                    "PT Tepian K3 Indonesia"}
                                </span>
                              )}
                              <div className="absolute -top-3 left-0 rounded bg-slate-800 px-1 text-[8px] text-white opacity-0 transition-opacity group-hover:opacity-100">
                                {fieldName} (X:{config.x}%, Y:{config.y}%)
                              </div>
                              <Move className="absolute -right-1 -bottom-1 h-3 w-3 text-slate-400 opacity-0 transition-opacity group-hover:opacity-100" />
                            </div>
                          );
                        },
                      )}
                    </div>
                  </div>
                </div>

                <div className="flex gap-2 rounded-lg bg-blue-50 p-4 text-xs text-blue-700">
                  <Sliders className="h-4 w-4 shrink-0" />
                  <div>
                    <strong>Petunjuk Editor:</strong> Tahan dan seret (drag)
                    label teks/QR Code di dalam kotak sertifikat di atas untuk
                    menentukan posisi pencetakan. Posisi disimpan dalam
                    persentase koordinat X dan Y terhadap ukuran halaman
                    sertifikat.
                  </div>
                </div>
              </div>

              {/* Sidebar Config Panel Column */}
              <div className="space-y-4">
                <div className="space-y-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
                  <h3 className="flex items-center gap-1.5 border-b pb-2 text-sm font-bold text-slate-800">
                    <Type className="h-4 w-4 text-blue-600" />
                    Properti Field: {selectedField}
                  </h3>

                  {selectedField && (
                    <div className="space-y-4">
                      {/* Enable toggle */}
                      <div className="flex items-center justify-between">
                        <Label
                          htmlFor="field-enabled"
                          className="text-xs font-semibold text-slate-600"
                        >
                          Aktifkan Field
                        </Label>
                        <input
                          id="field-enabled"
                          type="checkbox"
                          checked={editorMappings[selectedField].enabled}
                          onChange={(e) =>
                            handleFieldChange(
                              selectedField,
                              "enabled",
                              e.target.checked,
                            )
                          }
                          className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                        />
                      </div>

                      {editorMappings[selectedField].enabled && (
                        <>
                          {selectedField !== "qrCode" ? (
                            <>
                              {/* Font Size */}
                              <div className="space-y-1.5">
                                <div className="flex justify-between text-xs font-semibold text-slate-600">
                                  <Label>Ukuran Huruf (Font Size)</Label>
                                  <span>
                                    {
                                      (
                                        editorMappings[
                                          selectedField
                                        ] as FieldConfig
                                      ).fontSize
                                    }{" "}
                                    px
                                  </span>
                                </div>
                                <input
                                  type="range"
                                  min="8"
                                  max="72"
                                  value={
                                    (
                                      editorMappings[
                                        selectedField
                                      ] as FieldConfig
                                    ).fontSize
                                  }
                                  onChange={(e) =>
                                    handleFieldChange(
                                      selectedField,
                                      "fontSize",
                                      parseInt(e.target.value),
                                    )
                                  }
                                  className="h-1.5 w-full cursor-pointer appearance-none rounded-lg bg-slate-200"
                                />
                              </div>

                              {/* Color */}
                              <div className="space-y-1.5">
                                <Label className="text-xs font-semibold text-slate-600">
                                  Warna Teks (HEX)
                                </Label>
                                <div className="flex gap-2">
                                  <input
                                    type="color"
                                    value={
                                      (
                                        editorMappings[
                                          selectedField
                                        ] as FieldConfig
                                      ).color
                                    }
                                    onChange={(e) =>
                                      handleFieldChange(
                                        selectedField,
                                        "color",
                                        e.target.value,
                                      )
                                    }
                                    className="h-9 w-9 cursor-pointer rounded border border-slate-200"
                                  />
                                  <Input
                                    value={
                                      (
                                        editorMappings[
                                          selectedField
                                        ] as FieldConfig
                                      ).color
                                    }
                                    onChange={(e) =>
                                      handleFieldChange(
                                        selectedField,
                                        "color",
                                        e.target.value,
                                      )
                                    }
                                    className="h-9 text-xs"
                                  />
                                </div>
                              </div>

                              {/* Text Alignment */}
                              <div className="space-y-1.5">
                                <Label className="text-xs font-semibold text-slate-600">
                                  Rata Tengah/Kiri/Kanan
                                </Label>
                                <div className="grid grid-cols-3 gap-2">
                                  {["left", "center", "right"].map((align) => (
                                    <Button
                                      key={align}
                                      variant={
                                        (
                                          editorMappings[
                                            selectedField
                                          ] as FieldConfig
                                        ).align === align
                                          ? "default"
                                          : "outline"
                                      }
                                      size="sm"
                                      onClick={() =>
                                        handleFieldChange(
                                          selectedField,
                                          "align",
                                          align,
                                        )
                                      }
                                      className="text-[10px] font-bold uppercase"
                                    >
                                      {align === "left" && "Kiri"}
                                      {align === "center" && "Tengah"}
                                      {align === "right" && "Kanan"}
                                    </Button>
                                  ))}
                                </div>
                              </div>
                            </>
                          ) : (
                            <>
                              {/* QR Code Width/Height */}
                              <div className="space-y-1.5">
                                <div className="flex justify-between text-xs font-semibold text-slate-600">
                                  <Label>Lebar QR Code</Label>
                                  <span>
                                    {
                                      (
                                        editorMappings[
                                          selectedField
                                        ] as QRCodeConfig
                                      ).width
                                    }{" "}
                                    px
                                  </span>
                                </div>
                                <input
                                  type="range"
                                  min="40"
                                  max="200"
                                  value={
                                    (
                                      editorMappings[
                                        selectedField
                                      ] as QRCodeConfig
                                    ).width
                                  }
                                  onChange={(e) => {
                                    const val = parseInt(e.target.value);
                                    handleFieldChange("qrCode", "width", val);
                                    handleFieldChange("qrCode", "height", val);
                                  }}
                                  className="h-1.5 w-full cursor-pointer appearance-none rounded-lg bg-slate-200"
                                />
                              </div>
                            </>
                          )}

                          {/* Numeric Coordinates */}
                          <div className="grid grid-cols-2 gap-3 border-t pt-3">
                            <div className="space-y-1">
                              <Label className="text-[10px] font-semibold text-slate-500">
                                Koordinat X (%)
                              </Label>
                              <Input
                                type="number"
                                min="0"
                                max="100"
                                value={editorMappings[selectedField].x}
                                onChange={(e) =>
                                  handleFieldChange(
                                    selectedField,
                                    "x",
                                    Math.round(parseFloat(e.target.value) || 0),
                                  )
                                }
                                className="h-8 text-xs"
                              />
                            </div>
                            <div className="space-y-1">
                              <Label className="text-[10px] font-semibold text-slate-500">
                                Koordinat Y (%)
                              </Label>
                              <Input
                                type="number"
                                min="0"
                                max="100"
                                value={editorMappings[selectedField].y}
                                onChange={(e) =>
                                  handleFieldChange(
                                    selectedField,
                                    "y",
                                    Math.round(parseFloat(e.target.value) || 0),
                                  )
                                }
                                className="h-8 text-xs"
                              />
                            </div>
                          </div>
                        </>
                      )}
                    </div>
                  )}
                </div>

                {/* Field Selector List */}
                <div className="space-y-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
                  <h3 className="text-xs font-bold text-slate-800">
                    Daftar Field Tersedia
                  </h3>
                  <div className="space-y-1">
                    {Object.keys(DEFAULT_MAPPINGS).map((fieldName) => {
                      const mapping =
                        editorMappings[fieldName as keyof FieldMappings];
                      const isSelected = selectedField === fieldName;
                      return (
                        <button
                          key={fieldName}
                          onClick={() => setSelectedField(fieldName as any)}
                          className={`flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-xs font-semibold transition ${
                            isSelected
                              ? "bg-blue-600 text-white"
                              : "bg-slate-50 text-slate-700 hover:bg-slate-100"
                          }`}
                        >
                          <span>
                            {fieldName === "participantName" && "Nama Peserta"}
                            {fieldName === "certificateNumber" &&
                              "Nomor Sertifikat"}
                            {fieldName === "pelatihanTitle" &&
                              "Judul Pelatihan"}
                            {fieldName === "completionDate" &&
                              "Tanggal Kelulusan"}
                            {fieldName === "issuedAt" && "Tanggal Penerbitan"}
                            {fieldName === "finalScore" && "Nilai Akhir"}
                            {fieldName === "instructorName" &&
                              "Nama Instruktur"}
                            {fieldName === "companyName" && "Nama Perusahaan"}
                            {fieldName === "qrCode" && "QR Code Verifikasi"}
                          </span>
                          <span
                            className={`rounded px-1.5 py-0.5 text-[9px] ${
                              isSelected
                                ? "bg-blue-700 text-white"
                                : mapping.enabled
                                  ? "bg-emerald-100 text-emerald-800"
                                  : "bg-slate-200 text-slate-500"
                            }`}
                          >
                            {mapping.enabled ? "Aktif" : "Nonaktif"}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            /* Templates Management List */
            <div className="space-y-6">
              {isCreating ? (
                /* Create Template Form */
                <div className="max-w-2xl space-y-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
                  <div className="flex items-center justify-between border-b pb-3">
                    <h3 className="text-sm font-bold text-slate-800">
                      Upload Template Sertifikat Baru
                    </h3>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => {
                        setIsCreating(false);
                        setUploadResult(null);
                      }}
                      className="h-7 text-xs"
                    >
                      Batal
                    </Button>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-1.5">
                      <Label
                        htmlFor="template-name"
                        className="text-xs font-semibold text-slate-700"
                      >
                        Nama Template
                      </Label>
                      <Input
                        id="template-name"
                        placeholder="Contoh: Template Utama Sertifikat Pelatihan"
                        value={newTemplateName}
                        onChange={(e) => setNewTemplateName(e.target.value)}
                        className="text-xs"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <Label
                        htmlFor="template-desc"
                        className="text-xs font-semibold text-slate-700"
                      >
                        Deskripsi (Opsional)
                      </Label>
                      <Textarea
                        id="template-desc"
                        placeholder="Catatan tambahan mengenai template ini..."
                        value={newTemplateDesc}
                        onChange={(e) => setNewTemplateDesc(e.target.value)}
                        className="text-xs"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label className="block text-xs font-semibold text-slate-700">
                        Berkas Template Sertifikat
                      </Label>
                      <div className="relative cursor-pointer rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-6 text-center transition hover:border-blue-500">
                        <input
                          type="file"
                          accept="application/pdf,image/png,image/jpeg"
                          onChange={handleFileUpload}
                          className="absolute inset-0 h-full w-full cursor-pointer opacity-0"
                        />
                        <div className="space-y-1">
                          <Plus className="mx-auto h-8 w-8 text-slate-400" />
                          <p className="text-xs font-bold text-slate-600">
                            {uploadResult
                              ? uploadResult.name
                              : "Klik atau seret file PDF/PNG/JPEG di sini"}
                          </p>
                          <p className="text-[10px] text-slate-400">
                            Format PDF, PNG, atau JPEG landscape A4 disarankan
                            (Max. 10MB)
                          </p>
                        </div>
                      </div>
                    </div>

                    <Button
                      onClick={handleCreateTemplate}
                      disabled={
                        createTemplateMutation.isPending || !uploadResult
                      }
                      className="w-full rounded-lg bg-blue-600 py-2 text-xs font-bold text-white hover:bg-blue-700"
                    >
                      {createTemplateMutation.isPending
                        ? "Sedang Menyimpan..."
                        : "Buat & Konfigurasi Letak"}
                    </Button>
                  </div>
                </div>
              ) : (
                /* Templates List View */
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="text-sm font-bold text-slate-700">
                      Daftar Berkas Template
                    </h3>
                    <Button
                      onClick={() => setIsCreating(true)}
                      className="h-8 bg-blue-600 text-xs text-white hover:bg-blue-700"
                    >
                      <Plus className="mr-1 h-4 w-4" /> Unggah Template
                    </Button>
                  </div>

                  {isLoadingTemplates ? (
                    <div className="flex h-32 items-center justify-center text-xs text-slate-400">
                      Memuat daftar template...
                    </div>
                  ) : templates.length === 0 ? (
                    <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-xs text-slate-500">
                      Belum ada template sertifikat. Silakan unggah template
                      pertama Anda.
                    </div>
                  ) : (
                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                      {templates.map((template) => (
                        <div
                          key={template.id}
                          className={`flex flex-col justify-between gap-4 rounded-xl border bg-white p-5 shadow-sm transition-all ${
                            template.isActive
                              ? "border-blue-600 ring-2 ring-blue-100"
                              : "border-slate-200"
                          }`}
                        >
                          <div className="space-y-2">
                            <div className="flex items-start justify-between">
                              <div>
                                <h4 className="text-sm font-bold text-slate-800">
                                  {template.name}
                                </h4>
                                <p className="text-xs text-slate-400">
                                  File: {template.templateFileName}
                                </p>
                              </div>
                              <span
                                className={`rounded px-2 py-0.5 text-[10px] font-bold ${
                                  template.isActive
                                    ? "bg-blue-100 text-blue-800"
                                    : "bg-slate-100 text-slate-600"
                                }`}
                              >
                                {template.isActive ? "Aktif" : "Draft"}
                              </span>
                            </div>
                            {template.description && (
                              <p className="text-xs text-slate-500 italic">
                                {template.description}
                              </p>
                            )}
                          </div>

                          <div className="mt-2 flex items-center justify-between border-t pt-3">
                            <div className="flex gap-2">
                              {!template.isActive && (
                                <Button
                                  variant="outline"
                                  size="sm"
                                  onClick={() =>
                                    setActiveTemplateMutation.mutate({
                                      pelatihanId,
                                      templateId: template.id,
                                    })
                                  }
                                  disabled={setActiveTemplateMutation.isPending}
                                  className="h-7 border-blue-600 px-2.5 text-[10px] font-bold text-blue-600 hover:bg-blue-50"
                                >
                                  Aktifkan
                                </Button>
                              )}
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => setSelectedTemplate(template)}
                                className="h-7 px-2.5 text-[10px] font-bold text-slate-600"
                              >
                                Edit Tata Letak
                              </Button>
                            </div>

                            <div className="flex gap-1.5">
                              <a
                                href={template.templateFileUrl}
                                target="_blank"
                                rel="noreferrer"
                                className="inline-flex h-7 w-7 items-center justify-center rounded-lg border border-slate-200 text-slate-500 transition hover:bg-slate-50"
                              >
                                <Eye className="h-3.5 w-3.5" />
                              </a>
                              <Button
                                variant="ghost"
                                size="icon"
                                onClick={() =>
                                  deleteTemplateMutation.mutate({
                                    id: template.id,
                                  })
                                }
                                disabled={deleteTemplateMutation.isPending}
                                className="h-7 w-7 rounded-lg text-rose-600 hover:bg-rose-50"
                              >
                                <Trash2 className="h-3.5 w-3.5" />
                              </Button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {activeTab === "issued" && (
        <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
          {/* Filter Bar */}
          <div className="flex flex-col items-center justify-between gap-4 border-b border-slate-100 bg-slate-50/50 p-5 md:flex-row">
            <div className="relative w-full max-w-sm">
              <Search className="absolute top-2.5 left-3 h-4 w-4 text-slate-400" />
              <Input
                placeholder="Cari nama peserta atau no. sertifikat..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="h-9 pl-9 text-xs"
              />
            </div>
            <p className="text-xs text-slate-500">
              Menampilkan {issuedData?.pagination.totalItems || 0} sertifikat
              yang diterbitkan
            </p>
          </div>

          {/* Table */}
          {isLoadingIssued ? (
            <div className="flex h-32 items-center justify-center text-xs text-slate-400">
              Memuat data sertifikat...
            </div>
          ) : !issuedData || issuedData.data.length === 0 ? (
            <div className="p-8 text-center text-xs text-slate-400">
              Tidak ada data sertifikat yang ditemukan.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full border-collapse text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 bg-slate-50 text-[10px] font-bold text-slate-600 uppercase">
                    <th className="p-4">No. Sertifikat</th>
                    <th className="p-4">Peserta</th>
                    <th className="p-4">Tanggal Kelulusan</th>
                    <th className="p-4">Tanggal Terbit</th>
                    <th className="p-4">Nilai Akhir</th>
                    <th className="p-4 text-right">Aksi</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-slate-700">
                  {issuedData.data.map((cert) => (
                    <tr key={cert.id} className="hover:bg-slate-50/50">
                      <td className="p-4 font-mono font-bold text-slate-800">
                        {cert.certificateNumber}
                      </td>
                      <td className="p-4">
                        <div className="font-bold text-slate-900">
                          {cert.userName}
                        </div>
                        <div className="text-[10px] text-slate-400">
                          {cert.userEmail}
                        </div>
                      </td>
                      <td className="p-4">
                        {new Date(cert.completionDate).toLocaleDateString(
                          "id-ID",
                        )}
                      </td>
                      <td className="p-4">
                        {new Date(cert.issuedAt).toLocaleDateString("id-ID")}
                      </td>
                      <td className="p-4">
                        <span className="rounded bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-700">
                          {cert.finalScore} / 100
                        </span>
                      </td>
                      <td className="space-x-1 p-4 text-right">
                        <a
                          href={cert.documentUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="inline-flex h-8 items-center justify-center gap-1 rounded-lg border border-slate-200 px-2.5 text-xs font-semibold text-slate-600 hover:bg-slate-50"
                        >
                          <Download className="h-3.5 w-3.5" /> PDF
                        </a>
                        <Button
                          variant="ghost"
                          onClick={() => {
                            if (
                              confirm(
                                "Apakah Anda yakin ingin mencabut sertifikat ini? Status pendaftaran peserta akan dikembalikan ke progress.",
                              )
                            ) {
                              revokeCertMutation.mutate({
                                certificateId: cert.id,
                                reason: "Dicabut oleh admin",
                              });
                            }
                          }}
                          disabled={revokeCertMutation.isPending}
                          className="h-8 rounded-lg px-2 text-xs font-bold text-rose-600 hover:bg-rose-50"
                        >
                          Cabut
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Pagination */}
          {issuedData && issuedData.pagination.totalPages > 1 && (
            <div className="flex items-center justify-between border-t border-slate-100 p-4">
              <Button
                variant="outline"
                size="sm"
                disabled={issuedPage === 1}
                onClick={() => setIssuedPage((p) => p - 1)}
                className="h-8 text-xs"
              >
                <ChevronLeft className="mr-1 h-4 w-4" /> Sebelumnya
              </Button>
              <span className="text-xs text-slate-500">
                Halaman {issuedPage} dari {issuedData.pagination.totalPages}
              </span>
              <Button
                variant="outline"
                size="sm"
                disabled={issuedPage === issuedData.pagination.totalPages}
                onClick={() => setIssuedPage((p) => p + 1)}
                className="h-8 text-xs"
              >
                Selanjutnya <ChevronRight className="ml-1 h-4 w-4" />
              </Button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
