import { and, asc, eq, isNull } from "@tepian-k3/db";
import { db } from "@tepian-k3/db/client";
import { order, orderStatusHistory } from "@tepian-k3/db/schema";
import { logError } from "@tepian-k3/services/logger";
import {
  calculateDurationBetween,
  formatDateDDMMYYYY,
  formatDateTimeDDMMYYYY,
  formatTimeHHMMSS,
} from "@tepian-k3/utils/format-duration";
import { TRPCError } from "@trpc/server";
import { Effect } from "effect";

// ##################
// authored (generated by AI, Jul 28 2026 03:44 WITA)
// ##################

import type {
  AuditTrailFullData,
  TimelineAuditStep,
} from "@tepian-k3/types/pengujian/audit-trail.types";

const auditTrailQueries = {
  getAuditTrailByOrderId(orderId: string) {
    return Effect.gen(function* () {
      const orderData = yield* Effect.tryPromise({
        try: () =>
          db.query.order.findFirst({
            where: and(eq(order.id, orderId), isNull(order.deletedAt)),
            with: {
              user: true,
              company: {
                with: {
                  kbli: true,
                  province: true,
                  regency: true,
                  district: true,
                },
              },
              items: {
                with: {
                  parameter: true,
                  location: {
                    with: {
                      regency: true,
                      district: true,
                    },
                  },
                },
              },
              worksheet: {
                with: {
                  mainSupervisor: true,
                  accompanyingSupervisor: true,
                },
              },
              documents: true,
            },
          }),
        catch: (error) => {
          logError(
            "auditTrailQueries.getAuditTrailByOrderId",
            "Failed fetching order base data",
            { orderId, error },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data pesanan untuk audit trail",
          });
        },
      });

      if (!orderData) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Pesanan tidak ditemukan",
          }),
        );
      }

      // Ambil history perubahan status
      const historyLogs = yield* Effect.tryPromise({
        try: () =>
          db.query.orderStatusHistory.findMany({
            where: eq(orderStatusHistory.orderId, orderId),
            orderBy: [asc(orderStatusHistory.createdAt)],
            with: {
              changedByUser: true,
            },
          }),
        catch: (error) => {
          logError(
            "auditTrailQueries.getAuditTrailByOrderId",
            "Failed fetching status history",
            { orderId, error },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil riwayat status pesanan",
          });
        },
      });

      // Susun list timeline step
      const steps: TimelineAuditStep[] = [];
      let previousTimestamp: string | null = null;

      // 1. Initial Step: Created At
      const initialTimestamp = orderData.createdAt;
      steps.push({
        stepNumber: 1,
        status: "pending",
        statusLabel: "Pesanan Dibuat",
        changedByName: orderData.user.name,
        changedByEmail: orderData.user.email,
        timestampRaw: initialTimestamp,
        dateFormatted: formatDateDDMMYYYY(initialTimestamp),
        timeFormatted: formatTimeHHMMSS(initialTimestamp),
        dateTimeFormatted: formatDateTimeDDMMYYYY(initialTimestamp),
        durationFromPrevious: {
          text: "Awal",
          formatted: "00d 00h 00m 00s",
          totalSeconds: 0,
        },
        note: "Pesanan dibuat oleh pelanggan",
      });
      previousTimestamp = initialTimestamp;

      // 2. Transisi Status berikutnya dari orderStatusHistory
      historyLogs.forEach((log, index) => {
        const timestamp = log.createdAt;
        const duration = calculateDurationBetween(previousTimestamp, timestamp);

        steps.push({
          stepNumber: index + 2,
          status: log.status,
          statusLabel: log.status.replace(/_/g, " ").toUpperCase(),
          changedByName: log.changedByUser.name,
          changedByEmail: log.changedByUser.email,
          timestampRaw: timestamp,
          dateFormatted: formatDateDDMMYYYY(timestamp),
          timeFormatted: formatTimeHHMMSS(timestamp),
          dateTimeFormatted: formatDateTimeDDMMYYYY(timestamp),
          durationFromPrevious: duration,
          note: log.note ?? null,
        });

        previousTimestamp = timestamp;
      });

      // Total durasi keseluruhan
      const lastTimestamp = previousTimestamp ?? initialTimestamp;
      const totalDuration = calculateDurationBetween(
        initialTimestamp,
        lastTimestamp,
      );

      // Lokasi & Parameter
      const locationsAndParameters = orderData.items.map((item) => ({
        locationName: item.location?.name ?? "Default Location",
        regencyName: item.location?.regency?.name ?? null,
        districtName: item.location?.district?.name ?? null,
        parameterName: item.parameter?.name ?? "-",
        serviceType: item.parameter?.serviceType ?? "utama",
        quantity: item.quantity,
        price: item.price,
        subTotal: item.subTotal,
      }));

      // Dokumen Terkait
      const relatedDocs = (orderData.documents ?? []).map((doc) => ({
        id: doc.id,
        type: doc.type,
        documentNumber: doc.documentNumber,
        title: doc.title,
        fileUrl: doc.fileUrl,
        fileName: doc.fileName,
      }));

      const auditData: AuditTrailFullData = {
        orderInfo: {
          id: orderData.id,
          orderNumber: orderData.orderNumber,
          status: orderData.status,
          approvalStatus: orderData.approvalStatus,
          paymentStatus: orderData.paymentStatus,
          fundingType: orderData.fundingType,
          totalAmount: orderData.totalAmount,
          createdAt: orderData.createdAt,
          approvedAt: orderData.approvedAt,
          paidAt: orderData.paidAt,
          completedAt: orderData.completedAt,
          customerNote: orderData.customerNote,
        },
        customerInfo: {
          companyName: orderData.company?.name ?? orderData.user.name,
          companyAddress: orderData.company?.address ?? "-",
          kbliName: orderData.company?.kbli?.name ?? null,
          responsiblePerson:
            orderData.company?.responsibleTestingPerson ?? orderData.user.name,
          responsiblePhone:
            orderData.company?.responsibleTestingPersonPhone ?? "-",
          responsibleEmail:
            orderData.company?.responsibleTestingPersonEmail ??
            orderData.user.email,
          headOfCompany: orderData.company?.headOfCompany ?? "-",
          headPosition: orderData.company?.headOfCompanyPosition ?? "-",
          wlkpStatus: orderData.company?.wlkpStatus ?? false,
          bankName: orderData.company?.companyBankName ?? "-",
          bankAccount: orderData.company?.companyBankAccount ?? "-",
          userEmail: orderData.user.email,
          userName: orderData.user.name,
        },
        locationsAndParameters,
        timeline: {
          steps,
          totalDuration,
          startDateFormatted: formatDateDDMMYYYY(initialTimestamp),
          endDateFormatted: formatDateDDMMYYYY(lastTimestamp),
        },
        relatedDocuments: relatedDocs,
      };

      return yield* Effect.succeed(auditData);
    });
  },
};

export default auditTrailQueries;

// ##################
// end authored
// ##################
