import { db } from "@tepian-k3/db/client";
import {
  parameterCategories,
  parameters,
  toolCodes,
  tools,
  chemicalMaterials,
  clusters,
} from "@tepian-k3/db/schema";
import { eq, isNull } from "@tepian-k3/db";
import { Effect } from "effect";
import { TRPCError } from "@trpc/server";
import { logError } from "@tepian-k3/services/logger";
import type { ParseResult } from "@tepian-k3/services/excel";
import auditQueries from "../platform/audit.queries";

// ##################
// authored (generated by claude, Jun 24 2026 14:35 WITA)
// ##################

export const pengujianExcelQueries = {
  /**
   * Retrieves all master data necessary for exporting to Excel.
   */
  exportAllData() {
    return Effect.tryPromise({
      try: async () => {
        const [kategoriData, parameterData, kodeAlatData, alatData, bahanData] =
          await Promise.all([
            db.query.parameterCategories.findMany({
              where: isNull(parameterCategories.deletedAt),
              with: { cluster: true },
            }),
            db.query.parameters.findMany({
              where: isNull(parameters.deletedAt),
              with: { category: true },
            }),
            db.query.toolCodes.findMany({
              where: isNull(toolCodes.deletedAt),
            }),
            db.query.tools.findMany({
              where: isNull(tools.deletedAt),
              with: { toolCode: true },
            }),
            db.query.chemicalMaterials.findMany({
              where: isNull(chemicalMaterials.deletedAt),
            }),
          ]);

        return {
          kategoriData: kategoriData.map((c) => ({
            nama: c.name,
            cluster: c.cluster?.name || "",
            deskripsi: c.description || "",
          })),
          parameterData: parameterData.map((p) => ({
            nama: p.name,
            kategori: p.category?.name || "",
            referensi: p.reference || "",
            harga: p.price,
            satuan: p.unit,
          })),
          kodeAlatData: kodeAlatData.map((t) => ({
            kode: t.code,
            deskripsi: t.description || "",
            aktif: t.isActive ? "ya" : "tidak",
          })),
          alatData: alatData.map((t) => ({
            kodeAlat: t.toolCode?.code || "",
            kodeFisik: t.toolUniqueCode,
            namaAlat: t.toolName,
            merek: t.brand || "",
            tipe: t.type || "",
            nomorSeri: t.serialNumber || "",
            fungsi: t.function || "",
            lokasi: t.location || "",
            rak: t.shelf || "",
            nomorBMN: t.BMNnumber || "",
            nomorNUP: t.NUPnumber || "",
            tahunPerolehan: t.acquisitionYear || "",
            kondisi: t.condition || "baik",
            ketersediaan: t.availability || "ready",
          })),
          bahanData: bahanData.map((b) => ({
            kode: b.code,
            nomorKatalog: b.catalogNumber || "",
            rumusKimia: b.chemicalFormula || "",
            nama: b.name,
            stokTerpakai: b.usedStock || "",
            unitStokTerpakai: b.usedStockUnit || "",
            stokTersegel: b.sealedStock || "",
            unitStokTersegel: b.sealedStockUnit || "",
            penggunaanBulanan: b.monthlyUsage || "",
            unitPenggunaan: b.monthlyUsageUnit || "",
            status: b.status || "tersedia",
            tanggalKadaluarsa: b.expiredDate || "",
            catatanMasuk: b.incomingMaterialNote || "",
          })),
        };
      },
      catch: (error) => {
        logError(
          "pengujianExcelQueries.exportAllData",
          "Failed to export master data",
          { error },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data untuk export Excel.",
        });
      },
    });
  },

  /**
   * Imports parsed data into the database within a transaction.
   */
  importFromParsedData(parsed: ParseResult, userId: string, userEmail: string) {
    return Effect.tryPromise({
      try: async () => {
        // Pre-fetch all necessary reference tables to memory
        const [
          dbClusters,
          dbCategories,
          dbParameters,
          dbToolCodes,
          dbTools,
          dbChemicalMaterials,
        ] = await Promise.all([
          db.query.clusters.findMany({
            where: isNull(clusters.deletedAt),
          }),
          db.query.parameterCategories.findMany({
            where: isNull(parameterCategories.deletedAt),
          }),
          db.query.parameters.findMany({
            where: isNull(parameters.deletedAt),
          }),
          db.query.toolCodes.findMany({
            where: isNull(toolCodes.deletedAt),
          }),
          db.query.tools.findMany({
            where: isNull(tools.deletedAt),
          }),
          db.query.chemicalMaterials.findMany({
            where: isNull(chemicalMaterials.deletedAt),
          }),
        ]);

        // Initialize in-memory lookup Maps
        const clusterMap = new Map(dbClusters.map((c) => [c.name, c.id]));
        const categoryMap = new Map(dbCategories.map((c) => [c.name, c]));
        const parameterMap = new Map(dbParameters.map((p) => [p.name, p]));
        const toolCodeMap = new Map(dbToolCodes.map((tc) => [tc.code, tc]));
        const toolMap = new Map(dbTools.map((t) => [t.toolUniqueCode, t]));
        const chemicalMaterialMap = new Map(
          dbChemicalMaterials.map((cm) => [cm.code, cm]),
        );

        const summary = {
          parameterCategories: { processed: parsed.parameterCategories.length, success: 0, failed: 0 },
          parameters: { processed: parsed.parameters.length, success: 0, failed: 0 },
          toolCodes: { processed: parsed.toolCodes.length, success: 0, failed: 0 },
          tools: { processed: parsed.tools.length, success: 0, failed: 0 },
          chemicalMaterials: { processed: parsed.chemicalMaterials.length, success: 0, failed: 0 },
        };

        const remainingErrors = [...parsed.parseErrors];

        await db.transaction(async (tx) => {
          // 1. Kategori Parameter
          for (const row of parsed.parameterCategories) {
            try {
              const item = row.data;
              const existing = categoryMap.get(item.nama);

              // Find cluster
              let clusterId = existing?.clusterId;
              if (item.cluster) {
                const clusterIdFromMap = clusterMap.get(item.cluster);
                if (clusterIdFromMap) clusterId = clusterIdFromMap;
              }

              if (!clusterId) {
                throw new Error(`Cluster "${item.cluster}" tidak ditemukan.`);
              }

              if (existing) {
                const [updated] = await tx
                  .update(parameterCategories)
                  .set({
                    description: item.deskripsi,
                    clusterId,
                  })
                  .where(eq(parameterCategories.id, existing.id))
                  .returning();

                if (updated) {
                  categoryMap.set(updated.name, updated as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "parameter_category",
                    entityId: updated.id,
                    action: "update",
                    userId,
                    userEmail,
                    oldValues: existing,
                    newValues: updated,
                    description: `Memperbarui Kategori Parameter dari Excel: ${updated.name}`,
                  });
                }
              } else {
                const [inserted] = await tx
                  .insert(parameterCategories)
                  .values({
                    name: item.nama,
                    description: item.deskripsi,
                    clusterId,
                  })
                  .returning();

                if (inserted) {
                  categoryMap.set(inserted.name, inserted as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "parameter_category",
                    entityId: inserted.id,
                    action: "create",
                    userId,
                    userEmail,
                    oldValues: null,
                    newValues: inserted,
                    description: `Membuat Kategori Parameter dari Excel: ${inserted.name}`,
                  });
                }
              }
              summary.parameterCategories.success++;
            } catch (err: any) {
              summary.parameterCategories.failed++;
              remainingErrors.push({
                sheet: "KategoriParameter",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }

          // 2. Parameter
          for (const row of parsed.parameters) {
            try {
              const item = row.data;
              const existing = parameterMap.get(item.nama);
              const category = categoryMap.get(item.kategori);

              if (!category) {
                throw new Error(`Kategori Parameter "${item.kategori}" tidak ditemukan.`);
              }

              if (existing) {
                const [updated] = await tx
                  .update(parameters)
                  .set({
                    parameterCategoryId: category.id,
                    price: Number(item.harga) || 0,
                    unit: item.satuan,
                    reference: item.referensi,
                  })
                  .where(eq(parameters.id, existing.id))
                  .returning();

                if (updated) {
                  parameterMap.set(updated.name, updated as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "parameter",
                    entityId: updated.id,
                    action: "update",
                    userId,
                    userEmail,
                    oldValues: existing,
                    newValues: updated,
                    description: `Memperbarui Parameter dari Excel: ${updated.name}`,
                  });
                }
              } else {
                const [inserted] = await tx
                  .insert(parameters)
                  .values({
                    name: item.nama,
                    parameterCategoryId: category.id,
                    price: Number(item.harga) || 0,
                    unit: item.satuan,
                    reference: item.referensi,
                  })
                  .returning();

                if (inserted) {
                  parameterMap.set(inserted.name, inserted as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "parameter",
                    entityId: inserted.id,
                    action: "create",
                    userId,
                    userEmail,
                    oldValues: null,
                    newValues: inserted,
                    description: `Membuat Parameter dari Excel: ${inserted.name}`,
                  });
                }
              }
              summary.parameters.success++;
            } catch (err: any) {
              summary.parameters.failed++;
              remainingErrors.push({
                sheet: "Parameter",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }

          // 3. Kode Alat
          for (const row of parsed.toolCodes) {
            try {
              const item = row.data;
              const existing = toolCodeMap.get(item.kode);

              if (existing) {
                const [updated] = await tx
                  .update(toolCodes)
                  .set({
                    description: item.deskripsi,
                    isActive: item.aktif === "ya",
                  })
                  .where(eq(toolCodes.id, existing.id))
                  .returning();

                if (updated) {
                  toolCodeMap.set(updated.code, updated as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "tool_code",
                    entityId: updated.id,
                    action: "update",
                    userId,
                    userEmail,
                    oldValues: existing,
                    newValues: updated,
                    description: `Memperbarui Kode Alat dari Excel: ${updated.code}`,
                  });
                }
              } else {
                const [inserted] = await tx
                  .insert(toolCodes)
                  .values({
                    code: item.kode,
                    description: item.deskripsi,
                    isActive: item.aktif === "ya",
                  })
                  .returning();

                if (inserted) {
                  toolCodeMap.set(inserted.code, inserted as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "tool_code",
                    entityId: inserted.id,
                    action: "create",
                    userId,
                    userEmail,
                    oldValues: null,
                    newValues: inserted,
                    description: `Membuat Kode Alat dari Excel: ${inserted.code}`,
                  });
                }
              }
              summary.toolCodes.success++;
            } catch (err: any) {
              summary.toolCodes.failed++;
              remainingErrors.push({
                sheet: "KodeAlat",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }

          // 4. Alat
          for (const row of parsed.tools) {
            try {
              const item = row.data;
              const existing = toolMap.get(item.kodeFisik);
              const toolCode = toolCodeMap.get(item.kodeAlat);

              if (!toolCode) {
                throw new Error(`Kode Alat "${item.kodeAlat}" tidak ditemukan.`);
              }

              if (existing) {
                const [updated] = await tx
                  .update(tools)
                  .set({
                    toolCodeId: toolCode.id,
                    toolName: item.namaAlat,
                    function: item.fungsi,
                    location: item.lokasi,
                    shelf: item.rak,
                    BMNnumber: item.nomorBMN,
                    NUPnumber: item.nomorNUP,
                    brand: item.merek,
                    type: item.tipe,
                    serialNumber: item.nomorSeri,
                    acquisitionYear: item.tahunPerolehan,
                    condition: item.kondisi as any,
                    availability: item.ketersediaan as any,
                  })
                  .where(eq(tools.id, existing.id))
                  .returning();

                if (updated) {
                  toolMap.set(updated.toolUniqueCode, updated as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "tool",
                    entityId: updated.id,
                    action: "update",
                    userId,
                    userEmail,
                    oldValues: existing,
                    newValues: updated,
                    description: `Memperbarui Alat dari Excel: ${updated.toolUniqueCode}`,
                  });
                }
              } else {
                const [inserted] = await tx
                  .insert(tools)
                  .values({
                    toolUniqueCode: item.kodeFisik,
                    toolCodeId: toolCode.id,
                    toolName: item.namaAlat,
                    function: item.fungsi,
                    location: item.lokasi,
                    shelf: item.rak,
                    BMNnumber: item.nomorBMN,
                    NUPnumber: item.nomorNUP,
                    brand: item.merek,
                    type: item.tipe,
                    serialNumber: item.nomorSeri,
                    acquisitionYear: item.tahunPerolehan,
                    condition: item.kondisi as any,
                    availability: item.ketersediaan as any,
                  })
                  .returning();

                if (inserted) {
                  toolMap.set(inserted.toolUniqueCode, inserted as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "tool",
                    entityId: inserted.id,
                    action: "create",
                    userId,
                    userEmail,
                    oldValues: null,
                    newValues: inserted,
                    description: `Membuat Alat dari Excel: ${inserted.toolUniqueCode}`,
                  });
                }
              }
              summary.tools.success++;
            } catch (err: any) {
              summary.tools.failed++;
              remainingErrors.push({
                sheet: "Alat",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }

          // 5. Bahan Kimia
          for (const row of parsed.chemicalMaterials) {
            try {
              const item = row.data;
              const existing = chemicalMaterialMap.get(item.kode);

              if (existing) {
                const [updated] = await tx
                  .update(chemicalMaterials)
                  .set({
                    catalogNumber: item.nomorKatalog,
                    chemicalFormula: item.rumusKimia,
                    name: item.nama,
                    usedStock: item.stokTerpakai,
                    usedStockUnit: item.unitStokTerpakai as any,
                    sealedStock: item.stokTersegel,
                    sealedStockUnit: item.unitStokTersegel as any,
                    monthlyUsage: item.penggunaanBulanan,
                    monthlyUsageUnit: item.unitPenggunaan as any,
                    expiredDate: item.tanggalKadaluarsa,
                    status: item.status as any,
                    incomingMaterialNote: item.catatanMasuk,
                  })
                  .where(eq(chemicalMaterials.id, existing.id))
                  .returning();

                if (updated) {
                  chemicalMaterialMap.set(updated.code, updated as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "chemical_material",
                    entityId: updated.id,
                    action: "update",
                    userId,
                    userEmail,
                    oldValues: existing,
                    newValues: updated,
                    description: `Memperbarui Bahan Kimia dari Excel: ${updated.code}`,
                  });
                }
              } else {
                const [inserted] = await tx
                  .insert(chemicalMaterials)
                  .values({
                    code: item.kode,
                    catalogNumber: item.nomorKatalog,
                    chemicalFormula: item.rumusKimia,
                    name: item.nama,
                    usedStock: item.stokTerpakai,
                    usedStockUnit: item.unitStokTerpakai as any,
                    sealedStock: item.stokTersegel,
                    sealedStockUnit: item.unitStokTersegel as any,
                    monthlyUsage: item.penggunaanBulanan,
                    monthlyUsageUnit: item.unitPenggunaan as any,
                    expiredDate: item.tanggalKadaluarsa,
                    status: item.status as any,
                    incomingMaterialNote: item.catatanMasuk,
                  })
                  .returning();

                if (inserted) {
                  chemicalMaterialMap.set(inserted.code, inserted as any);
                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "chemical_material",
                    entityId: inserted.id,
                    action: "create",
                    userId,
                    userEmail,
                    oldValues: null,
                    newValues: inserted,
                    description: `Membuat Bahan Kimia dari Excel: ${inserted.code}`,
                  });
                }
              }
              summary.chemicalMaterials.success++;
            } catch (err: any) {
              summary.chemicalMaterials.failed++;
              remainingErrors.push({
                sheet: "BahanKimia",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }
        });

        return { summary, errors: remainingErrors };
      },
      catch: (error: any) => {
        logError(
          "pengujianExcelQueries.importFromParsedData",
          "Failed to import from parsed data",
          { error },
        );
        return new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengimpor data dari Excel.",
          cause: error,
        });
      },
    });
  },
};

// ##################
// end authored
// ##################
