import { Button } from "@/components/ui/button";
import { globalErrorToast, globalSuccessToast } from "@/lib/toast";
import { pageHead } from "@/utils/page-head";
import { queryClient, trpc } from "@/utils/trpc";
import { useMutation, useQuery } from "@tanstack/react-query";
import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import {
  ArrowLeft,
  ArrowRight,
  CheckCircle,
  FileText,
  Loader2,
} from "lucide-react";
import { getPublicUrl } from "@/utils/url";

// ##################
// authored (generated by antigravity, Jun 10 2026 06:35 WITA)
// ##################

/**
 * Mengekstrak ID video YouTube dari URL yang diberikan.
 * Mendukung format watch (youtube.com/watch?v=...), share (youtu.be/...), embed (youtube.com/embed/...), dll.
 */
function getYoutubeId(url: string): string | null {
  if (!url) return null;
  const regExp =
    /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|[&]v=)([^#&?]*).*/;
  const match = url.match(regExp);
  if (!match) return null;
  const id = match[2];
  return id && id.length === 11 ? id : null;
}

/**
 * Memeriksa apakah URL merupakan tautan YouTube.
 */
function isYoutubeUrl(url: string): boolean {
  if (!url) return false;
  return url.includes("youtube.com") || url.includes("youtu.be");
}

// ##################
// end authored
// ##################

export const Route = createFileRoute(
  "/(core)/dashboard/pelatihan/$enrollmentId/materi/$materialId",
)({
  head: () => pageHead("Detail Materi"),
  component: RouteComponent,
});

function RouteComponent() {
  const { enrollmentId, materialId } = Route.useParams();
  const router = useRouter();

  // Use the cached enrollment query
  const { data: enrollment, isLoading } = useQuery(
    trpc.pelatihan.enrollment.getUserEnrollmentById.queryOptions({
      id: enrollmentId,
    }),
  );

  const completeMutation = useMutation(
    trpc.pelatihan.enrollment.markMaterialCompleted.mutationOptions({
      onSuccess: async () => {
        await queryClient.invalidateQueries(
          trpc.pelatihan.enrollment.getUserEnrollmentById.queryOptions({
            id: enrollmentId,
          }),
        );
        await queryClient.invalidateQueries(
          trpc.pelatihan.enrollment.getUserEnrollments.queryOptions(),
        );
        globalSuccessToast("Materi ditandai selesai");
      },
      onError: (err) => {
        globalErrorToast(`Gagal menandai selesai: ${err.message}`);
      },
    }),
  );

  if (isLoading) {
    return (
      <div className="p-8 text-center font-['Poppins']">Memuat materi...</div>
    );
  }

  if (!enrollment) {
    return (
      <div className="p-8 text-center font-['Poppins'] text-destructive">
        Enrollment tidak ditemukan.
      </div>
    );
  }

  const { pelatihan } = enrollment;
  const materials = pelatihan.materials;
  const currentMaterialIndex = materials.findIndex((m) => m.id === materialId);
  const currentMaterial = materials[currentMaterialIndex];

  if (!currentMaterial) {
    return (
      <div className="p-8 text-center font-['Poppins'] text-destructive">
        Materi tidak ditemukan.
      </div>
    );
  }

  const previousMaterial = materials[currentMaterialIndex - 1];
  const nextMaterial = materials[currentMaterialIndex + 1];

  const handleComplete = async () => {
    try {
      await completeMutation.mutateAsync({ enrollmentId, materialId });
      if (nextMaterial) {
        router.navigate({
          to: "/dashboard/pelatihan/$enrollmentId/materi/$materialId",
          params: { enrollmentId, materialId: nextMaterial.id },
        });
      } else {
        router.navigate({
          to: "/dashboard/pelatihan/$enrollmentId/materi",
          params: { enrollmentId },
        });
      }
    } catch {
      // Error handled by mutation onError
    }
  };

  // ##################
  // authored (generated by antigravity, Jun 10 2026 06:35 WITA)
  // ##################
  const resolvedUrl = currentMaterial.fileUrl
    ? getPublicUrl(currentMaterial.fileUrl)
    : "";
  const youtubeId = isYoutubeUrl(resolvedUrl)
    ? getYoutubeId(resolvedUrl)
    : null;
  // ##################
  // end authored
  // ##################

  return (
    <div className="mx-auto max-w-4xl space-y-8 font-['Poppins']">
      {/* Header */}
      <div className="flex items-center justify-between border-b pb-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">
            {currentMaterial.title}
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Materi {currentMaterialIndex + 1} dari {materials.length}
          </p>
        </div>
      </div>

      {/* Content Area */}
      <div className="overflow-hidden rounded-xl border bg-card">
        {currentMaterial.type === "video" ? (
          <div className="relative flex aspect-video w-full items-center justify-center bg-black">
            {/* ##################
                authored (generated by antigravity, Jun 10 2026 06:35 WITA)
            ################## */}
            {youtubeId ? (
              <iframe
                src={`https://www.youtube.com/embed/${youtubeId}?autoplay=0&rel=0`}
                className="absolute inset-0 h-full w-full border-0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                title={currentMaterial.title}
              />
            ) : resolvedUrl ? (
              <video
                src={resolvedUrl}
                controls
                controlsList="nodownload"
                className="absolute inset-0 h-full w-full object-contain"
              />
            ) : (
              <div className="flex flex-col items-center justify-center gap-2 p-6 text-center text-slate-400">
                <svg
                  width="40"
                  height="40"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="opacity-60"
                >
                  <path d="m16 16 3-8 3 8c-.87.2-1.93.3-3 .3s-2.13-.1-3-.3Z" />
                  <path d="M19 8c-.69 0-1.25-.56-1.25-1.25S18.31 5.5 19 5.5s1.25.56 1.25 1.25S19.69 8 19 8Z" />
                  <path d="M10 8H4a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-8a2 2 0 0 0-2-2Z" />
                  <path d="M6 14v-2c0-.55-.45-1-1-1H4" />
                  <path d="M12 5H8a2 2 0 0 0-2 2v1" />
                </svg>
                <span className="text-xs font-bold text-slate-200">
                  Format tautan video tidak valid
                </span>
                <span className="max-w-xs text-[10px] leading-normal text-slate-400">
                  Tautan video kosong atau tidak valid. Harap periksa kembali
                  berkas/tautan materi.
                </span>
              </div>
            )}
            {/* ##################
                end authored
            ################## */}
          </div>
        ) : (
          <div className="flex h-[70vh] flex-col bg-muted/20">
            {/* ##################
                authored (generated by antigravity, Jun 10 2026 06:35 WITA)
            ################## */}
            {resolvedUrl ? (
              <iframe
                src={resolvedUrl}
                className="h-full w-full border-0"
                title={currentMaterial.title}
              />
            ) : (
              <div className="flex h-full flex-col items-center justify-center space-y-4 p-8 text-center">
                <FileText className="h-16 w-16 text-muted-foreground/50" />
                <p className="max-w-md text-muted-foreground">
                  Konten dokumen belum tersedia.
                </p>
                <div className="prose dark:prose-invert mt-4 max-w-none">
                  <p>{currentMaterial.description}</p>
                </div>
              </div>
            )}
            {/* ##################
                end authored
            ################## */}
          </div>
        )}
      </div>

      {/* Navigation */}
      <div className="flex items-center justify-between pt-4">
        {previousMaterial ? (
          <Button variant="outline" asChild>
            <Link
              to="/dashboard/pelatihan/$enrollmentId/materi/$materialId"
              params={{ enrollmentId, materialId: previousMaterial.id }}
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Materi Sebelumnya
            </Link>
          </Button>
        ) : (
          <div></div>
        )}

        <div className="flex items-center gap-4">
          <Button
            variant="secondary"
            onClick={handleComplete}
            disabled={completeMutation.isPending}
          >
            {completeMutation.isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <CheckCircle className="mr-2 h-4 w-4" />
            )}
            Tandai Selesai
          </Button>

          {nextMaterial && (
            <Button asChild>
              <Link
                to="/dashboard/pelatihan/$enrollmentId/materi/$materialId"
                params={{ enrollmentId, materialId: nextMaterial.id }}
              >
                Materi Selanjutnya
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}
