import JSZip from "jszip";

// ##################
// authored (generated by AI, Jul 28 2026 03:44 WITA)
// ##################

export interface ZipDocumentFile {
  fileName: string;
  fileBuffer: Buffer;
}

/**
 * Menggabungkan beberapa file dokumen (Penawaran, Invoice, SPK, SPT, Excel)
 * ke dalam satu file terkompresi .ZIP.
 *
 * @param documents - Array berisi nama file dan buffer dokumen.
 * @returns Buffer ZIP.
 */
export async function buildDocumentZipPackage(
  documents: ZipDocumentFile[],
): Promise<Buffer> {
  const zip = new JSZip();

  documents.forEach((doc) => {
    zip.file(doc.fileName, doc.fileBuffer);
  });

  const zipContent = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return zipContent;
}

// ##################
// end authored
// ##################
