export declare const env: Readonly<{
    AWS_ACCESS_KEY_ID?: string | undefined;
    AWS_SECRET_ACCESS_KEY?: string | undefined;
    S3_BUCKET?: string | undefined;
    MINIO_ENDPOINT?: string | undefined;
    MINIO_PORT?: string | undefined;
    MINIO_USE_SSL?: "true" | "false" | undefined;
    MINIO_ACCESS_KEY?: string | undefined;
    MINIO_SECRET_KEY?: string | undefined;
    MINIO_BUCKET?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: string | undefined;
    SMTP_SECURE?: "true" | "false" | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASSWORD?: string | undefined;
    EMAIL_USER?: string | undefined;
    EMAIL_PASSWORD?: string | undefined;
    SENDGRID_API_KEY?: string | undefined;
    MAILGUN_SMTP_HOST?: string | undefined;
    MAILGUN_SMTP_USER?: string | undefined;
    MAILGUN_SMTP_PASSWORD?: string | undefined;
    AWS_REGION?: string | undefined;
    AWS_SES_SMTP_USER?: string | undefined;
    AWS_SES_SMTP_PASSWORD?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    ETHEREAL_USER?: string | undefined;
    ETHEREAL_PASSWORD?: string | undefined;
    DASHBOARD_URL?: string | undefined;
    JWT_LEGAL_DOCUMENT_SECRET?: string | undefined;
    JWT_TESTING_DOCUMENT_SECRET?: string | undefined;
    JWT_COMPANY_DOCUMENT_SECRET?: string | undefined;
    NODE_ENV: "development" | "production" | "test";
    BASE_URL: string;
    STORAGE_TYPE: "filesystem" | "s3" | "minio";
    UPLOADS_DIR: string;
    EMAIL_FROM: string;
    EMAIL_PROVIDER: "smtp" | "sendgrid" | "mailgun" | "gmail" | "ses" | "resend";
    MEMURAI_HOST: string;
    MEMURAI_PORT: string;
    MEMURAI_PASSWORD: string;
    JWT_DOCUMENT_SECRET: string;
    DOCUMENT_QR_EXPIRATION: string;
    DOCUMENT_VERIFICATION_BASE_URL: string;
}>;
//# sourceMappingURL=env.d.ts.map