// ##################
// authored (generated by gemini, Jun 03 2026 22:50 WITA)
// ##################

import { db } from "@tepian-k3/db/client";
import {
  pelatihanAssessments,
  pelatihanAssessmentAttempts,
  pelatihanAssessmentAnswers,
  pelatihanQuestions,
  pelatihanQuestionOptions,
  pelatihanEnrollments,
  users,
} from "@tepian-k3/db/schema";
import { and, asc, eq, isNull, sql } from "@tepian-k3/db";
import { logError } from "@tepian-k3/services/logger";
import { TRPCError } from "@trpc/server";
import { Effect } from "effect";
import { logCreate, logUpdate, logDelete } from "../helpers/audit.helpers";
import type { z } from "zod";
import type {
  createPelatihanAssessmentSchema,
  updatePelatihanAssessmentSchema,
  addQuestionSchema,
} from "@tepian-k3/schema/pelatihan/pelatihan.schema";

const assessmentQueries = {
  /**
   * Get an assessment by ID
   */
  getAssessmentById(id: string) {
    return Effect.gen(function* () {
      const assessment = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanAssessments.findFirst({
            where: and(
              eq(pelatihanAssessments.id, id),
              isNull(pelatihanAssessments.deletedAt),
            ),
            with: {
              questions: {
                where: (questions, { isNull }) => isNull(questions.deletedAt),
                with: {
                  options: {
                    where: (options, { isNull }) => isNull(options.deletedAt),
                    orderBy: [asc(pelatihanQuestionOptions.orderIndex)],
                  },
                },
                orderBy: [asc(pelatihanQuestions.orderIndex)],
              },
            },
          }),
        catch: (error) => {
          logError(
            "assessmentQueries.getAssessmentById",
            "Failed to fetch assessment",
            { error, id },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data ujian",
          });
        },
      });

      if (!assessment) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Ujian tidak ditemukan",
          }),
        );
      }

      return assessment;
    });
  },
  /**
   * Get an assessment by its associated pelatihan and type (pre_test or post_test).
   * Includes its questions and options.
   *
   * @param pelatihanId - The pelatihan UUID
   * @param type - The type of assessment
   */
  getAssessmentByPelatihan(
    pelatihanId: string,
    type: "pre_test" | "post_test",
  ) {
    return Effect.gen(function* () {
      const assessment = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanAssessments.findFirst({
            where: and(
              eq(pelatihanAssessments.pelatihanId, pelatihanId),
              eq(pelatihanAssessments.type, type),
              isNull(pelatihanAssessments.deletedAt),
            ),
            with: {
              questions: {
                where: (questions, { isNull }) => isNull(questions.deletedAt),
                with: {
                  options: {
                    where: (options, { isNull }) => isNull(options.deletedAt),
                    orderBy: [asc(pelatihanQuestionOptions.orderIndex)],
                  },
                },
                orderBy: [asc(pelatihanQuestions.orderIndex)],
              },
            },
          }),
        catch: (error) => {
          logError(
            "assessmentQueries.getAssessmentByPelatihan",
            "Failed to fetch assessment",
            { error, pelatihanId, type },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data ujian",
          });
        },
      });

      if (!assessment) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Ujian tidak ditemukan",
          }),
        );
      }

      return assessment;
    });
  },

  /**
   * Starts a new attempt for an assessment.
   *
   * @param enrollmentId - The enrollment UUID
   * @param assessmentId - The assessment UUID
   * @param userId - The user UUID to verify ownership
   */
  startAttempt(enrollmentId: string, assessmentId: string, userId: string) {
    return Effect.gen(function* () {
      // 1. Verify enrollment ownership
      const enrollment = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanEnrollments.findFirst({
            where: and(
              eq(pelatihanEnrollments.id, enrollmentId),
              eq(pelatihanEnrollments.userId, userId),
            ),
            with: {
              pelatihan: true,
            },
          }),
        catch: (error) => {
          logError(
            "assessmentQueries.startAttempt",
            "Failed to fetch enrollment",
            { error, enrollmentId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal memverifikasi akses",
          });
        },
      });

      if (!enrollment) {
        return yield* Effect.fail(
          new TRPCError({ code: "NOT_FOUND", message: "Akses ditolak" }),
        );
      }

      // 2. Count existing attempts
      const previousAttempts = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanAssessmentAttempts.findMany({
            where: and(
              eq(pelatihanAssessmentAttempts.enrollmentId, enrollmentId),
              eq(pelatihanAssessmentAttempts.assessmentId, assessmentId),
            ),
            orderBy: [asc(pelatihanAssessmentAttempts.attemptNumber)],
          }),
        catch: () => [],
      });

      // Check if there is an in-progress attempt
      const inProgress = previousAttempts.find(
        (a) => a.status === "in_progress",
      );
      if (inProgress) {
        return {
          success: true,
          attemptId: inProgress.id,
          status: "existing",
          startedAt: inProgress.startedAt,
        };
      }

      // ##################
      // authored (generated by gemini, Jun 08 2026 19:43 WITA)
      // ##################
      // Fetch assessment to check maxAttempts
      const assessment = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanAssessments.findFirst({
            where: and(
              eq(pelatihanAssessments.id, assessmentId),
              isNull(pelatihanAssessments.deletedAt),
            ),
          }),
        catch: (error) => {
          logError(
            "assessmentQueries.startAttempt",
            "Failed to fetch assessment",
            { error, assessmentId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data ujian",
          });
        },
      });

      if (!assessment) {
        return yield* Effect.fail(
          new TRPCError({ code: "NOT_FOUND", message: "Ujian tidak ditemukan" }),
        );
      }

      if (
        assessment.maxAttempts !== null &&
        previousAttempts.length >= assessment.maxAttempts
      ) {
        return yield* Effect.fail(
          new TRPCError({
            code: "BAD_REQUEST",
            message: "Batas maksimal percobaan ujian telah tercapai",
          }),
        );
      }
      // ##################
      // end authored
      // ##################

      const attemptNumber = previousAttempts.length + 1;

      // 3. Create attempt
      const attempt = yield* Effect.tryPromise({
        try: () =>
          db
            .insert(pelatihanAssessmentAttempts)
            .values({
              enrollmentId,
              assessmentId,
              attemptNumber,
              status: "in_progress",
            })
            .returning()
            .then((res) => res[0]),
        catch: (error) => {
          logError(
            "assessmentQueries.startAttempt",
            "Failed to create attempt",
            { error, enrollmentId, assessmentId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal memulai ujian",
          });
        },
      });

      if (!attempt) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal membuat attempt",
        });
      }

      return {
        success: true,
        attemptId: attempt.id,
        status: "new",
        startedAt: attempt.startedAt,
      };
    });
  },

  /**
   * Submits an assessment attempt and calculates the score.
   */
  submitAttempt(
    attemptId: string,
    answers: Record<string, string>,
    userId: string,
  ) {
    return Effect.gen(function* () {
      // 1. Fetch attempt and verify ownership
      const attempt = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanAssessmentAttempts.findFirst({
            where: eq(pelatihanAssessmentAttempts.id, attemptId),
            with: {
              enrollment: true,
              assessment: {
                with: {
                  questions: {
                    with: {
                      options: true,
                    },
                  },
                },
              },
            },
          }),
        catch: (error) => {
          logError(
            "assessmentQueries.submitAttempt",
            "Failed to fetch attempt",
            { error, attemptId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data ujian",
          });
        },
      });

      if (!attempt || attempt.enrollment.userId !== userId) {
        return yield* Effect.fail(
          new TRPCError({ code: "NOT_FOUND", message: "Akses ditolak" }),
        );
      }

      if (attempt.status !== "in_progress") {
        return yield* Effect.fail(
          new TRPCError({
            code: "BAD_REQUEST",
            message: "Ujian sudah disubmit sebelumnya",
          }),
        );
      }

      // 2. Calculate score
      let totalPoints = 0;
      let earnedPoints = 0;
      const answerRecords: (typeof pelatihanAssessmentAnswers.$inferInsert)[] =
        [];

      for (const question of attempt.assessment.questions) {
        totalPoints += question.points || 1;
        const userAnswerId = answers[question.id];

        let isCorrect = false;
        let pointsEarned = 0;

        if (userAnswerId) {
          const selectedOption = question.options.find(
            (o) => o.id === userAnswerId,
          );
          if (selectedOption?.isCorrect) {
            isCorrect = true;
            pointsEarned = question.points || 1;
            earnedPoints += pointsEarned;
          }
        }

        answerRecords.push({
          attemptId,
          questionId: question.id,
          answer: userAnswerId || "",
          isCorrect,
          pointsEarned,
        });
      }

      // ##################
      // authored (generated by gemini, Jun 08 2026 21:00 WITA)
      // ##################
      const score = totalPoints === 0 ? 0 : Math.round((earnedPoints / totalPoints) * 100);
      const passed = score >= (attempt.assessment.passingScore || 0);
      // ##################
      // end authored
      // ##################

      // 3. Save answers and update attempt
      yield* Effect.tryPromise({
        try: async () => {
          await db.transaction(async (tx) => {
            if (answerRecords.length > 0) {
              await tx.insert(pelatihanAssessmentAnswers).values(answerRecords);
            }

            await tx
              .update(pelatihanAssessmentAttempts)
              .set({
                status: "graded",
                score,
                totalPoints,
                earnedPoints,
                passed,
                submittedAt: new Date().toISOString(),
              })
              .where(eq(pelatihanAssessmentAttempts.id, attemptId));

            // Update enrollment score
            const assessmentType = attempt.assessment.type;
            const enrollmentUpdate: Partial<
              typeof pelatihanEnrollments.$inferInsert
            > = {};
            if (assessmentType === "pre_test") {
              // Update preTestScore if it's the highest
              if (
                !attempt.enrollment.preTestScore ||
                score > attempt.enrollment.preTestScore
              ) {
                enrollmentUpdate.preTestScore = score;
              }
            } else if (assessmentType === "post_test") {
              // Update postTestScore and finalScore if it's the highest
              if (
                !attempt.enrollment.postTestScore ||
                score > attempt.enrollment.postTestScore
              ) {
                enrollmentUpdate.postTestScore = score;
                enrollmentUpdate.finalScore = score;
                if (passed) {
                  enrollmentUpdate.status = "completed";
                  enrollmentUpdate.completedAt = new Date().toISOString();
                }
              }
            }

            if (Object.keys(enrollmentUpdate).length > 0) {
              await tx
                .update(pelatihanEnrollments)
                .set(enrollmentUpdate)
                .where(eq(pelatihanEnrollments.id, attempt.enrollmentId));
            }
          });
        },
        catch: (error) => {
          logError(
            "assessmentQueries.submitAttempt",
            "Failed to save answers",
            { error, attemptId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menyimpan jawaban",
          });
        },
      });

      return {
        success: true,
        score,
        passed,
      };
    });
  },

  /**
   * Get all assessments for a specific pelatihan, including attempt status and score summary.
   *
   * @param pelatihanId - The pelatihan UUID
   * @param enrollmentId - The enrollment UUID for the user
   */
  getAssessmentsByPelatihanId(pelatihanId: string, enrollmentId: string) {
    return Effect.gen(function* () {
      const assessments = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanAssessments.findMany({
            where: and(
              eq(pelatihanAssessments.pelatihanId, pelatihanId),
              isNull(pelatihanAssessments.deletedAt),
            ),
            with: {
              questions: {
                where: (questions, { isNull }) => isNull(questions.deletedAt),
              },
            },
          }),
        catch: (error) => {
          logError(
            "assessmentQueries.getAssessmentsByPelatihanId",
            "Failed to fetch assessments",
            { error, pelatihanId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data ujian",
          });
        },
      });

      const attempts = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanAssessmentAttempts.findMany({
            where: eq(pelatihanAssessmentAttempts.enrollmentId, enrollmentId),
          }),
        catch: (error) => {
          logError(
            "assessmentQueries.getAssessmentsByPelatihanId",
            "Failed to fetch attempts",
            { error, enrollmentId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data pengerjaan ujian",
          });
        },
      });

      return assessments.map((assessment) => {
        const assessmentAttempts = attempts.filter(
          (a) => a.assessmentId === assessment.id,
        );
        const attemptCount = assessmentAttempts.length;

        const gradedAttempts = assessmentAttempts.filter(
          (a) => a.status === "graded",
        );
        const bestAttempt = gradedAttempts.reduce<
          (typeof gradedAttempts)[0] | null
        >((best, current) => {
          if (!best) return current;
          if (
            current.score !== null &&
            best.score !== null &&
            current.score > best.score
          ) {
            return current;
          }
          return best;
        }, null);

        const inProgressAttempt = assessmentAttempts.find(
          (a) => a.status === "in_progress",
        );

        return {
          id: assessment.id,
          type: assessment.type,
          title: assessment.title,
          description: assessment.description,
          passingScore: assessment.passingScore,
          timeLimit: assessment.timeLimit,
          maxAttempts: assessment.maxAttempts,
          questionCount: assessment.questions.length,
          attemptCount,
          bestScore: bestAttempt ? bestAttempt.score : null,
          isPassed: bestAttempt ? bestAttempt.passed : false,
          hasAttempted: attemptCount > 0,
          inProgressAttemptId: inProgressAttempt ? inProgressAttempt.id : null,
        };
      });
    });
  },

  /**
   * Membuat ujian baru (Pre-Test / Post-Test) terkait pelatihan.
   *
   * @param userId - ID user pembuat
   * @param input - Payload data ujian baru
   * @returns Data ujian yang berhasil dibuat
   */
  createAssessment(
    userId: string,
    input: z.infer<typeof createPelatihanAssessmentSchema>,
  ) {
    return Effect.gen(function* () {
      const [newAssessment] = yield* Effect.tryPromise({
        try: () =>
          db
            .insert(pelatihanAssessments)
            .values({
              ...input,
            })
            .returning(),
        catch: (error) => {
          logError("assessmentQueries.createAssessment", "Failed to create assessment", { error, input });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal membuat ujian baru",
          });
        },
      });

      if (!newAssessment) {
        return yield* Effect.fail(
          new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal membuat ujian baru",
          }),
        );
      }

      // Fetch user email from DB for audit log
      const user = yield* Effect.tryPromise({
        try: () =>
          db.query.users.findFirst({
            where: eq(users.id, userId),
          }),
        catch: () => null,
      });
      const userEmail = user?.email ?? "";

      yield* logCreate(
        "pelatihan",
        newAssessment.id,
        newAssessment as any,
        userId,
        userEmail,
        { description: `Membuat ujian baru: ${newAssessment.title}` },
      );

      return newAssessment;
    });
  },

  /**
   * Memperbarui konfigurasi/metadata ujian.
   *
   * @param userId - ID user pengubah
   * @param input - Payload data update ujian
   * @returns Data ujian yang diperbarui
   */
  updateAssessment(
    userId: string,
    input: z.infer<typeof updatePelatihanAssessmentSchema>,
  ) {
    return Effect.gen(function* () {
      const { id, ...updateData } = input;
      const [updated] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(pelatihanAssessments)
            .set(updateData)
            .where(eq(pelatihanAssessments.id, id))
            .returning(),
        catch: (error) => {
          logError("assessmentQueries.updateAssessment", "Failed to update assessment", { error, id });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal memperbarui ujian",
          });
        },
      });

      if (!updated) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Ujian tidak ditemukan",
          }),
        );
      }

      // Fetch user email from DB for audit log
      const user = yield* Effect.tryPromise({
        try: () =>
          db.query.users.findFirst({
            where: eq(users.id, userId),
          }),
        catch: () => null,
      });
      const userEmail = user?.email ?? "";

      yield* logUpdate(
        "pelatihan",
        id,
        { id },
        updated as any,
        userId,
        userEmail,
        { description: `Memperbarui ujian: ${updated.title}` },
      );

      return updated;
    });
  },

  /**
   * Menghapus ujian (soft delete).
   *
   * @param userId - ID user penghapus
   * @param id - ID ujian yang akan dihapus
   * @returns Data ujian yang dihapus
   */
  deleteAssessment(userId: string, id: string) {
    return Effect.gen(function* () {
      const [deleted] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(pelatihanAssessments)
            .set({ deletedAt: sql`CURRENT_TIMESTAMP` })
            .where(eq(pelatihanAssessments.id, id))
            .returning(),
        catch: (error) => {
          logError("assessmentQueries.deleteAssessment", "Failed to delete assessment", { error, id });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menghapus ujian",
          });
        },
      });

      if (!deleted) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Ujian tidak ditemukan",
          }),
        );
      }

      // Fetch user email from DB for audit log
      const user = yield* Effect.tryPromise({
        try: () =>
          db.query.users.findFirst({
            where: eq(users.id, userId),
          }),
        catch: () => null,
      });
      const userEmail = user?.email ?? "";

      yield* logDelete(
        "pelatihan",
        id,
        deleted as any,
        userId,
        userEmail,
        { description: `Menghapus ujian: ${deleted.title}` },
      );

      return deleted;
    });
  },

  /**
   * Menambahkan soal beserta pilihan jawabannya ke ujian.
   *
   * @param userId - ID user pembuat
   * @param input - Payload data soal dan opsi-opsi jawaban
   * @returns Objek pertanyaan dan opsi jawaban yang dibuat
   */
  addQuestion(
    userId: string,
    input: z.infer<typeof addQuestionSchema>,
  ) {
    return Effect.gen(function* () {
      const result = yield* Effect.tryPromise({
        try: () =>
          db.transaction(async (tx) => {
            const [newQuestion] = await tx
              .insert(pelatihanQuestions)
              .values({
                assessmentId: input.assessmentId,
                questionText: input.questionText,
                type: input.type,
                points: input.points,
              })
              .returning();

            if (!newQuestion) {
              throw new Error("Gagal membuat pertanyaan");
            }

            let insertedOptions: any[] = [];
            if (input.options && input.options.length > 0) {
              insertedOptions = await tx
                .insert(pelatihanQuestionOptions)
                .values(
                  input.options.map((opt, idx) => ({
                    questionId: newQuestion.id,
                    optionText: opt.optionText,
                    isCorrect: opt.isCorrect,
                    orderIndex: idx,
                  })),
                )
                .returning();
            }

            return { newQuestion, insertedOptions };
          }),
        catch: (error) => {
          logError("assessmentQueries.addQuestion", "Failed to add question", { error, input });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menambahkan soal",
          });
        },
      });

      // Fetch user email from DB for audit log
      const user = yield* Effect.tryPromise({
        try: () =>
          db.query.users.findFirst({
            where: eq(users.id, userId),
          }),
        catch: () => null,
      });
      const userEmail = user?.email ?? "";

      yield* logCreate(
        "pelatihan",
        result.newQuestion.id,
        result.newQuestion as any,
        userId,
        userEmail,
        { description: `Menambahkan soal ke ujian: ${input.questionText}` },
      );

      return result;
    });
  },

  /**
   * Menghapus soal dari ujian (soft delete).
   *
   * @param userId - ID user penghapus
   * @param id - ID soal yang akan dihapus
   * @returns Data soal yang dihapus
   */
  deleteQuestion(userId: string, id: string) {
    return Effect.gen(function* () {
      const [deleted] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(pelatihanQuestions)
            .set({ deletedAt: sql`CURRENT_TIMESTAMP` })
            .where(eq(pelatihanQuestions.id, id))
            .returning(),
        catch: (error) => {
          logError("assessmentQueries.deleteQuestion", "Failed to delete question", { error, id });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menghapus soal",
          });
        },
      });

      if (!deleted) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Soal tidak ditemukan",
          }),
        );
      }

      // Fetch user email from DB for audit log
      const user = yield* Effect.tryPromise({
        try: () =>
          db.query.users.findFirst({
            where: eq(users.id, userId),
          }),
        catch: () => null,
      });
      const userEmail = user?.email ?? "";

      yield* logDelete(
        "pelatihan",
        id,
        deleted as any,
        userId,
        userEmail,
        { description: `Menghapus soal: ${deleted.questionText}` },
      );

      return deleted;
    });
  },
};

export default assessmentQueries;
