import { db } from "@tepian-k3/db/client";
import { pelatihanCart, pelatihan } from "@tepian-k3/db/schema";
import { logError } from "@tepian-k3/services/logger";
import { TRPCError } from "@trpc/server";
import { and, eq, isNull, sql } from "@tepian-k3/db";
import { Effect } from "effect";

const pelatihanCartQueries = {
  // ##################
  // authored (generated by gemini, Jun 08 2026 19:43 WITA)
  // ##################
  /**
   * Mengambil isi keranjang belanja user yang belum dihapus (soft-deleted).
   *
   * @param userId - ID user pemilik keranjang
   * @returns Daftar item keranjang beserta informasi pelatihan terkait
   */
  getCart(userId: string) {
    return Effect.tryPromise({
      try: () =>
        db.query.pelatihanCart.findMany({
          where: and(
            eq(pelatihanCart.userId, userId),
            isNull(pelatihanCart.deletedAt),
          ),
          with: {
            pelatihan: true,
          },
        }),
      catch: (error) => {
        logError("pelatihanCartQueries.getCart", "Failed to fetch cart", {
          error,
          userId,
        });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil keranjang pelatihan",
        });
      },
    });
  },
  // ##################
  // end authored
  // ##################

  addToCart(userId: string, pelatihanId: string) {
    return Effect.gen(function* () {
      // Check if already in cart
      // ##################
      // authored (generated by gemini, Jun 08 2026 19:43 WITA)
      // ##################
      const existing = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihanCart.findFirst({
            where: and(
              eq(pelatihanCart.userId, userId),
              eq(pelatihanCart.pelatihanId, pelatihanId),
              isNull(pelatihanCart.deletedAt),
            ),
          }),
      // ##################
      // end authored
      // ##################
        catch: (error) => {
          logError(
            "pelatihanCartQueries.addToCart",
            "Failed to check existing cart item",
            {
              error,
              userId,
              pelatihanId,
            },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengecek keranjang pelatihan",
          });
        },
      });

      if (existing) {
        throw new TRPCError({
          code: "CONFLICT",
          message: "Pelatihan sudah ada di keranjang",
        });
      }

      const pelatihanInfo = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihan.findFirst({
            where: eq(pelatihan.id, pelatihanId),
          }),
        catch: (error) => {
          logError(
            "pelatihanCartQueries.addToCart",
            "Failed to fetch pelatihan info",
            { error, pelatihanId },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil data pelatihan",
          });
        },
      });

      if (!pelatihanInfo) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Pelatihan tidak ditemukan",
        });
      }

      // ##################
      // authored (generated by gemini, Jun 08 2026 21:00 WITA)
      // ##################
      // Add to cart
      return yield* Effect.tryPromise({
        try: () =>
          db
            .insert(pelatihanCart)
            .values({
              userId,
              pelatihanId,
              unitPrice: pelatihanInfo.price,
              discountPrice: pelatihanInfo.discountPrice,
            })
            .returning(),
      // ##################
      // end authored
      // ##################
        catch: (error) => {
          logError(
            "pelatihanCartQueries.addToCart",
            "Failed to add item to cart",
            {
              error,
              userId,
              pelatihanId,
            },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menambahkan pelatihan ke keranjang",
          });
        },
      });
    });
  },

  // ##################
  // authored (generated by gemini, Jun 08 2026 20:13 WITA)
  // ##################
  /**
   * Menghapus item tertentu dari keranjang belanja secara soft-delete.
   */
  removeFromCart(userId: string, pelatihanId: string) {
    return Effect.tryPromise({
      try: () =>
        db
          .update(pelatihanCart)
          .set({ deletedAt: sql`CURRENT_TIMESTAMP` })
          .where(
            and(
              eq(pelatihanCart.userId, userId),
              eq(pelatihanCart.pelatihanId, pelatihanId),
              isNull(pelatihanCart.deletedAt),
            ),
          ),
  // ##################
  // end authored
  // ##################
      catch: (error) => {
        logError(
          "pelatihanCartQueries.removeFromCart",
          "Failed to remove item from cart",
          {
            error,
            userId,
            pelatihanId,
          },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal menghapus pelatihan dari keranjang",
        });
      },
    });
  },

  // ##################
  // authored (generated by gemini, Jun 08 2026 20:13 WITA)
  // ##################
  /**
   * Mengosongkan keranjang belanja user secara soft-delete.
   */
  clearCart(userId: string) {
    return Effect.tryPromise({
      try: () =>
        db
          .update(pelatihanCart)
          .set({ deletedAt: sql`CURRENT_TIMESTAMP` })
          .where(
            and(
              eq(pelatihanCart.userId, userId),
              isNull(pelatihanCart.deletedAt),
            ),
          ),
  // ##################
  // end authored
  // ##################
      catch: (error) => {
        logError("pelatihanCartQueries.clearCart", "Failed to clear cart", {
          error,
          userId,
        });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengosongkan keranjang",
        });
      },
    });
  },
};

export default pelatihanCartQueries;
