import { db } from "@tepian-k3/db/client";
import {
  pelatihan,
  pelatihanCart,
  pelatihanEnrollments,
  pelatihanOrders,
  pelatihanCategories,
} from "@tepian-k3/db/schema";
import {
  and,
  count,
  desc,
  eq,
  ilike,
  isNotNull,
  isNull,
  sql,
} from "@tepian-k3/db";
import { logError } from "@tepian-k3/services/logger";
import { TRPCError } from "@trpc/server";
import { Effect } from "effect";
import type { z } from "zod";
import { pelatihanSchema } from "@tepian-k3/schema/pelatihan/pelatihan.schema";
import { logCreate } from "../helpers/audit.helpers";

const pelatihanQueries = {
  createPelatihan(
    userId: string,
    data: z.infer<typeof pelatihanSchema.createPelatihanSchema>,
  ) {
    return Effect.gen(function* () {
      // ##################
      // authored (generated by gemini, Jun 03 2026 12:35 WITA)
      // ##################
      const existing = yield* Effect.tryPromise({
        try: () =>
          db.query.pelatihan.findFirst({
            where: and(eq(pelatihan.slug, data.slug), isNull(pelatihan.deletedAt)),
          }),
        catch: (error) => {
          logError(
            "pelatihanQueries.createPelatihan.checkSlug",
            "Failed to check duplicate slug",
            { error, slug: data.slug }
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal memeriksa slug pelatihan",
          });
        },
      });

      if (existing) {
        return yield* Effect.fail(
          new TRPCError({
            code: "CONFLICT",
            message: "Pelatihan dengan slug tersebut sudah ada.",
          })
        );
      }
      // ##################
      // end authored
      // ##################

      const [newPelatihan] = yield* Effect.tryPromise({
        try: () => db.insert(pelatihan).values(data).returning(),
        catch: (error) => {
          logError(
            "pelatihanQueries.createPelatihan",
            "Failed to create pelatihan",
            {
              error,
              userId,
              data,
            },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal membuat pelatihan",
          });
        },
      });

      if (!newPelatihan) {
        return yield* Effect.fail(
          new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal membuat pelatihan",
          }),
        );
      }

      yield* Effect.forkDaemon(
        logCreate(
          "pelatihan",
          newPelatihan.id,
          newPelatihan as Record<string, unknown>,
          userId,
        ),
      );

      return newPelatihan;
    });
  },

  getAllPelatihan(
    input: z.infer<typeof pelatihanSchema.getAllPelatihanSchema>,
  ) {
    return Effect.gen(function* () {
      const offset = (input.page - 1) * input.perPage;
      const where = and(
        input.search ? ilike(pelatihan.title, `%${input.search}%`) : undefined,
        input.status ? eq(pelatihan.status, input.status) : undefined,
        input.level ? eq(pelatihan.level, input.level) : undefined,
        input.type ? eq(pelatihan.type, input.type) : undefined,
        input.categoryId
          ? eq(pelatihan.categoryId, input.categoryId)
          : undefined,
        input.showDeleted
          ? isNotNull(pelatihan.deletedAt)
          : isNull(pelatihan.deletedAt),
      );

      const { data, total } = yield* Effect.tryPromise({
        try: () =>
          db.transaction(async (tx) => {
            const data = await tx.query.pelatihan.findMany({
              where,
              limit: input.perPage,
              offset,
              orderBy: (table, { asc, desc }) =>
                input.sort && input.sort.length > 0
                  ? input.sort.map((item) =>
                      item.desc
                        ? desc((table as any)[item.id])
                        : asc((table as any)[item.id]),
                    )
                  : [desc(table.createdAt)],
            });

            const total = await tx
              .select({ count: count(pelatihan.id) })
              .from(pelatihan)
              .where(where)
              .execute()
              .then((res) => Number(res[0]?.count ?? 0));

            return { data, total };
          }),
        catch: (error) => {
          logError(
            "pelatihanQueries.getAllPelatihan",
            "Failed to fetch pelatihan",
            {
              error,
              input,
            },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengambil daftar pelatihan",
          });
        },
      });

      const pageCount = Math.ceil(total / input.perPage);

      return { data, pageCount };
    });
  },

  getPelatihanById(id: string) {
    return Effect.tryPromise({
      try: () =>
        db.query.pelatihan.findFirst({
          where: eq(pelatihan.id, id),
        }),
      catch: (error) => {
        logError(
          "pelatihanQueries.getPelatihanById",
          "Failed to fetch pelatihan by ID",
          {
            error,
            id,
          },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil pelatihan",
        });
      },
    });
  },

  getPelatihanBySlug(slug: string) {
    return Effect.tryPromise({
      try: () =>
        db.query.pelatihan.findFirst({
          where: eq(pelatihan.slug, slug),
          with: {
            category: true,
            // ##################
            // authored (generated by gemini, Jun 04 2026 13:36 WITA)
            // ##################
            modules: {
              where: (modules, { isNull }) => isNull(modules.deletedAt),
              orderBy: (modules, { asc }) => [asc(modules.orderIndex)],
              with: {
                materials: {
                  where: (materials, { isNull }) => isNull(materials.deletedAt),
                  orderBy: (materials, { asc }) => [asc(materials.orderIndex)],
                  columns: {
                    id: true,
                    title: true,
                    type: true,
                    description: true,
                    isPreview: true,
                    duration: true,
                    orderIndex: true,
                  },
                },
              },
            },
            // Materi orphan (tanpa modul)
            materials: {
              where: (materials, { isNull }) => isNull(materials.deletedAt),
              orderBy: (materials, { asc }) => [asc(materials.orderIndex)],
              columns: {
                id: true,
                title: true,
                type: true,
                description: true,
                isPreview: true,
                duration: true,
                orderIndex: true,
                moduleId: true,
              },
            },
            // ##################
            // end authored
            // ##################
          },
        }),
      catch: (error) => {
        logError(
          "pelatihanQueries.getPelatihanBySlug",
          "Failed to fetch pelatihan by slug",
          {
            error,
            slug,
          },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil pelatihan",
        });
      },
    });
  },

  enrollUser(userId: string, pelatihanId: string, orderId?: string) {
    return Effect.gen(function* () {
      const [enrollment] = yield* Effect.tryPromise({
        try: () =>
          db
            .insert(pelatihanEnrollments)
            .values({
              userId,
              pelatihanId,
              orderId,
              status: "enrolled",
            })
            .returning(),
        catch: (error) => {
          logError("pelatihanQueries.enrollUser", "Failed to enroll user", {
            error,
            userId,
            pelatihanId,
          });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mendaftarkan peserta ke pelatihan",
          });
        },
      });
      return enrollment;
    });
  },

  removeFromCart(userId: string, pelatihanId: string) {
    return Effect.gen(function* () {
      yield* Effect.tryPromise({
        try: () =>
          db
            .delete(pelatihanCart)
            .where(
              and(
                eq(pelatihanCart.userId, userId),
                eq(pelatihanCart.pelatihanId, pelatihanId),
              ),
            ),
        catch: (error) => {
          logError(
            "pelatihanQueries.removeFromCart",
            "Failed to remove from cart",
            {
              error,
              userId,
              pelatihanId,
            },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menghapus dari keranjang",
          });
        },
      });
    });
  },

  updatePelatihan(
    userId: string,
    id: string,
    data: Omit<z.infer<typeof pelatihanSchema.updatePelatihanSchema>, "id">,
  ) {
    return Effect.gen(function* () {
      // ##################
      // authored (generated by gemini, Jun 03 2026 12:35 WITA)
      // ##################
      if (data.slug) {
        const slugToCheck = data.slug;
        const existing = yield* Effect.tryPromise({
          try: () =>
            db.query.pelatihan.findFirst({
              where: and(
                eq(pelatihan.slug, slugToCheck),
                sql`${pelatihan.id} <> ${id}`,
                isNull(pelatihan.deletedAt),
              ),
            }),
          catch: (error) => {
            logError(
              "pelatihanQueries.updatePelatihan.checkSlug",
              "Failed to check duplicate slug",
              { error, slug: slugToCheck }
            );
            throw new TRPCError({
              code: "INTERNAL_SERVER_ERROR",
              message: "Gagal memeriksa slug pelatihan",
            });
          },
        });

        if (existing) {
          return yield* Effect.fail(
            new TRPCError({
              code: "CONFLICT",
              message: "Pelatihan dengan slug tersebut sudah ada.",
            })
          );
        }
      }
      // ##################
      // end authored
      // ##################

      const [updated] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(pelatihan)
            .set({ ...data, updatedAt: new Date().toISOString() })
            .where(eq(pelatihan.id, id))
            .returning(),
        catch: (error) => {
          logError(
            "pelatihanQueries.updatePelatihan",
            "Failed to update pelatihan",
            {
              error,
              id,
              userId,
            },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal memperbarui pelatihan",
          });
        },
      });

      return updated;
    });
  },

  deletePelatihan(userId: string, id: string) {
    return Effect.gen(function* () {
      const [deleted] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(pelatihan)
            .set({ deletedAt: new Date().toISOString() })
            .where(eq(pelatihan.id, id))
            .returning(),
        catch: (error) => {
          logError(
            "pelatihanQueries.deletePelatihan",
            "Failed to delete pelatihan",
            {
              error,
              id,
              userId,
            },
          );
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menghapus pelatihan",
          });
        },
      });

      return deleted;
    });
  },

  getDashboardStats() {
    return Effect.tryPromise({
      try: async () => {
        const { pelatihanCertificates } = await import("@tepian-k3/db/schema");

        const [totalPelatihan] = await db
          .select({ count: count(pelatihan.id) })
          .from(pelatihan)
          .where(isNull(pelatihan.deletedAt));

        const [totalEnrollments] = await db
          .select({ count: count(pelatihanEnrollments.id) })
          .from(pelatihanEnrollments)
          .where(isNull(pelatihanEnrollments.deletedAt));

        const [totalRevenue] = await db
          .select({
            sum: sql<number>`coalesce(sum(${pelatihanOrders.totalAmount}), 0)`,
          })
          .from(pelatihanOrders)
          .where(
            and(
              eq(pelatihanOrders.status, "verified"),
              isNull(pelatihanOrders.deletedAt),
            ),
          );

        const [pendingVerification] = await db
          .select({ count: count(pelatihanOrders.id) })
          .from(pelatihanOrders)
          .where(
            and(
              eq(pelatihanOrders.status, "waiting_verification"),
              isNull(pelatihanOrders.deletedAt),
            ),
          );

        const [totalCertificates] = await db
          .select({ count: count(pelatihanCertificates.id) })
          .from(pelatihanCertificates)
          .where(isNull(pelatihanCertificates.deletedAt));

        // Group counts by type
        const pelatihanTypes = await db
          .select({ type: pelatihan.type, count: count(pelatihan.id) })
          .from(pelatihan)
          .where(isNull(pelatihan.deletedAt))
          .groupBy(pelatihan.type);

        const enrollmentTypes = await db
          .select({
            type: pelatihan.type,
            count: count(pelatihanEnrollments.id),
          })
          .from(pelatihanEnrollments)
          .innerJoin(
            pelatihan,
            eq(pelatihanEnrollments.pelatihanId, pelatihan.id),
          )
          .where(isNull(pelatihanEnrollments.deletedAt))
          .groupBy(pelatihan.type);

        const recentOrders = await db.query.pelatihanOrders.findMany({
          where: and(
            eq(pelatihanOrders.status, "verified"),
            isNull(pelatihanOrders.deletedAt),
          ),
          orderBy: [desc(pelatihanOrders.createdAt)],
          limit: 10,
        });

        const recentEnrollments = await db.query.pelatihanEnrollments.findMany({
          where: isNull(pelatihanEnrollments.deletedAt),
          with: {
            user: { columns: { id: true, name: true, email: true } },
            pelatihan: {
              columns: { id: true, title: true, level: true, type: true },
            },
          },
          orderBy: [desc(pelatihanEnrollments.enrolledAt)],
          limit: 5,
        });

        return {
          totalPelatihan: Number(totalPelatihan?.count ?? 0),
          totalEnrollments: Number(totalEnrollments?.count ?? 0),
          totalRevenue: Number(totalRevenue?.sum ?? 0),
          pendingVerification: Number(pendingVerification?.count ?? 0),
          totalCertificates: Number(totalCertificates?.count ?? 0),
          pelatihanTypeCounts: {
            elearning: Number(
              pelatihanTypes.find((t) => t.type === "elearning")?.count ?? 0,
            ),
            bimtek: Number(
              pelatihanTypes.find((t) => t.type === "bimtek")?.count ?? 0,
            ),
            webinar: Number(
              pelatihanTypes.find((t) => t.type === "webinar")?.count ?? 0,
            ),
          },
          enrollmentTypeCounts: {
            elearning: Number(
              enrollmentTypes.find((t) => t.type === "elearning")?.count ?? 0,
            ),
            bimtek: Number(
              enrollmentTypes.find((t) => t.type === "bimtek")?.count ?? 0,
            ),
            webinar: Number(
              enrollmentTypes.find((t) => t.type === "webinar")?.count ?? 0,
            ),
          },
          recentOrders: recentOrders.map((o) => ({
            id: o.id,
            orderNumber: o.orderNumber,
            totalAmount: o.totalAmount,
            createdAt: o.createdAt,
          })),
          recentEnrollments: recentEnrollments.map((e) => ({
            id: e.id,
            user: e.user,
            pelatihan: e.pelatihan,
            enrolledAt: e.enrolledAt,
          })),
        };
      },
      catch: (error) => {
        logError(
          "pelatihanQueries.getDashboardStats",
          "Failed to fetch dashboard stats",
          { error },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data statistik dashboard",
        });
      },
    });
  },
  getAllCategories() {
    return Effect.tryPromise({
      try: () =>
        db.query.pelatihanCategories.findMany({
          where: isNull(pelatihanCategories.deletedAt),
          orderBy: desc(pelatihanCategories.orderIndex),
        }),
      catch: (error) => {
        logError(
          "pelatihanQueries.getAllCategories",
          "Failed to fetch categories",
          { error }
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data kategori pelatihan",
        });
      },
    });
  },

  // ##################
  // authored (generated by gemini, Jun 09 2026 18:18 WITA)
  // ##################
  /**
   * Mengambil data statistik ringkasan dan aktivitas pendaftaran terbaru
   * untuk detail pelatihan tertentu di back-office.
   * 
   * @param pelatihanId ID pelatihan (UUID)
   * @returns Data statistik agregat dan aktivitas pendaftaran
   */
  getPelatihanStats(pelatihanId: string) {
    return Effect.tryPromise({
      try: async () => {
        // 1. Total Peserta
        const [totalPeserta] = await db
          .select({ count: count(pelatihanEnrollments.id) })
          .from(pelatihanEnrollments)
          .where(
            and(
              eq(pelatihanEnrollments.pelatihanId, pelatihanId),
              isNull(pelatihanEnrollments.deletedAt),
            ),
          );

        // 2. Total Peserta Baru Bulan Ini (30 Hari Terakhir)
        const thirtyDaysAgo = new Date();
        thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
        const [totalPesertaBaru] = await db
          .select({ count: count(pelatihanEnrollments.id) })
          .from(pelatihanEnrollments)
          .where(
            and(
              eq(pelatihanEnrollments.pelatihanId, pelatihanId),
              sql`${pelatihanEnrollments.enrolledAt} >= ${thirtyDaysAgo.toISOString()}`,
              isNull(pelatihanEnrollments.deletedAt),
            ),
          );

        // 3. Rata-rata Progress
        const [avgProgress] = await db
          .select({
            avg: sql<number>`coalesce(avg(${pelatihanEnrollments.progressPercentage}), 0)`,
          })
          .from(pelatihanEnrollments)
          .where(
            and(
              eq(pelatihanEnrollments.pelatihanId, pelatihanId),
              isNull(pelatihanEnrollments.deletedAt),
            ),
          );

        // 4. Rata-rata Pre-Test
        const [avgPretest] = await db
          .select({
            avg: sql<number>`coalesce(avg(${pelatihanEnrollments.preTestScore}), 0)`,
          })
          .from(pelatihanEnrollments)
          .where(
            and(
              eq(pelatihanEnrollments.pelatihanId, pelatihanId),
              isNotNull(pelatihanEnrollments.preTestScore),
              isNull(pelatihanEnrollments.deletedAt),
            ),
          );

        // 5. Rata-rata Post-Test
        const [avgPosttest] = await db
          .select({
            avg: sql<number>`coalesce(avg(${pelatihanEnrollments.postTestScore}), 0)`,
          })
          .from(pelatihanEnrollments)
          .where(
            and(
              eq(pelatihanEnrollments.pelatihanId, pelatihanId),
              isNotNull(pelatihanEnrollments.postTestScore),
              isNull(pelatihanEnrollments.deletedAt),
            ),
          );

        // 6. Recent Activity (5 latest enrollments)
        const recentActivity = await db.query.pelatihanEnrollments.findMany({
          where: and(
            eq(pelatihanEnrollments.pelatihanId, pelatihanId),
            isNull(pelatihanEnrollments.deletedAt),
          ),
          with: {
            user: { columns: { id: true, name: true, email: true } },
          },
          orderBy: [desc(pelatihanEnrollments.enrolledAt)],
          limit: 5,
        });

        return {
          totalPeserta: Number(totalPeserta?.count ?? 0),
          totalPesertaBaru: Number(totalPesertaBaru?.count ?? 0),
          avgProgress: Math.round(Number(avgProgress?.avg ?? 0)),
          avgPretest: Number(Number(avgPretest?.avg ?? 0).toFixed(1)),
          avgPosttest: Number(Number(avgPosttest?.avg ?? 0).toFixed(1)),
          recentActivity: recentActivity.map((e) => ({
            id: e.id,
            name: e.participantName || e.user?.name || "Pengguna",
            email: e.participantEmail || e.user?.email || "-",
            progress: e.progressPercentage,
            status: e.status,
            enrolledAt: e.enrolledAt,
          })),
        };
      },
      catch: (error) => {
        logError(
          "pelatihanQueries.getPelatihanStats",
          "Failed to fetch pelatihan overview stats",
          { error, pelatihanId },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data statistik pelatihan",
        });
      },
    });
  },
  // ##################
  // end authored
  // ##################
};

export default pelatihanQueries;
