// ##################
// authored (generated by claude, Jun 14 2026 20:45 WITA)
// ##################

import getMediaPublicationsColumns from "@/components/columns/media-publications-columns";
import { DataTable } from "@/components/data-table/data-table";
import { DataTableFilterMenu } from "@/components/data-table/data-table-filter-menu";
import { DataTableSortList } from "@/components/data-table/data-table-sort-list";
import { DataTableToolbar } from "@/components/data-table/data-table-toolbar";
import { PermissionGate } from "@/components/permission-gate";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { pageHead } from "@/utils/page-head";
import { requirePermission } from "@/utils/require-permission";
import { trpc } from "@/utils/trpc";
import { useQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import mediaPublicationsSchema from "@tepian-k3/schema/platform/media-publications.schema";
import { PlusCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { useDataTableRouter } from "@/hooks/use-data-table-router";

export const Route = createFileRoute("/(core)/back-office/media-publications/")(
  {
    validateSearch: mediaPublicationsSchema.getAllMediaSchema,
    beforeLoad: async ({ context }) =>
      await requirePermission(context, {
        permission: "media-publications.view",
      }),
    component: RouteComponent,
    head: () => pageHead("Manajemen Media & Publikasi"),
  },
);

/**
 * Komponen halaman utama manajemen Media & Publikasi di Back Office.
 * Menampilkan tabel data dengan filter pencarian, kategori, status terbit,
 * tombol tambah, dan checkbox untuk melihat item yang dihapus.
 *
 * @returns {JSX.Element} Elemen halaman Back Office Media & Publikasi.
 */
function RouteComponent() {
  const params = Route.useSearch();
  const navigate = Route.useNavigate();

  const {
    data: media,
    isLoading,
    error,
  } = useQuery(
    trpc.platform.mediaPublications.getPaginatedMedia.queryOptions(params),
  );

  const [showDeleted, setShowDeleted] = useState(params.showDeleted);

  const columns = useMemo(
    () =>
      getMediaPublicationsColumns({
        currentPage: params.page,
        perPage: params.perPage,
      }),
    [params.page, params.perPage],
  );

  const { table } = useDataTableRouter({
    data: media?.data ?? [],
    columns,
    pageCount: media?.pageCount ?? 0,
    search: params,
    navigate: ({ search: updater }) => {
      navigate({ search: updater });
    },
    initialState: {
      sorting: [{ id: "createdAt", desc: false }],
    },
    getRowId: (row) => row.id,
  });

  return (
    <div className="flex flex-col">
      <div className="mb-4 flex items-center justify-between gap-4">
        <div className="flex flex-row items-center gap-2">
          <Checkbox
            id="show-deleted-media"
            checked={showDeleted}
            onCheckedChange={(checked) => {
              navigate({
                to: "/back-office/media-publications",
                search: {
                  ...params,
                  showDeleted: Boolean(checked),
                },
              });
              setShowDeleted(Boolean(checked));
            }}
          />
          <Label htmlFor="show-deleted-media">Deleted Items</Label>
        </div>
        <PermissionGate permission="media-publications.create">
          <Button
            onClick={() =>
              navigate({ to: "/back-office/media-publications/create" })
            }
          >
            <PlusCircle className="mr-2 size-4" />
            Tambah Media & Publikasi
          </Button>
        </PermissionGate>
      </div>
      <DataTable
        table={table}
        isLoading={isLoading}
        error={error}
        emptyMessage="Tidak ada media & publikasi ditemukan."
      >
        <DataTableToolbar table={table}>
          <DataTableFilterMenu table={table} />
          <DataTableSortList table={table} />
        </DataTableToolbar>
      </DataTable>
    </div>
  );
}

// ##################
// end authored
// ##################
