import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { getClusterColor, getClusterIcon } from "@/lib/cluster-colors";
import { globalErrorToast, globalSuccessToast } from "@/lib/toast";
import { cn } from "@/lib/utils";
import { queryClient, trpc } from "@/utils/trpc";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Globe2 } from "lucide-react";
import { createElement } from "react";

// ##################
// authored (generated by AI, Jul 28 2026 03:07 WITA)
// ##################

/**
 * Panel pengatur urutan klaster untuk Back-Office.
 * Menyediakan tombol panah ← dan → untuk menggeser posisi klaster secara visual.
 */
export function ClusterReorderPanel() {
  const { data: clusters, isLoading } = useQuery(
    trpc.pengujian.cluster.getAllClusters.queryOptions(),
  );

  const reorderMutation = useMutation(
    trpc.pengujian.cluster.reorderCluster.mutationOptions({
      onSuccess: async () => {
        await queryClient.invalidateQueries(
          trpc.pengujian.cluster.getAllClusters.queryOptions(),
        );
        await queryClient.invalidateQueries(
          trpc.pengujian.cluster.getPaginatedClusters.queryOptions({}),
        );
        globalSuccessToast("Urutan klaster berhasil diperbarui");
      },
      onError: (error) => {
        globalErrorToast(`Gagal menggeser klaster: ${error.message}`);
      },
    }),
  );

  const handleMove = (id: string, direction: "left" | "right") => {
    reorderMutation.mutate({ id, direction });
  };

  return (
    <Card className="mb-6 border-slate-200 shadow-xs">
      <CardHeader className="pb-3">
        <CardTitle className="text-base font-bold text-slate-800">
          Atur Urutan Tampilan Klaster
        </CardTitle>
        <CardDescription className="text-xs text-slate-500">
          Gunakan tombol panah &larr; dan &rarr; pada setiap kartu klaster di
          bawah untuk menggeser urutan kartu yang tampil di halaman utama
          pengujian.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="flex gap-4 overflow-x-auto pb-2">
            {Array.from({ length: 5 }).map((_, index) => (
              <Skeleton
                key={index}
                className="h-28 w-44 shrink-0 rounded-2xl"
              />
            ))}
          </div>
        ) : (
          <div className="flex flex-wrap gap-4">
            {(clusters ?? []).map((cluster, index) => {
              const isFirst = index === 0;
              const isLast = index === (clusters?.length ?? 0) - 1;

              return (
                <div
                  key={cluster.id}
                  className={cn(
                    "relative flex h-32 w-44 shrink-0 flex-col items-center justify-between rounded-2xl p-3 text-white shadow-md transition-all",
                    getClusterColor(cluster.name),
                  )}
                >
                  <div className="flex items-center gap-2 pt-1">
                    {createElement(getClusterIcon(cluster.name) || Globe2, {
                      className: "size-5",
                    })}
                    <span className="line-clamp-1 text-xs font-bold tracking-wider uppercase">
                      {cluster.name}
                    </span>
                  </div>

                  <span className="rounded-full bg-black/20 px-2 py-0.5 text-[10px] font-medium">
                    Urutan #{index + 1}
                  </span>

                  <div className="flex w-full items-center justify-between gap-1 border-t border-white/20 pt-1">
                    <Button
                      type="button"
                      size="icon"
                      variant="ghost"
                      disabled={isFirst || reorderMutation.isPending}
                      onClick={() => handleMove(cluster.id, "left")}
                      className="size-7 text-white hover:bg-white/20 hover:text-white disabled:opacity-30"
                      title="Geser Kiri"
                    >
                      <ChevronLeft className="size-4" />
                    </Button>
                    <span className="text-[10px] font-semibold opacity-75">
                      Geser
                    </span>
                    <Button
                      type="button"
                      size="icon"
                      variant="ghost"
                      disabled={isLast || reorderMutation.isPending}
                      onClick={() => handleMove(cluster.id, "right")}
                      className="size-7 text-white hover:bg-white/20 hover:text-white disabled:opacity-30"
                      title="Geser Kanan"
                    >
                      <ChevronRight className="size-4" />
                    </Button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ##################
// end authored
// ##################
