// ##################
// authored (generated by codex, Jun 01 2026 10:04 WITA)
// ##################

import { NavMain } from "@/components/nav-main";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenuButton,
} from "@/components/ui/sidebar";
import { backOfficeMenu } from "@/lib/back-office-menu";
import { employeeMenu } from "@/lib/employee-menu";
import { userMenu } from "@/lib/user-menu";
import { trpc } from "@/utils/trpc";
import { useSuspenseQuery } from "@tanstack/react-query";
import { Link, useRouterState, useNavigate } from "@tanstack/react-router";
import { BACK_OFFICE_ROLES, EMPLOYEE_ROLES } from "@tepian-k3/constants";
import * as React from "react";
import ImageWithFallback from "./image-with-fallback";
import {
  IconSettings,
  IconLogout,
  IconFlask,
  IconBook,
} from "@tabler/icons-react";
import { logout } from "@/lib/logout";
import { useDashboardStore } from "@/stores/dashboard.stores";
import { cn } from "@/lib/utils";

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {
  const { data: profile } = useSuspenseQuery(
    trpc.platform.auth.profile.queryOptions(),
  );

  const navigate = useNavigate();
  const { activeMode, setActiveMode } = useDashboardStore();
  const pathname = useRouterState({ select: (s) => s.location.pathname });
  const isOnBackOffice = pathname.startsWith("/back-office");

  // Auto-detect dashboard active mode based on route segment
  React.useEffect(() => {
    if (isOnBackOffice) {
      if (
        pathname.includes("/back-office/pelatihan") ||
        pathname.includes("/back-office/order-pelatihan") ||
        pathname.includes("/back-office/absensi") ||
        pathname.includes("/back-office/sertifikat-pelatihan") ||
        pathname.includes("/back-office/landing-settings") ||
        pathname.includes("/back-office/ppid") ||
        pathname.includes("/back-office/media-publications")
      ) {
        setActiveMode("pelatihan");
      } else if (
        pathname.includes("/back-office/orders") ||
        pathname.includes("/back-office/worksheets") ||
        pathname.includes("/back-office/testings") ||
        pathname.includes("/back-office/users") ||
        pathname.includes("/back-office/positions") ||
        pathname.includes("/back-office/employees") ||
        pathname.includes("/back-office/roles") ||
        pathname.includes("/back-office/clusters") ||
        pathname.includes("/back-office/parameter-categories") ||
        pathname.includes("/back-office/parameters") ||
        pathname.includes("/back-office/tool-codes") ||
        pathname.includes("/back-office/tools") ||
        pathname.includes("/back-office/chemical-materials") ||
        pathname.includes("/back-office/kblis") ||
        pathname.includes("/back-office/survey-questions") ||
        pathname.includes("/back-office/banners") ||
        pathname.includes("/back-office/news") ||
        pathname.includes("/back-office/audits")
      ) {
        setActiveMode("pengujian");
      }
    } else {
      if (
        pathname.includes("/dashboard/pelatihan") ||
        pathname.includes("/pelatihan/transaksi")
      ) {
        setActiveMode("pelatihan");
      } else if (
        pathname.includes("/dashboard/company") ||
        pathname.includes("/pengujian")
      ) {
        setActiveMode("pengujian");
      }
    }
  }, [pathname, isOnBackOffice, setActiveMode]);

  const roleNames = profile.roles.map((role) => role.name);
  const hasUserRole = roleNames.includes("user");
  const hasEmployeeRole =
    roleNames.some((name) =>
      (EMPLOYEE_ROLES as readonly string[]).includes(name),
    ) || roleNames.some((name) => name !== "user");
  const hasBackOfficeRole =
    isOnBackOffice ||
    roleNames.some((name) =>
      (BACK_OFFICE_ROLES as readonly string[]).includes(name),
    ) ||
    roleNames.some((name) => name !== "user");

  // A user may have multiple roles — collect items from all applicable menus
  // and deduplicate by URL so overlapping items don't appear twice.
  // When on /back-office/* routes, back-office menu takes priority over employee menu.
  const filteredNavMain = React.useMemo(() => {
    const seen = new Set<string>();
    const items: any[] = [];

    const push = (candidate: any) => {
      const key = candidate.url || candidate.title;
      if (!seen.has(key)) {
        seen.add(key);
        items.push(candidate);
      }
    };

    const filterSubItems = (item: any) => {
      if (item.items) {
        const filteredChildren = item.items.filter(
          (sub: any) =>
            !sub.permission || profile.permissions.includes(sub.permission),
        );
        return { ...item, items: filteredChildren };
      }
      return item;
    };

    if (hasUserRole && !isOnBackOffice) {
      if (activeMode === "pelatihan") {
        userMenu.pelatihan.forEach(push);
      } else {
        userMenu.pengujian.forEach(push);
      }
    }

    if (hasEmployeeRole && !isOnBackOffice) {
      employeeMenu.navMain
        .filter(
          (item) =>
            !item.permission || profile.permissions.includes(item.permission),
        )
        .forEach(push);
    }

    if (hasBackOfficeRole && isOnBackOffice) {
      const sourceMenu =
        activeMode === "pelatihan"
          ? backOfficeMenu.pelatihan
          : backOfficeMenu.pengujian;

      sourceMenu.forEach((parent) => {
        const filteredParent = filterSubItems(parent);

        // Jika memiliki anak menu dan semuanya tidak bisa diakses, jangan render induknya
        if (filteredParent.items && filteredParent.items.length === 0) {
          return;
        }

        // Jika menu induk butuh permission
        if (
          filteredParent.permission &&
          !profile.permissions.includes(filteredParent.permission)
        ) {
          return;
        }

        push(filteredParent);
      });
    }

    return items;
  }, [
    hasUserRole,
    activeMode,
    hasEmployeeRole,
    hasBackOfficeRole,
    isOnBackOffice,
    profile.permissions,
  ]);

  return (
    <Sidebar
      collapsible="offcanvas"
      {...props}
      className="border-r border-transparent bg-[#1e53a4] text-white select-none"
    >
      {/* Decorative Wave Background Graphic */}
      <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden bg-[#1e53a4]">
        <svg
          className="absolute bottom-0 left-[-100px] h-[400px] w-[500px] opacity-15"
          viewBox="0 0 400 400"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M-80 250 C 50 180, 150 350, 300 220 C 450 90, 500 280, 600 200 L 600 500 L -80 500 Z"
            fill="url(#paint0_linear)"
          />
          <path
            d="M-80 300 C 100 220, 120 380, 280 280 C 440 180, 480 320, 600 260 L 600 500 L -80 500 Z"
            fill="url(#paint1_linear)"
          />
          <defs>
            <linearGradient
              id="paint0_linear"
              x1="260"
              y1="120"
              x2="260"
              y2="400"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="white" stopOpacity="0.6" />
              <stop offset="1" stopColor="white" stopOpacity="0" />
            </linearGradient>
            <linearGradient
              id="paint1_linear"
              x1="260"
              y1="180"
              x2="260"
              y2="400"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="white" stopOpacity="0.4" />
              <stop offset="1" stopColor="white" stopOpacity="0" />
            </linearGradient>
          </defs>
        </svg>
      </div>

      {/* 1. White Header Section with Brand Logo Colored Asset */}
      <SidebarHeader className="z-10 flex shrink-0 flex-col items-center justify-center border-b border-neutral-100 bg-white px-4 py-4">
        <Link to="/" className="flex w-full items-center justify-center py-1">
          <ImageWithFallback
            src="/assets/logo-tepiank3.webp"
            alt="Tepian K3 Logo"
            className="h-12 w-auto max-w-[200px] object-contain"
          />
        </Link>

        {hasUserRole && !isOnBackOffice && (
          <div className="mt-3 flex w-full rounded-xl border border-slate-200/50 bg-slate-100 p-1">
            <button
              type="button"
              onClick={() => {
                setActiveMode("pengujian");
                navigate({ to: "/dashboard" });
              }}
              className={cn(
                "flex flex-grow cursor-pointer items-center justify-center gap-1.5 rounded-lg py-1.5 text-[10px] font-extrabold tracking-wide transition-all duration-300",
                activeMode === "pengujian"
                  ? "bg-white text-[#1061D6] shadow-sm"
                  : "text-slate-500 hover:text-slate-800",
              )}
            >
              <IconFlask className="size-3.5" />
              PENGUJIAN K3
            </button>
            <button
              type="button"
              onClick={() => {
                setActiveMode("pelatihan");
                navigate({
                  to: "/dashboard/pelatihan",
                  search: { tab: "profil" },
                });
              }}
              className={cn(
                "flex flex-grow cursor-pointer items-center justify-center gap-1.5 rounded-lg py-1.5 text-[10px] font-extrabold tracking-wide transition-all duration-300",
                activeMode === "pelatihan"
                  ? "bg-white text-[#1061D6] shadow-sm"
                  : "text-slate-500 hover:text-slate-800",
              )}
            >
              <IconBook className="size-3.5" />
              PELATIHAN K3
            </button>
          </div>
        )}

        {isOnBackOffice && (
          <div className="mt-3 flex w-full rounded-xl border border-slate-200/50 bg-slate-100 p-1">
            <button
              type="button"
              onClick={() => {
                setActiveMode("pengujian");
                navigate({ to: "/back-office" });
              }}
              className={cn(
                "flex flex-grow cursor-pointer items-center justify-center gap-1.5 rounded-lg py-1.5 text-[10px] font-extrabold tracking-wide transition-all duration-300",
                activeMode === "pengujian"
                  ? "bg-white text-[#1061D6] shadow-sm"
                  : "text-slate-500 hover:text-slate-800",
              )}
            >
              <IconFlask className="size-3.5" />
              PENGUJIAN
            </button>
            <button
              type="button"
              onClick={() => {
                setActiveMode("pelatihan");
                navigate({ to: "/back-office" });
              }}
              className={cn(
                "flex flex-grow cursor-pointer items-center justify-center gap-1.5 rounded-lg py-1.5 text-[10px] font-extrabold tracking-wide transition-all duration-300",
                activeMode === "pelatihan"
                  ? "bg-white text-[#1061D6] shadow-sm"
                  : "text-slate-500 hover:text-slate-800",
              )}
            >
              <IconBook className="size-3.5" />
              PELATIHAN
            </button>
          </div>
        )}
      </SidebarHeader>

      {/* 2. Deep Blue Navigation Area */}
      <SidebarContent className="z-10 bg-transparent py-2">
        <NavMain items={filteredNavMain} />
      </SidebarContent>

      {/* 3. Integrated Footer Section with Settings and Logout */}
      <SidebarFooter className="z-10 shrink-0 border-t border-white/5 bg-transparent p-0">
        <div className="flex w-full flex-col gap-0.5 py-4">
          {/* Settings Button */}
          <SidebarMenuButton
            onClick={() => navigate({ to: "/settings" })}
            className="h-12 w-full gap-3.5 rounded-none bg-transparent pr-6 pl-6 text-[#dce7ff] transition-all hover:bg-white/10 hover:text-white [&>svg]:stroke-[#dce7ff] [&>svg]:text-[#dce7ff]"
          >
            <IconSettings className="size-5 shrink-0" />
            <span className="text-sm font-medium">Pengaturan</span>
          </SidebarMenuButton>

          {/* Logout Button (Highlight Red) */}
          <SidebarMenuButton
            onClick={() => logout()}
            className="h-12 w-full gap-3.5 rounded-none bg-transparent pr-6 pl-6 text-[#ef4444] transition-all hover:bg-red-500/10 hover:text-red-500 [&>svg]:stroke-[#ef4444] [&>svg]:text-[#ef4444]"
          >
            <IconLogout className="size-5 shrink-0" />
            <span className="text-sm font-bold">Keluar</span>
          </SidebarMenuButton>
        </div>
      </SidebarFooter>
    </Sidebar>
  );
}

// ##################
// end authored
// ##################
