// ##################
// authored (generated by gemini, Aug 30 2026 14:58 WITA)
// ##################

import { createFileRoute } from "@tanstack/react-router";
import { pageHead } from "@/utils/page-head";
import { requirePermission } from "@/utils/require-permission";
import { useRedirectBackWithTimeout } from "@/lib/redirect-back-with-timeout";
import { Controller, useFieldArray, useForm } from "react-hook-form";
import type { z } from "zod";
import teamMemberSchema from "@tepian-k3/schema/platform/team-member.schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { trpc } from "@/utils/trpc";
import { globalErrorToast, globalSuccessToast } from "@/lib/toast";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NumberInput } from "@/components/ui/number-input";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { toFormData } from "@/utils/form-data-mapper";
import SingleImageUpload from "@/components/ui/single-image-upload";
import { Checkbox } from "@/components/ui/checkbox";
import { useMutation } from "@tanstack/react-query";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { IconPlus, IconTrash } from "@tabler/icons-react";

export const Route = createFileRoute("/(core)/back-office/team-members/create")(
  {
    beforeLoad: async ({ context }) =>
      await requirePermission(context, { permission: "banners.create" }),
    component: RouteComponent,
    head: () => pageHead("Tambah Anggota Tim"),
  },
);

const POPULAR_PLATFORMS = [
  { value: "linkedin", label: "LinkedIn" },
  { value: "email", label: "Email" },
  { value: "instagram", label: "Instagram" },
  { value: "twitter", label: "Twitter / X" },
  { value: "github", label: "GitHub" },
  { value: "website", label: "Website / Portofolio" },
];

function RouteComponent() {
  const redirectBack = useRedirectBackWithTimeout();

  const form = useForm<z.infer<typeof teamMemberSchema.createTeamMemberSchema>>(
    {
      resolver: zodResolver(teamMemberSchema.createTeamMemberSchema),
      defaultValues: {
        name: "",
        role: "",
        bio: "",
        socialLinks: [
          { platform: "linkedin", url: "", label: "LinkedIn" },
          { platform: "email", url: "", label: "Email" },
        ],
        order: 0,
        isActive: true,
      },
    },
  );

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "socialLinks",
  });

  const createMutation = useMutation({
    ...trpc.platform.teamMember.createTeamMember.mutationOptions(),
    onSuccess: async () => {
      globalSuccessToast("Anggota tim berhasil ditambahkan");
      await redirectBack();
    },
    onError: (error) => {
      globalErrorToast(`Gagal menambahkan anggota tim: ${error.message}`);
    },
  });

  const handleSubmit = (
    data: z.infer<typeof teamMemberSchema.createTeamMemberSchema>,
  ) => {
    // Filter out empty URLs in socialLinks
    const validSocialLinks = (data.socialLinks || []).filter(
      (link) => link.url && link.url.trim() !== "",
    );

    const payload = {
      ...data,
      socialLinks: validSocialLinks,
    };

    const formData = toFormData(payload);
    createMutation.mutate(formData);
  };

  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-6 px-2 py-4">
      <Card className="rounded-2xl border-slate-100 shadow-xs">
        <CardHeader>
          <CardTitle className="text-xl font-bold text-slate-800">
            Tambah Anggota Tim Baru
          </CardTitle>
          <CardDescription>
            Isi formulir di bawah untuk menambahkan profil anggota tim ke
            halaman Tim Kami.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form
            onSubmit={form.handleSubmit(handleSubmit)}
            className="flex flex-col gap-6"
          >
            {/* Foto Profil */}
            <FieldGroup>
              <FieldLabel className="font-bold text-slate-700">
                Foto Profil Anggota
              </FieldLabel>
              <Controller
                control={form.control}
                name="photo"
                render={({ field, fieldState }) => (
                  <div className="max-w-xs">
                    <SingleImageUpload
                      value={field.value}
                      onChange={field.onChange}
                      onBlur={field.onBlur}
                      name={field.name}
                      error={fieldState.error?.message}
                      aspectRatio={4 / 5}
                      targetWidth={600}
                      targetHeight={750}
                      maxSize={5 * 1024 * 1024}
                    />
                  </div>
                )}
              />
              <p className="text-xs text-slate-400">
                Format: JPG, PNG, atau WebP. Maksimal 5MB. Rekomendasi rasio
                foto potret 4:5.
              </p>
            </FieldGroup>

            {/* Nama & Role */}
            <div className="grid gap-4 sm:grid-cols-2">
              <FieldGroup>
                <Controller
                  control={form.control}
                  name="name"
                  render={({ field, fieldState }) => (
                    <Field>
                      <FieldLabel className="font-bold text-slate-700">
                        Nama Lengkap <span className="text-red-500">*</span>
                      </FieldLabel>
                      <Input
                        {...field}
                        placeholder="Contoh: Budi Santoso, S.Kom"
                        className="font-medium"
                      />
                      {fieldState.invalid && (
                        <FieldError errors={[fieldState.error]} />
                      )}
                    </Field>
                  )}
                />
              </FieldGroup>

              <FieldGroup>
                <Controller
                  control={form.control}
                  name="role"
                  render={({ field, fieldState }) => (
                    <Field>
                      <FieldLabel className="font-bold text-slate-700">
                        Jabatan / Posisi <span className="text-red-500">*</span>
                      </FieldLabel>
                      <Input
                        {...field}
                        placeholder="Contoh: Lead Frontend Engineer"
                        className="font-medium"
                      />
                      {fieldState.invalid && (
                        <FieldError errors={[fieldState.error]} />
                      )}
                    </Field>
                  )}
                />
              </FieldGroup>
            </div>

            {/* Bio Singkat */}
            <FieldGroup>
              <Controller
                control={form.control}
                name="bio"
                render={({ field, fieldState }) => (
                  <Field>
                    <FieldLabel className="font-bold text-slate-700">
                      Bio / Deskripsi Singkat (Opsional)
                    </FieldLabel>
                    <Textarea
                      {...field}
                      value={field.value ?? ""}
                      rows={3}
                      placeholder="Tuliskan deskripsi singkat mengenai keahlian atau peran..."
                    />
                    {fieldState.invalid && (
                      <FieldError errors={[fieldState.error]} />
                    )}
                  </Field>
                )}
              />
            </FieldGroup>

            {/* Sosial Media Dinamis */}
            <div className="space-y-3 rounded-xl border border-slate-200 bg-slate-50/50 p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-sm font-bold text-slate-800">
                    Tautan Sosial Media & Kontak
                  </h4>
                  <p className="text-xs text-slate-500">
                    Tambahkan akun sosial media atau alamat kontak anggota tim.
                  </p>
                </div>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() =>
                    append({
                      platform: "instagram",
                      url: "",
                      label: "Instagram",
                    })
                  }
                  className="gap-1.5 font-bold"
                >
                  <IconPlus className="h-4 w-4" />
                  Tambah Platform
                </Button>
              </div>

              <div className="space-y-3 pt-2">
                {fields.map((item, index) => (
                  <div
                    key={item.id}
                    className="flex flex-col gap-2 rounded-lg border border-slate-200 bg-white p-3 sm:flex-row sm:items-center"
                  >
                    {/* Platform Selector */}
                    <div className="w-full sm:w-44">
                      <Controller
                        control={form.control}
                        name={`socialLinks.${index}.platform`}
                        render={({ field }) => (
                          <Select
                            value={field.value}
                            onValueChange={(val) => {
                              field.onChange(val);
                              const matched = POPULAR_PLATFORMS.find(
                                (p) => p.value === val,
                              );
                              if (matched) {
                                form.setValue(
                                  `socialLinks.${index}.label`,
                                  matched.label,
                                );
                              }
                            }}
                          >
                            <SelectTrigger className="h-9 text-xs font-semibold">
                              <SelectValue placeholder="Pilih Platform" />
                            </SelectTrigger>
                            <SelectContent>
                              {POPULAR_PLATFORMS.map((p) => (
                                <SelectItem key={p.value} value={p.value}>
                                  {p.label}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        )}
                      />
                    </div>

                    {/* Label Input */}
                    <div className="w-full sm:w-36">
                      <Controller
                        control={form.control}
                        name={`socialLinks.${index}.label`}
                        render={({ field }) => (
                          <Input
                            {...field}
                            placeholder="Label (e.g. LinkedIn)"
                            className="h-9 text-xs"
                          />
                        )}
                      />
                    </div>

                    {/* URL Input */}
                    <div className="flex-1">
                      <Controller
                        control={form.control}
                        name={`socialLinks.${index}.url`}
                        render={({ field }) => (
                          <Input
                            {...field}
                            placeholder="URL profil atau mailto:..."
                            className="h-9 font-mono text-xs"
                          />
                        )}
                      />
                    </div>

                    {/* Delete Link Button */}
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon-sm"
                      onClick={() => remove(index)}
                      className="h-9 w-9 text-red-500 hover:bg-red-50 hover:text-red-700"
                    >
                      <IconTrash className="h-4 w-4" />
                    </Button>
                  </div>
                ))}
              </div>
            </div>

            {/* Order & Status */}
            <div className="grid gap-4 sm:grid-cols-2">
              <FieldGroup>
                <Controller
                  control={form.control}
                  name="order"
                  render={({ field, fieldState }) => (
                    <Field>
                      <FieldLabel className="font-bold text-slate-700">
                        Nomor Urutan Tampil
                      </FieldLabel>
                      <NumberInput
                        value={field.value}
                        onChange={field.onChange}
                        onBlur={field.onBlur}
                        name={field.name}
                        className="font-medium"
                      />
                      <p className="text-xs text-slate-400">
                        Angka lebih kecil akan tampil lebih awal di halaman
                        publik.
                      </p>
                      {fieldState.invalid && (
                        <FieldError errors={[fieldState.error]} />
                      )}
                    </Field>
                  )}
                />
              </FieldGroup>

              <div className="flex items-center pt-6">
                <Controller
                  control={form.control}
                  name="isActive"
                  render={({ field }) => (
                    <div className="flex items-center gap-3">
                      <Checkbox
                        id="is-active"
                        checked={field.value}
                        onCheckedChange={field.onChange}
                      />
                      <label
                        htmlFor="is-active"
                        className="cursor-pointer text-sm font-bold text-slate-700"
                      >
                        Status Aktif (Tampilkan di Halaman Publik)
                      </label>
                    </div>
                  )}
                />
              </div>
            </div>

            {/* Form Actions */}
            <div className="flex justify-end gap-3 border-t border-slate-100 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={async () => await redirectBack()}
              >
                Batal
              </Button>
              <Button
                type="submit"
                className="bg-blue-600 font-bold hover:bg-blue-700"
                disabled={createMutation.isPending}
              >
                {createMutation.isPending && (
                  <Spinner className="mr-2 h-4 w-4" />
                )}
                Simpan Anggota Tim
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// ##################
// end authored
// ##################
