import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { trpc } from "@/utils/trpc";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { ChevronRight, CheckCircle } from "lucide-react";
import { toast } from "sonner";
import { pageHead } from "@/utils/page-head";

// ##################
// authored (generated by antigravity, Jun 24 2026 21:18 WITA)
// ##################

export const Route = createFileRoute(
  "/(core)/pelatihan/belajar/$enrollmentId/materi/$materiId",
)({
  head: () => pageHead("Pelatihan - Materi"),
  component: MateriComponent,
});

function MateriComponent() {
  const { enrollmentId, materiId } = Route.useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const { data: enrollment } = useQuery(
    trpc.pelatihan.enrollment.getUserEnrollmentById.queryOptions({
      id: enrollmentId,
    }),
  );

  const materials = enrollment?.pelatihan?.materials ?? [];
  const progresses = enrollment?.progresses ?? [];
  const currentMaterial = materials.find((m) => m.id === materiId);
  const currentIndex = materials.findIndex((m) => m.id === materiId);

  const isCompleted = progresses.some(
    (p) => p.materialId === materiId && p.completed,
  );

  const markCompletedMutation = useMutation({
    ...trpc.pelatihan.enrollment.markMaterialCompleted.mutationOptions(),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: trpc.pelatihan.enrollment.getUserEnrollmentById.queryKey({
          id: enrollmentId,
        }),
      });

      const nextMaterial = materials[currentIndex + 1];
      if (nextMaterial) {
        toast.success("Materi selesai, lanjut ke materi berikutnya");
        navigate({
          to: "/pelatihan/belajar/$enrollmentId/materi/$materiId",
          params: { enrollmentId, materiId: nextMaterial.id },
        });
      } else {
        toast.success("Semua materi telah diselesaikan!");
        // Usually redirect to post-test here, or dashboard
      }
    },
    onError: () => {
      toast.error("Gagal menandai materi selesai");
    },
  });

  const handleComplete = () => {
    if (isCompleted) {
      const nextMaterial = materials[currentIndex + 1];
      if (nextMaterial) {
        navigate({
          to: "/pelatihan/belajar/$enrollmentId/materi/$materiId",
          params: { enrollmentId, materiId: nextMaterial.id },
        });
      }
      return;
    }

    markCompletedMutation.mutate({
      enrollmentId,
      materialId: materiId,
    });
  };

  if (!currentMaterial) {
    return (
      <div className="p-8 text-center text-muted-foreground">
        Materi tidak ditemukan
      </div>
    );
  }

  // Determine if it's a youtube embed
  const isYoutube =
    currentMaterial.type === "video" &&
    currentMaterial.fileUrl?.includes("youtube.com/watch");
  let embedUrl = currentMaterial.fileUrl;

  if (isYoutube && embedUrl) {
    try {
      const url = new URL(embedUrl);
      const v = url.searchParams.get("v");
      if (v) {
        embedUrl = `https://www.youtube.com/embed/${v}`;
      }
    } catch (e) {
      // invalid URL
    }
  }

  return (
    <div className="relative flex h-full flex-col bg-background">
      <div className="flex-1 overflow-y-auto pb-20">
        <div className="mx-auto max-w-5xl space-y-6 p-4 md:p-8">
          <div className="space-y-2">
            <h1 className="text-2xl font-bold tracking-tight md:text-3xl">
              {currentMaterial.title}
            </h1>
            {currentMaterial.description && (
              <p className="text-muted-foreground">
                {currentMaterial.description}
              </p>
            )}
          </div>

          <div className="aspect-video w-full overflow-hidden rounded-xl border bg-black">
            {currentMaterial.type === "video" ? (
              isYoutube ? (
                <iframe
                  src={embedUrl ?? ""}
                  className="h-full w-full"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                />
              ) : (
                <video
                  src={currentMaterial.fileUrl ?? undefined}
                  controls
                  controlsList="nodownload"
                  className="h-full w-full object-contain"
                />
              )
            ) : currentMaterial.type === "pdf" ? (
              <iframe
                src={`${currentMaterial.fileUrl}#toolbar=0`}
                className="h-full w-full"
              />
            ) : (
              <div className="flex h-full w-full flex-col items-center justify-center space-y-4 bg-muted p-8 text-center">
                <p className="text-muted-foreground">
                  Materi ini berupa dokumen untuk diunduh
                </p>
                {currentMaterial.fileUrl && (
                  <Button asChild variant="outline">
                    <a
                      href={currentMaterial.fileUrl}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Unduh Dokumen
                    </a>
                  </Button>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="fixed bottom-0 z-10 flex w-full items-center justify-between border-t bg-card p-4 md:absolute">
        <div className="flex hidden items-center gap-2 text-sm text-muted-foreground sm:flex">
          {currentIndex > 0 && (
            <span>Materi sebelumnya: {materials[currentIndex - 1]?.title}</span>
          )}
        </div>
        <Button
          onClick={handleComplete}
          disabled={markCompletedMutation.isPending}
          className="ml-auto w-full sm:w-auto"
        >
          {markCompletedMutation.isPending ? (
            "Menyimpan..."
          ) : isCompleted ? (
            <>
              Lanjut <ChevronRight className="ml-2 h-4 w-4" />
            </>
          ) : (
            <>
              Tandai Selesai & Lanjut <CheckCircle className="ml-2 h-4 w-4" />
            </>
          )}
        </Button>
      </div>
    </div>
  );
}
