import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { trpc } from "@/utils/trpc";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { pageHead } from "@/utils/page-head";
import { useState } from "react";
import { QuizQuestion } from "../../-components/quiz-question";
import { QuizResult } from "../../-components/quiz-result";

// ##################
// authored (generated by antigravity, Jun 24 2026 21:30 WITA)
// ##################

export const Route = createFileRoute(
  "/(core)/pelatihan/belajar/$enrollmentId/ujian/$assessmentId",
)({
  head: () => pageHead("Pelatihan - Ujian"),
  component: UjianComponent,
});

function UjianComponent() {
  const { enrollmentId, assessmentId } = Route.useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [answers, setAnswers] = useState<Record<string, string>>({});

  // Get assessment details
  const { data: assessment, isLoading: isLoadingAssessment } = useQuery(
    trpc.pelatihan.assessment.getAssessmentById.queryOptions({
      id: assessmentId,
    }),
  );

  // Get all assessments for this enrollment to check attempts
  const { data: assessmentsList, isLoading: isLoadingList } = useQuery({
    ...trpc.pelatihan.assessment.getAssessmentsByPelatihanId.queryOptions({
      pelatihanId: assessment?.pelatihanId || "",
      enrollmentId: enrollmentId,
    }),
    enabled: !!assessment?.pelatihanId,
  });

  const currentAssessmentData = assessmentsList?.find(
    (a) => a.id === assessmentId,
  );
  const existingAttemptId = currentAssessmentData?.inProgressAttemptId;
  const hasAttempt = currentAssessmentData?.hasAttempted;
  const isFinished = hasAttempt && !existingAttemptId;

  const startAttemptMutation = useMutation({
    ...trpc.pelatihan.assessment.startAttempt.mutationOptions(),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey:
          trpc.pelatihan.assessment.getAssessmentsByPelatihanId.queryKey({
            pelatihanId: assessment?.pelatihanId || "",
            enrollmentId,
          }),
      });
      toast.success("Ujian dimulai. Selamat mengerjakan!");
    },
    onError: () => {
      toast.error("Gagal memulai ujian.");
    },
  });

  const submitAttemptMutation = useMutation({
    ...trpc.pelatihan.assessment.submitAttempt.mutationOptions(),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey:
          trpc.pelatihan.assessment.getAssessmentsByPelatihanId.queryKey({
            pelatihanId: assessment?.pelatihanId || "",
            enrollmentId,
          }),
      });
      toast.success("Jawaban berhasil dikirim!");
    },
    onError: () => {
      toast.error("Gagal mengirim jawaban ujian.");
    },
  });

  const handleStart = () => {
    startAttemptMutation.mutate({
      enrollmentId,
      assessmentId,
    });
  };

  const handleSubmit = () => {
    if (!existingAttemptId) return;

    // Check if all questions answered
    const unanswered = assessment?.questions?.filter((q) => !answers[q.id]);
    if (unanswered && unanswered.length > 0) {
      toast.error(`Ada ${unanswered.length} soal yang belum dijawab.`);
      return;
    }

    submitAttemptMutation.mutate({
      attemptId: existingAttemptId,
      answers,
    });
  };

  const handleContinue = () => {
    // Navigate back to LMS index, it will auto-redirect to next material
    navigate({
      to: "/pelatihan/belajar/$enrollmentId",
      params: { enrollmentId },
    });
  };

  const isLoading = isLoadingAssessment || isLoadingList;

  if (isLoading) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!assessment) {
    return (
      <div className="p-8 text-center text-muted-foreground">
        Ujian tidak ditemukan
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-8 md:px-8">
      <div className="mb-8 border-b pb-6">
        <h1 className="text-3xl font-bold tracking-tight">
          {assessment.title}
        </h1>
        {assessment.description && (
          <p className="mt-2 text-muted-foreground">{assessment.description}</p>
        )}
        <div className="mt-4 flex gap-4 text-sm text-muted-foreground">
          <div className="rounded-full bg-secondary px-3 py-1">
            Tipe: {assessment.type === "pre_test" ? "Pre-Test" : "Post-Test"}
          </div>
          <div className="rounded-full bg-secondary px-3 py-1">
            Passing Grade: {assessment.passingScore}
          </div>
          {assessment.timeLimit && (
            <div className="rounded-full bg-secondary px-3 py-1">
              Durasi: {assessment.timeLimit} menit
            </div>
          )}
        </div>
      </div>

      {!hasAttempt ? (
        <div className="rounded-xl border bg-card py-12 text-center shadow-sm">
          <h2 className="mb-2 text-xl font-semibold">Siap untuk memulai?</h2>
          <p className="mx-auto mb-6 max-w-md text-muted-foreground">
            Pastikan koneksi internet stabil. Waktu akan berjalan setelah Anda
            menekan tombol mulai.
          </p>
          <Button
            size="lg"
            onClick={handleStart}
            disabled={startAttemptMutation.isPending}
          >
            {startAttemptMutation.isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : null}
            Mulai Ujian Sekarang
          </Button>
        </div>
      ) : isFinished ? (
        <QuizResult
          score={currentAssessmentData?.bestScore}
          passingScore={assessment.passingScore}
          status={
            currentAssessmentData?.latestAttemptStatus === "submitted"
              ? "pending_review"
              : currentAssessmentData?.isPassed
                ? "passed"
                : "failed"
          }
          onContinue={() =>
            navigate({ to: `/pelatihan/belajar/${enrollmentId}` })
          }
          onRetry={
            (currentAssessmentData?.attemptCount ?? 0) <
            (assessment.maxAttempts || 999)
              ? handleStart
              : undefined
          }
        />
      ) : (
        <div className="space-y-8">
          {assessment.questions?.map((question, idx) => (
            <QuizQuestion
              key={question.id}
              question={question as any}
              index={idx}
              value={answers[question.id]}
              onChange={(val) =>
                setAnswers((prev) => ({ ...prev, [question.id]: val }))
              }
              disabled={submitAttemptMutation.isPending}
            />
          ))}

          <div className="flex justify-end pt-6">
            <Button
              size="lg"
              onClick={handleSubmit}
              disabled={submitAttemptMutation.isPending}
            >
              {submitAttemptMutation.isPending ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : null}
              Kirim Jawaban
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
