import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { globalErrorToast, globalSuccessToast } from "@/lib/toast";
import { trpc } from "@/utils/trpc";
import { useMutation, useQuery } from "@tanstack/react-query";
import {
  Clock,
  FileSpreadsheet,
  FileArchive,
  Building2,
  Loader2,
  Calendar,
} from "lucide-react";

// ##################
// authored (generated by AI, Jul 28 2026 03:45 WITA)
// ##################

interface QuickAuditModalProps {
  orderId: string | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/**
 * Modal Quick Audit Trail untuk menampilkan ringkasan pelanggan, lokasi,
 * dan hitungan durasi waktu pengujian secara langsung tanpa berpindah halaman.
 */
export function QuickAuditModal({
  orderId,
  open,
  onOpenChange,
}: QuickAuditModalProps) {
  const { data: auditData, isLoading } = useQuery({
    ...trpc.pengujian.auditTrail.getAuditTrail.queryOptions(
      { orderId: orderId ?? "" },
      { enabled: Boolean(orderId) && open },
    ),
  });

  const downloadExcelMutation = useMutation(
    trpc.pengujian.auditTrail.downloadExcel.mutationOptions({
      onSuccess: (res) => {
        const link = document.createElement("a");
        link.href = `data:${res.mimeType};base64,${res.base64}`;
        link.download = res.filename;
        link.click();
        globalSuccessToast("Rekap Excel berhasil diunduh");
      },
      onError: (err) => {
        globalErrorToast(`Gagal mendownload Excel: ${err.message}`);
      },
    }),
  );

  const downloadZipMutation = useMutation(
    trpc.pengujian.auditTrail.downloadZip.mutationOptions({
      onSuccess: (res) => {
        const link = document.createElement("a");
        link.href = `data:${res.mimeType};base64,${res.base64}`;
        link.download = res.filename;
        link.click();
        globalSuccessToast("Bundle Dokumen ZIP berhasil diunduh");
      },
      onError: (err) => {
        globalErrorToast(`Gagal mendownload ZIP: ${err.message}`);
      },
    }),
  );

  if (!orderId) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] max-w-4xl overflow-y-auto p-6">
        <DialogHeader className="border-b border-slate-100 pb-4">
          <div className="flex items-center justify-between gap-4 pr-6">
            <div>
              <DialogTitle className="flex items-center gap-2 text-xl font-bold text-slate-900">
                <Clock className="size-5 text-blue-600" />
                Audit Trail &amp; Rekap Waktu —{" "}
                {auditData?.orderInfo.orderNumber ?? "..."}
              </DialogTitle>
              <DialogDescription className="mt-1 text-xs text-slate-500">
                Rekapitulasi lengkap waktu proses, durasi antar-stage, dan
                rincian lokasi pengujian.
              </DialogDescription>
            </div>

            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="outline"
                className="border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100"
                disabled={downloadExcelMutation.isPending}
                onClick={() => downloadExcelMutation.mutate({ orderId })}
              >
                {downloadExcelMutation.isPending ? (
                  <Loader2 className="mr-1.5 size-4 animate-spin" />
                ) : (
                  <FileSpreadsheet className="mr-1.5 size-4 text-emerald-600" />
                )}
                Excel (.xlsx)
              </Button>

              <Button
                size="sm"
                className="bg-blue-600 text-white hover:bg-blue-700"
                disabled={downloadZipMutation.isPending}
                onClick={() =>
                  downloadZipMutation.mutate({ orderId, includeZipDocs: true })
                }
              >
                {downloadZipMutation.isPending ? (
                  <Loader2 className="mr-1.5 size-4 animate-spin" />
                ) : (
                  <FileArchive className="mr-1.5 size-4" />
                )}
                ZIP Bundle Dokumen
              </Button>
            </div>
          </div>
        </DialogHeader>

        {isLoading || !auditData ? (
          <div className="space-y-4 py-4">
            <Skeleton className="h-20 w-full rounded-xl" />
            <Skeleton className="h-32 w-full rounded-xl" />
            <Skeleton className="h-40 w-full rounded-xl" />
          </div>
        ) : (
          <div className="space-y-6 pt-2">
            {/* Info Pelanggan & Ringkasan Durasi Total */}
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div className="space-y-2 rounded-xl border border-slate-200 bg-slate-50/50 p-4">
                <div className="flex items-center gap-2 text-sm font-bold text-slate-800">
                  <Building2 className="size-4 text-blue-600" />
                  Informasi Pelanggan
                </div>
                <p className="text-sm font-semibold text-slate-900">
                  {auditData.customerInfo.companyName}
                </p>
                <p className="line-clamp-2 text-xs text-slate-600">
                  {auditData.customerInfo.companyAddress}
                </p>
                <div className="pt-1 text-xs text-slate-500">
                  PJ:{" "}
                  <span className="font-medium text-slate-700">
                    {auditData.customerInfo.responsiblePerson}
                  </span>{" "}
                  ({auditData.customerInfo.responsiblePhone})
                </div>
              </div>

              <div className="flex flex-col justify-between space-y-2 rounded-xl border border-blue-200 bg-blue-50/60 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm font-bold text-blue-900">
                    <Calendar className="size-4 text-blue-600" />
                    Total Waktu Keseluruhan
                  </div>
                  <Badge
                    variant="secondary"
                    className="bg-blue-600 font-mono text-[11px] text-white"
                  >
                    {auditData.timeline.totalDuration.formatted}
                  </Badge>
                </div>
                <div>
                  <p className="text-lg font-extrabold text-blue-950">
                    {auditData.timeline.totalDuration.text}
                  </p>
                  <p className="mt-0.5 text-xs text-blue-700">
                    Periode: {auditData.timeline.startDateFormatted} s.d.{" "}
                    {auditData.timeline.endDateFormatted}
                  </p>
                </div>
              </div>
            </div>

            {/* Tabel Rincian Timeline & Durasi Antar Stage */}
            <div className="space-y-3">
              <h4 className="flex items-center gap-2 text-sm font-bold text-slate-800">
                <Clock className="size-4 text-slate-600" />
                Rincian Timeline &amp; Durasi Antar-Stage
              </h4>
              <div className="overflow-hidden rounded-xl border border-slate-200 shadow-2xs">
                <table className="w-full text-left text-xs">
                  <thead className="border-b border-slate-200 bg-slate-100 font-semibold text-slate-700">
                    <tr>
                      <th className="w-10 p-2.5 text-center">Step</th>
                      <th className="p-2.5">Tahap Status</th>
                      <th className="p-2.5">Diubah Oleh</th>
                      <th className="p-2.5 text-center">
                        Tanggal (DD-MM-YYYY)
                      </th>
                      <th className="p-2.5 text-center">Waktu (HH-MM-SS)</th>
                      <th className="p-2.5 text-right">
                        Durasi dari Step Sebelumnya
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 bg-white">
                    {auditData.timeline.steps.map((step) => (
                      <tr
                        key={step.stepNumber}
                        className="transition-colors hover:bg-slate-50/80"
                      >
                        <td className="p-2.5 text-center font-bold text-slate-500">
                          {step.stepNumber}
                        </td>
                        <td className="p-2.5">
                          <span className="font-semibold text-slate-800">
                            {step.statusLabel}
                          </span>
                        </td>
                        <td className="p-2.5 text-slate-600">
                          {step.changedByName}
                        </td>
                        <td className="p-2.5 text-center font-mono font-medium text-slate-700">
                          {step.dateFormatted}
                        </td>
                        <td className="p-2.5 text-center font-mono text-slate-600">
                          {step.timeFormatted}
                        </td>
                        <td className="p-2.5 text-right">
                          <span className="rounded-full border border-blue-100 bg-blue-50 px-2 py-0.5 font-semibold text-blue-700">
                            {step.durationFromPrevious.text}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Ringkasan Dokumen Resmi */}
            <div className="space-y-2 pt-1">
              <h4 className="text-xs font-bold tracking-wider text-slate-700 uppercase">
                Dokumen Resmi Terlampir ({auditData.relatedDocuments.length})
              </h4>
              <div className="flex flex-wrap gap-2">
                {auditData.relatedDocuments.map((doc) => (
                  <Badge
                    key={doc.id}
                    variant="outline"
                    className="border-slate-200 bg-slate-50 p-1.5 text-[11px] text-slate-700"
                  >
                    📄 {doc.type.toUpperCase()}:{" "}
                    <span className="ml-1 font-semibold">
                      {doc.documentNumber}
                    </span>
                  </Badge>
                ))}
              </div>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

// ##################
// end authored
// ##################
