// ##################
// authored (generated by claude, Jun 01 2026 19:43 WITA)
// ##################

import { faqs } from "@tepian-k3/db/schema";
import { createInsertSchema, createUpdateSchema } from "drizzle-zod";
import z from "zod";
import { createPaginationSchema } from "./pagination.schema";

export const SORTABLE_FAQ_FIELDS = [
  "category",
  "orderIndex",
  "isActive",
  "createdAt",
  "updatedAt",
  "deletedAt",
] as const satisfies readonly (keyof typeof faqs.$inferSelect)[];

const getAllFaqsSchema = createPaginationSchema(
  SORTABLE_FAQ_FIELDS,
).extend({
  question: z.string().default(""),
  category: z.string().optional(),
  isActive: z.boolean().optional(),
});

const createFaqSchema = createInsertSchema(faqs, {
  question: z.string().min(1, "Pertanyaan harus diisi"),
  answer: z.string().min(1, "Jawaban harus diisi"),
  category: z.string().min(1, "Kategori harus diisi").max(100),
  orderIndex: z.number().int().default(0),
  isActive: z.boolean().default(true),
});

const updateFaqSchema = createUpdateSchema(faqs, {
  id: z.uuidv7(),
  question: z.string().min(1, "Pertanyaan harus diisi").optional(),
  answer: z.string().min(1, "Jawaban harus diisi").optional(),
  category: z.string().min(1, "Kategori harus diisi").max(100).optional(),
  orderIndex: z.number().int().optional(),
  isActive: z.boolean().optional(),
});

export const faqSchema = {
  getAllFaqsSchema,
  createFaqSchema,
  updateFaqSchema,
};

export default faqSchema;

// ##################
// end authored
// ##################
