// ##################
// authored (generated by claude, Jun 14 2026 20:17 WITA)
// ##################

import { mediaPublications } from "@tepian-k3/db/schema";
import { createInsertSchema, createUpdateSchema } from "drizzle-zod";
import z from "zod";
import { createPaginationSchema } from "./pagination.schema";

export const SORTABLE_MEDIA_FIELDS = [
  "title",
  "category",
  "isPublished",
  "publishedAt",
  "createdAt",
  "updatedAt",
  "deletedAt",
] as const satisfies readonly (keyof typeof mediaPublications.$inferSelect)[];

const getAllMediaSchema = createPaginationSchema(SORTABLE_MEDIA_FIELDS).extend({
  title: z.string().default(""),
  category: z.string().optional(),
  isPublished: z.boolean().optional(),
});

const createMediaSchema = createInsertSchema(mediaPublications, {
  title: z.string().min(1).max(255),
  description: z.string().optional(),
  content: z.string().min(1),
  category: z.string().min(1).max(100),
  isPublished: z.boolean(),
  publishedAt: z.iso.datetime().optional(),
  publisher: z.string().min(1).max(255),
})
  .omit({
    imageUrl: true,
  })
  .extend({
    image: z
      .file()
      .max(10 * 1024 * 1024)
      .mime(["image/jpeg", "image/png", "image/webp"]),
  });

const updateMediaSchema = createUpdateSchema(mediaPublications, {
  id: z.uuidv7(),
  title: z.string().min(1).max(255),
  description: z.string().optional(),
  content: z.string().min(1),
  category: z.string().min(1).max(100),
  isPublished: z.optional(z.boolean()),
  publishedAt: z.optional(z.iso.datetime()),
  publisher: z.string().min(1).max(255),
})
  .omit({
    imageUrl: true,
  })
  .extend({
    image: z
      .file()
      .max(10 * 1024 * 1024)
      .mime(["image/jpeg", "image/png", "image/webp"])
      .optional(),
  });

const mediaPublicationsSchema = {
  getAllMediaSchema,
  createMediaSchema,
  updateMediaSchema,
};

export default mediaPublicationsSchema;

// ##################
// end authored
// ##################
