import { db } from "@tepian-k3/db/client";
import {
  positions,
  employees,
  employeeCertifications,
} from "@tepian-k3/db/schema";
import { eq, isNull, and } from "@tepian-k3/db";
import { Effect } from "effect";
import { TRPCError } from "@trpc/server";
import { logError } from "@tepian-k3/services/logger";
import type { KepegawaianParseResult } from "@tepian-k3/services/excel";
import auditQueries from "../platform/audit.queries";

// ##################
// authored (generated by claude, Jul 12 2026)
// ##################

export const kepegawaianExcelQueries = {
  /**
   * Retrieves all master data necessary for exporting to Excel.
   */
  exportAllData() {
    return Effect.tryPromise({
      try: async () => {
        const [jabatanData, pegawaiData, sertifikasiData] = await Promise.all([
          db.query.positions.findMany({
            where: isNull(positions.deletedAt),
          }),
          db.query.employees.findMany({
            where: isNull(employees.deletedAt),
            with: { position: true },
          }),
          db.query.employeeCertifications.findMany({
            where: isNull(employeeCertifications.deletedAt),
            with: { employee: true },
          }),
        ]);

        return {
          jabatan: jabatanData.map((j) => ({
            nama: j.name,
            deskripsi: j.description || "",
          })),
          pegawai: pegawaiData.map((p) => ({
            nip: p.nip,
            nama: p.name,
            email: p.email,
            tipe: p.type,
            jabatan: p.position?.name || "",
            status: p.status,
          })),
          sertifikasi: sertifikasiData.map((s) => ({
            nipPegawai: s.employee?.nip || "",
            namaSertifikasi: s.certificationName,
            diterbitkanOleh: s.issuedBy,
            tanggalTerbit: s.issueDate
              ? new Date(s.issueDate).toISOString().split("T")[0]
              : "",
            tanggalKadaluarsa: s.expiryDate
              ? new Date(s.expiryDate).toISOString().split("T")[0]
              : "",
          })),
        };
      },
      catch: (e) => {
        logError("kepegawaianExcelQueries", "Gagal mengambil data kepegawaian untuk export", { error: e });
        return new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data kepegawaian untuk export.",
        });
      },
    });
  },

  /**
   * Meng-import data dari hasil parsing Excel.
   * Berjalan dalam satu transaksi untuk menjamin integritas.
   */
  importFromParsedData(
    parsed: KepegawaianParseResult,
    userId: string,
    userEmail: string,
  ) {
    return Effect.tryPromise({
      try: async () => {
        const summary = {
          jabatan: { processed: parsed.jabatan.length, success: 0, failed: 0 },
          pegawai: { processed: parsed.pegawai.length, success: 0, failed: 0 },
          sertifikasi: {
            processed: parsed.sertifikasi.length,
            success: 0,
            failed: 0,
          },
        };

        const remainingErrors = [...parsed.parseErrors];

        await db.transaction(async (tx) => {
          // 1. Import Jabatan
          // Simpan map jabatan name -> id untuk referensi
          const positionMap = new Map<string, string>();
          const existingPositions = await tx.query.positions.findMany({
            where: isNull(positions.deletedAt),
          });
          existingPositions.forEach((p) => positionMap.set(p.name, p.id));

          for (const row of parsed.jabatan) {
            try {
              const { nama, deskripsi } = row.data;
              let positionId = positionMap.get(nama);

              if (positionId) {
                // Update
                const oldVal = existingPositions.find((p) => p.id === positionId);
                const updateData: any = {};
                if (deskripsi !== undefined) updateData.description = deskripsi;

                if (Object.keys(updateData).length > 0) {
                  const [updated] = await tx
                    .update(positions)
                    .set(updateData)
                    .where(eq(positions.id, positionId))
                    .returning();

                  await auditQueries.createAuditLogTx(tx, {
                    entityType: "position",
                    entityId: positionId,
                    action: "update",
                    userId,
                    userEmail,
                    oldValues: oldVal,
                    newValues: updated,
                    description: `Mengubah data jabatan via import excel`,
                  });
                }
              } else {
                // Insert
                const [inserted] = await tx
                  .insert(positions)
                  .values({
                    name: nama,
                    description: deskripsi,
                  })
                  .returning();

                const insertedId = inserted?.id;
                if (!insertedId) {
                  throw new Error("Gagal mendapatkan ID setelah insert jabatan.");
                }

                positionId = insertedId;
                positionMap.set(nama, positionId);

                await auditQueries.createAuditLogTx(tx, {
                  entityType: "position",
                  entityId: positionId,
                  action: "create",
                  userId,
                  userEmail,
                  oldValues: null,
                  newValues: inserted,
                  description: `Menambahkan data jabatan via import excel`,
                });
              }
              summary.jabatan.success++;
            } catch (err: any) {
              summary.jabatan.failed++;
              remainingErrors.push({
                sheet: "Jabatan",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }

          // 2. Import Pegawai
          // Simpan map pegawai NIP -> id untuk referensi sertifikasi
          const employeeMap = new Map<string, string>();
          const existingEmployees = await tx.query.employees.findMany({
            where: isNull(employees.deletedAt),
          });
          existingEmployees.forEach((e) => employeeMap.set(e.nip, e.id));

          for (const row of parsed.pegawai) {
            try {
              const { nip, nama, email, tipe, jabatan, status } = row.data;

              // Validate position
              const posId = positionMap.get(jabatan);
              if (!posId) {
                throw new Error(`Jabatan "${jabatan}" tidak ditemukan di database atau sheet Jabatan`);
              }

              const employeeId = employeeMap.get(nip);
              if (employeeId) {
                // Update existing employee
                const oldVal = existingEmployees.find((e) => e.id === employeeId);
                const [updated] = await tx
                  .update(employees)
                  .set({
                    name: nama,
                    email: email,
                    type: tipe,
                    positionId: posId,
                    status: status as any,
                  })
                  .where(eq(employees.id, employeeId))
                  .returning();

                await auditQueries.createAuditLogTx(tx, {
                  entityType: "employee",
                  entityId: employeeId,
                  action: "update",
                  userId,
                  userEmail,
                  oldValues: oldVal,
                  newValues: updated,
                  description: `Mengubah data pegawai via import excel`,
                });
                summary.pegawai.success++;
              } else {
                // Skip insert since we can't create User without proper UI flow
                throw new Error(`Pegawai dengan NIP "${nip}" tidak ditemukan. Pembuatan pegawai baru tidak diizinkan melalui Excel.`);
              }
            } catch (err: any) {
              summary.pegawai.failed++;
              remainingErrors.push({
                sheet: "Pegawai",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }

          // 3. Import SertifikasiPegawai
          const existingCertifications = await tx.query.employeeCertifications.findMany({
            where: isNull(employeeCertifications.deletedAt),
          });

          for (const row of parsed.sertifikasi) {
            try {
              const { nipPegawai, namaSertifikasi, diterbitkanOleh, tanggalTerbit, tanggalKadaluarsa } = row.data;

              const empId = employeeMap.get(nipPegawai);
              if (!empId) {
                throw new Error(`Pegawai dengan NIP "${nipPegawai}" tidak ditemukan di database.`);
              }

              const existingCert = existingCertifications.find(
                (c) => c.employeeId === empId && c.certificationName === namaSertifikasi
              );

              const issueDateIso = tanggalTerbit ? new Date(tanggalTerbit).toISOString() : new Date().toISOString();
              const expiryDateIso = tanggalKadaluarsa ? new Date(tanggalKadaluarsa).toISOString() : null;

              if (existingCert) {
                // Update
                const [updated] = await tx
                  .update(employeeCertifications)
                  .set({
                    issuedBy: diterbitkanOleh,
                    issueDate: issueDateIso,
                    expiryDate: expiryDateIso,
                  })
                  .where(eq(employeeCertifications.id, existingCert.id))
                  .returning();

                await auditQueries.createAuditLogTx(tx, {
                  entityType: "employee_certification",
                  entityId: existingCert.id,
                  action: "update",
                  userId,
                  userEmail,
                  oldValues: existingCert,
                  newValues: updated,
                  description: `Mengubah data sertifikasi pegawai via import excel`,
                });
              } else {
                // Insert (dummy file_url since we don't have files via Excel)
                const [inserted] = await tx
                  .insert(employeeCertifications)
                  .values({
                    employeeId: empId,
                    certificationName: namaSertifikasi,
                    issuedBy: diterbitkanOleh,
                    issueDate: issueDateIso,
                    expiryDate: expiryDateIso,
                    certificate_fileUrl: "-",
                  })
                  .returning();

                const insertedId = inserted?.id;
                if (!insertedId) {
                  throw new Error("Gagal mendapatkan ID setelah insert sertifikasi.");
                }

                await auditQueries.createAuditLogTx(tx, {
                  entityType: "employee_certification",
                  entityId: insertedId,
                  action: "create",
                  userId,
                  userEmail,
                  oldValues: null,
                  newValues: inserted,
                  description: `Menambahkan data sertifikasi pegawai via import excel`,
                });
              }
              summary.sertifikasi.success++;
            } catch (err: any) {
              summary.sertifikasi.failed++;
              remainingErrors.push({
                sheet: "SertifikasiPegawai",
                row: row.rowNumber,
                message: err.message || "Gagal menyimpan ke database",
              });
            }
          }
        }); // End transaction

        return { summary, errors: remainingErrors };
      },
      catch: (e) => {
        logError("kepegawaianExcelQueries", "Terjadi kesalahan saat menyimpan data import", { error: e });
        return new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Terjadi kesalahan saat menyimpan data import ke database.",
        });
      },
    });
  },
};
