// ##################
// authored (generated by claude, Jun 01 2026 19:43 WITA)
// ##################

import { TRPCError } from "@trpc/server";
import { db } from "@tepian-k3/db/client";
import { and, eq, isNull } from "@tepian-k3/db";
import { settings } from "@tepian-k3/db/schema";
import { z } from "zod";
import settingSchema from "@tepian-k3/schema/platform/setting.schema";
import { Effect } from "effect";
import { logError } from "@tepian-k3/services/logger";

const settingQueries = {
  /**
   * Get a setting value by unique key string
   * @param {string} key
   */
  getSettingByKey: (key: string) =>
    Effect.tryPromise({
      try: () =>
        db.query.settings.findFirst({
          where: and(eq(settings.key, key), isNull(settings.deletedAt)),
        }),
      catch: (error) => {
        logError("setting.queries", "getSettingByKey", { error, key });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data pengaturan.",
        });
      },
    }),

  /**
   * Set (Upsert) setting value by key
   * @param {z.infer<typeof settingSchema.setSettingSchema>} data
   */
  setSetting: (data: z.infer<typeof settingSchema.setSettingSchema>) =>
    Effect.tryPromise({
      try: async () => {
        // Check if there is an existing deleted or active row with this key
        const existing = await db.query.settings.findFirst({
          where: eq(settings.key, data.key),
        });

        if (existing) {
          // Update existing setting (and clear soft delete timestamp if present)
          const [updated] = await db
            .update(settings)
            .set({
              value: data.value,
              description: data.description || existing.description,
              deletedAt: null,
            })
            .where(eq(settings.key, data.key))
            .returning();
          
          if (!updated) {
            throw new TRPCError({
              code: "INTERNAL_SERVER_ERROR",
              message: "Gagal menyimpan pengaturan.",
            });
          }
          return updated;
        } else {
          // Insert new setting
          const [newSetting] = await db
            .insert(settings)
            .values(data)
            .returning();

          if (!newSetting) {
            throw new TRPCError({
              code: "INTERNAL_SERVER_ERROR",
              message: "Gagal menyimpan pengaturan.",
            });
          }
          return newSetting;
        }
      },
      catch: (error) => {
        logError("setting.queries", "setSetting", { error, data });
        if (error instanceof TRPCError) throw error;
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal menyimpan pengaturan.",
        });
      },
    }),
};

export default settingQueries;

// ##################
// end authored
// ##################
