// ##################
// authored (generated by gemini, Aug 30 2026 14:55 WITA)
// ##################

import { TRPCError } from "@trpc/server";
import { db } from "@tepian-k3/db/client";
import { and, asc, eq, ilike, isNotNull, isNull } from "@tepian-k3/db";
import { teamMembers } from "@tepian-k3/db/schema";
import { z } from "zod";
import teamMemberSchema from "@tepian-k3/schema/platform/team-member.schema";
import { Effect } from "effect";
import { logError } from "@tepian-k3/services/logger";
import { getOffsetPaginated } from "../utils/get-offset-paginated";
import {
  deleteStorageFile,
  replaceStorageFile,
} from "../helpers/storage.helpers";

const teamMemberQueries = {
  /**
   * Get all active team members for user display on /credit
   */
  getAllActiveTeamMembers: () =>
    Effect.tryPromise({
      try: () =>
        db.query.teamMembers.findMany({
          where: and(
            eq(teamMembers.isActive, true),
            isNull(teamMembers.deletedAt),
          ),
          orderBy: asc(teamMembers.order),
        }),
      catch: (error) => {
        logError("team-member.queries", "getAllActiveTeamMembers", { error });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data tim aktif.",
        });
      },
    }),

  /**
   * Get all team members (active & inactive) for admin management
   */
  getAllTeamMembersForAdmin: () =>
    Effect.tryPromise({
      try: () =>
        db.query.teamMembers.findMany({
          where: isNull(teamMembers.deletedAt),
          orderBy: asc(teamMembers.order),
        }),
      catch: (error) => {
        logError("team-member.queries", "getAllTeamMembersForAdmin", { error });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil semua data anggota tim.",
        });
      },
    }),

  /**
   * Get team member by ID
   * @param {string} id
   */
  getTeamMemberById: (id: string) =>
    Effect.tryPromise({
      try: () =>
        db.query.teamMembers.findFirst({
          where: and(eq(teamMembers.id, id), isNull(teamMembers.deletedAt)),
        }),
      catch: (error) => {
        logError("team-member.queries", "getTeamMemberById", { error, id });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data anggota tim.",
        });
      },
    }),

  /**
   * Get team member by order
   * @param {number} order
   */
  getTeamMemberByOrder: (order: number) =>
    Effect.tryPromise({
      try: () =>
        db.query.teamMembers.findFirst({
          where: and(
            eq(teamMembers.order, order),
            isNull(teamMembers.deletedAt),
          ),
        }),
      catch: (error) => {
        logError("team-member.queries", "getTeamMemberByOrder", {
          error,
          order,
        });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil urutan anggota tim.",
        });
      },
    }),

  /**
   * Get deleted team member by ID
   * @param {string} id
   */
  getDeletedTeamMemberById: (id: string) =>
    Effect.tryPromise({
      try: () =>
        db.query.teamMembers.findFirst({
          where: and(eq(teamMembers.id, id), isNotNull(teamMembers.deletedAt)),
        }),
      catch: (error) => {
        logError("team-member.queries", "getDeletedTeamMemberById", {
          error,
          id,
        });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengambil data anggota tim terhapus.",
        });
      },
    }),

  /**
   * Get Offset Paginated Team Members
   * @param {z.infer<typeof teamMemberSchema.getAllTeamMembersSchema>} input
   */
  getOffsetPaginatedTeamMembers: (
    input: z.infer<typeof teamMemberSchema.getAllTeamMembersSchema>,
  ) =>
    getOffsetPaginated({
      table: teamMembers,
      input,
      searchConditions: [
        input.name ? ilike(teamMembers.name, `%${input.name}%`) : undefined,
        input.order ? eq(teamMembers.order, input.order) : undefined,
        input.isActive !== undefined
          ? eq(teamMembers.isActive, input.isActive)
          : undefined,
      ],
      errorContext: {
        queryName: "team-member.queries",
        errorMessage: "Gagal mengambil data anggota tim.",
      },
    }),

  /**
   * Create Team Member
   * @param {z.infer<typeof teamMemberSchema.createTeamMemberSchema>} data
   * @param {string} photoUrl
   */
  createTeamMember: (
    data: z.infer<typeof teamMemberSchema.createTeamMemberSchema>,
    photoUrl?: string | null,
  ) =>
    Effect.gen(this, function* () {
      const isExisting = yield* teamMemberQueries.getTeamMemberByOrder(
        data.order,
      );

      if (isExisting) {
        const allMembers = yield* Effect.tryPromise({
          try: () => db.select({ order: teamMembers.order }).from(teamMembers),
          catch: () => [],
        });
        const maxOrder = allMembers.reduce(
          (max, m) => Math.max(max, m.order),
          0,
        );
        data.order = maxOrder + 1;
      }

      const { photo: _, ...insertData } = data;

      const [newMember] = yield* Effect.tryPromise({
        try: () =>
          db
            .insert(teamMembers)
            .values({ ...insertData, photoUrl: photoUrl ?? null })
            .returning(),
        catch: (error) => {
          logError("team-member.queries", "createTeamMember", { error, data });
          return new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menambahkan anggota tim.",
          });
        },
      });

      if (!newMember) {
        return yield* Effect.fail(
          new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menambahkan anggota tim.",
          }),
        );
      }

      return newMember;
    }),

  /**
   * Update Team Member
   * @param {z.infer<typeof teamMemberSchema.updateTeamMemberSchema>} data
   * @param {string} photoUrl (optional)
   */
  updateTeamMember: (
    data: z.infer<typeof teamMemberSchema.updateTeamMemberSchema>,
    photoUrl?: string | null,
  ) =>
    Effect.gen(this, function* () {
      const existingMember = yield* teamMemberQueries.getTeamMemberById(
        data.id,
      );

      if (!existingMember) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Anggota tim tidak ditemukan.",
          }),
        );
      }

      // Handle order changes
      if (data.order !== undefined && data.order !== existingMember.order) {
        const memberWithTargetOrder =
          yield* teamMemberQueries.getTeamMemberByOrder(data.order);

        if (memberWithTargetOrder) {
          yield* Effect.tryPromise({
            try: () =>
              db
                .update(teamMembers)
                .set({ order: existingMember.order })
                .where(eq(teamMembers.id, memberWithTargetOrder.id)),
            catch: (error) => {
              logError("team-member.queries", "updateTeamMember:swapOrder", {
                error,
              });
              return new TRPCError({
                code: "INTERNAL_SERVER_ERROR",
                message: "Gagal memperbarui urutan anggota tim.",
              });
            },
          });
        }
      }

      const { photo: _, ...updateData } = data;

      const [updatedMember] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(teamMembers)
            .set({
              ...updateData,
              ...(photoUrl !== undefined ? { photoUrl } : {}),
            })
            .where(eq(teamMembers.id, data.id))
            .returning(),
        catch: (error) => {
          logError("team-member.queries", "updateTeamMember", { error, data });
          return new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal memperbarui anggota tim.",
          });
        },
      });

      if (!updatedMember) {
        return yield* Effect.fail(
          new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal memperbarui anggota tim.",
          }),
        );
      }

      if (photoUrl && existingMember.photoUrl) {
        yield* replaceStorageFile(
          photoUrl,
          existingMember.photoUrl,
          "team-member.queries",
        );
      }

      return updatedMember;
    }),

  /**
   * Delete team member (soft delete)
   * @param {string} id
   */
  deleteTeamMember: (id: string) =>
    Effect.gen(this, function* () {
      const existingMember = yield* teamMemberQueries.getTeamMemberById(id);

      if (!existingMember) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Anggota tim tidak ditemukan.",
          }),
        );
      }

      const [deleted] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(teamMembers)
            .set({ deletedAt: new Date().toISOString(), isActive: false })
            .where(eq(teamMembers.id, id))
            .returning(),
        catch: (error) => {
          logError("team-member.queries", "deleteTeamMember", { error, id });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menghapus anggota tim.",
          });
        },
      });

      if (!deleted) {
        return yield* Effect.fail(
          new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menghapus anggota tim.",
          }),
        );
      }

      return deleted;
    }),

  /**
   * Restore team member
   * @param {string} id
   */
  restoreTeamMember: (id: string) =>
    Effect.gen(this, function* () {
      const deletedMember =
        yield* teamMemberQueries.getDeletedTeamMemberById(id);

      if (!deletedMember) {
        return yield* Effect.fail(
          new TRPCError({
            code: "NOT_FOUND",
            message: "Anggota tim terhapus tidak ditemukan.",
          }),
        );
      }

      const [restored] = yield* Effect.tryPromise({
        try: () =>
          db
            .update(teamMembers)
            .set({ deletedAt: null })
            .where(eq(teamMembers.id, id))
            .returning(),
        catch: (error) => {
          logError("team-member.queries", "restoreTeamMember", { error, id });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengembalikan data anggota tim.",
          });
        },
      });

      if (!restored) {
        return yield* Effect.fail(
          new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal mengembalikan data anggota tim.",
          }),
        );
      }

      return restored;
    }),

  /**
   * Hard delete team member
   * @param {string} id
   */
  hardDeleteTeamMember: (id: string) =>
    Effect.gen(this, function* () {
      const existingMember = yield* teamMemberQueries.getTeamMemberById(id);

      const [deleted] = yield* Effect.tryPromise({
        try: () =>
          db.delete(teamMembers).where(eq(teamMembers.id, id)).returning(),
        catch: (error) => {
          logError("team-member.queries", "hardDeleteTeamMember", {
            error,
            id,
          });
          throw new TRPCError({
            code: "INTERNAL_SERVER_ERROR",
            message: "Gagal menghapus permanen anggota tim.",
          });
        },
      });

      if (existingMember?.photoUrl) {
        yield* deleteStorageFile(
          existingMember.photoUrl,
          "team-member.queries",
        );
      }

      return deleted;
    }),

  /**
   * Bulk reorder team members
   * @param {Array<{ id: string; order: number }>} items
   */
  reorderTeamMembers: (items: Array<{ id: string; order: number }>) =>
    Effect.tryPromise({
      try: () =>
        db.transaction(async (tx) => {
          for (const item of items) {
            await tx
              .update(teamMembers)
              .set({ order: item.order })
              .where(eq(teamMembers.id, item.id));
          }
          return items;
        }),
      catch: (error) => {
        logError("team-member.queries", "reorderTeamMembers", { error });
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal memperbarui urutan anggota tim.",
        });
      },
    }),
};

export default teamMemberQueries;

// ##################
// end authored
// ##################
