// ##################
// authored (generated by gemini, Jun 12 2026 17:50 WITA)
// ##################

import { requirePermission } from "@/utils/require-permission";
import { createFileRoute } from "@tanstack/react-router";
import { pageHead } from "@/utils/page-head";
import { trpc } from "@/utils/trpc";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from "@/components/ui/dialog";
import { format } from "date-fns";
import { id as idLocale } from "date-fns/locale";
import { FileText, PlusCircle, Edit, Trash2, Eye, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { getPublicUrl } from "@/utils/url";

export const Route = createFileRoute("/(core)/back-office/ppid/")({
  beforeLoad: async ({ context }) =>
    await requirePermission(context, { permission: "ppid-submissions.read" }),
  component: PPIDBackOfficePage,
  head: () => pageHead("Manajemen PPID - Back Office"),
});

function PPIDBackOfficePage() {
  const queryClient = useQueryClient();

  // Active Tab
  const [activeTab, setActiveTab] = useState<"submissions" | "documents">(
    "submissions",
  );

  // Query submissions
  const [subPage, setSubPage] = useState(1);
  const [subSearch, setSubSearch] = useState("");
  const { data: subData, isLoading: isSubLoading } = useQuery(
    trpc.platform.ppid.getAdminSubmissions.queryOptions({
      page: subPage,
      perPage: 10,
      search: subSearch,
    }),
  );

  // Query documents
  const [docPage, setDocPage] = useState(1);
  const [docSearch, setDocSearch] = useState("");
  const { data: docData, isLoading: isDocLoading } = useQuery(
    trpc.platform.ppid.getAdminDocuments.queryOptions({
      page: docPage,
      perPage: 10,
      title: docSearch,
    }),
  );

  // Dialog State: Edit Submission
  const [selectedSub, setSelectedSub] = useState<any>(null);
  const [isSubDialogOpen, setIsSubDialogOpen] = useState(false);
  const [subStatus, setSubStatus] = useState<
    "pending" | "disetujui" | "ditolak" | "selesai"
  >("pending");
  const [adminNotes, setAdminNotes] = useState("");
  const [responseFile, setResponseFile] = useState<File | null>(null);

  // Dialog State: Create/Edit Document
  const [selectedDoc, setSelectedDoc] = useState<any>(null);
  const [isDocDialogOpen, setIsDocDialogOpen] = useState(false);
  const [docForm, setDocForm] = useState({
    title: "",
    documentNumber: "",
    description: "",
    category: "setiap-saat" as
      | "setiap-saat"
      | "berkala"
      | "serta-merta"
      | "dikecualikan",
    type: "",
    publisher: "",
    isActive: true,
  });
  const [docFile, setDocFile] = useState<File | null>(null);

  // Mutations
  const updateSubMutation = useMutation(
    trpc.platform.ppid.updateSubmissionStatus.mutationOptions({
      onSuccess: () => {
        toast.success("Berhasil mengubah status permohonan");
        setIsSubDialogOpen(false);
        setSelectedSub(null);
        setResponseFile(null);
        queryClient.invalidateQueries({
          queryKey: trpc.platform.ppid.getAdminSubmissions.queryKey(),
        });
      },
      onError: (err) => {
        toast.error(err.message || "Gagal memperbarui permohonan");
      },
    }),
  );

  const deleteSubMutation = useMutation(
    trpc.platform.ppid.deleteSubmission.mutationOptions({
      onSuccess: () => {
        toast.success("Berhasil menghapus permohonan");
        queryClient.invalidateQueries({
          queryKey: trpc.platform.ppid.getAdminSubmissions.queryKey(),
        });
      },
      onError: (err) => {
        toast.error(err.message || "Gagal menghapus permohonan");
      },
    }),
  );

  const createDocMutation = useMutation(
    trpc.platform.ppid.createDocument.mutationOptions({
      onSuccess: () => {
        toast.success("Berhasil membuat dokumen PPID baru");
        setIsDocDialogOpen(false);
        setDocFile(null);
        queryClient.invalidateQueries({
          queryKey: trpc.platform.ppid.getAdminDocuments.queryKey(),
        });
      },
      onError: (err) => {
        toast.error(err.message || "Gagal membuat dokumen");
      },
    }),
  );

  const updateDocMutation = useMutation(
    trpc.platform.ppid.updateDocument.mutationOptions({
      onSuccess: () => {
        toast.success("Berhasil memperbarui dokumen PPID");
        setIsDocDialogOpen(false);
        setSelectedDoc(null);
        setDocFile(null);
        queryClient.invalidateQueries({
          queryKey: trpc.platform.ppid.getAdminDocuments.queryKey(),
        });
      },
      onError: (err) => {
        toast.error(err.message || "Gagal memperbarui dokumen");
      },
    }),
  );

  const deleteDocMutation = useMutation(
    trpc.platform.ppid.deleteDocument.mutationOptions({
      onSuccess: () => {
        toast.success("Berhasil menghapus dokumen PPID");
        queryClient.invalidateQueries({
          queryKey: trpc.platform.ppid.getAdminDocuments.queryKey(),
        });
      },
      onError: (err) => {
        toast.error(err.message || "Gagal menghapus dokumen");
      },
    }),
  );

  const handleOpenSubDialog = (sub: any) => {
    setSelectedSub(sub);
    setSubStatus(sub.status);
    setAdminNotes(sub.adminNotes || "");
    setIsSubDialogOpen(true);
  };

  const handleSubSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const formData = new FormData();
    formData.append("id", selectedSub.id);
    formData.append("status", subStatus);
    formData.append("adminNotes", adminNotes);
    if (responseFile) {
      formData.append("responseFile", responseFile);
    }
    updateSubMutation.mutate(formData);
  };

  const handleOpenDocDialog = (doc: any = null) => {
    setSelectedDoc(doc);
    if (doc) {
      setDocForm({
        title: doc.title,
        documentNumber: doc.documentNumber || "",
        description: doc.description || "",
        category: doc.category,
        type: doc.type,
        publisher: doc.publisher,
        isActive: doc.isActive,
      });
    } else {
      setDocForm({
        title: "",
        documentNumber: "",
        description: "",
        category: "setiap-saat",
        type: "",
        publisher: "",
        isActive: true,
      });
    }
    setIsDocDialogOpen(true);
  };

  const handleDocSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const formData = new FormData();
    if (selectedDoc) {
      formData.append("id", selectedDoc.id);
    }
    formData.append("title", docForm.title);
    formData.append("documentNumber", docForm.documentNumber);
    formData.append("description", docForm.description);
    formData.append("category", docForm.category);
    formData.append("type", docForm.type);
    formData.append("publisher", docForm.publisher);
    formData.append("isActive", String(docForm.isActive));
    if (docFile) {
      formData.append("file", docFile);
    }

    if (selectedDoc) {
      updateDocMutation.mutate(formData);
    } else {
      createDocMutation.mutate(formData);
    }
  };

  return (
    <div className="flex flex-col gap-6 p-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">
          Manajemen Layanan PPID
        </h1>
        <p className="text-sm text-muted-foreground">
          Kelola tiket permohonan informasi publik dari masyarakat dan kelola
          dokumen regulasi PPID.
        </p>
      </div>

      <Tabs
        value={activeTab}
        onValueChange={(val) => setActiveTab(val as any)}
        className="w-full"
      >
        <TabsList className="mb-6 grid w-full grid-cols-2 rounded-xl sm:max-w-md">
          <TabsTrigger value="submissions" className="rounded-lg">
            Permohonan Masuk ({subData?.data.length || 0})
          </TabsTrigger>
          <TabsTrigger value="documents" className="rounded-lg">
            Dokumen Regulasi ({docData?.data.length || 0})
          </TabsTrigger>
        </TabsList>

        {/* TAB 1: SUBMISSIONS */}
        <TabsContent value="submissions" className="space-y-4">
          <div className="flex items-center justify-between gap-4">
            <Input
              placeholder="Cari pemohon, nomor tiket, atau email..."
              value={subSearch}
              onChange={(e) => {
                setSubSearch(e.target.value);
                setSubPage(1);
              }}
              className="max-w-xs"
            />
          </div>

          <Card className="overflow-hidden rounded-xl border shadow-xs">
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="border-b bg-slate-50 text-xs font-semibold text-slate-500 uppercase dark:bg-neutral-900 dark:text-neutral-400">
                  <tr>
                    <th className="px-6 py-4">Nomor Tiket</th>
                    <th className="px-6 py-4">Nama Pemohon</th>
                    <th className="px-6 py-4">Email / Telepon</th>
                    <th className="px-6 py-4">Informasi yang Diminta</th>
                    <th className="px-6 py-4">Status</th>
                    <th className="px-6 py-4">Tanggal Pengajuan</th>
                    <th className="w-32 px-6 py-4 text-center">Aksi</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-neutral-900">
                  {isSubLoading ? (
                    <tr>
                      <td
                        colSpan={7}
                        className="px-6 py-8 text-center text-muted-foreground"
                      >
                        Memuat data permohonan...
                      </td>
                    </tr>
                  ) : subData?.data.length === 0 ? (
                    <tr>
                      <td
                        colSpan={7}
                        className="px-6 py-8 text-center text-muted-foreground"
                      >
                        Belum ada permohonan masuk.
                      </td>
                    </tr>
                  ) : (
                    subData?.data.map((sub: any) => (
                      <tr
                        key={sub.id}
                        className="hover:bg-slate-50/50 dark:hover:bg-neutral-900/30"
                      >
                        <td className="px-6 py-4 font-bold text-primary">
                          {sub.ticketNumber}
                        </td>
                        <td className="px-6 py-4 font-medium">
                          {sub.namaPemohon}
                        </td>
                        <td className="px-6 py-4 text-xs text-muted-foreground">
                          <div>{sub.email}</div>
                          <div>{sub.phone}</div>
                        </td>
                        <td className="max-w-xs truncate px-6 py-4">
                          {sub.jenisInformasi}
                        </td>
                        <td className="px-6 py-4">
                          <span
                            className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold uppercase ${
                              sub.status === "pending"
                                ? "bg-amber-100 text-amber-800"
                                : sub.status === "disetujui"
                                  ? "bg-blue-100 text-blue-800"
                                  : sub.status === "ditolak"
                                    ? "bg-red-100 text-red-800"
                                    : "bg-emerald-100 text-emerald-800"
                            }`}
                          >
                            {sub.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-xs">
                          {format(
                            new Date(sub.createdAt),
                            "dd MMM yyyy HH:mm",
                            { locale: idLocale },
                          )}
                        </td>
                        <td className="px-6 py-4 text-center">
                          <div className="flex items-center justify-center gap-2">
                            <Button
                              size="sm"
                              onClick={() => handleOpenSubDialog(sub)}
                            >
                              Kelola
                            </Button>
                            <Button
                              size="icon"
                              variant="ghost"
                              className="size-8 text-destructive hover:bg-red-50"
                              onClick={() => {
                                if (
                                  confirm(
                                    "Apakah Anda yakin ingin menghapus permohonan ini?",
                                  )
                                ) {
                                  deleteSubMutation.mutate({ id: sub.id });
                                }
                              }}
                            >
                              <Trash2 className="size-4" />
                            </Button>
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </Card>
        </TabsContent>

        {/* TAB 2: DOCUMENTS */}
        <TabsContent value="documents" className="space-y-4">
          <div className="flex items-center justify-between gap-4">
            <Input
              placeholder="Cari regulasi..."
              value={docSearch}
              onChange={(e) => {
                setDocSearch(e.target.value);
                setDocPage(1);
              }}
              className="max-w-xs"
            />
            <Button className="gap-1.5" onClick={() => handleOpenDocDialog()}>
              <PlusCircle className="size-4" />
              Tambah Dokumen
            </Button>
          </div>

          <Card className="overflow-hidden rounded-xl border shadow-xs">
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="border-b bg-slate-50 text-xs font-semibold text-slate-500 uppercase dark:bg-neutral-900 dark:text-neutral-400">
                  <tr>
                    <th className="px-6 py-4">Judul Dokumen</th>
                    <th className="px-6 py-4">Nomor</th>
                    <th className="px-6 py-4">Kategori</th>
                    <th className="px-6 py-4">Jenis / Penerbit</th>
                    <th className="px-6 py-4">Status</th>
                    <th className="w-32 px-6 py-4 text-center">Aksi</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-neutral-900">
                  {isDocLoading ? (
                    <tr>
                      <td
                        colSpan={6}
                        className="px-6 py-8 text-center text-muted-foreground"
                      >
                        Memuat data regulasi...
                      </td>
                    </tr>
                  ) : docData?.data.length === 0 ? (
                    <tr>
                      <td
                        colSpan={6}
                        className="px-6 py-8 text-center text-muted-foreground"
                      >
                        Belum ada dokumen PPID ditambahkan.
                      </td>
                    </tr>
                  ) : (
                    docData?.data.map((doc: any) => (
                      <tr
                        key={doc.id}
                        className="hover:bg-slate-50/50 dark:hover:bg-neutral-900/30"
                      >
                        <td className="px-6 py-4 font-semibold">{doc.title}</td>
                        <td className="px-6 py-4 text-xs text-muted-foreground">
                          {doc.documentNumber || "-"}
                        </td>
                        <td className="px-6 py-4 text-xs font-medium text-slate-700 capitalize dark:text-neutral-300">
                          {doc.category}
                        </td>
                        <td className="px-6 py-4 text-xs">
                          <div>{doc.type}</div>
                          <div className="text-muted-foreground">
                            {doc.publisher}
                          </div>
                        </td>
                        <td className="px-6 py-4">
                          <span
                            className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold ${
                              doc.isActive
                                ? "bg-emerald-100 text-emerald-800"
                                : "bg-slate-100 text-slate-600"
                            }`}
                          >
                            {doc.isActive ? "Aktif" : "Nonaktif"}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-center">
                          <div className="flex items-center justify-center gap-1">
                            <Button
                              size="icon"
                              variant="ghost"
                              className="size-8"
                              onClick={() => handleOpenDocDialog(doc)}
                            >
                              <Edit className="size-4 text-slate-600" />
                            </Button>
                            <Button
                              size="icon"
                              variant="ghost"
                              className="size-8 text-destructive hover:bg-red-50"
                              onClick={() => {
                                if (
                                  confirm(
                                    "Apakah Anda yakin ingin menghapus dokumen ini?",
                                  )
                                ) {
                                  deleteDocMutation.mutate({ id: doc.id });
                                }
                              }}
                            >
                              <Trash2 className="size-4" />
                            </Button>
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </Card>
        </TabsContent>
      </Tabs>

      {/* DIALOG: KELOLA SUBMISSION */}
      <Dialog open={isSubDialogOpen} onOpenChange={setIsSubDialogOpen}>
        <DialogContent className="rounded-2xl sm:max-w-xl">
          {selectedSub && (
            <form onSubmit={handleSubSubmit} className="space-y-6">
              <DialogHeader>
                <DialogTitle>Kelola Permohonan PPID</DialogTitle>
                <DialogDescription>
                  Tiket: {selectedSub.ticketNumber}
                </DialogDescription>
              </DialogHeader>

              <div className="max-h-[400px] space-y-4 overflow-y-auto pr-2 text-sm">
                <div className="grid grid-cols-2 gap-4 border-b pb-4">
                  <div>
                    <Label className="block text-xs text-muted-foreground">
                      NAMA PEMOHON
                    </Label>
                    <span className="font-semibold">
                      {selectedSub.namaPemohon}
                    </span>
                  </div>
                  <div>
                    <Label className="block text-xs text-muted-foreground">
                      KONTAK
                    </Label>
                    <span className="font-semibold">
                      {selectedSub.email} / {selectedSub.phone}
                    </span>
                  </div>
                </div>

                <div>
                  <Label className="block text-xs text-muted-foreground">
                    INFORMASI YANG DIMINTA
                  </Label>
                  <p className="rounded-lg border bg-slate-50 p-3 text-xs leading-relaxed dark:bg-neutral-900">
                    {selectedSub.jenisInformasi}
                  </p>
                </div>

                <div>
                  <Label className="block text-xs text-muted-foreground">
                    RINCIAN & TUJUAN PENGGUNAAN
                  </Label>
                  <p className="rounded-lg border bg-slate-50 p-3 text-xs leading-relaxed dark:bg-neutral-900">
                    {selectedSub.rincianInformasi}
                    <br />
                    <strong className="mt-2 block text-primary">
                      Tujuan: {selectedSub.tujuanPenggunaan}
                    </strong>
                  </p>
                </div>

                <div>
                  <Label className="mb-1.5 block text-xs text-muted-foreground">
                    DOKUMEN PENDUKUNG / IDENTITAS
                  </Label>
                  <div className="flex flex-col gap-2">
                    {selectedSub.identityFiles &&
                    Array.isArray(selectedSub.identityFiles) &&
                    selectedSub.identityFiles.length > 0 ? (
                      selectedSub.identityFiles.map(
                        (file: any, idx: number) => (
                          <div key={idx} className="flex items-center gap-2">
                            <Button
                              asChild
                              size="sm"
                              variant="outline"
                              className="gap-1.5"
                            >
                              <a
                                href={getPublicUrl(file.url)}
                                target="_blank"
                                rel="noreferrer"
                              >
                                <Eye className="size-4" />
                                <span>
                                  Lihat Dokumen {idx + 1} ({file.name})
                                </span>
                              </a>
                            </Button>
                          </div>
                        ),
                      )
                    ) : selectedSub.identityFileUrl ? (
                      <Button
                        asChild
                        size="sm"
                        variant="outline"
                        className="gap-1.5"
                      >
                        <a
                          href={getPublicUrl(selectedSub.identityFileUrl)}
                          target="_blank"
                          rel="noreferrer"
                        >
                          <Eye className="size-4" />
                          <span>Lihat KTP Pemohon</span>
                        </a>
                      </Button>
                    ) : (
                      <span className="text-xs text-slate-500">
                        Tidak ada dokumen pendukung
                      </span>
                    )}
                  </div>
                </div>

                <div className="space-y-4 border-t pt-4">
                  <h4 className="font-bold text-slate-800 dark:text-slate-200">
                    Tanggapan Administrasi
                  </h4>

                  <div className="space-y-2">
                    <Label>Ubah Status Permohonan</Label>
                    <select
                      className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                      value={subStatus}
                      onChange={(e: any) => setSubStatus(e.target.value)}
                    >
                      <option value="pending">
                        Menunggu Verifikasi (Pending)
                      </option>
                      <option value="disetujui">
                        Setujui Permohonan (Proses Berkas)
                      </option>
                      <option value="ditolak">
                        Tolak Permohonan (Dokumen Rahasia)
                      </option>
                      <option value="selesai">
                        Selesai (Lampirkan Jawaban/PDF)
                      </option>
                    </select>
                  </div>

                  <div className="space-y-2">
                    <Label>Catatan Admin / Alasan Penolakan</Label>
                    <Textarea
                      placeholder="Masukkan catatan jawaban atau alasan penolakan jika permohonan ditolak..."
                      value={adminNotes}
                      onChange={(e) => setAdminNotes(e.target.value)}
                      rows={3}
                    />
                  </div>

                  {subStatus === "selesai" && (
                    <div className="space-y-2">
                      <Label>Unggah File Jawaban (PDF Resmi PPID)</Label>
                      <div className="relative flex cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed bg-slate-50 p-4">
                        <input
                          type="file"
                          accept=".pdf"
                          className="absolute inset-0 cursor-pointer opacity-0"
                          onChange={(e) => {
                            if (e.target.files && e.target.files[0]) {
                              setResponseFile(e.target.files[0]);
                            }
                          }}
                        />
                        <FileText className="mb-1 size-6 text-slate-400" />
                        <span className="text-xs font-semibold text-slate-700">
                          {responseFile
                            ? responseFile.name
                            : "Unggah dokumen jawaban PPID"}
                        </span>
                      </div>
                    </div>
                  )}
                </div>
              </div>

              <DialogFooter>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setIsSubDialogOpen(false)}
                >
                  Batal
                </Button>
                <Button type="submit" disabled={updateSubMutation.isPending}>
                  {updateSubMutation.isPending && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  Simpan Perubahan
                </Button>
              </DialogFooter>
            </form>
          )}
        </DialogContent>
      </Dialog>

      {/* DIALOG: TAMBAH/EDIT DOKUMEN */}
      <Dialog open={isDocDialogOpen} onOpenChange={setIsDocDialogOpen}>
        <DialogContent className="rounded-2xl sm:max-w-md">
          <form onSubmit={handleDocSubmit} className="space-y-4">
            <DialogHeader>
              <DialogTitle>
                {selectedDoc ? "Edit Dokumen PPID" : "Tambah Dokumen PPID"}
              </DialogTitle>
              <DialogDescription>
                Unggah regulasi resmi atau informasi berkala untuk ditampilkan
                di portal publik.
              </DialogDescription>
            </DialogHeader>

            <div className="max-h-[420px] space-y-3 overflow-y-auto pr-2 text-sm">
              <div className="space-y-1">
                <Label htmlFor="docTitle">Judul Dokumen</Label>
                <Input
                  id="docTitle"
                  placeholder="Contoh: Undang-Undang K3 Nomor 1 Tahun 1970"
                  value={docForm.title}
                  onChange={(e) =>
                    setDocForm({ ...docForm, title: e.target.value })
                  }
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <Label htmlFor="docNumber">Nomor Regulasi</Label>
                  <Input
                    id="docNumber"
                    placeholder="Contoh: UU No. 1/1970"
                    value={docForm.documentNumber}
                    onChange={(e) =>
                      setDocForm({ ...docForm, documentNumber: e.target.value })
                    }
                  />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="docCategory">Kategori PPID</Label>
                  <select
                    id="docCategory"
                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                    value={docForm.category}
                    onChange={(e: any) =>
                      setDocForm({ ...docForm, category: e.target.value })
                    }
                  >
                    <option value="setiap-saat">
                      Setiap Saat (Selalu Tersedia)
                    </option>
                    <option value="berkala">Berkala (Rutin)</option>
                    <option value="serta-merta">Serta Merta (Darurat)</option>
                    <option value="dikecualikan">Dikecualikan (Rahasia)</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <Label htmlFor="docType">Jenis Dokumen</Label>
                  <Input
                    id="docType"
                    placeholder="Contoh: Undang-Undang"
                    value={docForm.type}
                    onChange={(e) =>
                      setDocForm({ ...docForm, type: e.target.value })
                    }
                    required
                  />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="docPublisher">Penerbit Regulasi</Label>
                  <Input
                    id="docPublisher"
                    placeholder="Contoh: Pemerintah RI / Kemenaker"
                    value={docForm.publisher}
                    onChange={(e) =>
                      setDocForm({ ...docForm, publisher: e.target.value })
                    }
                    required
                  />
                </div>
              </div>

              <div className="space-y-1">
                <Label htmlFor="docDesc">Deskripsi Singkat / Abstraksi</Label>
                <Textarea
                  id="docDesc"
                  placeholder="Masukkan deskripsi abstrak ringkas mengenai dokumen..."
                  value={docForm.description}
                  onChange={(e) =>
                    setDocForm({ ...docForm, description: e.target.value })
                  }
                  rows={2}
                />
              </div>

              {docForm.category !== "dikecualikan" && (
                <div className="space-y-1">
                  <Label>Unggah File Dokumen (PDF/Image)</Label>
                  <div className="relative flex cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed bg-slate-50 p-4">
                    <input
                      type="file"
                      accept=".pdf,image/*"
                      className="absolute inset-0 cursor-pointer opacity-0"
                      onChange={(e) => {
                        if (e.target.files && e.target.files[0]) {
                          setDocFile(e.target.files[0]);
                        }
                      }}
                      required={!selectedDoc}
                    />
                    <FileText className="mb-1 size-6 text-slate-400" />
                    <span className="text-xs font-semibold text-slate-700">
                      {docFile
                        ? docFile.name
                        : "Pilih file regulasi (Maksimal 20MB)"}
                    </span>
                  </div>
                </div>
              )}

              <div className="flex items-center space-x-2 pt-2">
                <input
                  type="checkbox"
                  id="docActive"
                  className="size-4 rounded-md border-slate-300 text-primary focus:ring-primary"
                  checked={docForm.isActive}
                  onChange={(e) =>
                    setDocForm({ ...docForm, isActive: e.target.checked })
                  }
                />
                <Label
                  htmlFor="docActive"
                  className="text-xs font-medium text-slate-700"
                >
                  Tampilkan dokumen di portal publik (Aktif)
                </Label>
              </div>
            </div>

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => setIsDocDialogOpen(false)}
              >
                Batal
              </Button>
              <Button
                type="submit"
                disabled={
                  createDocMutation.isPending || updateDocMutation.isPending
                }
              >
                {(createDocMutation.isPending ||
                  updateDocMutation.isPending) && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Simpan Dokumen
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ##################
// end authored
// ##################
