// ##################
// authored (generated by gemini, Jun 04 2026 00:40 WITA)
// ##################

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { trpc } from "@/utils/trpc";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { BookOpen, Calendar, Video } from "lucide-react";
import dayjs from "dayjs";
import { Pagination } from "./pagination";
import ImageWithFallback from "@/components/image-with-fallback";

interface WebinarTabProps {
  page: number;
  limit: number;
  onPageChange: (page: number) => void;
}

export function WebinarTab({ page, limit, onPageChange }: WebinarTabProps) {
  const { data, isLoading } = useQuery(
    trpc.pelatihan.enrollment.getUserEnrollmentsByType.queryOptions({
      type: "webinar",
      page,
      limit,
    }),
  );

  if (isLoading) {
    return (
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {[1, 2].map((i) => (
          <Card key={i} className="animate-pulse border-slate-100 shadow-sm">
            <div className="h-40 bg-slate-100" />
            <CardHeader className="space-y-2">
              <div className="h-4 w-3/4 rounded bg-slate-100" />
              <div className="h-4 w-1/2 rounded bg-slate-100" />
            </CardHeader>
          </Card>
        ))}
      </div>
    );
  }

  const enrollments = data?.data ?? [];
  const totalPages = data?.pagination?.totalPages ?? 0;

  if (enrollments.length === 0) {
    return (
      <div className="flex h-64 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 bg-white p-6 text-center">
        <div className="mb-4 rounded-full bg-blue-50 p-4">
          <BookOpen className="h-6 w-6 text-[#1061D6]" />
        </div>
        <p className="font-['Plus_Jakarta_Sans'] text-sm font-bold text-slate-800">
          Belum ada Webinar
        </p>
        <p className="mb-6 max-w-sm font-['Poppins'] text-xs text-slate-500">
          Anda belum terdaftar di Webinar manapun. Silakan lihat katalog
          pelatihan kami.
        </p>
        <Button
          className="rounded-xl bg-[#1061D6] font-bold text-white hover:bg-[#1061D6]/90"
          asChild
        >
          <Link to="/pelatihan">Jelajahi Katalog</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {enrollments.map((enrollment) => {
          const isUpcoming = enrollment.pelatihan.startDate
            ? dayjs().isBefore(dayjs(enrollment.pelatihan.startDate))
            : false;

          return (
            <Card
              key={enrollment.id}
              className="flex flex-col overflow-hidden border-slate-100 shadow-sm transition-all hover:border-[#1061D6]/10 hover:shadow-md"
            >
              <div className="relative h-40 shrink-0 bg-slate-50">
                <ImageWithFallback
                  src={enrollment.pelatihan.thumbnailUrl ?? ""}
                  alt={enrollment.pelatihan.title}
                  imgClassName="h-full w-full object-cover"
                />
              </div>
              <CardHeader className="pt-4 pb-3">
                <div className="mb-1 flex flex-wrap gap-1">
                  <span
                    className={`inline-flex items-center rounded-md px-2 py-0.5 text-[10px] font-bold tracking-wider uppercase ${
                      isUpcoming
                        ? "bg-blue-50 text-[#1061D6]"
                        : "bg-slate-100 text-slate-700"
                    }`}
                  >
                    {isUpcoming ? "Akan Datang" : "Selesai"}
                  </span>
                  {enrollment.verificationStatus === "pending" && (
                    <span className="inline-flex items-center rounded-md bg-amber-50 px-2 py-0.5 text-[10px] font-bold tracking-wider text-amber-700 uppercase">
                      Menunggu Verifikasi
                    </span>
                  )}
                  {enrollment.verificationStatus === "rejected" && (
                    <span className="inline-flex items-center rounded-md bg-rose-50 px-2 py-0.5 text-[10px] font-bold tracking-wider text-rose-700 uppercase">
                      Ditolak
                    </span>
                  )}
                </div>
                <CardTitle className="line-clamp-2 font-['Plus_Jakarta_Sans'] text-sm leading-tight font-bold text-slate-800">
                  {enrollment.pelatihan.title}
                </CardTitle>
                <CardDescription className="flex items-center gap-1 font-['Poppins'] text-[10px] font-semibold text-slate-400">
                  <Calendar className="h-3 w-3" /> Pelaksanaan:{" "}
                  {enrollment.pelatihan.startDate
                    ? dayjs(enrollment.pelatihan.startDate).format(
                        "DD MMM YYYY, HH:mm",
                      )
                    : "-"}
                </CardDescription>
              </CardHeader>
              {enrollment.verificationStatus === "rejected" &&
                enrollment.rejectionReason && (
                  <CardContent className="pb-3">
                    <p className="font-['Poppins'] text-[10px] font-medium text-rose-600">
                      Alasan penolakan: {enrollment.rejectionReason}
                    </p>
                  </CardContent>
                )}
              <CardFooter className="border-t border-slate-50 pt-3 pb-4">
                {enrollment.verificationStatus !== "verified" ? (
                  <Button
                    className="w-full rounded-xl font-bold"
                    variant="secondary"
                    disabled
                  >
                    {enrollment.verificationStatus === "pending"
                      ? "Menunggu Verifikasi Admin"
                      : "Pendaftaran Ditolak"}
                  </Button>
                ) : (
                  <Button
                    className="w-full rounded-xl bg-[#1061D6] font-bold text-white hover:bg-[#1061D6]/90"
                    asChild
                  >
                    <Link
                      to="/dashboard/pelatihan/$enrollmentId/materi"
                      params={{ enrollmentId: enrollment.id }}
                    >
                      <Video className="mr-1.5 h-4 w-4" />
                      Detail Webinar
                    </Link>
                  </Button>
                )}
              </CardFooter>
            </Card>
          );
        })}
      </div>

      <Pagination
        currentPage={page}
        totalPages={totalPages}
        onPageChange={onPageChange}
      />
    </div>
  );
}

// ##################
// end authored
// ##################
