import { createFileRoute } from "@tanstack/react-router";
import { trpc } from "@/utils/trpc";
import { useQuery } from "@tanstack/react-query";
import { z } from "zod";
import { pageHead } from "@/utils/page-head";
import { Download, Award, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";

// ##################
// authored (generated by antigravity, Jun 24 2026 21:35 WITA)
// ##################

export const Route = createFileRoute(
  "/(core)/pelatihan/sertifikat/$enrollmentId",
)({
  params: z.object({ enrollmentId: z.string().uuid() }),
  head: () => pageHead("Pelatihan - Sertifikat"),
  component: SertifikatComponent,
});

function SertifikatComponent() {
  const { enrollmentId } = Route.useParams();

  const { data: enrollment, isLoading } = useQuery(
    trpc.pelatihan.enrollment.getUserEnrollmentById.queryOptions({
      id: enrollmentId,
    }),
  );

  if (isLoading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="flex animate-pulse flex-col items-center gap-4">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
          <p className="text-muted-foreground">Memuat data sertifikat...</p>
        </div>
      </div>
    );
  }

  if (!enrollment) {
    return (
      <div className="p-8 text-center text-muted-foreground">
        Data pelatihan tidak ditemukan.
      </div>
    );
  }

  const isCompleted = enrollment.status === "completed";
  const hasCertificate = !!enrollment.certificateUrl;

  return (
    <div className="mx-auto max-w-4xl px-4 py-12 md:px-8">
      <div className="flex flex-col items-start gap-8 md:flex-row">
        <div className="flex-1 space-y-6">
          <div>
            <h1 className="mb-2 text-3xl font-bold tracking-tight">
              Sertifikat Pelatihan
            </h1>
            <p className="text-muted-foreground">
              {enrollment.pelatihan.title}
            </p>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div className="rounded-lg border bg-card p-4">
              <div className="mb-1 text-sm text-muted-foreground">
                Nama Peserta
              </div>
              <div className="font-medium">
                {enrollment.participantName || "Peserta"}
              </div>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <div className="mb-1 text-sm text-muted-foreground">
                Nilai Akhir
              </div>
              <div className="font-medium">
                {enrollment.finalScore !== null
                  ? enrollment.finalScore
                  : "Belum tersedia"}
              </div>
            </div>
          </div>

          {!isCompleted ? (
            <div className="flex flex-col items-center space-y-4 rounded-xl border bg-muted/50 p-6 text-center">
              <div className="rounded-full bg-background p-4">
                <Clock className="h-8 w-8 text-muted-foreground" />
              </div>
              <div>
                <h3 className="text-lg font-semibold">
                  Pelatihan Belum Selesai
                </h3>
                <p className="mt-1 text-muted-foreground">
                  Selesaikan seluruh materi dan ujian untuk mendapatkan
                  sertifikat.
                </p>
              </div>
            </div>
          ) : !hasCertificate ? (
            <div className="flex flex-col items-center space-y-4 rounded-xl border border-yellow-500/20 bg-yellow-500/10 p-6 text-center">
              <div className="rounded-full bg-background p-4">
                <Clock className="h-8 w-8 text-yellow-600" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-yellow-800 dark:text-yellow-400">
                  Sertifikat Sedang Diproses
                </h3>
                <p className="mt-1 max-w-md text-yellow-700/80 dark:text-yellow-400/80">
                  Selamat Anda telah menyelesaikan pelatihan ini. Sertifikat
                  Anda sedang dalam tahap verifikasi dan penerbitan oleh Admin.
                  Silakan periksa kembali secara berkala.
                </p>
              </div>
            </div>
          ) : (
            <div className="flex flex-col items-center space-y-4 rounded-xl border border-green-500/20 bg-green-500/10 p-6 text-center">
              <div className="rounded-full bg-background p-4 shadow-sm">
                <Award className="h-8 w-8 text-green-600" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-green-800 dark:text-green-400">
                  Sertifikat Tersedia
                </h3>
                <p className="mt-1 text-green-700/80 dark:text-green-400/80">
                  Sertifikat pelatihan Anda telah diterbitkan.
                </p>
              </div>
              <Button asChild size="lg" className="mt-4">
                <a
                  href={enrollment.certificateUrl || undefined}
                  target="_blank"
                  rel="noreferrer"
                >
                  <Download className="mr-2 h-4 w-4" />
                  Unduh Sertifikat
                </a>
              </Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
