import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { trpc } from "@/utils/trpc";
import { pageHead } from "@/utils/page-head";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { EnrollmentCard } from "./-components/enrollment-card";
import { OrderCard } from "./-components/order-card";
import { OrderListSkeleton } from "@/components/order-card-skeleton";
import z from "zod";

// ##################
// authored (generated by antigravity, Jun 24 2026 21:09 WITA)
// ##################

export const Route = createFileRoute("/(core)/pelatihan/transaksi")({
  validateSearch: z.object({
    tab: z.enum(["kelas", "transaksi"]).default("kelas"),
  }),
  head: () => pageHead("Pelatihan - Transaksi Saya"),
  component: RouteComponent,
});

function RouteComponent() {
  const { tab } = Route.useSearch();
  const navigate = Route.useNavigate();

  const { data: enrollments, isLoading: isLoadingEnrollments } = useQuery(
    trpc.pelatihan.enrollment.getUserEnrollments.queryOptions(),
  );

  const { data: orders, isLoading: isLoadingOrders } = useQuery(
    trpc.pelatihan.order.getUserOrders.queryOptions(),
  );

  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-0">
      {/* Header */}
      <div className="mb-6">
        <h1 className="mb-1 text-xl font-bold text-foreground sm:text-2xl">
          Pelatihan Saya
        </h1>
        <p className="text-sm text-muted-foreground">
          Kelola pelatihan dan pantau status transaksi Anda
        </p>
      </div>

      <Tabs
        value={tab}
        onValueChange={(value) => {
          navigate({
            to: "/pelatihan/transaksi",
            search: { tab: value as "kelas" | "transaksi" },
          });
        }}
        className="mb-6"
      >
        <div className="-mx-4 overflow-x-auto px-4 sm:mx-0 sm:px-0">
          <TabsList className="inline-flex w-max bg-white sm:w-auto">
            <TabsTrigger
              value="kelas"
              className="text-xs whitespace-nowrap data-[state=active]:bg-blue-500 data-[state=active]:text-white data-[state=active]:shadow-sm sm:text-sm"
            >
              Kelas Saya
            </TabsTrigger>
            <TabsTrigger
              value="transaksi"
              className="text-xs whitespace-nowrap data-[state=active]:bg-blue-500 data-[state=active]:text-white data-[state=active]:shadow-sm sm:text-sm"
            >
              Transaksi
            </TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value="kelas" className="mt-4">
          {isLoadingEnrollments ? (
            <OrderListSkeleton count={3} />
          ) : (
            <div className="flex flex-col gap-3">
              {!enrollments || enrollments.length === 0 ? (
                <div className="py-12 text-center text-muted-foreground">
                  Anda belum terdaftar di pelatihan manapun
                </div>
              ) : (
                enrollments.map((enrollment: any) => (
                  <EnrollmentCard key={enrollment.id} enrollment={enrollment} />
                ))
              )}
            </div>
          )}
        </TabsContent>

        <TabsContent value="transaksi" className="mt-4">
          {isLoadingOrders ? (
            <OrderListSkeleton count={3} />
          ) : (
            <div className="flex flex-col gap-3">
              {!orders || orders.length === 0 ? (
                <div className="py-12 text-center text-muted-foreground">
                  Tidak ada riwayat transaksi pelatihan
                </div>
              ) : (
                orders.map((order: any) => (
                  <OrderCard key={order.id} order={order} />
                ))
              )}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
