import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { trpc } from "@/utils/trpc";
import { pageHead } from "@/utils/page-head";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ChevronLeft, FileText } from "lucide-react";
import { format } from "date-fns";
import { toast } from "sonner";
import SingleImageUpload from "@/components/ui/single-image-upload";
import ImageWithFallback from "@/components/image-with-fallback";
import { useState } from "react";

// ##################
// authored (generated by antigravity, Jun 24 2026 21:10 WITA)
// ##################

export const Route = createFileRoute("/(core)/pelatihan/transaksi/$orderId")({
  head: () => pageHead("Pelatihan - Detail Transaksi"),
  component: RouteComponent,
});

const PELATIHAN_ORDER_STATUS_COLORS: Record<string, string> = {
  pending: "bg-yellow-100 text-yellow-700",
  waiting_payment: "bg-orange-100 text-orange-700",
  waiting_verification: "bg-blue-100 text-blue-700",
  verified: "bg-green-100 text-green-700",
  cancelled: "bg-gray-100 text-gray-700",
  expired: "bg-gray-100 text-gray-700",
  rejected: "bg-red-100 text-red-700",
};

const PELATIHAN_ORDER_STATUS_LABELS: Record<string, string> = {
  pending: "Pending",
  waiting_payment: "Menunggu Pembayaran",
  waiting_verification: "Menunggu Verifikasi",
  verified: "Terverifikasi",
  cancelled: "Dibatalkan",
  expired: "Kadaluarsa",
  rejected: "Ditolak",
};

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(amount);
}

function RouteComponent() {
  const { orderId } = Route.useParams();
  const navigate = Route.useNavigate();
  const queryClient = useQueryClient();
  const [file, setFile] = useState<File | null>(null);

  const { data: order, isLoading } = useQuery(
    trpc.pelatihan.order.getUserOrderById.queryOptions({ id: orderId }),
  );

  const uploadMutation = useMutation(
    trpc.pelatihan.order.uploadPaymentProof.mutationOptions({
      onSuccess: () => {
        toast.success("Bukti pembayaran berhasil diunggah");
        queryClient.invalidateQueries({
          queryKey: trpc.pelatihan.order.getUserOrderById.queryKey({
            id: orderId,
          }),
        });
      },
      onError: (error) => {
        toast.error(error.message || "Gagal mengunggah bukti pembayaran");
      },
    }),
  );

  if (isLoading) {
    return (
      <div className="p-8 text-center text-muted-foreground">
        Memuat detail transaksi...
      </div>
    );
  }

  if (!order) {
    return (
      <div className="p-8 text-center text-muted-foreground">
        Transaksi tidak ditemukan
      </div>
    );
  }

  const badgeColorClass =
    PELATIHAN_ORDER_STATUS_COLORS[order.status] || "bg-gray-200 text-gray-800";
  const badgeLabel =
    PELATIHAN_ORDER_STATUS_LABELS[order.status] || order.status;
  const canUpload =
    order.status === "waiting_payment" ||
    (order.status === "pending" && order.approvalStatus === "approved");

  return (
    <div className="mx-auto max-w-3xl px-4 pb-12 sm:px-0">
      <button
        onClick={() =>
          navigate({ to: "/pelatihan/transaksi", search: { tab: "transaksi" } })
        }
        className="mb-6 flex items-center text-sm font-medium text-muted-foreground hover:text-foreground"
      >
        <ChevronLeft className="mr-1 h-4 w-4" />
        Kembali ke Transaksi
      </button>

      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">
            Detail Transaksi
          </h1>
          <p className="text-sm text-muted-foreground">
            {order.orderNumber} •{" "}
            {format(new Date(order.createdAt), "dd MMMM yyyy HH:mm")}
          </p>
        </div>
        <Badge className={`w-fit border-0 ${badgeColorClass}`}>
          {badgeLabel}
        </Badge>
      </div>

      <div className="grid gap-6">
        <Card className="p-6">
          <h2 className="mb-4 text-lg font-semibold">Daftar Pelatihan</h2>
          <div className="space-y-4">
            {order.items.map((item: any) => (
              <div
                key={item.id}
                className="flex items-start gap-4 border-b border-border pb-4 last:border-0 last:pb-0"
              >
                {item.pelatihan.thumbnailUrl ? (
                  <ImageWithFallback
                    src={item.pelatihan.thumbnailUrl}
                    alt={item.pelatihan.title}
                    className="h-16 w-24 rounded-lg"
                    imgClassName="object-cover"
                  />
                ) : (
                  <div className="flex h-16 w-24 items-center justify-center rounded-lg bg-secondary">
                    <FileText className="h-6 w-6 text-muted-foreground" />
                  </div>
                )}
                <div className="flex-1">
                  <h3 className="font-medium">{item.pelatihan.title}</h3>
                  <p className="text-sm text-muted-foreground">
                    Level: {item.pelatihan.level} • {item.pelatihan.duration}{" "}
                    Menit
                  </p>
                  <p className="mt-1 font-semibold">
                    {formatCurrency(item.price)}
                  </p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-6 flex justify-between border-t border-border pt-4">
            <span className="font-semibold">Total Tagihan</span>
            <span className="text-lg font-bold text-blue-600">
              {formatCurrency(order.totalAmount)}
            </span>
          </div>
        </Card>

        {canUpload && (
          <Card className="border-blue-200 bg-blue-50/50 p-6">
            <h2 className="mb-2 text-lg font-semibold">
              Upload Bukti Pembayaran
            </h2>
            <p className="mb-4 text-sm text-muted-foreground">
              Silakan lakukan pembayaran sesuai nominal di atas dan unggah bukti
              transfer di bawah ini.
            </p>
            <div className="space-y-4">
              <SingleImageUpload
                value={file}
                onChange={setFile}
                maxSize={5 * 1024 * 1024}
              />
              <Button
                className="w-full"
                disabled={!file || uploadMutation.isPending}
                onClick={() => {
                  if (!file) return;
                  const formData = new FormData();
                  formData.append("orderId", order.id);
                  formData.append("file", file);
                  uploadMutation.mutate(formData);
                }}
              >
                {uploadMutation.isPending
                  ? "Mengunggah..."
                  : "Kirim Bukti Pembayaran"}
              </Button>
            </div>
          </Card>
        )}

        {order.paymentProofUrl && !canUpload && (
          <Card className="p-6">
            <h2 className="mb-4 text-lg font-semibold">Bukti Pembayaran</h2>
            <div className="relative aspect-[3/4] max-w-sm overflow-hidden rounded-lg border border-border">
              <ImageWithFallback
                src={order.paymentProofUrl}
                alt="Bukti Pembayaran"
                className="h-full w-full"
                imgClassName="object-contain"
              />
            </div>
          </Card>
        )}
      </div>
    </div>
  );
}
