// ##################
// authored (generated by gemini, Jun 02 2026 22:46 WITA)
// ##################

import { createFileRoute } from "@tanstack/react-router";
import { PelatihanKatalog } from "./-components/pelatihan-katalog";

export const Route = createFileRoute("/pelatihan/elearning")({
  component: RouteComponent,
});

function RouteComponent() {
  return <PelatihanKatalog type="elearning" title="E-Learning K3 Terpopuler" />;
}
