import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { trpc } from "@/utils/trpc";
import ImageWithFallback from "@/components/image-with-fallback";
import { Clock, ArrowRight, ChevronLeft, ChevronRight } from "lucide-react";
import { useState, useEffect, useRef, useMemo } from "react";
import { toast } from "sonner";
import { getPublicUrl } from "@/utils/url";

export const Route = createFileRoute("/pelatihan/")({
  component: RouteComponent,
});

// Interfaces matching backend Pelatihan schema
interface PelatihanItem {
  id: string;
  slug: string;
  title: string;
  description: string;
  shortDescription?: string | null;
  duration: number;
  capacity?: number | null;
  level: "beginner" | "intermediate" | "advanced";
  price: number;
  type: "elearning" | "bimtek" | "webinar";
  thumbnailUrl?: string | null;
  category?: {
    name: string;
  } | null;
}

function RouteComponent() {
  const navigate = useNavigate();
  const [currentSlide, setCurrentSlide] = useState(0);
  const slideInterval = useRef<NodeJS.Timeout | null>(null);

  // Fetch actual published K3 items from backend
  const { data: dbData, isLoading } = useQuery(
    trpc.pelatihan.base.getAllPelatihan.queryOptions({
      page: 1,
      perPage: 50,
      status: "published",
    }),
  );

  // Fetch dynamic landing page settings
  const { data: whyChooseUsSetting } = useQuery(
    trpc.platform.setting.getByKey.queryOptions({
      key: "landing.why_choose_us.image_url",
    }),
  );

  const { data: inHouseSetting } = useQuery(
    trpc.platform.setting.getByKey.queryOptions({
      key: "landing.in_house_training.image_url",
    }),
  );

  const { data: trainingSlidesSetting } = useQuery(
    trpc.platform.setting.getByKey.queryOptions({
      key: "pelatihan.hero.slides",
    }),
  );

  // Slide content for the Hero Carousel
  const heroSlides = useMemo(() => {
    try {
      if (trainingSlidesSetting?.value) {
        const parsed = JSON.parse(trainingSlidesSetting.value);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed.map((src) => getPublicUrl(src));
        }
      }
    } catch (e) {
      console.error(e);
    }
    return [
      "/assets/hero-banner.webp",
      "/assets/banner-auth.webp",
      "/assets/profile-banner.webp",
    ];
  }, [trainingSlidesSetting]);

  // Carousel auto-advance
  useEffect(() => {
    startSlideShow();
    return () => stopSlideShow();
  }, [heroSlides.length]);

  const startSlideShow = () => {
    stopSlideShow();
    if (heroSlides.length <= 1) return;
    slideInterval.current = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % heroSlides.length);
    }, 6000);
  };

  const stopSlideShow = () => {
    if (slideInterval.current) {
      clearInterval(slideInterval.current);
    }
  };

  const handlePrevSlide = () => {
    stopSlideShow();
    setCurrentSlide((prev) => (prev === 0 ? heroSlides.length - 1 : prev - 1));
    startSlideShow();
  };

  const handleNextSlide = () => {
    stopSlideShow();
    setCurrentSlide((prev) => (prev + 1) % heroSlides.length);
    startSlideShow();
  };

  // ##################
  // authored (generated by gemini, Jun 08 2026 20:26 WITA)
  // ##################
  // Group items by type (E-learning, Bimtek, Webinar) from database only.
  const getCategorizedItems = (
    type: "elearning" | "bimtek" | "webinar",
  ): PelatihanItem[] => {
    const fromDb =
      (dbData?.data as any[])?.filter((item) => item.type === type) || [];

    return fromDb.slice(0, 4).map((item: any) => ({
      id: item.id,
      slug: item.slug,
      title: item.title,
      description: item.description,
      shortDescription: item.shortDescription,
      duration: item.duration,
      capacity: item.capacity,
      level: item.level,
      price: item.price,
      type: item.type,
      thumbnailUrl: item.thumbnailUrl,
      category:
        item.category || (item.categoryId ? { name: "Sertifikasi K3" } : null),
    }));
  };
  // ##################
  // end authored
  // ##################

  const elearningItems = getCategorizedItems("elearning");
  const bimtekItems = getCategorizedItems("bimtek");
  const webinarItems = getCategorizedItems("webinar");

  const handleCardCta = (item: PelatihanItem) => {
    navigate({ to: `/pelatihan/${item.slug}` });
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900">
      {/* Background Subtle Grid Effect */}
      <div
        className="pointer-events-none fixed inset-0 z-0 opacity-[0.02]"
        style={{
          backgroundImage: "radial-gradient(#0056B3 1px, transparent 1px)",
          backgroundSize: "24px 24px",
        }}
      />

      <div className="relative z-10 flex flex-col">
        {/* Navigation Header */}
        <Navbar />

        {/* ================= HERO CAROUSEL BANNER SECTION ================= */}
        <section className="mx-auto w-full max-w-7xl px-4 py-8 md:py-12">
          <div
            className="group/carousel relative h-[180px] w-full overflow-hidden rounded-[2rem] bg-slate-900 shadow-2xl transition-all duration-300 sm:h-[280px] md:h-[380px] lg:h-[430px] xl:h-[450px]"
            onMouseEnter={stopSlideShow}
            onMouseLeave={startSlideShow}
          >
            {/* Carousel Slides with Cross-Fade */}
            {heroSlides.map((slideSrc, index) => (
              <div
                key={index}
                className={`absolute inset-0 transition-opacity duration-700 ease-in-out ${
                  currentSlide === index ? "z-10 opacity-100" : "z-0 opacity-0"
                }`}
              >
                <ImageWithFallback
                  src={slideSrc}
                  alt={`Slide Banner Pelatihan ${index + 1}`}
                  className="h-full w-full object-cover"
                />
              </div>
            ))}

            {/* Slider Arrow Controls (Only show if multiple slides exist) */}
            {heroSlides.length > 1 && (
              <>
                <button
                  className="absolute top-1/2 left-4 z-20 flex h-10 w-10 -translate-y-1/2 cursor-pointer items-center justify-center rounded-full border border-white/20 bg-black/30 text-white opacity-0 backdrop-blur-xs transition group-hover/carousel:opacity-100 hover:bg-black/50 active:scale-95"
                  onClick={handlePrevSlide}
                  aria-label="Slide sebelumnya"
                >
                  <ChevronLeft className="h-6 w-6" />
                </button>
                <button
                  className="absolute top-1/2 right-4 z-20 flex h-10 w-10 -translate-y-1/2 cursor-pointer items-center justify-center rounded-full border border-white/20 bg-black/30 text-white opacity-0 backdrop-blur-xs transition group-hover/carousel:opacity-100 hover:bg-black/50 active:scale-95"
                  onClick={handleNextSlide}
                  aria-label="Slide berikutnya"
                >
                  <ChevronRight className="h-6 w-6" />
                </button>
              </>
            )}

            {/* Indicator Dots (Only show if multiple slides exist) */}
            {heroSlides.length > 1 && (
              <div className="absolute bottom-4 left-1/2 z-20 flex -translate-x-1/2 items-center gap-2 rounded-full bg-black/20 px-3 py-1.5 backdrop-blur-xs">
                {heroSlides.map((_, index) => (
                  <button
                    key={index}
                    className={`h-2.5 cursor-pointer rounded-full transition-all duration-300 ${
                      currentSlide === index
                        ? "w-8 bg-amber-500"
                        : "w-2.5 bg-white/40"
                    }`}
                    onClick={() => {
                      stopSlideShow();
                      setCurrentSlide(index);
                      startSlideShow();
                    }}
                    aria-label={`Pindah ke slide ${index + 1}`}
                  />
                ))}
              </div>
            )}
          </div>
        </section>

        {/* ================= "KENAPA MEMILIH KAMI?" SECTION ================= */}
        <section className="mx-auto w-full max-w-7xl px-4 py-12 md:py-16">
          <div className="grid items-center gap-12 lg:grid-cols-12">
            {/* Left: Key advantages list */}
            <div className="space-y-8 lg:col-span-7">
              <div className="space-y-4">
                <div className="flex items-center gap-2.5">
                  <div className="h-3.5 w-3.5 shrink-0 bg-gradient-to-r from-[#1061D6] to-[#78E275]" />
                  <span className="font-poppins text-xl font-semibold tracking-wide text-[#1061D6]">
                    Keunggulan kami
                  </span>
                </div>
                <h2 className="font-poppins text-4xl font-extrabold tracking-tight text-[#1061D6] sm:text-5xl">
                  Kenapa Memilih Kami?
                </h2>
                <div className="h-[7px] w-full bg-gradient-to-r from-[#1061D6] via-[#78E275] to-transparent" />
              </div>

              <div className="space-y-8">
                {/* Advantage Item 1 */}
                <div className="flex items-start gap-5">
                  <div className="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-r from-[#1061D6] to-[#78E275] shadow-xs">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="4"
                      stroke="currentColor"
                      className="h-5 w-5 text-white"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="m4.5 12.75 6 6 9-13.5"
                      />
                    </svg>
                  </div>
                  <div className="space-y-1">
                    <h3 className="font-poppins text-2xl font-bold text-[#1061D6]">
                      Instruktur Bersertifikasi
                    </h3>
                    <p className="text-lg leading-relaxed font-medium text-[#4D4D4D]">
                      Dilatih langsung oleh para praktisi dan asesor K3
                      profesional.
                    </p>
                  </div>
                </div>

                {/* Advantage Item 2 */}
                <div className="flex items-start gap-5">
                  <div className="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-r from-[#1061D6] to-[#78E275] shadow-xs">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="4"
                      stroke="currentColor"
                      className="h-5 w-5 text-white"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="m4.5 12.75 6 6 9-13.5"
                      />
                    </svg>
                  </div>
                  <div className="space-y-1">
                    <h3 className="font-poppins text-2xl font-bold text-[#1061D6]">
                      Sertifikasi Resmi BNSP
                    </h3>
                    <p className="text-lg leading-relaxed font-medium text-[#4D4D4D]">
                      Sertifikat yang diterbitkan diakui secara nasional oleh
                      Kemnaker RI dan BNSP.
                    </p>
                  </div>
                </div>

                {/* Advantage Item 3 */}
                <div className="flex items-start gap-5">
                  <div className="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-r from-[#1061D6] to-[#78E275] shadow-xs">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="4"
                      stroke="currentColor"
                      className="h-5 w-5 text-white"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="m4.5 12.75 6 6 9-13.5"
                      />
                    </svg>
                  </div>
                  <div className="space-y-1">
                    <h3 className="font-poppins text-2xl font-bold text-[#1061D6]">
                      Metode Belajar Fleksibel
                    </h3>
                    <p className="text-lg leading-relaxed font-medium text-[#4D4D4D]">
                      Pilihan metode pelatihan secara Offline (Tatap Muka),
                      Online (Daring), maupun Blended Learning sesuai kebutuhan.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Right: Custom Figma Talent Image with Floating Gears Layout */}
            {/* authored (generated by gemini, Jun 15 2026 01:35 WITA) */}
            <div className="relative flex w-full items-center justify-center lg:col-span-5">
              <div className="relative aspect-[571/662] w-full max-w-[571px] select-none">
                {/* Floating Gear 1 (Top-Left, Smaller) */}
                <ImageWithFallback
                  src="/assets/gear_k3.png"
                  alt="Floating K3 Gear"
                  className="pointer-events-none absolute top-[12%] left-[7%] z-20 aspect-square w-[24.5%] overflow-visible rounded-none"
                  imgClassName="object-contain"
                  style={{
                    filter: "blur(2px)",
                    animation: "spin 25s linear infinite",
                  }}
                />

                {/* Main GAMBAR TALENT Container */}
                <div className="absolute top-0 left-[2.4%] z-10 h-[89%] w-[96.3%]">
                  <div className="relative h-full w-full">
                    {/* Blue Background Shape */}
                    <ImageWithFallback
                      src="/assets/talent_bg.png"
                      alt="Background Blue Shape"
                      className="pointer-events-none absolute right-0 bottom-0 h-[443.65px] max-h-[75%] w-[527.44px] max-w-full overflow-visible rounded-none md:max-h-none"
                      imgClassName="object-contain"
                    />

                    {/* Front Image */}
                    <div className="absolute bottom-17 left-[15%] h-[78%] w-[65%] overflow-hidden rounded-tl-[140px] rounded-tr-none rounded-br-none rounded-bl-[155px]">
                      <ImageWithFallback
                        src={
                          whyChooseUsSetting?.value
                            ? getPublicUrl(whyChooseUsSetting.value)
                            : "/assets/talent_new.png"
                        }
                        alt="Talent K3 Profesional"
                        className="h-full w-full scale-x-[-1] object-cover"
                      />
                    </div>
                  </div>
                </div>

                {/* Floating Gear 2 (Bottom-Right, Larger) */}
                <ImageWithFallback
                  src="/assets/gear_k3.png"
                  alt="Floating K3 Gear"
                  className="pointer-events-none absolute top-[59%] left-[54%] z-20 aspect-square w-[39%] overflow-visible rounded-none"
                  imgClassName="object-contain"
                  style={{
                    filter: "blur(3px)",
                    animation: "spin 35s linear infinite reverse",
                  }}
                />
              </div>
            </div>
          </div>
        </section>

        {/* ================= E-LEARNING K3 CATALOG ROW ================= */}
        <section
          id="elearning-section"
          className="w-full bg-[#3A86F4] py-16 text-white"
        >
          <div className="mx-auto w-full max-w-7xl px-4 md:px-6">
            {/* Header Area */}
            <div className="mb-10 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <div className="h-3.5 w-3.5 shrink-0 bg-gradient-to-r from-[#1061D6] to-[#78E275]" />
                <h2 className="font-poppins text-3xl font-extrabold tracking-tight text-[#F8FAFC]">
                  E-learning K3
                </h2>
              </div>
              <Link
                to="/pelatihan/elearning"
                className="flex items-center gap-2 rounded-xl border border-[#AFCFFA] bg-white px-6 py-2.5 text-sm font-bold text-[#1061D6] shadow-[0_0_100px_-2px_rgba(16,97,214,0.14)] transition-all hover:scale-[1.02] hover:bg-slate-50 active:scale-[0.98]"
              >
                Lihat semua
                <ArrowRight className="h-4 w-4 text-[#1061D6]" />
              </Link>
            </div>

            {/* E-Learning Grid */}
            <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {isLoading
                ? Array.from({ length: 4 }).map((_, i) => (
                    <div
                      key={i}
                      className="animate-pulse space-y-4 rounded-2xl bg-white/10 p-4"
                    >
                      <div className="aspect-video w-full rounded-xl bg-white/20" />
                      <div className="h-4 w-2/3 rounded-sm bg-white/20" />
                      <div className="h-6 w-full rounded-sm bg-white/20" />
                      <div className="h-4 w-1/3 rounded-sm bg-white/20" />
                    </div>
                  ))
                : elearningItems.map((item) => (
                    <div
                      key={item.id}
                      className="group flex flex-col overflow-hidden rounded-[1.25rem] border border-transparent bg-white shadow-lg transition-all duration-300 hover:-translate-y-1.5 hover:shadow-2xl"
                    >
                      {/* Thumbnail Header */}
                      <div className="relative h-[205px] w-full overflow-hidden bg-slate-100">
                        <ImageWithFallback
                          src={item.thumbnailUrl ?? "/assets/pelatihan.webp"}
                          alt={item.title}
                          className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                        />
                        <div className="absolute top-3 left-3 rounded-lg bg-[#22C55E] px-3 py-1 text-[10px] font-bold tracking-wider text-white uppercase shadow-md">
                          HSE PROGRAM
                        </div>
                      </div>

                      {/* Card Content body */}
                      <div className="flex flex-1 flex-col space-y-4 p-5 text-slate-800">
                        <h3 className="font-poppins line-clamp-2 min-h-[44px] text-base leading-tight font-bold text-[#000000] transition-colors group-hover:text-[#1061D6]">
                          {item.title}
                        </h3>

                        {/* Clock / Registered Date Area */}
                        <div className="mt-1 flex items-center gap-1.5 text-xs font-semibold text-[#4D4D4D]">
                          <Clock className="h-4 w-4 text-[#4D4D4D]" />
                          <span>Terdaftar : 2 juni 2026</span>
                        </div>

                        {/* Pricing and Button */}
                        <div className="mt-auto space-y-4 pt-2">
                          <div className="space-y-0.5">
                            <p className="text-[10px] font-bold tracking-wider text-slate-400 uppercase">
                              Harga Mulai
                            </p>
                            <p className="font-poppins text-xl font-extrabold text-[#1061D6]">
                              {item.price === 0 ? (
                                <span className="font-bold text-emerald-600">
                                  Gratis
                                </span>
                              ) : (
                                `Rp ${item.price.toLocaleString("id-ID")}`
                              )}
                            </p>
                          </div>
                          <button
                            className="flex h-10 w-full items-center justify-center rounded-xl border-2 border-[#AFCFFA] bg-white text-sm font-semibold text-[#4D4D4D] shadow-[0_0_100px_-2px_rgba(16,97,214,0.14)] transition-all hover:scale-[1.02] hover:bg-slate-50 active:scale-[0.98]"
                            onClick={() => handleCardCta(item)}
                          >
                            Detail Pelatihan
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
            </div>
          </div>
        </section>

        {/* ================= BIMTEK K3 CATALOG ROW ================= */}
        <section id="bimtek-section" className="w-full bg-white py-16">
          <div className="mx-auto w-full max-w-7xl px-4 md:px-6">
            {/* Header Area */}
            <div className="mb-10 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <div className="h-3.5 w-3.5 shrink-0 bg-gradient-to-r from-[#1061D6] to-[#78E275]" />
                <h2 className="font-poppins text-3xl font-bold tracking-tight text-[#1061D6]">
                  Bimtek K3
                </h2>
              </div>
              <Link
                to="/pelatihan/bimtek"
                className="flex items-center gap-2 rounded-xl border border-[#AFCFFA] bg-white px-6 py-2.5 text-sm font-bold text-[#1061D6] shadow-[0_4px_12px_rgba(16,97,214,0.04)] transition-all hover:scale-[1.02] hover:bg-slate-50 active:scale-[0.98]"
              >
                Lihat semua
                <ArrowRight className="h-4 w-4 text-[#1061D6]" />
              </Link>
            </div>

            {/* Bimtek Grid */}
            <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {isLoading
                ? Array.from({ length: 4 }).map((_, i) => (
                    <div
                      key={i}
                      className="animate-pulse space-y-4 rounded-[1.25rem] border bg-white p-4"
                    >
                      <div className="aspect-video w-full rounded-xl bg-slate-200" />
                      <div className="h-4 w-2/3 rounded-sm bg-slate-200" />
                      <div className="h-6 w-full rounded-sm bg-slate-200" />
                      <div className="h-4 w-1/3 rounded-sm bg-slate-200" />
                    </div>
                  ))
                : bimtekItems.map((item) => (
                    <div
                      key={item.id}
                      className="group flex flex-col overflow-hidden rounded-[1.25rem] border border-slate-100 bg-white shadow-xs transition-all duration-300 hover:-translate-y-1.5 hover:border-blue-100 hover:shadow-xl"
                    >
                      {/* Thumbnail Header */}
                      <div className="relative h-[205px] w-full overflow-hidden bg-slate-100">
                        <ImageWithFallback
                          src={item.thumbnailUrl ?? "/assets/pelatihan.webp"}
                          alt={item.title}
                          className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                        />
                        <div className="absolute top-3 left-3 rounded-lg bg-[#22C55E] px-3 py-1 text-[10px] font-bold tracking-wider text-white uppercase shadow-md">
                          HSE PROGRAM
                        </div>
                      </div>

                      {/* Card Content body */}
                      <div className="flex flex-1 flex-col space-y-4 p-5 text-slate-800">
                        <h3 className="font-poppins line-clamp-2 min-h-[44px] text-base leading-tight font-bold text-[#000000] transition-colors group-hover:text-[#1061D6]">
                          {item.title}
                        </h3>

                        {/* Clock / Registered Date Area */}
                        <div className="mt-1 flex items-center gap-1.5 text-xs font-semibold text-[#4D4D4D]">
                          <Clock className="h-4 w-4 text-[#4D4D4D]" />
                          <span>Terdaftar : 2 juni 2026</span>
                        </div>

                        {/* Pricing and Button */}
                        <div className="mt-auto space-y-4 pt-2">
                          <div className="space-y-0.5">
                            <p className="text-[10px] font-bold tracking-wider text-slate-400 uppercase">
                              Harga Mulai
                            </p>
                            <p className="font-poppins text-xl font-extrabold text-[#1061D6]">
                              {item.price === 0 ? (
                                <span className="font-bold text-emerald-600">
                                  Gratis
                                </span>
                              ) : (
                                `Rp ${item.price.toLocaleString("id-ID")}`
                              )}
                            </p>
                          </div>
                          <button
                            className="flex h-10 w-full items-center justify-center rounded-xl border border-[#AFCFFA] bg-white text-sm font-semibold text-[#4D4D4D] shadow-[0_4px_12px_rgba(16,97,214,0.06)] transition-all hover:scale-[1.02] hover:bg-slate-50 active:scale-[0.98]"
                            onClick={() => handleCardCta(item)}
                          >
                            Detail Pelatihan
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
            </div>
          </div>
        </section>

        {/* ================= WEBINAR CATALOG ROW ================= */}
        <section
          id="webinar-section"
          className="w-full bg-[#3A86F4] py-16 text-white"
        >
          <div className="mx-auto w-full max-w-7xl px-4 md:px-6">
            {/* Header Area */}
            <div className="mb-10 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <div className="h-3.5 w-3.5 shrink-0 bg-gradient-to-r from-[#1061D6] to-[#78E275]" />
                <h2 className="font-poppins text-3xl font-bold tracking-tight text-[#F8FAFC]">
                  Webinar
                </h2>
              </div>
              <Link
                to="/pelatihan/webinar"
                className="flex items-center gap-2 rounded-xl border border-[#AFCFFA] bg-white px-6 py-2.5 text-sm font-bold text-[#1061D6] shadow-[0_0_100px_-2px_rgba(16,97,214,0.14)] transition-all hover:scale-[1.02] hover:bg-slate-50 active:scale-[0.98]"
              >
                Lihat semua
                <ArrowRight className="h-4 w-4 text-[#1061D6]" />
              </Link>
            </div>

            {/* Webinar Grid */}
            <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {isLoading
                ? Array.from({ length: 4 }).map((_, i) => (
                    <div
                      key={i}
                      className="animate-pulse space-y-4 rounded-[1.25rem] bg-white/10 p-4"
                    >
                      <div className="aspect-video w-full rounded-xl bg-white/20" />
                      <div className="h-4 w-2/3 rounded-sm bg-white/20" />
                      <div className="h-6 w-full rounded-sm bg-white/20" />
                      <div className="h-4 w-1/3 rounded-sm bg-white/20" />
                    </div>
                  ))
                : webinarItems.map((item) => (
                    <div
                      key={item.id}
                      className="group flex flex-col overflow-hidden rounded-[1.25rem] border border-transparent bg-white shadow-lg transition-all duration-300 hover:-translate-y-1.5 hover:shadow-2xl"
                    >
                      {/* Thumbnail Header */}
                      <div className="relative h-[205px] w-full overflow-hidden bg-slate-100">
                        <ImageWithFallback
                          src={item.thumbnailUrl ?? "/assets/pelatihan.webp"}
                          alt={item.title}
                          className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                        />
                        <div className="absolute top-3 left-3 rounded-lg bg-[#22C55E] px-3 py-1 text-[10px] font-bold tracking-wider text-white uppercase shadow-md">
                          HSE PROGRAM
                        </div>
                      </div>

                      {/* Card Content body */}
                      <div className="flex flex-1 flex-col space-y-4 p-5 text-slate-800">
                        <h3 className="font-poppins line-clamp-2 min-h-[44px] text-base leading-tight font-bold text-[#000000] transition-colors group-hover:text-[#1061D6]">
                          {item.title}
                        </h3>

                        {/* Clock / Registered Date Area */}
                        <div className="mt-1 flex items-center gap-1.5 text-xs font-semibold text-[#4D4D4D]">
                          <Clock className="h-4 w-4 text-[#4D4D4D]" />
                          <span>Terdaftar : 2 juni 2026</span>
                        </div>

                        {/* Pricing and Button */}
                        <div className="mt-auto space-y-4 pt-2">
                          <div className="space-y-0.5">
                            <p className="text-[10px] font-bold tracking-wider text-slate-400 uppercase">
                              Harga Mulai
                            </p>
                            <p className="font-poppins text-xl font-extrabold text-[#1061D6]">
                              {item.price === 0 ? (
                                <span className="font-bold text-emerald-600">
                                  Gratis
                                </span>
                              ) : (
                                `Rp ${item.price.toLocaleString("id-ID")}`
                              )}
                            </p>
                          </div>
                          <button
                            className="flex h-10 w-full items-center justify-center rounded-xl border border-[#AFCFFA] bg-white text-sm font-semibold text-[#4D4D4D] shadow-[0_0_100px_-2px_rgba(16,97,214,0.14)] transition-all hover:scale-[1.02] hover:bg-slate-50 active:scale-[0.98]"
                            onClick={() => handleCardCta(item)}
                          >
                            Detail Pelatihan
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
            </div>
          </div>
        </section>

        {/* ================= IN-HOUSE TRAINING BANNER ================= */}
        <section
          id="inhouse-banner"
          className="mx-auto w-full max-w-7xl px-4 py-12 md:py-16"
        >
          <div className="relative flex min-h-[480px] flex-col items-stretch justify-between overflow-hidden rounded-[2rem] bg-[#3A86F4] text-white shadow-2xl md:flex-row">
            {/* Background Logo Watermark */}
            <ImageWithFallback
              src="/assets/logo-watermark.png"
              alt="Logo Watermark"
              className="pointer-events-none absolute top-[-32px] left-[-27px] h-[584px] w-[618px] overflow-visible rounded-none opacity-20 mix-blend-overlay select-none"
              imgClassName="object-contain"
            />

            {/* Content Left Column */}
            <div className="relative z-10 flex flex-col justify-center gap-6 px-6 py-12 sm:px-12 md:w-[55%] md:py-16 md:pl-16">
              <h2
                className="font-poppins text-4xl leading-tight font-extrabold tracking-tight text-white sm:text-5xl"
                style={{
                  fontFamily: "Plus Jakarta Sans",
                  fontWeight: 800,
                }}
              >
                Butuh In-House
                <br />
                Training Untuk
                <br />
                Perusahaan?
              </h2>
              <p className="font-poppins max-w-[544px] text-lg leading-relaxed font-normal text-white/80 sm:text-xl">
                Kami menyediakan paket pelatihan khusus sesuai dengan kebutuhan
                spesifik industri dan perusahaan Anda. Dapatkan penawaran harga
                kompetitif untuk grup besar.
              </p>

              <div className="flex flex-wrap items-center gap-4 pt-4">
                <button
                  className="font-poppins inline-flex h-14 cursor-pointer items-center justify-center rounded-xl border-none bg-white px-8 py-4 text-base font-semibold tracking-tight text-[#0EA5E9] shadow-md transition-all hover:scale-[1.02] hover:bg-slate-50 active:scale-[0.98]"
                  onClick={() => {
                    toast.success(
                      "Membuka jalur konsultasi tim program korporat Balai K3 Samarinda via WhatsApp...",
                    );
                    window.open(
                      "https://wa.me/628115551234?text=Halo%20Balai%20K3%20Samarinda,%20perusahaan%20kami%20tertarik%20mengadakan%20In-House%20Training",
                      "_blank",
                    );
                  }}
                >
                  Hubungi Corporate Sales
                </button>
                <button
                  className="inline-flex h-14 cursor-pointer items-center justify-center gap-2 rounded-xl border-none bg-[#F97316] px-8 py-4 shadow-md transition-all hover:scale-[1.02] hover:bg-orange-600 active:scale-[0.98]"
                  onClick={() => {
                    toast.success(
                      "Memulai pengunduhan katalog brosur program pelatihan K3 2026...",
                    );
                  }}
                >
                  <span className="font-poppins text-base font-semibold tracking-tight text-white">
                    Download Brosur
                  </span>
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M8 11.575C7.86667 11.575 7.74167 11.5542 7.625 11.5125C7.50833 11.4708 7.4 11.4 7.3 11.3L3.7 7.7C3.5 7.5 3.40417 7.26667 3.4125 7C3.42083 6.73333 3.51667 6.5 3.7 6.3C3.9 6.1 4.1375 5.99583 4.4125 5.9875C4.6875 5.97917 4.925 6.075 5.125 6.275L7 8.15V1C7 0.716667 7.09583 0.479167 7.2875 0.2875C7.47917 0.0958333 7.71667 0 8 0C8.28333 0 8.52083 0.0958333 8.7125 0.2875C8.90417 0.479167 9 0.716667 9 1V8.15L10.875 6.275C11.075 6.075 11.3125 5.97917 11.5875 5.9875C11.8625 5.99583 12.1 6.1 12.3 6.3C12.4833 6.5 12.5792 6.73333 12.5875 7C12.5958 7.26667 12.5 7.5 12.3 7.7L8.7 11.3C8.6 11.4 8.49167 11.4708 8.375 11.5125C8.25833 11.5542 8.13333 11.575 8 11.575ZM2 16C1.45 16 0.979167 15.8042 0.5875 15.4125C0.195833 15.0208 0 14.55 0 14V12C0 11.7167 0.0958333 11.4792 0.2875 11.2875C0.479167 11.0958 0.716667 11 1 11C1.28333 11 1.52083 11.0958 1.7125 11.2875C1.90417 11.4792 2 11.7167 2 12V14H14V12C14 11.7167 14.0958 11.4792 14.2875 11.2875C14.4792 11.0958 14.7167 11 15 11C15.2833 11 15.5208 11.0958 15.7125 11.2875C15.9042 11.4792 16 11.7167 16 12V14C16 14.55 15.8042 15.0208 15.4125 15.4125C15.0208 15.8042 14.55 16 14 16H2Z"
                      fill="white"
                    />
                  </svg>
                </button>
              </div>
            </div>

            {/* Banner Right Image Column */}
            <div className="relative z-10 mt-6 flex items-end justify-center px-6 md:mt-0 md:w-[45%] md:justify-end md:px-0">
              <div className="h-[280px] w-full max-w-[450px] overflow-visible sm:h-[350px] md:absolute md:right-[32px] md:bottom-0 md:h-[450px] md:max-w-none">
                <ImageWithFallback
                  src={
                    inHouseSetting?.value
                      ? getPublicUrl(inHouseSetting.value)
                      : "/assets/in_house_new.png"
                  }
                  alt="In-House Training"
                  className="h-full w-full object-contain object-bottom select-none"
                />
              </div>
            </div>
          </div>
          {/* ################## */}
          {/* end authored */}
          {/* ################## */}
        </section>

        {/* ================= GLOBAL PREMIUM FOOTER ================= */}
        <Footer />
      </div>
    </div>
  );
}

// ##################
// end authored
// ##################
