import { protectedProcedure, createTRPCRouter, withPermission } from "../..";
import { runEffect } from "../../utils/run-effect";
import { z } from "zod";
import {
  createPelatihanAssessmentSchema,
  updatePelatihanAssessmentSchema,
  addQuestionSchema,
} from "@tepian-k3/schema/pelatihan/pelatihan.schema";

// ##################
// authored (generated by gemini, Jun 08 2026 19:43 WITA)
// ##################
/**
 * Router tRPC untuk mengelola data assessment (ujian/kuis) pelatihan.
 * Menyediakan prosedur untuk mengambil assessment, memulai attempt, submit jawaban,
 * serta manajemen CRUD assessment dan question (khusus admin).
 */
export const assessmentRouter = createTRPCRouter({
  getAssessmentByPelatihan: protectedProcedure
    .input(
      z.object({
        pelatihanId: z.string().uuid(),
        type: z.enum(["pre_test", "post_test"]),
      }),
    )
    .query(async ({ input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.getAssessmentByPelatihan(
          input.pelatihanId,
          input.type,
        ),
      );
    }),

  getAssessmentById: protectedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(assessmentQueries.getAssessmentById(input.id));
    }),

  startAttempt: protectedProcedure
    .input(
      z.object({
        enrollmentId: z.string().uuid(),
        assessmentId: z.string().uuid(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.startAttempt(
          input.enrollmentId,
          input.assessmentId,
          ctx.user.id,
        ),
      );
    }),

  submitAttempt: protectedProcedure
    .input(
      z.object({
        attemptId: z.string().uuid(),
        answers: z.record(z.string().uuid(), z.string().uuid().or(z.string())),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.submitAttempt(
          input.attemptId,
          input.answers,
          ctx.user.id,
        ),
      );
    }),

  getAssessmentsByPelatihanId: protectedProcedure
    .input(
      z.object({
        pelatihanId: z.string().uuid(),
        enrollmentId: z.string().uuid(),
      }),
    )
    .query(async ({ input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.getAssessmentsByPelatihanId(
          input.pelatihanId,
          input.enrollmentId,
        ),
      );
    }),

  createAssessment: withPermission("pelatihan.create")
    .input(createPelatihanAssessmentSchema)
    .mutation(async ({ ctx, input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.createAssessment(ctx.user.id, input),
      );
    }),

  updateAssessment: withPermission("pelatihan.update")
    .input(updatePelatihanAssessmentSchema)
    .mutation(async ({ ctx, input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.updateAssessment(ctx.user.id, input),
      );
    }),

  deleteAssessment: withPermission("pelatihan.delete")
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.deleteAssessment(ctx.user.id, input.id),
      );
    }),

  addQuestion: withPermission("pelatihan.create")
    .input(addQuestionSchema)
    .mutation(async ({ ctx, input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.addQuestion(ctx.user.id, input),
      );
    }),

  deleteQuestion: withPermission("pelatihan.delete")
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      const assessmentQueries =
        await import("@tepian-k3/queries/pelatihan/assessment.queries").then(
          (m) => m.default,
        );
      return await runEffect(
        assessmentQueries.deleteQuestion(ctx.user.id, input.id),
      );
    }),
});
// ##################
// end authored
// ##################
