import pelatihanQueries from "@tepian-k3/queries/pelatihan/pelatihan.queries";
import pelatihanSchema from "@tepian-k3/schema/pelatihan/pelatihan.schema";
import { z } from "zod";
import { createTRPCRouter, publicProcedure, withPermission, formDataInput, formDataProcedure } from "../..";
import { runEffect } from "../../utils/run-effect";

export const pelatihanBaseRouter = createTRPCRouter({
  getAllPelatihan: publicProcedure
    .input(pelatihanSchema.getAllPelatihanSchema)
    .query(async ({ input }) => {
      return await runEffect(pelatihanQueries.getAllPelatihan(input));
    }),

  getPelatihanBySlug: publicProcedure
    .input(z.object({ slug: z.string() }))
    .query(async ({ input }) => {
      return await runEffect(pelatihanQueries.getPelatihanBySlug(input.slug));
    }),

  getPelatihanById: publicProcedure
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ input }) => {
      return await runEffect(pelatihanQueries.getPelatihanById(input.id));
    }),

  createPelatihan: withPermission("pelatihan.create")
    .input(pelatihanSchema.createPelatihanSchema)
    .mutation(async ({ input, ctx }) => {
      return await runEffect(
        pelatihanQueries.createPelatihan(ctx.user.id, input),
      );
    }),

  updatePelatihan: withPermission("pelatihan.update")
    .input(pelatihanSchema.updatePelatihanSchema)
    .mutation(async ({ input, ctx }) => {
      const { id, ...data } = input;
      return await runEffect(
        pelatihanQueries.updatePelatihan(ctx.user.id, id, data),
      );
    }),

  deletePelatihan: withPermission("pelatihan.delete")
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ input, ctx }) => {
      return await runEffect(
        pelatihanQueries.deletePelatihan(ctx.user.id, input.id),
      );
    }),

  getDashboardStats: withPermission("pelatihan.view").query(async () => {
    return await runEffect(pelatihanQueries.getDashboardStats());
  }),

  getPelatihanStats: withPermission("pelatihan.view")
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ input }) => {
      // ##################
      // authored (generated by gemini, Jun 09 2026 18:20 WITA)
      // ##################
      return await runEffect(pelatihanQueries.getPelatihanStats(input.id));
      // ##################
      // end authored
      // ##################
    }),

  getAllCategories: publicProcedure.query(async () => {
    return await runEffect(pelatihanQueries.getAllCategories());
  }),

  uploadThumbnail: withPermission("pelatihan.create")
    .input(formDataInput)
    .use(
      formDataProcedure(
        z.object({
          file: z
            .file()
            .max(5 * 1024 * 1024)
            .mime(["image/jpeg", "image/png", "image/webp"]),
        })
      )
    )
    .mutation(async ({ ctx }) => {
      const { processAndUploadImage } = await import("../../utils/image-upload");
      const { Effect } = await import("effect");
      return await runEffect(
        Effect.gen(function* () {
          const uploadedFile = yield* processAndUploadImage(
            ctx.input.data.file,
            { folder: "pelatihan" }
          );
          return { key: uploadedFile.key };
        })
      );
    }),
});
