// ##################
// authored (generated by gemini, Jun 04 2026 11:35 WITA)
// ##################

import { z } from "zod";
import { Effect } from "effect";
import {
  createTRPCRouter,
  protectedProcedure,
  formDataInput,
  formDataProcedure,
} from "../..";
import { runEffect } from "../../utils/run-effect";
import { upsertProfileSchema } from "@tepian-k3/schema/pelatihan/profile.schema";
import { submitRegistrationRequirementsSchema } from "@tepian-k3/schema/pelatihan/pelatihan.schema";
import profileQueries from "@tepian-k3/queries/pelatihan/profile.queries";
import { processAndUploadFile } from "../../utils/image-upload";
import { storageService } from "@tepian-k3/services/storage";

export const profileRouter = createTRPCRouter({
  getProfile: protectedProcedure.query(async ({ ctx }) =>
    runEffect(profileQueries.getProfileByUserId(ctx.user.id)),
  ),

  upsertProfile: protectedProcedure
    .input(upsertProfileSchema)
    .mutation(async ({ ctx, input }) =>
      runEffect(profileQueries.upsertProfile(ctx.user.id, input)),
    ),

  getMyDocuments: protectedProcedure.query(async ({ ctx }) =>
    runEffect(
      Effect.gen(function* () {
        const docs = yield* profileQueries.getDocumentsByUserId(ctx.user.id);
        return docs.map((doc) => ({
          ...doc,
          fileUrl: storageService.getPublicUrl(doc.fileUrl),
        }));
      }),
    ),
  ),

  uploadDocument: protectedProcedure
    .input(formDataInput)
    .use(
      formDataProcedure(
        z.object({
          type: z.enum([
            "id_card",
            "employment_letter",
            "salary_slip",
            "employment_contract",
            "diploma",
            "pass_photo",
          ]),
          file: z.custom<File>((val) => val instanceof File, {
            message: "File berkas wajib diunggah",
          }),
        }),
      ),
    )
    .mutation(async ({ ctx }) =>
      runEffect(
        Effect.gen(function* () {
          const file = ctx.input.data.file;
          const docType = ctx.input.data.type;

          const uploadedFile = yield* processAndUploadFile(file, {
            folder: `pelatihan/user-documents/${docType}`,
          });

          const docNumber = `DOC-USER-${ctx.user.id.substring(0, 8)}-${Date.now()}`;
          const docTitle =
            docType === "id_card"
              ? "Kartu Identitas (KTP)"
              : docType === "employment_letter"
                ? "Surat Keterangan Kerja"
                : docType === "salary_slip"
                  ? "Slip Gaji Bulanan"
                  : docType === "employment_contract"
                    ? "Kontrak Kerja"
                    : docType === "pass_photo"
                      ? "Pass Foto Latar Merah"
                      : "Ijazah Terakhir";

          const result = yield* profileQueries.createDocument(ctx.user.id, {
            documentNumber: docNumber,
            type: docType,
            title: docTitle,
            fileUrl: uploadedFile.key,
            fileName: file.name,
            fileSize: file.size,
            mimeType: file.type,
          });

          return {
            ...result,
            fileUrl: storageService.getPublicUrl(result.fileUrl),
          };
        }),
      ),
    ),

  deleteDocument: protectedProcedure
    .input(z.object({ documentId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) =>
      runEffect(profileQueries.deleteDocument(input.documentId, ctx.user.id)),
    ),

  saveRequirementsAndUpdateProfile: protectedProcedure
    .input(submitRegistrationRequirementsSchema)
    .mutation(async ({ ctx, input }) =>
      runEffect(profileQueries.upsertTrainingProfileAndDocuments(ctx.user.id, input)),
    ),
});

export default profileRouter;

// ##################
// end authored
// ##################
