import auditTrailSchema from "@tepian-k3/schema/pengujian/audit-trail.schema";
import auditTrailQueries from "@tepian-k3/queries/pengujian/audit-trail.queries";
import { buildAuditTrailWorkbook } from "@tepian-k3/services/excel";
import {
  buildDocumentZipPackage,
  type ZipDocumentFile,
} from "@tepian-k3/services/archive";
import { storageService } from "@tepian-k3/services/storage";
import { logError } from "@tepian-k3/services/logger";
import { createTRPCRouter, withPermission, withRateLimit } from "../..";
import { rateLimiters } from "@tepian-k3/services/rate-limiter";
import { runEffect } from "../../utils/run-effect";
import { TRPCError } from "@trpc/server";

// ##################
// authored (generated by AI, Jul 28 2026 03:45 WITA)
// ##################

export const auditTrailRouter = createTRPCRouter({
  /**
   * Mengambil data audit trail JSON lengkap untuk preview modal di frontend.
   */
  getAuditTrail: withPermission("orders.view")
    .input(auditTrailSchema.getAuditTrailSchema)
    .query(async ({ input }) => {
      const data = await runEffect(
        auditTrailQueries.getAuditTrailByOrderId(input.orderId),
      );
      return data;
    }),

  /**
   * Mengunduh file Rekap Audit Trail dalam format Excel (.xlsx).
   */
  downloadExcel: withRateLimit(rateLimiters.moderate())
    .input(auditTrailSchema.getAuditTrailSchema)
    .mutation(async ({ input }) => {
      const data = await runEffect(
        auditTrailQueries.getAuditTrailByOrderId(input.orderId),
      );

      try {
        const excelBuffer = await buildAuditTrailWorkbook(data);
        const filename = `Audit_Trail_${data.orderInfo.orderNumber}.xlsx`;

        return {
          filename,
          base64: excelBuffer.toString("base64"),
          mimeType:
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        };
      } catch (error) {
        logError(
          "auditTrailRouter.downloadExcel",
          "Gagal membuat file Excel audit trail",
          { orderId: input.orderId, error },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal membuat file Rekap Excel Audit Trail",
        });
      }
    }),

  /**
   * Mengunduh bundle ZIP berisi dokumen resmi (Penawaran, Invoice, SPK, SPT)
   * dan file Excel Audit Trail.
   */
  downloadZip: withRateLimit(rateLimiters.moderate())
    .input(auditTrailSchema.exportSingleAuditTrailSchema)
    .mutation(async ({ input }) => {
      const data = await runEffect(
        auditTrailQueries.getAuditTrailByOrderId(input.orderId),
      );

      const zipFiles: ZipDocumentFile[] = [];

      // 1. Sertakan Excel Audit Trail
      try {
        const excelBuffer = await buildAuditTrailWorkbook(data);
        zipFiles.push({
          fileName: `Audit_Trail_${data.orderInfo.orderNumber}.xlsx`,
          fileBuffer: excelBuffer,
        });
      } catch (error) {
        logError(
          "auditTrailRouter.downloadZip",
          "Warning: Gagal menyertakan Excel dalam ZIP",
          { orderId: input.orderId, error },
        );
      }

      // 2. Unduh file PDF dokumen resmi dari Storage (Penawaran, Invoice, SPK, SPT)
      for (const doc of data.relatedDocuments) {
        try {
          if (doc.fileUrl) {
            const key =
              storageService.getKeyFromUrl(doc.fileUrl) ?? doc.fileUrl;
            const buffer = await runEffect(storageService.download(key));
            if (buffer) {
              const safeName = `${doc.type.toUpperCase()}_${doc.documentNumber.replace(/[/\\?%*:|"<>]/g, "-")}.pdf`;
              zipFiles.push({
                fileName: safeName,
                fileBuffer: buffer,
              });
            }
          }
        } catch (err) {
          logError(
            "auditTrailRouter.downloadZip",
            `Gagal mengambil dokumen storage: ${doc.type}`,
            { docId: doc.id, fileUrl: doc.fileUrl, err },
          );
        }
      }

      if (zipFiles.length === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Tidak ada dokumen yang ditemukan untuk di-zip",
        });
      }

      try {
        const zipBuffer = await buildDocumentZipPackage(zipFiles);
        const filename = `Audit_Bundle_${data.orderInfo.orderNumber}.zip`;

        return {
          filename,
          base64: zipBuffer.toString("base64"),
          mimeType: "application/zip",
        };
      } catch (error) {
        logError(
          "auditTrailRouter.downloadZip",
          "Gagal mengompres bundle ZIP",
          { orderId: input.orderId, error },
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Gagal mengompres bundle dokumen ZIP",
        });
      }
    }),
});

// ##################
// end authored
// ##################
