import {
  createTRPCRouter,
  formDataProcedure,
  formDataInput,
  withPermission,
  withProtectedRateLimit,
} from "../../index";
import { runEffect } from "../../utils/run-effect";
import { Effect } from "effect";
import { pengujianExcelQueries } from "@tepian-k3/queries/pengujian/pengujian-excel.queries";
import { importExcelFormSchema } from "@tepian-k3/schema/pengujian/pengujian-excel.schema";
import {
  parsePengujianExcelBuffer,
  buildExportWorkbook,
  buildImportReportWorkbook,
  buildTemplateWorkbook,
} from "@tepian-k3/services/excel";
import { TRPCError } from "@trpc/server";
import { rateLimiters } from "@tepian-k3/services/rate-limiter";

// ##################
// authored (generated by claude, Jun 24 2026 14:56 WITA)
// ##################

export const pengujianExcelRouter = createTRPCRouter({
  downloadTemplate: withPermission("pengujian-import-export.read").query(
    async () =>
      await runEffect(
        Effect.gen(function* () {
          const buffer = yield* Effect.tryPromise({
            try: () => buildTemplateWorkbook(),
            catch: (e) =>
              new TRPCError({
                code: "INTERNAL_SERVER_ERROR",
                message: "Failed to build template",
                cause: e,
              }),
          });
          return {
            base64: buffer.toString("base64"),
          };
        }),
      ),
  ),

  importData: withProtectedRateLimit(rateLimiters.moderate())
    .use(
      withPermission("pengujian-import-export.create")._def.middlewares[0] ||
        (async ({ ctx, next }) => next({ ctx })),
    )
    .input(formDataInput)
    .use(formDataProcedure(importExcelFormSchema))
    .mutation(
      async ({ ctx }) =>
        await runEffect(
          Effect.gen(function* () {
            const arrayBuffer = yield* Effect.tryPromise<
              ArrayBuffer,
              TRPCError
            >({
              try: () => ctx.input.data.file.arrayBuffer(),
              catch: (e) =>
                new TRPCError({
                  code: "BAD_REQUEST",
                  message: "Failed to read file",
                  cause: e,
                }),
            });
            const buffer = Buffer.from(arrayBuffer);

            const parsedData = yield* Effect.tryPromise({
              try: () => parsePengujianExcelBuffer(buffer),
              catch: (e) =>
                new TRPCError({
                  code: "INTERNAL_SERVER_ERROR",
                  message: "Failed to parse excel",
                  cause: e,
                }),
            });

            if (parsedData.parseErrors.length > 0) {
              const errorBuffer = yield* Effect.tryPromise({
                try: () => {
                  const summary: Record<
                    string,
                    { processed: number; success: number; failed: number }
                  > = {
                    parameterCategories: {
                      processed: parsedData.parameterCategories.length,
                      success: parsedData.parameterCategories.length,
                      failed: 0,
                    },
                    parameters: {
                      processed: parsedData.parameters.length,
                      success: parsedData.parameters.length,
                      failed: 0,
                    },
                    toolCodes: {
                      processed: parsedData.toolCodes.length,
                      success: parsedData.toolCodes.length,
                      failed: 0,
                    },
                    tools: {
                      processed: parsedData.tools.length,
                      success: parsedData.tools.length,
                      failed: 0,
                    },
                    chemicalMaterials: {
                      processed: parsedData.chemicalMaterials.length,
                      success: parsedData.chemicalMaterials.length,
                      failed: 0,
                    },
                  };

                  // Hitung error ke dalam summary
                  for (const err of parsedData.parseErrors) {
                    const sheetKey =
                      Object.keys(summary).find((k) =>
                        k
                          .toLowerCase()
                          .includes(
                            (
                              err.sheet.split(" ")[0] || err.sheet
                            ).toLowerCase(),
                          ),
                      ) || err.sheet;
                    if (!summary[sheetKey]) {
                      summary[sheetKey] = {
                        processed: 0,
                        success: 0,
                        failed: 0,
                      };
                    }
                    summary[sheetKey].failed += 1;
                    summary[sheetKey].processed += 1;
                  }

                  return buildImportReportWorkbook({
                    summary,
                    errors: parsedData.parseErrors,
                  });
                },
                catch: (e) =>
                  new TRPCError({
                    code: "INTERNAL_SERVER_ERROR",
                    message: "Failed to build error report",
                    cause: e,
                  }),
              });

              return {
                success: false,
                hasErrors: true,
                errorCount: parsedData.parseErrors.length,
                errorReportBase64: errorBuffer.toString("base64"),
                summary: null,
              };
            }

            const importResult =
              yield* pengujianExcelQueries.importFromParsedData(
                parsedData,
                ctx.user.id,
                ctx.user.email,
              );

            return {
              success: true,
              hasErrors: false,
              errorCount: 0,
              summary: importResult,
            };
          }),
        ),
    ),

  exportData: withPermission("pengujian-import-export.read").query(
    async () =>
      await runEffect(
        Effect.gen(function* () {
          const data = yield* pengujianExcelQueries.exportAllData();

          const exportData = {
            parameterCategories: data.kategoriData,
            parameters: data.parameterData,
            toolCodes: data.kodeAlatData,
            tools: data.alatData,
            chemicalMaterials: data.bahanData,
          };

          const buffer = yield* Effect.tryPromise<Buffer, TRPCError>({
            try: () => buildExportWorkbook(exportData),
            catch: (e) =>
              new TRPCError({
                code: "INTERNAL_SERVER_ERROR",
                message: "Failed to build excel",
                cause: e,
              }),
          });

          return {
            buffer: buffer.toString("base64"),
            filename: `Export_Master_Pengujian_${new Date().toISOString().split("T")[0]}.xlsx`,
          };
        }),
      ),
  ),
});

// ##################
// end authored
// ##################
