// ##################
// authored (generated by claude, Jun 01 2026 11:05 WITA)
// ##################

import { createFileRoute, Outlet } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { requirePermission } from "@/utils/require-permission";
import { trpc } from "@/utils/trpc";
import { pageHead } from "@/utils/page-head";
import { z } from "zod";
import { CourseHeader } from "./$pelatihanId/-components/course-header";
import { TabNav } from "./$pelatihanId/-components/tab-nav";

export const Route = createFileRoute(
  "/(core)/back-office/pelatihan/$pelatihanId",
)({
  params: z.object({
    pelatihanId: z.string(),
  }),
  beforeLoad: async ({ context, params }) => {
    await requirePermission(context, { permission: "pelatihan.view" });
    // Ensure the record exists before rendering
    await context.queryClient.ensureQueryData(
      context.trpc.pelatihan.base.getPelatihanById.queryOptions({
        id: params.pelatihanId,
      }),
    );
  },
  head: () => pageHead("Detail Pelatihan"),
  component: RouteComponent,
});

function RouteComponent() {
  const { pelatihanId } = Route.useParams();

  const { data: pelatihan } = useSuspenseQuery(
    trpc.pelatihan.base.getPelatihanById.queryOptions({ id: pelatihanId }),
  );

  if (!pelatihan) {
    return (
      <div className="flex h-64 items-center justify-center text-slate-500">
        Pelatihan tidak ditemukan.
      </div>
    );
  }

  return (
    <div className="w-full flex-1 space-y-4 bg-[#F8FAFC] font-['Poppins']">
      {/* Course Header Card */}
      <CourseHeader pelatihan={pelatihan} />

      {/* Tab Navigator */}
      <TabNav pelatihanId={pelatihanId} />

      {/* Tab Content */}
      <Outlet />
    </div>
  );
}

// ##################
// end authored
// ##################
