import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { v7 as uuidv7 } from "uuid";
import { createTable, timestamps } from "../utils";
import { users, documents, provinces, regencies, districts } from "./platform";

// Enums
export const pelatihanLevelEnum = pgEnum("pelatihan_level", [
  "beginner",
  "intermediate",
  "advanced",
]);

export const pelatihanStatusEnum = pgEnum("pelatihan_status", [
  "draft",
  "published",
  "archived",
]);

export const pelatihanTypeEnum = pgEnum("pelatihan_type", [
  "elearning",
  "bimtek",
  "webinar",
]);

export const materialTypeEnum = pgEnum("material_type", [
  "ppt",
  "pdf",
  "video",
  "document",
  "link",
]);

export const assessmentTypeEnum = pgEnum("assessment_type", [
  "pre_test",
  "post_test",
  "quiz",
]);

export const questionTypeEnum = pgEnum("question_type", [
  "multiple_choice",
  "true_false",
  "essay",
]);

export const enrollmentStatusEnum = pgEnum("enrollment_status", [
  "enrolled",
  "in_progress",
  "completed",
  "failed",
  "expired",
]);

export const pelatihanOrderStatusEnum = pgEnum("pelatihan_order_status", [
  "pending",
  "waiting_payment",
  "waiting_verification",
  "verified",
  "cancelled",
  "expired",
  "rejected",
]);

export const pelatihanPaymentStatusEnum = pgEnum("pelatihan_payment_status", [
  "unpaid",
  "pending",
  "pending_verification",
  "paid",
  "refunded",
  "rejected",
]);

export const pelatihanOrderApprovalStatusEnum = pgEnum("pelatihan_order_approval_status", [
  "pending",
  "approved",
  "rejected",
]);

export const attemptStatusEnum = pgEnum("attempt_status", [
  "in_progress",
  "submitted",
  "graded",
  "reviewed",
]);

// ##################
// authored (generated by gemini, Jun 08 2026 20:13 WITA)
// ##################
export const verificationStatusEnum = pgEnum("pelatihan_verification_status", [
  "pending",
  "verified",
  "rejected",
]);
// ##################
// end authored
// ##################

export const attendanceStatusEnum = pgEnum("attendance_status", [
  "present",
  "absent",
  "excused",
  "sick",
  "visited",
]);

// ##################
// authored (generated by gemini, Jun 08 2026 20:13 WITA)
// ##################
// 1. pelatihanCategories
export const pelatihanCategories = createTable(
  "pelatihan_categories",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    name: varchar("name", { length: 250 }).notNull(),
    slug: varchar("slug", { length: 250 }).notNull(),
    description: text("description"),
    iconUrl: varchar("icon_url", { length: 500 }),
    orderIndex: integer("order_index").notNull().default(0),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("pelatihan_category_slug_idx")
      .on(table.slug)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);
// ##################
// end authored
// ##################

// 2. pelatihan
export const pelatihan = createTable(
  "pelatihan",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    title: varchar("title", { length: 250 }).notNull(),
    slug: varchar("slug", { length: 250 }).notNull().unique(),
    description: text("description"),
    shortDescription: varchar("short_description", { length: 500 }),
    categoryId: uuid("category_id").references(() => pelatihanCategories.id, {
      onDelete: "set null",
    }),
    level: pelatihanLevelEnum("level"),
    type: pelatihanTypeEnum("type").notNull().default("elearning"),
    duration: integer("duration").notNull(),
    capacity: integer("capacity"),
    price: integer("price").notNull().default(0),
    discountPrice: integer("discount_price"),
    prerequisiteIds: uuid("prerequisite_ids").array(),
    minimumScore: integer("minimum_score").notNull().default(70),
    status: pelatihanStatusEnum("status").notNull().default("draft"),
    publishedAt: timestamp("published_at", {
      withTimezone: true,
      mode: "string",
    }),
    thumbnailUrl: varchar("thumbnail_url", { length: 500 }),
    instructorName: varchar("instructor_name", { length: 250 }),
    instructorBio: text("instructor_bio"),
    startDate: timestamp("start_date", {
      withTimezone: true,
      mode: "string",
    }),
    endDate: timestamp("end_date", {
      withTimezone: true,
      mode: "string",
    }),
    location: varchar("location", { length: 250 }),
    facilities: varchar("facilities", { length: 250 }).array(),
    requirements: text("requirements"),
    dynamicRequirements: jsonb("dynamic_requirements").$type<{
      participantNik?: boolean;
      participantBirthPlace?: boolean;
      participantBirthDate?: boolean;
      participantPhone?: boolean;
      participantAddress?: boolean;
      participantBloodType?: boolean;
      companyName?: boolean;
      companyAddress?: boolean;
      companyProvinceId?: boolean;
      companyRegencyId?: boolean;
      companyDistrictId?: boolean;
      companyKbli?: boolean;
      ktpDoc?: boolean;
      employmentLetter?: boolean;
      consentLetter?: boolean;
      diploma?: boolean;
      passPhoto?: boolean;
    }>().default({}),
    certificateNumberFormat: varchar("certificate_number_format", { length: 250 }),
    attendanceRequired: boolean("attendance_required").notNull().default(true),
    minAttendancePercentage: integer("min_attendance_percentage").notNull().default(85),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("pelatihan_slug_idx")
      .on(table.slug)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);

// 3. pelatihanCart
export const pelatihanCart = createTable(
  "pelatihan_cart",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    pelatihanId: uuid("pelatihan_id")
      .notNull()
      .references(() => pelatihan.id, { onDelete: "cascade" }),
    quantity: integer("quantity").notNull().default(1),
    unitPrice: integer("unit_price").notNull(),
    discountPrice: integer("discount_price"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("cart_user_pelatihan_idx")
      .on(table.userId, table.pelatihanId)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);

// 4. pelatihanOrders — tabel order khusus pelatihan (terpisah dari order pengujian)
export const pelatihanOrders = createTable(
  "pelatihan_orders",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    orderNumber: varchar("order_number", { length: 50 }).notNull().unique(),
    status: pelatihanOrderStatusEnum("status").notNull().default("pending"),
    totalAmount: integer("total_amount").notNull().default(0),
    approvalStatus: pelatihanOrderApprovalStatusEnum("approval_status")
      .notNull()
      .default("pending"),
    approvalRejectReason: text("approval_reject_reason"),
    paymentStatus: pelatihanPaymentStatusEnum("payment_status")
      .notNull()
      .default("unpaid"),
    paymentRejectedReason: text("payment_rejected_reason"),
    paymentProofUrl: varchar("payment_proof_url", { length: 500 }),
    paymentProofUploadedAt: timestamp("payment_proof_uploaded_at", {
      withTimezone: true,
      mode: "string",
    }),
    approvedAt: timestamp("approved_at", {
      withTimezone: true,
      mode: "string",
    }),
    approvedBy: uuid("approved_by").references(() => users.id, {
      onDelete: "set null",
    }),
    verifiedBy: uuid("verified_by").references(() => users.id, {
      onDelete: "set null",
    }),
    verifiedAt: timestamp("verified_at", {
      withTimezone: true,
      mode: "string",
    }),
    notes: text("notes"),
    ...timestamps,
  },
  (table) => [
    index("pelatihan_orders_user_idx").on(table.userId),
    index("pelatihan_orders_status_idx").on(table.status),
    index("pelatihan_orders_approval_status_idx").on(table.approvalStatus),
  ],
);

// 4a. pelatihanOrderItems — item-item dalam order pelatihan
export const pelatihanOrderItems = createTable("pelatihan_order_items", {
  id: uuid("id")
    .primaryKey()
    .notNull()
    .$default(() => uuidv7()),
  orderId: uuid("order_id")
    .notNull()
    .references(() => pelatihanOrders.id, { onDelete: "cascade" }),
  pelatihanId: uuid("pelatihan_id")
    .notNull()
    .references(() => pelatihan.id, { onDelete: "cascade" }),
  price: integer("price").notNull(),
  ...timestamps,
});

// 5. pelatihanModules (folder/modul untuk mengelompokkan materi)
export const pelatihanModules = createTable("pelatihan_modules", {
  id: uuid("id")
    .primaryKey()
    .notNull()
    .$default(() => uuidv7()),
  pelatihanId: uuid("pelatihan_id")
    .notNull()
    .references(() => pelatihan.id, { onDelete: "cascade" }),
  title: varchar("title", { length: 250 }).notNull(),
  description: text("description"),
  orderIndex: integer("order_index").notNull().default(0),
  ...timestamps,
});

// 6. pelatihanMaterials
export const pelatihanMaterials = createTable("pelatihan_materials", {
  id: uuid("id")
    .primaryKey()
    .notNull()
    .$default(() => uuidv7()),
  pelatihanId: uuid("pelatihan_id")
    .notNull()
    .references(() => pelatihan.id, { onDelete: "cascade" }),
  moduleId: uuid("module_id").references(() => pelatihanModules.id, {
    onDelete: "set null",
  }),
  title: varchar("title", { length: 250 }).notNull(),
  description: text("description"),
  type: materialTypeEnum("type").notNull(),
  fileUrl: varchar("file_url", { length: 500 }),
  fileSize: integer("file_size"),
  mimeType: varchar("mime_type", { length: 100 }),
  duration: integer("duration"),
  orderIndex: integer("order_index").notNull().default(0),
  isPreview: boolean("is_preview").notNull().default(false),
  ...timestamps,
});


// 5. pelatihanAssessments
export const pelatihanAssessments = createTable("pelatihan_assessments", {
  id: uuid("id")
    .primaryKey()
    .notNull()
    .$default(() => uuidv7()),
  pelatihanId: uuid("pelatihan_id")
    .notNull()
    .references(() => pelatihan.id, { onDelete: "cascade" }),
  type: assessmentTypeEnum("type").notNull(),
  title: varchar("title", { length: 250 }).notNull(),
  description: text("description"),
  passingScore: integer("passing_score").notNull().default(70),
  timeLimit: integer("time_limit"),
  maxAttempts: integer("max_attempts"),
  randomizeQuestions: boolean("randomize_questions").notNull().default(false),
  randomizeOptions: boolean("randomize_options").notNull().default(false),
  availableAfter: integer("available_after"),
  ...timestamps,
});

// 6. pelatihanQuestions
export const pelatihanQuestions = createTable("pelatihan_questions", {
  id: uuid("id")
    .primaryKey()
    .notNull()
    .$default(() => uuidv7()),
  assessmentId: uuid("assessment_id")
    .notNull()
    .references(() => pelatihanAssessments.id, { onDelete: "cascade" }),
  questionText: text("question_text").notNull(),
  type: questionTypeEnum("type").notNull(),
  points: integer("points").notNull().default(1),
  correctAnswer: text("correct_answer"),
  explanation: text("explanation"),
  orderIndex: integer("order_index").notNull().default(0),
  ...timestamps,
});

// 7. pelatihanQuestionOptions
export const pelatihanQuestionOptions = createTable(
  "pelatihan_question_options",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    questionId: uuid("question_id")
      .notNull()
      .references(() => pelatihanQuestions.id, { onDelete: "cascade" }),
    optionText: text("option_text").notNull(),
    isCorrect: boolean("is_correct").notNull().default(false),
    orderIndex: integer("order_index").notNull().default(0),
    ...timestamps,
  },
);

// 8. pelatihanEnrollments
export const pelatihanEnrollments = createTable(
  "pelatihan_enrollments",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    pelatihanId: uuid("pelatihan_id")
      .notNull()
      .references(() => pelatihan.id, { onDelete: "cascade" }),
    status: enrollmentStatusEnum("status").notNull().default("enrolled"),
    enrolledAt: timestamp("enrolled_at", { withTimezone: true, mode: "string" })
      .notNull()
      .defaultNow(),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "string" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "string",
    }),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "string" }),
    orderId: uuid("order_id").references(() => pelatihanOrders.id, {
      onDelete: "set null",
    }),
    progressPercentage: integer("progress_percentage").notNull().default(0),
    certificateUrl: varchar("certificate_url", { length: 500 }),
    certificateIssuedAt: timestamp("certificate_issued_at", {
      withTimezone: true,
      mode: "string",
    }),
    preTestScore: integer("pre_test_score"),
    postTestScore: integer("post_test_score"),
    finalScore: integer("final_score"),

    // ##################
    // authored (generated by gemini, Jun 03 2026 13:10 WITA)
    // ##################
    // Data Perusahaan
    companyName: varchar("company_name", { length: 250 }),
    companyAddress: text("company_address"),
    companyProvinceId: uuid("company_province_id").references(() => provinces.id, {
      onDelete: "set null",
    }),
    companyRegencyId: uuid("company_regency_id").references(() => regencies.id, {
      onDelete: "set null",
    }),
    companyDistrictId: uuid("company_district_id").references(() => districts.id, {
      onDelete: "set null",
    }),
    companyKbli: varchar("company_kbli", { length: 250 }),

    // Data Diri Peserta
    participantName: varchar("participant_name", { length: 250 }),
    participantNik: varchar("participant_nik", { length: 50 }),
    participantBirthPlace: varchar("participant_birth_place", { length: 250 }),
    participantBirthDate: timestamp("participant_birth_date", {
      withTimezone: true,
      mode: "string",
    }),
    participantEmail: varchar("participant_email", { length: 250 }),
    participantPhone: varchar("participant_phone", { length: 50 }),
    participantAddress: text("participant_address"),

    // Uploaded Documents
    employmentLetterUrl: varchar("employment_letter_url", { length: 500 }),
    employmentLetterName: varchar("employment_letter_name", { length: 250 }),
    consentLetterUrl: varchar("consent_letter_url", { length: 500 }),
    consentLetterName: varchar("consent_letter_name", { length: 250 }),
    diplomaUrl: varchar("diploma_url", { length: 500 }),
    diplomaName: varchar("diploma_name", { length: 250 }),
    passPhotoUrl: varchar("pass_photo_url", { length: 500 }),
    passPhotoName: varchar("pass_photo_name", { length: 250 }),

    // Verification Status
    // ##################
    // authored (generated by gemini, Jun 08 2026 20:13 WITA)
    // ##################
    verificationStatus: verificationStatusEnum("verification_status")
      .notNull()
      .default("pending"),
    // ##################
    // end authored
    // ##################
    rejectionReason: text("rejection_reason"),
    verifiedAt: timestamp("verified_at", {
      withTimezone: true,
      mode: "string",
    }),
    verifiedBy: uuid("verified_by").references(() => users.id, {
      onDelete: "set null",
    }),
    // ##################
    // end authored
    // ##################

    ...timestamps,
  },
  (table) => [
    uniqueIndex("enrollment_user_pelatihan_idx")
      .on(table.userId, table.pelatihanId)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);

// 9. pelatihanProgress
export const pelatihanProgress = createTable(
  "pelatihan_progress",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    enrollmentId: uuid("enrollment_id")
      .notNull()
      .references(() => pelatihanEnrollments.id, { onDelete: "cascade" }),
    materialId: uuid("material_id")
      .notNull()
      .references(() => pelatihanMaterials.id, { onDelete: "cascade" }),
    completed: boolean("completed").notNull().default(false),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "string",
    }),
    watchedDuration: integer("watched_duration"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("progress_enrollment_material_idx")
      .on(table.enrollmentId, table.materialId)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);

// 10. pelatihanAssessmentAttempts
export const pelatihanAssessmentAttempts = createTable(
  "pelatihan_assessment_attempts",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    enrollmentId: uuid("enrollment_id")
      .notNull()
      .references(() => pelatihanEnrollments.id, { onDelete: "cascade" }),
    assessmentId: uuid("assessment_id")
      .notNull()
      .references(() => pelatihanAssessments.id, { onDelete: "cascade" }),
    attemptNumber: integer("attempt_number").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "string" })
      .notNull()
      .defaultNow(),
    submittedAt: timestamp("submitted_at", {
      withTimezone: true,
      mode: "string",
    }),
    score: integer("score"),
    totalPoints: integer("total_points"),
    earnedPoints: integer("earned_points"),
    passed: boolean("passed"),
    status: attemptStatusEnum("status").notNull().default("in_progress"),
    ...timestamps,
  },
);

// 11. pelatihanAssessmentAnswers
export const pelatihanAssessmentAnswers = createTable(
  "pelatihan_assessment_answers",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    attemptId: uuid("attempt_id")
      .notNull()
      .references(() => pelatihanAssessmentAttempts.id, {
        onDelete: "cascade",
      }),
    questionId: uuid("question_id")
      .notNull()
      .references(() => pelatihanQuestions.id, { onDelete: "cascade" }),
    answer: text("answer").notNull(),
    isCorrect: boolean("is_correct"),
    pointsEarned: integer("points_earned").notNull().default(0),
    gradedBy: uuid("graded_by").references(() => users.id, {
      onDelete: "set null",
    }),
    gradedAt: timestamp("graded_at", { withTimezone: true, mode: "string" }),
    feedback: text("feedback"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("answer_attempt_question_idx")
      .on(table.attemptId, table.questionId)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);

// ##################
// authored (generated by gemini, Jun 08 2026 20:13 WITA)
// ##################
// 12a. pelatihanCertificateTemplates
export const pelatihanCertificateTemplates = createTable(
  "pelatihan_certificate_templates",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    pelatihanId: uuid("pelatihan_id")
      .notNull()
      .references(() => pelatihan.id, { onDelete: "cascade" }),
    name: varchar("name", { length: 250 }).notNull(),
    description: text("description"),
    templateFileUrl: varchar("template_file_url", { length: 500 }).notNull(),
    templateFileName: varchar("template_file_name", { length: 250 }).notNull(),
    templateFileType: varchar("template_file_type", { length: 50 }).notNull(), // e.g. "pdf"
    fieldMappings: jsonb("field_mappings").$type<{
      participantName?: { x: number; y: number; fontSize: number; color?: string; align?: string; enabled: boolean };
      certificateNumber?: { x: number; y: number; fontSize: number; color?: string; align?: string; enabled: boolean };
      pelatihanTitle?: { x: number; y: number; fontSize: number; color?: string; align?: string; enabled: boolean };
      completionDate?: { x: number; y: number; fontSize: number; color?: string; align?: string; enabled: boolean };
      issuedAt?: { x: number; y: number; fontSize: number; color?: string; align?: string; enabled: boolean };
      finalScore?: { x: number; y: number; fontSize: number; color?: string; align?: string; enabled: boolean };
      instructorName?: { x: number; y: number; fontSize: number; color?: string; align?: string; enabled: boolean };
      qrCode?: { x: number; y: number; width: number; height: number; enabled: boolean };
    }>().notNull().default({}),
    isActive: boolean("is_active").notNull().default(false),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    ...timestamps,
  },
  (table) => [
    index("cert_template_pelatihan_idx").on(table.pelatihanId),
    index("cert_template_active_idx").on(table.pelatihanId, table.isActive),
  ],
);

// 12. pelatihanCertificates
export const pelatihanCertificates = createTable(
  "pelatihan_certificates",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    enrollmentId: uuid("enrollment_id")
      .notNull()
      .references(() => pelatihanEnrollments.id)
      .unique(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    pelatihanId: uuid("pelatihan_id")
      .notNull()
      .references(() => pelatihan.id, { onDelete: "cascade" }),
    templateId: uuid("template_id").references(() => pelatihanCertificateTemplates.id, {
      onDelete: "set null",
    }),
    certificateNumber: varchar("certificate_number", { length: 100 })
      .notNull()
      .unique(),
    issuedAt: timestamp("issued_at", { withTimezone: true, mode: "string" })
      .notNull()
      .defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "string" }),
    documentId: uuid("document_id").references(() => documents.id, {
      onDelete: "set null",
    }),
    documentUrl: varchar("document_url", { length: 500 }).notNull(),
    verificationToken: text("verification_token").notNull(),
    qrCodeUrl: varchar("qr_code_url", { length: 500 }),
    instructorName: varchar("instructor_name", { length: 250 }),
    finalScore: integer("final_score").notNull(),
    completionDate: timestamp("completion_date", {
      withTimezone: true,
      mode: "string",
    }).notNull(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("certificate_number_idx")
      .on(table.certificateNumber)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);
// ##################
// end authored
// ##################

// ##################
// authored (generated by gemini, Jun 03 2026 17:40 WITA)
// ##################

// 13. pelatihanSchedules
export const pelatihanSchedules = createTable("pelatihan_schedules", {
  id: uuid("id")
    .primaryKey()
    .notNull()
    .$default(() => uuidv7()),
  pelatihanId: uuid("pelatihan_id")
    .notNull()
    .references(() => pelatihan.id, { onDelete: "cascade" }),
  title: varchar("title", { length: 250 }).notNull(),
  description: text("description"),
  sessionDate: timestamp("session_date", {
    withTimezone: true,
    mode: "string",
  }).notNull(),
  startTime: varchar("start_time", { length: 50 }).notNull(),
  endTime: varchar("end_time", { length: 50 }).notNull(),
  room: varchar("room", { length: 250 }),
  category: varchar("category", { length: 100 }),
  materialUrl: varchar("material_url", { length: 500 }),
  meetUrl: varchar("meet_url", { length: 500 }),
  ...timestamps,
});

// 14. pelatihanAttendances
export const pelatihanAttendances = createTable(
  "pelatihan_attendances",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    enrollmentId: uuid("enrollment_id")
      .notNull()
      .references(() => pelatihanEnrollments.id, { onDelete: "cascade" }),
    scheduleId: uuid("schedule_id")
      .notNull()
      .references(() => pelatihanSchedules.id, { onDelete: "cascade" }),
    status: attendanceStatusEnum("status").notNull().default("present"),
    checkedInAt: timestamp("checked_in_at", {
      withTimezone: true,
      mode: "string",
    }).notNull().defaultNow(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("attendance_enrollment_schedule_idx")
      .on(table.enrollmentId, table.scheduleId)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);

// ##################
// end authored
// ##################

// ##################
// authored (generated by gemini, Jun 04 2026 11:20 WITA)
// ##################

// 15. userTrainingProfiles
export const userTrainingProfiles = createTable(
  "user_training_profiles",
  {
    id: uuid("id")
      .primaryKey()
      .notNull()
      .$default(() => uuidv7()),
    userId: uuid("user_id")
      .notNull()
      .unique()
      .references(() => users.id, { onDelete: "cascade" }),
    
    // Data Perusahaan
    companyName: varchar("company_name", { length: 250 }),
    companyAddress: text("company_address"),
    companyProvinceId: uuid("company_province_id").references(() => provinces.id, {
      onDelete: "set null",
    }),
    companyRegencyId: uuid("company_regency_id").references(() => regencies.id, {
      onDelete: "set null",
    }),
    companyDistrictId: uuid("company_district_id").references(() => districts.id, {
      onDelete: "set null",
    }),
    companyKbli: varchar("company_kbli", { length: 250 }),

    // Data Diri Peserta
    participantName: varchar("participant_name", { length: 250 }),
    participantNik: varchar("participant_nik", { length: 50 }),
    participantBirthPlace: varchar("participant_birth_place", { length: 250 }),
    participantBirthDate: timestamp("participant_birth_date", {
      withTimezone: true,
      mode: "string",
    }),
    participantPhone: varchar("participant_phone", { length: 50 }),
    participantAddress: text("participant_address"),
    participantBloodType: varchar("participant_blood_type", { length: 10 }),
    participantProvinceId: uuid("participant_province_id").references(() => provinces.id, {
      onDelete: "set null",
    }),
    participantRegencyId: uuid("participant_regency_id").references(() => regencies.id, {
      onDelete: "set null",
    }),
    participantDistrictId: uuid("participant_district_id").references(() => districts.id, {
      onDelete: "set null",
    }),

    ...timestamps,
  },
  (table) => [
    index("user_training_profile_user_id_idx").using("btree", table.userId),
  ],
);

// ##################
// end authored
// ##################

