import {
  pelatihan,
  pelatihanAssessments,
  pelatihanCategories,
  pelatihanCart,
  pelatihanEnrollments,
  pelatihanMaterials,
  pelatihanQuestions,
  pelatihanQuestionOptions,
  pelatihanModules,
} from "@tepian-k3/db/schema";
import { createInsertSchema } from "drizzle-zod";
import z from "zod";
import { createPaginationSchema } from "../platform/pagination.schema";

// Category Schemas
export const createPelatihanCategorySchema = createInsertSchema(
  pelatihanCategories,
  {
    name: z.string().min(1).max(250),
    slug: z.string().min(1).max(250),
  },
).omit({ id: true, createdAt: true, updatedAt: true, deletedAt: true });

export const dynamicRequirementsSchema = z.object({
  participantNik: z.boolean().optional(),
  participantBirthPlace: z.boolean().optional(),
  participantBirthDate: z.boolean().optional(),
  participantPhone: z.boolean().optional(),
  participantAddress: z.boolean().optional(),
  participantBloodType: z.boolean().optional(),
  companyName: z.boolean().optional(),
  companyAddress: z.boolean().optional(),
  companyProvinceId: z.boolean().optional(),
  companyRegencyId: z.boolean().optional(),
  companyDistrictId: z.boolean().optional(),
  companyKbli: z.boolean().optional(),
  ktpDoc: z.boolean().optional(),
  employmentLetter: z.boolean().optional(),
  consentLetter: z.boolean().optional(),
  diploma: z.boolean().optional(),
  passPhoto: z.boolean().optional(),
}).optional();

// ##################
// authored (generated by gemini, Jun 09 2026 07:12 WITA)
// ##################
// Pelatihan Schemas
export const createPelatihanSchema = createInsertSchema(pelatihan, {
  title: z.string().min(1).max(250),
  slug: z.string().min(1).max(250),
  price: z.number().min(0),
  categoryId: z.string().uuid().nullable().optional(),
  level: z.enum(["beginner", "intermediate", "advanced"]).nullable().optional(),
  prerequisiteIds: z.array(z.string().uuid()).nullable().optional(),
  description: z.string().nullable().optional(),
  shortDescription: z.string().nullable().optional(),
  thumbnailUrl: z.string().nullable().optional(),
  instructorName: z.string().nullable().optional(),
  instructorBio: z.string().nullable().optional(),
  startDate: z.string().nullable().optional(),
  endDate: z.string().nullable().optional(),
  location: z.string().nullable().optional(),
  facilities: z.array(z.string()).nullable().optional(),
  requirements: z.string().nullable().optional(),
  dynamicRequirements: dynamicRequirementsSchema,
  certificateNumberFormat: z.string().nullable().optional(),
  attendanceRequired: z.boolean().default(true),
  minAttendancePercentage: z.number().int().min(0).max(100).default(85),
}).omit({ id: true, createdAt: true, updatedAt: true, deletedAt: true });

export const updatePelatihanSchema = createInsertSchema(pelatihan, {
  title: z.string().min(1).max(250),
  slug: z.string().min(1).max(250),
  price: z.number().min(0),
  categoryId: z.string().uuid().nullable().optional(),
  level: z.enum(["beginner", "intermediate", "advanced"]).nullable().optional(),
  prerequisiteIds: z.array(z.string().uuid()).nullable().optional(),
  description: z.string().nullable(),
  shortDescription: z.string().nullable(),
  thumbnailUrl: z.string().nullable(),
  instructorName: z.string().nullable(),
  instructorBio: z.string().nullable(),
  startDate: z.string().nullable(),
  endDate: z.string().nullable(),
  location: z.string().nullable(),
  facilities: z.array(z.string()).nullable(),
  requirements: z.string().nullable(),
  dynamicRequirements: dynamicRequirementsSchema,
  certificateNumberFormat: z.string().nullable(),
  attendanceRequired: z.boolean().optional(),
  minAttendancePercentage: z.number().int().min(0).max(100).optional(),
})
  .omit({ createdAt: true, updatedAt: true, deletedAt: true })
  .partial()
  .extend({
    id: z.string().uuid(),
  });
// ##################
// end authored
// ##################

// Cart
export const createPelatihanCartSchema = createInsertSchema(pelatihanCart).omit(
  {
    id: true,
    createdAt: true,
    updatedAt: true,
    deletedAt: true,
    userId: true,
  },
);

// Modules Schemas
export const createPelatihanModuleSchema = createInsertSchema(
  pelatihanModules,
  {
    title: z.string().min(1).max(250),
  },
).omit({ id: true, createdAt: true, updatedAt: true, deletedAt: true, orderIndex: true });

export const updatePelatihanModuleSchema = createInsertSchema(
  pelatihanModules,
  {
    title: z.string().min(1).max(250).optional(),
  },
).omit({ id: true, pelatihanId: true, createdAt: true, updatedAt: true, deletedAt: true, orderIndex: true });

// Materials Schema
export const createPelatihanMaterialSchema = createInsertSchema(
  pelatihanMaterials,
  {
    title: z.string().min(1).max(250),
    type: z.enum(["ppt", "pdf", "video", "document", "link"]),
  },
).omit({ id: true, createdAt: true, updatedAt: true, deletedAt: true, orderIndex: true });

export const updatePelatihanMaterialSchema = createInsertSchema(
  pelatihanMaterials,
  {
    title: z.string().min(1).max(250).optional(),
    type: z.enum(["ppt", "pdf", "video", "document", "link"]).optional(),
  },
).omit({ id: true, pelatihanId: true, createdAt: true, updatedAt: true, deletedAt: true, orderIndex: true });


// Assessments Schema
export const createPelatihanAssessmentSchema = createInsertSchema(
  pelatihanAssessments,
  {
    title: z.string().min(1).max(250),
  },
).omit({ id: true, createdAt: true, updatedAt: true, deletedAt: true });

// Questions Schema
export const createPelatihanQuestionSchema = createInsertSchema(
  pelatihanQuestions,
  {
    questionText: z.string().min(1),
  },
).omit({ id: true, createdAt: true, updatedAt: true, deletedAt: true });

// Question Options
export const createPelatihanQuestionOptionSchema = createInsertSchema(
  pelatihanQuestionOptions,
).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
});

const SORTABLE_PELATIHAN_FIELDS = [
  "createdAt",
  "title",
  "price",
  "status",
] as const satisfies readonly (keyof typeof pelatihan.$inferSelect)[];

export const getAllPelatihanSchema = createPaginationSchema(
  SORTABLE_PELATIHAN_FIELDS,
  {
    id: "createdAt",
    desc: true,
  },
).extend({
  status: z.enum(["draft", "published", "archived"]).optional(),
  level: z.enum(["beginner", "intermediate", "advanced"]).optional(),
  type: z.enum(["elearning", "bimtek", "webinar"]).optional(),
  categoryId: z.string().uuid().optional(),
  search: z.string().default(""),
});

const SORTABLE_ENROLLMENT_FIELDS = [
  "enrolledAt",
  "createdAt",
  "status",
  "progressPercentage",
] as const satisfies readonly (keyof typeof pelatihanEnrollments.$inferSelect)[];

export const getAllEnrollmentsSchema = createPaginationSchema(
  SORTABLE_ENROLLMENT_FIELDS,
  {
    id: "enrolledAt",
    desc: true,
  },
).extend({
  status: z
    .enum(["enrolled", "in_progress", "completed", "failed", "expired"])
    .optional(),
  search: z.string().default(""),
  pelatihanId: z.string().uuid().optional(),
});

// ##################
// authored (generated by gemini, Jun 03 2026 13:12 WITA)
// ##################

export const registerBimtekSchema = z.object({
  pelatihanId: z.string().uuid(),
  // Data Perusahaan
  companyName: z.string().min(1, "Nama perusahaan wajib diisi").max(250),
  companyAddress: z.string().min(1, "Alamat perusahaan wajib diisi"),
  companyProvinceId: z.string().uuid("Provinsi wajib dipilih"),
  companyRegencyId: z.string().uuid("Kabupaten/Kota wajib dipilih"),
  companyDistrictId: z.string().uuid("Kecamatan wajib dipilih"),
  companyKbli: z.string().min(1, "KBLI wajib diisi").max(250),

  // Data Diri
  participantName: z.string().min(1, "Nama lengkap wajib diisi").max(250),
  participantNik: z.string().min(16, "NIK harus 16 digit").max(16, "NIK harus 16 digit"),
  participantBirthPlace: z.string().min(1, "Tempat lahir wajib diisi").max(250),
  participantBirthDate: z.string().min(1, "Tanggal lahir wajib diisi"),
  participantEmail: z.string().email("Format email tidak valid").max(250),
  participantPhone: z.string().min(8, "Nomor HP minimal 8 digit").max(50),
  participantAddress: z.string().min(1, "Alamat domisili wajib diisi"),

  // Documents
  employmentLetterUrl: z.string().min(1, "Surat Keterangan Kerja wajib diunggah"),
  employmentLetterName: z.string().min(1, "Nama berkas Surat Keterangan Kerja wajib diisi"),
  consentLetterUrl: z.string().min(1, "Surat Pernyataan Kesediaan wajib diunggah"),
  consentLetterName: z.string().min(1, "Nama berkas Surat Pernyataan Kesediaan wajib diisi"),
  diplomaUrl: z.string().min(1, "Ijazah Terakhir wajib diunggah"),
  diplomaName: z.string().min(1, "Nama berkas Ijazah Terakhir wajib diisi"),
  passPhotoUrl: z.string().optional(),
  passPhotoName: z.string().optional(),
});

export const updateBimtekDocumentsSchema = z.object({
  enrollmentId: z.string().uuid(),
  employmentLetterUrl: z.string().optional(),
  employmentLetterName: z.string().optional(),
  consentLetterUrl: z.string().optional(),
  consentLetterName: z.string().optional(),
  diplomaUrl: z.string().optional(),
  diplomaName: z.string().optional(),
  passPhotoUrl: z.string().optional(),
  passPhotoName: z.string().optional(),
});

export const checkInBimtekSchema = z.object({
  enrollmentId: z.string().uuid(),
  scheduleId: z.string().uuid(),
  status: z.enum(["present", "excused"]),
});

export const updatePelatihanAssessmentSchema = createInsertSchema(
  pelatihanAssessments,
  {
    title: z.string().min(1).max(250).optional(),
    passingScore: z.number().min(0).max(100).optional(),
    timeLimit: z.number().min(0).nullable().optional(),
    maxAttempts: z.number().min(1).nullable().optional(),
    randomizeQuestions: z.boolean().optional(),
  },
)
  .omit({ createdAt: true, updatedAt: true, deletedAt: true, pelatihanId: true, type: true })
  .extend({
    id: z.string().uuid(),
  });

export const addQuestionSchema = z.object({
  assessmentId: z.string().uuid(),
  questionText: z.string().min(1, "Pertanyaan wajib diisi"),
  type: z.enum(["multiple_choice", "true_false", "essay"]),
  points: z.number().min(0).default(10),
  options: z.array(
    z.object({
      optionText: z.string().min(1, "Teks opsi wajib diisi"),
      isCorrect: z.boolean(),
    })
  ).min(1, "Minimal harus ada satu opsi jawaban"),
});

export const verifyEnrollmentSchema = z.object({
  enrollmentId: z.string().uuid(),
  status: z.enum(["verified", "rejected"]),
  rejectionReason: z.string().optional(),
});

export const submitRegistrationRequirementsSchema = z.object({
  pelatihanId: z.string().uuid(),
  // Personal Data
  participantName: z.string().min(1, "Nama lengkap wajib diisi").max(250).optional(),
  participantNik: z.string().min(16, "NIK harus 16 digit").max(16, "NIK harus 16 digit").optional(),
  participantBirthPlace: z.string().max(250).optional(),
  participantBirthDate: z.string().optional(),
  participantPhone: z.string().max(50).optional(),
  participantAddress: z.string().optional(),
  participantBloodType: z.string().max(10).optional(),
  // Company Data
  companyName: z.string().max(250).optional(),
  companyAddress: z.string().optional(),
  companyProvinceId: z.string().uuid().optional().nullable(),
  companyRegencyId: z.string().uuid().optional().nullable(),
  companyDistrictId: z.string().uuid().optional().nullable(),
  companyKbli: z.string().max(250).optional(),
  // Documents
  ktpDocUrl: z.string().url().optional(),
  ktpDocName: z.string().optional(),
  employmentLetterUrl: z.string().url().optional(),
  employmentLetterName: z.string().optional(),
  consentLetterUrl: z.string().url().optional(),
  consentLetterName: z.string().optional(),
  diplomaUrl: z.string().url().optional(),
  diplomaName: z.string().optional(),
  passPhotoUrl: z.string().url().optional(),
  passPhotoName: z.string().optional(),
});

// ##################
// end authored
// ##################

export const pelatihanSchema = {
  createPelatihanCategorySchema,
  createPelatihanSchema,
  updatePelatihanSchema,
  createPelatihanCartSchema,
  createPelatihanModuleSchema,
  updatePelatihanModuleSchema,
  createPelatihanMaterialSchema,
  updatePelatihanMaterialSchema,
  createPelatihanAssessmentSchema,
  createPelatihanQuestionSchema,
  createPelatihanQuestionOptionSchema,
  getAllPelatihanSchema,
  getAllEnrollmentsSchema,
  registerBimtekSchema,
  updateBimtekDocumentsSchema,
  checkInBimtekSchema,
  updatePelatihanAssessmentSchema,
  addQuestionSchema,
  verifyEnrollmentSchema,
  dynamicRequirementsSchema,
  submitRegistrationRequirementsSchema,
};

export default pelatihanSchema;

