// ##################
// authored (generated by gemini, Jun 04 2026 11:25 WITA)
// ##################

import { z } from "zod";

export const upsertProfileSchema = z.object({
  // Data Perusahaan
  companyName: z
    .string()
    .min(1, "Nama perusahaan wajib diisi")
    .max(250, "Nama perusahaan maksimal 250 karakter"),
  companyAddress: z.string().min(1, "Alamat perusahaan wajib diisi"),
  companyProvinceId: z.string().uuid("Provinsi perusahaan wajib dipilih"),
  companyRegencyId: z.string().uuid("Kabupaten/Kota perusahaan wajib dipilih"),
  companyDistrictId: z.string().uuid("Kecamatan perusahaan wajib dipilih"),
  companyKbli: z
    .string()
    .min(1, "KBLI wajib diisi")
    .max(250, "KBLI maksimal 250 karakter"),

  // Data Diri Peserta
  participantName: z
    .string()
    .min(1, "Nama lengkap peserta wajib diisi")
    .max(250, "Nama lengkap maksimal 250 karakter"),
  participantNik: z
    .string()
    .min(16, "NIK harus 16 digit")
    .max(16, "NIK harus 16 digit")
    .regex(/^[0-9]+$/, "NIK hanya boleh berisi angka"),
  participantBirthPlace: z
    .string()
    .min(1, "Tempat lahir wajib diisi")
    .max(250, "Tempat lahir maksimal 250 karakter"),
  participantBirthDate: z.string().min(1, "Tanggal lahir wajib diisi"),
  participantPhone: z
    .string()
    .min(8, "Nomor HP minimal 8 digit")
    .max(50, "Nomor HP maksimal 50 karakter")
    .regex(/^\+?[0-9\s\-()]+$/, "Nomor HP tidak valid"),
  participantAddress: z.string().min(1, "Alamat domisili wajib diisi"),
  participantBloodType: z
    .string()
    .min(1, "Golongan darah wajib diisi")
    .max(10, "Golongan darah maksimal 10 karakter"),
  participantProvinceId: z.string().uuid("Provinsi peserta wajib dipilih"),
  participantRegencyId: z.string().uuid("Kabupaten/Kota peserta wajib dipilih"),
  participantDistrictId: z.string().uuid("Kecamatan peserta wajib dipilih"),
});

export const profileSchema = {
  upsertProfileSchema,
};

export default profileSchema;

// ##################
// end authored
// ##################
