import { createFileRoute } from "@tanstack/react-router";
import { requirePermission } from "@/utils/require-permission";
import { trpc, queryClient } from "@/utils/trpc";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { toast } from "sonner";
import { Download, Upload, AlertTriangle } from "lucide-react";
import { useRef, useState } from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { pageHead } from "@/utils/page-head";

// ##################
// authored (generated by claude, Jul 12 2026)
// ##################

export const Route = createFileRoute(
  "/(core)/back-office/pengujian/import-export/",
)({
  beforeLoad: async ({ context }) => {
    await requirePermission(context, {
      permission: ["pengujian-import-export.read", "kepegawaian-import-export.read"],
    });
  },
  component: ImportExportMainPage,
  head: () => pageHead("Import / Export Data Master", "Kelola data master pengujian dan kepegawaian melalui file Excel"),
});

function ImportExportMainPage() {
  const { data: profile } = useQuery(
    trpc.platform.auth.profile.queryOptions()
  );
  
  const hasPengujian = profile?.permissions.includes("pengujian-import-export.read");
  const hasKepegawaian = profile?.permissions.includes("kepegawaian-import-export.read");

  const defaultTab = hasPengujian ? "pengujian" : "kepegawaian";

  if (!profile) return null;

  return (
    <div className="flex w-full flex-col gap-6 pb-10">
      <div className="mb-4 flex flex-col gap-2">
        <h1 className="text-3xl font-bold tracking-tight">
          Import / Export Data Master
        </h1>
        <p className="text-muted-foreground">
          Kelola data master pengujian dan kepegawaian secara massal menggunakan format Excel.
        </p>
      </div>

      <Tabs defaultValue={defaultTab} className="w-full">
        <TabsList className="grid w-full grid-cols-2 lg:w-[400px]">
          {hasPengujian && <TabsTrigger value="pengujian">Pengujian</TabsTrigger>}
          {hasKepegawaian && <TabsTrigger value="kepegawaian">Kepegawaian</TabsTrigger>}
        </TabsList>
        
        {hasPengujian && (
          <TabsContent value="pengujian" className="mt-6">
            <ImportExportPengujianTab />
          </TabsContent>
        )}
        
        {hasKepegawaian && (
          <TabsContent value="kepegawaian" className="mt-6">
            <ImportExportKepegawaianTab />
          </TabsContent>
        )}
      </Tabs>
    </div>
  );
}

function ImportExportPengujianTab() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isDownloadingTemplate, setIsDownloadingTemplate] = useState(false);
  const [importSummary, setImportSummary] = useState<any>(null);

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);

  const importMutation = useMutation({
    ...trpc.pengujian.pengujianExcel.importData.mutationOptions(),
    onSuccess: (data: any) => {
      setIsImporting(false);
      setImportSummary(data);
      if (data.hasErrors) {
        toast.error(
          `Import gagal: ditemukan ${data.errorCount} baris yang tidak valid.`,
        );
      } else {
        toast.success("Berhasil mengimpor data master");
      }
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    },
    onError: (error: any) => {
      setIsImporting(false);
      toast.error(error.message || "Gagal mengimpor data");
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    },
  });

  const downloadBase64Excel = (base64String: string, filename: string) => {
    const binaryString = window.atob(base64String);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    const blob = new Blob([bytes], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const handleExport = async () => {
    try {
      setIsExporting(true);
      const promise = queryClient.fetchQuery(
        trpc.pengujian.pengujianExcel.exportData.queryOptions(),
      );

      toast.promise(promise, {
        loading: "Mempersiapkan data Excel...",
        success: "Berhasil mengunduh data",
        error: "Gagal mengunduh data",
      });

      const data = await promise;
      downloadBase64Excel(data.buffer, data.filename);
    } catch (error) {
      console.error(error);
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownloadTemplate = async () => {
    try {
      setIsDownloadingTemplate(true);
      const promise = queryClient.fetchQuery(
        trpc.pengujian.pengujianExcel.downloadTemplate.queryOptions(),
      );

      toast.promise(promise, {
        loading: "Mempersiapkan template Excel...",
        success: "Berhasil mengunduh template",
        error: "Gagal mengunduh template",
      });

      const data = await promise;
      downloadBase64Excel(data.base64, "Template_Data_Master_Pengujian.xlsx");
    } catch (error) {
      console.error(error);
    } finally {
      setIsDownloadingTemplate(false);
    }
  };

  const handleDownloadErrorReport = () => {
    if (importSummary?.errorReportBase64) {
      downloadBase64Excel(
        importSummary.errorReportBase64,
        "Laporan_Error_Import_Pengujian.xlsx",
      );
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (
      file.type !==
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" &&
      !file.name.endsWith(".xlsx")
    ) {
      toast.error("File harus berupa Excel (.xlsx)");
      return;
    }

    setSelectedFile(file);
    setShowConfirmDialog(true);
  };

  const handleConfirmImport = () => {
    if (!selectedFile) return;

    setShowConfirmDialog(false);
    setIsImporting(true);
    setImportSummary(null); // Reset prev summary

    const formData = new FormData();
    formData.append("file", selectedFile);

    toast.promise(importMutation.mutateAsync(formData), {
      loading: "Mengimpor dan memvalidasi data...",
      success: "Proses import selesai",
      error: "Gagal memproses import",
    });
  };

  const handleCancelImport = () => {
    setShowConfirmDialog(false);
    setSelectedFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Download className="h-5 w-5" />
              Export Data & Template (Pengujian)
            </CardTitle>
            <CardDescription>
              Unduh data master pengujian saat ini atau template kosong dalam format Excel
              (.xlsx).
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <Button
              onClick={handleExport}
              disabled={isExporting || isDownloadingTemplate}
              className="w-full"
            >
              {isExporting
                ? "Mempersiapkan..."
                : "Download Excel (Data Saat Ini)"}
            </Button>
            <Button
              variant="outline"
              onClick={handleDownloadTemplate}
              disabled={isExporting || isDownloadingTemplate}
              className="w-full"
            >
              {isDownloadingTemplate
                ? "Mempersiapkan..."
                : "Download Template Kosong"}
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Upload className="h-5 w-5" />
              Import Data (Pengujian)
            </CardTitle>
            <CardDescription>
              Unggah file Excel yang telah diisi atau diubah untuk memperbarui
              data master pengujian ke dalam sistem.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col gap-4">
              <input
                type="file"
                accept=".xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                className="hidden"
                ref={fileInputRef}
                onChange={handleFileChange}
                disabled={isImporting}
              />
              <Button
                variant="default"
                onClick={() => fileInputRef.current?.click()}
                disabled={isImporting}
                className="w-full"
              >
                {isImporting ? "Mengimpor..." : "Pilih File Excel"}
              </Button>
              <p className="text-sm text-muted-foreground">
                Perhatian: Baris dengan ID / Nama yang sama akan diperbarui
                nilainya. Baris baru akan ditambahkan. Pastikan format tabel
                tidak berubah.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      {importSummary && !importSummary.hasErrors && (
        <Card>
          <CardHeader>
            <CardTitle>Ringkasan Hasil Import</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto rounded-lg border">
              <table className="w-full text-left text-sm">
                <thead className="bg-muted text-xs text-muted-foreground uppercase">
                  <tr>
                    <th className="px-4 py-3">Data Master</th>
                    <th className="px-4 py-3">Baru (Insert)</th>
                    <th className="px-4 py-3">Diperbarui (Update)</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  <tr>
                    <td className="px-4 py-3 font-medium">
                      Kategori Parameter
                    </td>
                    <td className="px-4 py-3 text-green-600">
                      {importSummary.summary?.kategoriParameter?.insert ?? 0}
                    </td>
                    <td className="px-4 py-3 text-blue-600">
                      {importSummary.summary?.kategoriParameter?.update ?? 0}
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 font-medium">Parameter</td>
                    <td className="px-4 py-3 text-green-600">
                      {importSummary.summary?.parameter?.insert ?? 0}
                    </td>
                    <td className="px-4 py-3 text-blue-600">
                      {importSummary.summary?.parameter?.update ?? 0}
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 font-medium">Kode Alat</td>
                    <td className="px-4 py-3 text-green-600">
                      {importSummary.summary?.kodeAlat?.insert ?? 0}
                    </td>
                    <td className="px-4 py-3 text-blue-600">
                      {importSummary.summary?.kodeAlat?.update ?? 0}
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 font-medium">Alat</td>
                    <td className="px-4 py-3 text-green-600">
                      {importSummary.summary?.alat?.insert ?? 0}
                    </td>
                    <td className="px-4 py-3 text-blue-600">
                      {importSummary.summary?.alat?.update ?? 0}
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 font-medium">Bahan Kimia</td>
                    <td className="px-4 py-3 text-green-600">
                      {importSummary.summary?.bahanKimia?.insert ?? 0}
                    </td>
                    <td className="px-4 py-3 text-blue-600">
                      {importSummary.summary?.bahanKimia?.update ?? 0}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      {importSummary && importSummary.hasErrors && (
        <Card className="border-red-200">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-red-600">
              <AlertTriangle className="h-5 w-5" />
              Import Gagal: {importSummary.errorCount} Error Validasi Ditemukan
            </CardTitle>
            <CardDescription className="text-red-600/80">
              Tidak ada data yang disimpan ke database. Silakan unduh laporan
              error di bawah ini untuk melihat rincian kolom yang bermasalah.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button
              variant="destructive"
              onClick={handleDownloadErrorReport}
              className="w-full sm:w-auto"
            >
              <Download className="mr-2 h-4 w-4" />
              Download Laporan Error (.xlsx)
            </Button>
          </CardContent>
        </Card>
      )}

      <AlertDialog open={showConfirmDialog} onOpenChange={setShowConfirmDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Konfirmasi Import Data Pengujian</AlertDialogTitle>
            <AlertDialogDescription>
              Apakah Anda yakin ingin mengimpor data dari file{" "}
              <strong>{selectedFile?.name}</strong>? Proses ini akan memperbarui
              atau menambahkan data master secara permanen ke database.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={handleCancelImport}>
              Batal
            </AlertDialogCancel>
            <AlertDialogAction onClick={handleConfirmImport}>
              Ya, Import Data
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

function ImportExportKepegawaianTab() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isDownloadingTemplate, setIsDownloadingTemplate] = useState(false);
  const [importSummary, setImportSummary] = useState<any>(null);

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);

  const importMutation = useMutation({
    ...trpc.platform.kepegawaianExcel.importData.mutationOptions(),
    onSuccess: (data: any) => {
      setIsImporting(false);
      setImportSummary(data);
      if (data.hasErrors) {
        toast.error(
          `Import selesai dengan catatan: ditemukan ${data.errorCount} baris yang tidak valid.`,
        );
      } else {
        toast.success("Berhasil mengimpor data master kepegawaian");
      }
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    },
    onError: (error: any) => {
      setIsImporting(false);
      toast.error(error.message || "Gagal mengimpor data");
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    },
  });

  const downloadBase64Excel = (base64String: string, filename: string) => {
    const binaryString = window.atob(base64String);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    const blob = new Blob([bytes], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const handleExport = async () => {
    try {
      setIsExporting(true);
      const promise = queryClient.fetchQuery(
        trpc.platform.kepegawaianExcel.exportData.queryOptions(),
      );

      toast.promise(promise, {
        loading: "Menyiapkan file ekspor...",
        success: (data) => {
          downloadBase64Excel(data.buffer, data.filename);
          return "Berhasil mengekspor data";
        },
        error: "Gagal mengekspor data",
      });

      await promise;
    } catch (error) {
      console.error("Export error:", error);
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownloadTemplate = async () => {
    try {
      setIsDownloadingTemplate(true);
      const promise = queryClient.fetchQuery(
        trpc.platform.kepegawaianExcel.downloadTemplate.queryOptions(),
      );

      toast.promise(promise, {
        loading: "Menyiapkan file template...",
        success: (data) => {
          downloadBase64Excel(data.base64, "Template_Master_Kepegawaian.xlsx");
          return "Berhasil mengunduh template";
        },
        error: "Gagal mengunduh template",
      });

      await promise;
    } catch (error) {
      console.error("Download template error:", error);
    } finally {
      setIsDownloadingTemplate(false);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (
        file.type !==
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" &&
        !file.name.endsWith(".xlsx")
      ) {
        toast.error("File harus berformat Excel (.xlsx)");
        if (fileInputRef.current) {
          fileInputRef.current.value = "";
        }
        return;
      }
      setSelectedFile(file);
      setShowConfirmDialog(true);
    }
  };

  const confirmImport = () => {
    if (!selectedFile) return;

    setShowConfirmDialog(false);
    setIsImporting(true);
    setImportSummary(null);

    const formData = new FormData();
    formData.append("file", selectedFile);

    importMutation.mutate(formData);
  };

  const cancelImport = () => {
    setShowConfirmDialog(false);
    setSelectedFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="grid gap-6 md:grid-cols-2">
        {/* EXPORT CARD */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Download className="h-5 w-5" />
              Ekspor Data & Template (Kepegawaian)
            </CardTitle>
            <CardDescription>
              Unduh seluruh data master kepegawaian yang ada ke format Excel,
              atau unduh template kosong untuk mengisi data baru.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <Button
              variant="outline"
              className="w-full justify-start"
              onClick={handleDownloadTemplate}
              disabled={isDownloadingTemplate}
            >
              <Download className="mr-2 h-4 w-4" />
              {isDownloadingTemplate
                ? "Mengunduh Template..."
                : "Unduh Template Kosong"}
            </Button>
            <Button
              className="w-full justify-start"
              onClick={handleExport}
              disabled={isExporting}
            >
              <Download className="mr-2 h-4 w-4" />
              {isExporting ? "Mengekspor Data..." : "Ekspor Semua Data"}
            </Button>
          </CardContent>
        </Card>

        {/* IMPORT CARD */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Upload className="h-5 w-5" />
              Impor Data (Kepegawaian)
            </CardTitle>
            <CardDescription>
              Unggah file Excel untuk mengimpor atau memperbarui data master
              kepegawaian. Hanya tipe .xlsx yang didukung. <br />
              <strong>Catatan:</strong> Impor pegawai hanya akan melakukan
              UPDATE pada data pegawai yang sudah ada.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <input
              type="file"
              accept=".xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
              className="hidden"
              ref={fileInputRef}
              onChange={handleFileChange}
              disabled={isImporting}
            />
            <Button
              variant="default"
              className="w-full"
              onClick={() => fileInputRef.current?.click()}
              disabled={isImporting}
            >
              <Upload className="mr-2 h-4 w-4" />
              {isImporting ? "Mengimpor..." : "Pilih File Excel"}
            </Button>

            {importSummary && (
              <div
                className={`mt-6 rounded-md border p-4 ${importSummary.hasErrors ? "border-destructive/50 bg-destructive/10" : "border-green-200 bg-green-50 dark:border-green-900/50 dark:bg-green-900/20"}`}
              >
                <h3
                  className={`font-semibold flex items-center gap-2 ${importSummary.hasErrors ? "text-destructive" : "text-green-700 dark:text-green-400"}`}
                >
                  {importSummary.hasErrors ? (
                    <>
                      <AlertTriangle className="h-4 w-4" />
                      Impor Selesai dengan Catatan
                    </>
                  ) : (
                    "Impor Berhasil"
                  )}
                </h3>

                {importSummary.hasErrors && (
                  <div className="mt-2 text-sm text-destructive">
                    <p>
                      Ditemukan <strong>{importSummary.errorCount}</strong>{" "}
                      baris yang gagal diimpor karena tidak valid.
                    </p>
                    <Button
                      variant="outline"
                      size="sm"
                      className="mt-3 bg-background"
                      onClick={() =>
                        downloadBase64Excel(
                          importSummary.errorReportBase64,
                          "Laporan_Error_Import_Kepegawaian.xlsx",
                        )
                      }
                    >
                      <Download className="mr-2 h-4 w-4" />
                      Unduh Laporan Error
                    </Button>
                  </div>
                )}

                {!importSummary.hasErrors && importSummary.summary && (
                  <div className="mt-3 text-sm">
                    <p>Rincian data yang diimpor:</p>
                    <ul className="list-disc pl-5 mt-1 space-y-1">
                      <li>
                        Jabatan: {importSummary.summary.jabatan.success} baris
                      </li>
                      <li>
                        Pegawai (Update):{" "}
                        {importSummary.summary.pegawai.success} baris
                      </li>
                      <li>
                        Sertifikasi:{" "}
                        {importSummary.summary.sertifikasiPegawai?.success ||
                          0}{" "}
                        baris
                      </li>
                    </ul>
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* CONFIRMATION DIALOG */}
      <AlertDialog open={showConfirmDialog} onOpenChange={cancelImport}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Konfirmasi Impor Data Kepegawaian</AlertDialogTitle>
            <AlertDialogDescription>
              Apakah Anda yakin ingin mengimpor data dari file{" "}
              <strong>{selectedFile?.name}</strong>?
              <br />
              <br />
              Proses ini mungkin membutuhkan waktu beberapa saat tergantung pada
              ukuran file.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={cancelImport}>Batal</AlertDialogCancel>
            <AlertDialogAction onClick={confirmImport}>
              Ya, Impor Sekarang
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// ##################
// end authored
// ##################
