import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ChevronRight, FileText } from "lucide-react";
import { useNavigate } from "@tanstack/react-router";
import { cn } from "@/lib/utils";
import { format } from "date-fns";

const PELATIHAN_ORDER_STATUS_COLORS: Record<string, string> = {
  pending: "bg-yellow-100 text-yellow-700",
  waiting_payment: "bg-orange-100 text-orange-700",
  waiting_verification: "bg-blue-100 text-blue-700",
  verified: "bg-green-100 text-green-700",
  cancelled: "bg-gray-100 text-gray-700",
  expired: "bg-gray-100 text-gray-700",
  rejected: "bg-red-100 text-red-700",
};

const PELATIHAN_ORDER_STATUS_LABELS: Record<string, string> = {
  pending: "Pending",
  waiting_payment: "Menunggu Pembayaran",
  waiting_verification: "Menunggu Verifikasi",
  verified: "Terverifikasi",
  cancelled: "Dibatalkan",
  expired: "Kadaluarsa",
  rejected: "Ditolak",
};

// ##################
// authored (generated by antigravity, Jun 24 2026 21:07 WITA)
// ##################

export interface PelatihanOrderCardProps {
  order: {
    id: string;
    orderNumber: string;
    status: string;
    totalAmount: number;
    createdAt: string;
  };
}

function formatDate(dateString: string): string {
  return format(new Date(dateString), "dd MMM yyyy");
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(amount);
}

export function OrderCard({ order }: PelatihanOrderCardProps) {
  const navigate = useNavigate();

  const badgeColorClass =
    PELATIHAN_ORDER_STATUS_COLORS[order.status] || "bg-gray-200 text-gray-800";

  const badgeLabel =
    PELATIHAN_ORDER_STATUS_LABELS[order.status] || order.status;

  return (
    <button
      onClick={() =>
        navigate({
          to: "/pelatihan/transaksi/$orderId",
          params: { orderId: order.id },
        })
      }
      className="w-full text-left"
    >
      <Card className="cursor-pointer p-4 transition-shadow hover:shadow-md">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-100">
              <FileText className="h-6 w-6 text-blue-500" />
            </div>
            <div>
              <h3 className="font-semibold text-foreground">
                {order.orderNumber}
              </h3>
              <p className="text-sm text-muted-foreground">
                {formatDate(order.createdAt)} •{" "}
                {formatCurrency(order.totalAmount)}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Badge className={cn("border-0", badgeColorClass)}>
              {badgeLabel}
            </Badge>
            <ChevronRight className="h-5 w-5 text-muted-foreground" />
          </div>
        </div>
      </Card>
    </button>
  );
}
