import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

// ##################
// authored (generated by antigravity, Jun 24 2026 21:26 WITA)
// ##################

export interface QuizQuestionProps {
  question: {
    id: string;
    questionText: string;
    type: string;
    options?: {
      id: string;
      optionText: string;
    }[];
  };
  index: number;
  value?: string;
  onChange: (value: string) => void;
  disabled?: boolean;
}

export function QuizQuestion({
  question,
  index,
  value,
  onChange,
  disabled,
}: QuizQuestionProps) {
  return (
    <div className="space-y-4 rounded-lg border bg-card p-4 shadow-sm md:p-6">
      <div className="text-lg leading-relaxed font-medium">
        <span className="mr-2">{index + 1}.</span>
        {question.questionText}
      </div>

      {(question.type === "multiple_choice" ||
        question.type === "true_false") && (
        <RadioGroup
          value={value}
          onValueChange={onChange}
          disabled={disabled}
          className="mt-4 space-y-3"
        >
          {question.options?.map((option) => (
            <div
              key={option.id}
              className={`flex cursor-pointer items-center space-y-0 space-x-3 rounded-md border p-3 transition-colors ${
                value === option.id
                  ? "border-primary bg-primary/5"
                  : "hover:bg-muted"
              }`}
            >
              <RadioGroupItem value={option.id} id={option.id} />
              <Label
                htmlFor={option.id}
                className="flex-1 cursor-pointer leading-snug font-normal"
              >
                {option.optionText}
              </Label>
            </div>
          ))}
        </RadioGroup>
      )}

      {question.type === "essay" && (
        <div className="mt-4">
          <Textarea
            value={value || ""}
            onChange={(e) => onChange(e.target.value)}
            disabled={disabled}
            placeholder="Tuliskan jawaban Anda di sini..."
            className="min-h-[120px]"
          />
        </div>
      )}
    </div>
  );
}
