// ##################
// authored (generated by gemini, Jun 04 2026 00:45 WITA)
// ##################

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { trpc } from "@/utils/trpc";
import { useQuery } from "@tanstack/react-query";
import { Award, Calendar, Download } from "lucide-react";
import dayjs from "dayjs";
import { Pagination } from "./pagination";

interface SertifikatTabProps {
  page: number;
  limit: number;
  onPageChange: (page: number) => void;
}

export function SertifikatTab({
  page,
  limit,
  onPageChange,
}: SertifikatTabProps) {
  const { data, isLoading } = useQuery(
    trpc.pelatihan.enrollment.getUserCertificates.queryOptions({
      page,
      limit,
    }),
  );

  if (isLoading) {
    return (
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {[1, 2].map((i) => (
          <Card key={i} className="animate-pulse border-slate-100 shadow-sm">
            <div className="h-40 bg-slate-100" />
            <CardHeader className="space-y-2">
              <div className="h-4 w-3/4 rounded bg-slate-100" />
              <div className="h-4 w-1/2 rounded bg-slate-100" />
            </CardHeader>
          </Card>
        ))}
      </div>
    );
  }

  const certificates = data?.data ?? [];
  const totalPages = data?.pagination?.totalPages ?? 0;

  if (certificates.length === 0) {
    return (
      <div className="flex h-64 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 bg-white p-6 text-center">
        <div className="mb-4 rounded-full bg-blue-50 p-4">
          <Award className="h-6 w-6 text-[#1061D6]" />
        </div>
        <p className="font-['Plus_Jakarta_Sans'] text-sm font-bold text-slate-800">
          Belum ada Sertifikat
        </p>
        <p className="mb-6 max-w-sm font-['Poppins'] text-xs text-slate-500">
          Anda belum memiliki sertifikat yang diterbitkan. Selesaikan kelas
          pelatihan Anda untuk mendapatkan sertifikat.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {certificates.map((cert) => (
          <Card
            key={cert.id}
            className="flex flex-col overflow-hidden border-slate-100 shadow-sm transition-all hover:border-[#1061D6]/10 hover:shadow-md"
          >
            <div className="relative flex h-40 shrink-0 items-center justify-center border-b border-slate-50 bg-slate-50">
              <Award className="h-16 w-16 text-[#1061D6]/20" />
              <div className="absolute inset-0 flex items-end bg-gradient-to-t from-slate-900/50 to-transparent p-4">
                <span className="font-['Poppins'] text-xs font-bold text-white">
                  Sertifikat K3
                </span>
              </div>
            </div>
            <CardHeader className="pt-4 pb-3">
              <div className="mb-1">
                <span className="inline-flex items-center rounded-md bg-emerald-50 px-2 py-0.5 text-[10px] font-bold tracking-wider text-emerald-700 uppercase">
                  Aktif
                </span>
              </div>
              <CardTitle className="line-clamp-2 font-['Plus_Jakarta_Sans'] text-sm leading-tight font-bold text-slate-800">
                {cert.pelatihan.title}
              </CardTitle>
              <CardDescription className="flex items-center gap-1 font-['Poppins'] text-[10px] font-semibold text-slate-400">
                <Calendar className="h-3 w-3" /> Diterbitkan:{" "}
                {cert.certificateIssuedAt
                  ? dayjs(cert.certificateIssuedAt).format("DD MMM YYYY")
                  : cert.completedAt
                    ? dayjs(cert.completedAt).format("DD MMM YYYY")
                    : "-"}
              </CardDescription>
            </CardHeader>
            <CardContent className="flex-1 pb-3 font-['Poppins'] text-xs text-slate-500">
              <p className="line-clamp-1">
                <span className="font-semibold">Tipe:</span>{" "}
                {cert.pelatihan.type === "elearning"
                  ? "E-Learning"
                  : cert.pelatihan.type === "bimtek"
                    ? "Bimtek"
                    : "Webinar"}
              </p>
            </CardContent>
            <CardFooter className="flex gap-2 border-t border-slate-50 pt-3 pb-4">
              {cert.certificateUrl && (
                <Button
                  className="flex-1 rounded-xl bg-[#1061D6] font-bold text-white hover:bg-[#1061D6]/90"
                  asChild
                >
                  <a
                    href={cert.certificateUrl}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Download className="mr-1.5 h-4 w-4" />
                    Unduh
                  </a>
                </Button>
              )}
            </CardFooter>
          </Card>
        ))}
      </div>

      <Pagination
        currentPage={page}
        totalPages={totalPages}
        onPageChange={onPageChange}
      />
    </div>
  );
}

// ##################
// end authored
// ##################
