// ##################
// authored (generated by gemini, Jun 05 2026 14:35 WITA)
// ##################

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import ImageWithFallback from "@/components/image-with-fallback";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { globalErrorToast, globalSuccessToast } from "@/lib/toast";
import { pageHead } from "@/utils/page-head";
import { requirePermission } from "@/utils/require-permission";
import { queryClient, trpc } from "@/utils/trpc";
import { useMutation, useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { format } from "date-fns";
import { id as localeId } from "date-fns/locale";
import {
  ArrowLeft,
  BookOpen,
  CheckCircle2,
  Clock,
  CreditCard,
  ExternalLink,
  Mail,
  Phone,
  User,
  XCircle,
  AlertCircle,
} from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute(
  "/(core)/back-office/order-pelatihan/$orderId",
)({
  beforeLoad: async ({ context }) => {
    await requirePermission(context, { permission: "pelatihan.view" });
  },
  loader: async ({ context, params }) =>
    context.queryClient.ensureQueryData(
      context.trpc.pelatihan.order.getAdminOrderById.queryOptions({
        id: params.orderId,
      }),
    ),
  head: () => pageHead("Detail Order Pelatihan"),
  component: RouteComponent,
});

const ORDER_STATUS_MAP: Record<
  string,
  {
    label: string;
    variant: "default" | "secondary" | "destructive" | "outline";
    icon: React.ComponentType<{ className?: string }>;
  }
> = {
  pending: { label: "Menunggu Pembayaran", variant: "secondary", icon: Clock },
  waiting_payment: {
    label: "Menunggu Pembayaran",
    variant: "secondary",
    icon: Clock,
  },
  waiting_verification: {
    label: "Menunggu Verifikasi",
    variant: "outline",
    icon: Clock,
  },
  verified: { label: "Terverifikasi", variant: "default", icon: CheckCircle2 },
  cancelled: { label: "Dibatalkan", variant: "destructive", icon: XCircle },
  expired: { label: "Kadaluarsa", variant: "destructive", icon: XCircle },
  rejected: { label: "Ditolak", variant: "destructive", icon: XCircle },
};

function formatDate(dateString: string | null | undefined) {
  if (!dateString) return "-";
  return format(new Date(dateString), "dd MMMM yyyy, HH:mm", {
    locale: localeId,
  });
}

function InfoRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-start justify-between gap-4 py-2">
      <span className="min-w-36 text-sm text-muted-foreground">{label}</span>
      <span className="text-right text-sm font-medium">{value}</span>
    </div>
  );
}

function getApprovalBadge(status: string) {
  switch (status) {
    case "approved":
      return <Badge variant="default">Disetujui</Badge>;
    case "rejected":
      return <Badge variant="destructive">Ditolak</Badge>;
    default:
      return <Badge variant="secondary">Menunggu Persetujuan</Badge>;
  }
}

function getPaymentStatusBadge(status: string) {
  switch (status) {
    case "paid":
      return <Badge variant="default">Lunas</Badge>;
    case "rejected":
      return <Badge variant="destructive">Ditolak</Badge>;
    case "pending_verification":
      return <Badge variant="outline">Menunggu Verifikasi</Badge>;
    default:
      return <Badge variant="secondary">Belum Bayar</Badge>;
  }
}

function RouteComponent() {
  const { orderId } = Route.useParams();

  // Rejection dialog states
  const [isRejectApprovalOpen, setIsRejectApprovalOpen] = useState(false);
  const [rejectApprovalReason, setRejectApprovalReason] = useState("");

  const [isRejectPaymentOpen, setIsRejectPaymentOpen] = useState(false);
  const [rejectPaymentReason, setRejectPaymentReason] = useState("");

  const { data: order, isLoading } = useQuery(
    trpc.pelatihan.order.getAdminOrderById.queryOptions({ id: orderId }),
  );

  // Mutations
  const approveMutation = useMutation(
    trpc.pelatihan.order.approveOrder.mutationOptions({
      onSuccess: () => {
        globalSuccessToast("Order berhasil disetujui.");
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAdminOrderById.queryOptions({ id: orderId }),
        );
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAllOrders.queryOptions({}),
        );
      },
      onError: (err) => {
        globalErrorToast(`Gagal menyetujui: ${err.message}`);
      },
    }),
  );

  const rejectApprovalMutation = useMutation(
    trpc.pelatihan.order.rejectOrderApproval.mutationOptions({
      onSuccess: () => {
        globalSuccessToast("Order berhasil ditolak.");
        setIsRejectApprovalOpen(false);
        setRejectApprovalReason("");
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAdminOrderById.queryOptions({ id: orderId }),
        );
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAllOrders.queryOptions({}),
        );
      },
      onError: (err) => {
        globalErrorToast(`Gagal menolak order: ${err.message}`);
      },
    }),
  );

  const verifyMutation = useMutation(
    trpc.pelatihan.order.verifyPayment.mutationOptions({
      onSuccess: () => {
        globalSuccessToast(
          "Pembayaran berhasil diverifikasi. Peserta otomatis ter-enroll.",
        );
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAdminOrderById.queryOptions({ id: orderId }),
        );
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAllOrders.queryOptions({}),
        );
      },
      onError: (err) => {
        globalErrorToast(`Gagal memverifikasi: ${err.message}`);
      },
    }),
  );

  const rejectPaymentMutation = useMutation(
    trpc.pelatihan.order.rejectPayment.mutationOptions({
      onSuccess: () => {
        globalSuccessToast("Pembayaran berhasil ditolak.");
        setIsRejectPaymentOpen(false);
        setRejectPaymentReason("");
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAdminOrderById.queryOptions({ id: orderId }),
        );
        void queryClient.invalidateQueries(
          trpc.pelatihan.order.getAllOrders.queryOptions({}),
        );
      },
      onError: (err) => {
        globalErrorToast(`Gagal menolak pembayaran: ${err.message}`);
      },
    }),
  );

  if (isLoading || !order) {
    return (
      <div className="flex max-w-4xl flex-col gap-6">
        <Skeleton className="h-8 w-64" />
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          <Skeleton className="h-48" />
          <Skeleton className="h-48" />
        </div>
      </div>
    );
  }

  const statusInfo = (ORDER_STATUS_MAP[order.status] ??
    ORDER_STATUS_MAP.pending) as {
    label: string;
    variant: "default" | "secondary" | "destructive" | "outline";
    icon: React.ComponentType<{ className?: string }>;
  };
  const StatusIcon = statusInfo.icon;

  const handleApprove = () => {
    approveMutation.mutate({ orderId: order.id });
  };

  const handleRejectApprovalSubmit = () => {
    if (rejectApprovalReason.trim().length < 10) {
      globalErrorToast("Alasan penolakan minimal 10 karakter");
      return;
    }
    rejectApprovalMutation.mutate({
      orderId: order.id,
      reason: rejectApprovalReason,
    });
  };

  const handleVerifyPayment = () => {
    verifyMutation.mutate({ orderId: order.id });
  };

  const handleRejectPaymentSubmit = () => {
    if (rejectPaymentReason.trim().length < 10) {
      globalErrorToast("Alasan penolakan minimal 10 karakter");
      return;
    }
    rejectPaymentMutation.mutate({
      orderId: order.id,
      reason: rejectPaymentReason,
    });
  };

  return (
    <div className="flex max-w-4xl flex-col gap-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="sm" asChild>
          <Link to="/back-office/order-pelatihan">
            <ArrowLeft className="mr-1 h-4 w-4" />
            Kembali
          </Link>
        </Button>
        <Separator orientation="vertical" className="h-5" />
        <div className="flex flex-col">
          <h1 className="text-xl font-bold">Detail Order Pelatihan</h1>
          <p className="text-sm text-muted-foreground">
            <code className="text-xs">{order.orderNumber}</code>
          </p>
        </div>
      </div>

      {/* Action Banners */}
      {order.approvalStatus === "pending" && (
        <div className="flex flex-col gap-4 rounded-lg border border-amber-200 bg-amber-50/50 p-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3">
            <Clock className="h-5 w-5 animate-pulse text-amber-600" />
            <div>
              <p className="text-sm font-semibold text-amber-800">
                Menunggu Persetujuan Order
              </p>
              <p className="mt-0.5 text-xs text-amber-700">
                Silakan tinjau pesanan ini sebelum memberikan persetujuan
                pembayaran.
              </p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              className="border-amber-300 text-amber-800 hover:bg-amber-100"
              onClick={() => setIsRejectApprovalOpen(true)}
            >
              Tolak Order
            </Button>
            <Button
              className="bg-amber-600 text-white hover:bg-amber-700"
              disabled={approveMutation.isPending}
              onClick={handleApprove}
            >
              {approveMutation.isPending ? "Memproses..." : "Approve"}
            </Button>
          </div>
        </div>
      )}

      {order.approvalStatus === "approved" &&
        order.status === "waiting_verification" && (
          <div className="flex flex-col gap-4 rounded-lg border border-blue-200 bg-blue-50/50 p-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center gap-3">
              <Clock className="h-5 w-5 animate-pulse text-blue-600" />
              <div>
                <p className="text-sm font-semibold text-blue-800">
                  Menunggu Verifikasi Pembayaran
                </p>
                <p className="mt-0.5 text-xs text-blue-700">
                  Bukti pembayaran telah diunggah. Silakan verifikasi kesesuaian
                  dana transfer.
                </p>
              </div>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                className="border-blue-300 text-blue-800 hover:bg-blue-100"
                onClick={() => setIsRejectPaymentOpen(true)}
              >
                Tolak Pembayaran
              </Button>
              <Button
                className="bg-blue-600 text-white hover:bg-blue-700"
                disabled={verifyMutation.isPending}
                onClick={handleVerifyPayment}
              >
                {verifyMutation.isPending
                  ? "Memverifikasi..."
                  : "Verifikasi Pembayaran"}
              </Button>
            </div>
          </div>
        )}

      {order.approvalStatus === "rejected" && (
        <div className="flex items-center gap-3 rounded-lg border border-destructive/20 bg-destructive/5 p-4 text-destructive">
          <XCircle className="h-5 w-5" />
          <div>
            <p className="text-sm font-semibold">Order Telah Ditolak</p>
            <p className="mt-0.5 text-xs">
              Alasan: <strong>{order.approvalRejectReason || "-"}</strong>
            </p>
          </div>
        </div>
      )}

      {order.paymentStatus === "rejected" && (
        <div className="flex items-center gap-3 rounded-lg border border-destructive/20 bg-destructive/5 p-4 text-destructive">
          <AlertCircle className="h-5 w-5" />
          <div>
            <p className="text-sm font-semibold">Pembayaran Ditolak</p>
            <p className="mt-0.5 text-xs">
              Alasan penolakan pembayaran:{" "}
              <strong>{order.paymentRejectedReason || "-"}</strong>
            </p>
          </div>
        </div>
      )}

      {/* Status Banner */}
      <div className="flex items-center justify-between rounded-lg border bg-muted/30 p-4">
        <div className="flex items-center gap-3">
          <StatusIcon className="h-5 w-5 text-muted-foreground" />
          <div>
            <p className="text-sm font-medium">Status Order / Persetujuan</p>
            <div className="mt-1 flex flex-wrap gap-1.5">
              <Badge variant={statusInfo.variant}>
                Order: {statusInfo.label}
              </Badge>
              {getApprovalBadge(order.approvalStatus)}
              {getPaymentStatusBadge(order.paymentStatus)}
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        {/* Informasi Pembeli */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <User className="h-4 w-4" />
              Informasi Pembeli
            </CardTitle>
            <CardDescription>
              Data pengguna yang melakukan pembelian
            </CardDescription>
          </CardHeader>
          <CardContent className="divide-y">
            <InfoRow label="Nama" value={order.user?.name ?? "-"} />
            <InfoRow
              label="Email"
              value={
                order.user?.email ? (
                  <a
                    href={`mailto:${order.user.email}`}
                    className="flex items-center gap-1 text-primary hover:underline"
                  >
                    <Mail className="h-3 w-3" />
                    {order.user.email}
                  </a>
                ) : (
                  "-"
                )
              }
            />
            <InfoRow
              label="No. Telepon"
              value={
                order.user?.phone ? (
                  <a
                    href={`tel:${order.user.phone}`}
                    className="flex items-center gap-1 text-primary hover:underline"
                  >
                    <Phone className="h-3 w-3" />
                    {order.user.phone}
                  </a>
                ) : (
                  "-"
                )
              }
            />
          </CardContent>
        </Card>

        {/* Informasi Pembayaran */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <CreditCard className="h-4 w-4" />
              Informasi Pembayaran
            </CardTitle>
            <CardDescription>
              Status dan detail transaksi keuangan
            </CardDescription>
          </CardHeader>
          <CardContent className="divide-y">
            <InfoRow
              label="No. Order"
              value={<code className="text-xs">{order.orderNumber}</code>}
            />
            <InfoRow
              label="Total"
              value={
                <span className="font-bold text-primary">
                  Rp {order.totalAmount.toLocaleString("id-ID")}
                </span>
              }
            />
            <InfoRow
              label="Tanggal Order"
              value={formatDate(order.createdAt)}
            />
            <InfoRow
              label="Tgl. Upload Bukti"
              value={formatDate(order.paymentProofUploadedAt)}
            />
            <InfoRow
              label="Tgl. Verifikasi"
              value={formatDate(order.verifiedAt)}
            />
            {order.approvedBy && (
              <InfoRow
                label="Disetujui Oleh"
                value={`${order.approvedBy.name} (${order.approvedBy.email})`}
              />
            )}
            {order.approvedAt && (
              <InfoRow
                label="Tgl. Disetujui"
                value={formatDate(order.approvedAt)}
              />
            )}
            {order.verifiedBy && (
              <InfoRow
                label="Diverifikasi Oleh"
                value={`${order.verifiedBy.name} (${order.verifiedBy.email})`}
              />
            )}
          </CardContent>
        </Card>
      </div>

      {/* Bukti Pembayaran */}
      {order.paymentProofUrl && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Bukti Pembayaran</CardTitle>
            <CardDescription>
              Diunggah oleh peserta pada{" "}
              {formatDate(order.paymentProofUploadedAt)}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {order.paymentProofUrl.startsWith("blob:") ? (
              <p className="text-sm text-muted-foreground italic">
                Bukti pembayaran diunggah secara lokal (preview sementara).
                Untuk lingkungan produksi, berkas akan tersimpan di cloud
                storage.
              </p>
            ) : (
              <div className="space-y-3">
                <ImageWithFallback
                  src={order.paymentProofUrl}
                  alt="Bukti pembayaran"
                  className="max-h-64 w-full rounded-lg border bg-muted object-contain"
                />
                <Button variant="outline" size="sm" asChild>
                  <a
                    href={order.paymentProofUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <ExternalLink className="mr-2 h-3 w-3" />
                    Buka di Tab Baru
                  </a>
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Daftar Kelas yang Dibeli */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <BookOpen className="h-4 w-4" />
            Kelas yang Dibeli ({order.items.length})
          </CardTitle>
          <CardDescription>Daftar pelatihan dalam order ini</CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          <div className="divide-y">
            {order.items.map((item) => (
              <div key={item.id} className="flex items-center gap-4 p-4">
                <div className="h-14 w-20 flex-shrink-0 overflow-hidden rounded-md bg-muted">
                  {item.pelatihan.thumbnailUrl ? (
                    <ImageWithFallback
                      src={item.pelatihan.thumbnailUrl}
                      alt={item.pelatihan.title}
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <div className="flex h-full w-full items-center justify-center">
                      <BookOpen className="h-5 w-5 text-muted-foreground/40" />
                    </div>
                  )}
                </div>
                <div className="min-w-0 flex-1">
                  <p className="line-clamp-2 text-sm font-medium">
                    {item.pelatihan.title}
                  </p>
                  <p className="mt-0.5 text-xs text-muted-foreground capitalize">
                    {item.pelatihan.level} · {item.pelatihan.duration} hari
                  </p>
                </div>
                <div className="flex-shrink-0 text-right">
                  <p className="text-sm font-semibold">
                    {item.price === 0
                      ? "Gratis"
                      : `Rp ${item.price.toLocaleString("id-ID")}`}
                  </p>
                </div>
              </div>
            ))}
          </div>
          <Separator />
          <div className="flex items-center justify-between px-4 py-3">
            <span className="text-sm font-medium text-muted-foreground">
              Total Pembayaran
            </span>
            <span className="text-base font-bold">
              Rp {order.totalAmount.toLocaleString("id-ID")}
            </span>
          </div>
        </CardContent>
      </Card>

      {/* Reject Order Approval Dialog */}
      <Dialog
        open={isRejectApprovalOpen}
        onOpenChange={setIsRejectApprovalOpen}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Tolak Persetujuan Order</DialogTitle>
            <DialogDescription>
              Berikan alasan menolak persetujuan order ini. Alasan ini akan
              ditampilkan kepada pengguna.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <Textarea
              placeholder="Contoh: Kuota kelas telah penuh atau ada kesalahan data transaksi."
              value={rejectApprovalReason}
              onChange={(e) => setRejectApprovalReason(e.target.value)}
              className="min-h-24"
            />
            <p className="mt-1.5 text-xs text-muted-foreground">
              Minimal 10 karakter. Panjang karakter saat ini:{" "}
              {rejectApprovalReason.trim().length}
            </p>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsRejectApprovalOpen(false)}
            >
              Batal
            </Button>
            <Button
              variant="destructive"
              onClick={handleRejectApprovalSubmit}
              disabled={
                rejectApprovalMutation.isPending ||
                rejectApprovalReason.trim().length < 10
              }
            >
              {rejectApprovalMutation.isPending
                ? "Memproses..."
                : "Tolak Order"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Reject Payment Dialog */}
      <Dialog open={isRejectPaymentOpen} onOpenChange={setIsRejectPaymentOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Tolak Verifikasi Pembayaran</DialogTitle>
            <DialogDescription>
              Berikan alasan menolak bukti pembayaran ini. Pengguna akan diminta
              untuk mengunggah bukti pembayaran ulang.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <Textarea
              placeholder="Contoh: Bukti transfer tidak terbaca atau nominal tidak sesuai."
              value={rejectPaymentReason}
              onChange={(e) => setRejectPaymentReason(e.target.value)}
              className="min-h-24"
            />
            <p className="mt-1.5 text-xs text-muted-foreground">
              Minimal 10 karakter. Panjang karakter saat ini:{" "}
              {rejectPaymentReason.trim().length}
            </p>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsRejectPaymentOpen(false)}
            >
              Batal
            </Button>
            <Button
              variant="destructive"
              onClick={handleRejectPaymentSubmit}
              disabled={
                rejectPaymentMutation.isPending ||
                rejectPaymentReason.trim().length < 10
              }
            >
              {rejectPaymentMutation.isPending
                ? "Memproses..."
                : "Tolak Pembayaran"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
