-- ##################
-- # authored (generated by claude, Jun 09 2026 WITA)
-- ##################
--
-- One-off cleanup for the `offerRevision` double-write bug.
--
-- Before the fix, orderQueries.offerRevision inserted the same "revision"
-- status-history row twice per call: once inside the transaction and once
-- immediately after it. This removes those duplicates.
--
-- Strategy: delete a row only when an EARLIER row with an identical
-- (order_id, status, changed_by, note) exists within a 60-second window.
-- The 60s guard ensures we only collapse the near-simultaneous duplicates
-- produced by the bug, and never two legitimately-separate events (e.g. the
-- four distinct "pending" workflow steps, which alternate changed_by and are
-- minutes apart). The earliest row in each duplicate group is always kept.
--
-- Run a dry-run first to preview affected rows, then run the DELETE.

-- ---- DRY RUN: preview the rows that WOULD be deleted ----
-- SELECT a.id, a.order_id, a.status, a.changed_by, a.note, a.created_at
-- FROM order_status_history a
-- JOIN order_status_history b
--   ON a.order_id = b.order_id
--   AND a.status = b.status
--   AND a.changed_by = b.changed_by
--   AND COALESCE(a.note, '') = COALESCE(b.note, '')
--   AND b.created_at < a.created_at
--   AND a.created_at - b.created_at < interval '60 seconds'
-- ORDER BY a.order_id, a.created_at;

-- ---- DELETE: remove the duplicates ----
DELETE FROM order_status_history a
USING order_status_history b
WHERE a.order_id = b.order_id
  AND a.status = b.status
  AND a.changed_by = b.changed_by
  AND COALESCE(a.note, '') = COALESCE(b.note, '')
  AND b.created_at < a.created_at
  AND a.created_at - b.created_at < interval '60 seconds';

-- ##################
-- # end authored
-- ##################
