import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { Effect } from "effect";
import { TRPCError } from "@trpc/server";

interface FieldMappingConfig {
  x: number;
  y: number;
  fontSize: number;
  color?: string;
  align?: string;
  enabled: boolean;
}

interface QRCodeConfig {
  x: number;
  y: number;
  width: number;
  height: number;
  enabled: boolean;
}

export interface CertificateData {
  participantName: string;
  participantNik?: string;
  certificateNumber: string;
  pelatihanTitle: string;
  pelatihanType: string;
  completionDate: string;
  issuedAt: string;
  finalScore?: string;
  instructorName?: string;
  companyName?: string;
}

export interface GenerateCertificateOptions {
  templateBuffer: Buffer;
  templateFileType?: string;
  data: CertificateData;
  fieldMappings: {
    participantName?: FieldMappingConfig;
    certificateNumber?: FieldMappingConfig;
    pelatihanTitle?: FieldMappingConfig;
    completionDate?: FieldMappingConfig;
    issuedAt?: FieldMappingConfig;
    finalScore?: FieldMappingConfig;
    instructorName?: FieldMappingConfig;
    companyName?: FieldMappingConfig;
    qrCode?: QRCodeConfig;
  };
  qrCodeDataURL?: string;
}

/**
 * Converts a hex color string to pdf-lib rgb color object.
 */
function hexToRgb(hex: string) {
  const cleanHex = hex.replace("#", "");
  const r = parseInt(cleanHex.substring(0, 2), 16) / 255;
  const g = parseInt(cleanHex.substring(2, 4), 16) / 255;
  const b = parseInt(cleanHex.substring(4, 6), 16) / 255;
  return rgb(isNaN(r) ? 0 : r, isNaN(g) ? 0 : g, isNaN(b) ? 0 : b);
}

/**
 * Generates a certificate PDF by overlaying text and QR code on a template PDF using pdf-lib.
 * Uses percentage-based coordinates to support different template dimensions.
 * Coordinate translation:
 * - Input (x, y): percentage from TOP-LEFT of page (0 to 100)
 * - Output (pdfX, pdfY): points from BOTTOM-LEFT of page in pdf-lib coordinate space
 * 
 * Authored (generated by gemini, Jun 05 2026 17:35 WITA)
 */
export const generateDynamicCertificatePdf = (
  options: GenerateCertificateOptions,
): Effect.Effect<Buffer, TRPCError> =>
  Effect.tryPromise({
    try: async () => {
      const { templateBuffer, templateFileType, data, fieldMappings, qrCodeDataURL } = options;
      
      let pdfDoc: PDFDocument;
      let page;
      let width: number;
      let height: number;

      // Auto-detect file type if not explicitly provided
      const fileType = templateFileType?.toLowerCase() || (
        templateBuffer.slice(0, 4).toString() === "%PDF" ? "pdf" :
        (templateBuffer[0] === 0x89 && templateBuffer[1] === 0x50) ? "png" :
        (templateBuffer[0] === 0xff && templateBuffer[1] === 0xd8) ? "jpeg" : "pdf"
      );

      if (fileType === "pdf") {
        pdfDoc = await PDFDocument.load(templateBuffer);
        const pages = pdfDoc.getPages();
        page = pages[0];
        if (!page) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Template PDF tidak memiliki halaman",
          });
        }
        const size = page.getSize();
        width = size.width;
        height = size.height;
      } else if (fileType === "png" || fileType === "jpeg" || fileType === "jpg") {
        pdfDoc = await PDFDocument.create();
        let image;
        if (fileType === "png") {
          image = await pdfDoc.embedPng(templateBuffer);
        } else {
          image = await pdfDoc.embedJpg(templateBuffer);
        }
        page = pdfDoc.addPage([image.width, image.height]);
        page.drawImage(image, {
          x: 0,
          y: 0,
          width: image.width,
          height: image.height,
        });
        width = image.width;
        height = image.height;
      } else {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: `Format template ${fileType} tidak didukung`,
        });
      }
      const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
      
      // Helper function to draw dynamic fields
      const drawField = (textValue: string, config?: FieldMappingConfig, isBold = false) => {
        if (!config || !config.enabled) return;
        
        const font = isBold ? helveticaBold : helvetica;
        const color = config.color ? hexToRgb(config.color) : rgb(0, 0, 0);
        
        // Translate from percentage top-left to points bottom-left
        const pdfX = (config.x / 100) * width;
        const pdfY = ((100 - config.y) / 100) * height;
        
        const textWidth = font.widthOfTextAtSize(textValue, config.fontSize);
        
        // Handle alignment offsets
        let finalX = pdfX;
        const align = config.align || "center";
        if (align === "center") {
          finalX = pdfX - textWidth / 2;
        } else if (align === "right") {
          finalX = pdfX - textWidth;
        }
        
        // Draw the text
        page.drawText(textValue, {
          x: finalX,
          y: pdfY,
          size: config.fontSize,
          font,
          color,
        });
      };
      
      // Draw fields
      drawField(data.participantName, fieldMappings.participantName, true);
      drawField(data.certificateNumber, fieldMappings.certificateNumber, false);
      drawField(data.pelatihanTitle, fieldMappings.pelatihanTitle, true);
      drawField(data.completionDate, fieldMappings.completionDate, false);
      drawField(data.issuedAt, fieldMappings.issuedAt, false);
      if (data.finalScore) {
        drawField(data.finalScore, fieldMappings.finalScore, false);
      }
      if (data.instructorName) {
        drawField(data.instructorName, fieldMappings.instructorName, false);
      }
      if (data.companyName) {
        drawField(data.companyName, fieldMappings.companyName, false);
      }
      
      // Draw QR Code if enabled and provided
      const qrConfig = fieldMappings.qrCode;
      if (qrConfig && qrConfig.enabled && qrCodeDataURL) {
        const base64Data = qrCodeDataURL.split(",")[1];
        if (base64Data) {
          const qrBuffer = Buffer.from(base64Data, "base64");
          const qrImage = await pdfDoc.embedPng(qrBuffer);
          
          const qrWidth = qrConfig.width || 80;
          const qrHeight = qrConfig.height || 80;
          
          // Translate to bottom-left coordinates of the image box
          const pdfX = (qrConfig.x / 100) * width - qrWidth / 2;
          const pdfY = ((100 - qrConfig.y) / 100) * height - qrHeight / 2;
          
          page.drawImage(qrImage, {
            x: pdfX,
            y: pdfY,
            width: qrWidth,
            height: qrHeight,
          });
        }
      }
      
      // Save changes
      const pdfBytes = await pdfDoc.save();
      return Buffer.from(pdfBytes);
    },
    catch: (error) => {
      return new TRPCError({
        code: "INTERNAL_SERVER_ERROR",
        message: `Gagal menghasilkan PDF sertifikat: ${error instanceof Error ? error.message : "Unknown error"}`,
        cause: error,
      });
    },
  });
